### ISSUE TITLE
Support Logical functions in Azure Resource Manager Tools extension

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurearmtools#10]
(moved from https://github.com/Microsoft/vscode/issues/34177)
//cc @russcam

The logical functions for Azure Resource Manager templates have been out for a little while now, but the latest Azure Resource Manager tools Version 0.3.6 (07/27/2017) does not support them:

![30302219-e4c42496-97a2-11e7-993d-9a177ce053d2](https://user-images.githubusercontent.com/1487073/33850441-c519b6d0-de68-11e7-94da-027596831969.png)

Please add support for them to make authoring templates that little bit less fiddly!

**Comment by bmoore-msft** [comment]
These are supported already - see: https://github.com/Microsoft/vscode-azurearmtools/blob/master/assets/ExpressionMetadata.json#L12

**Comment by StephenWeatherford** [comment]
As noted by Brian, these are currently supported (have been since it was open sourced).

**Comment by russcam** [comment]
thanks!

**Comment by StephenWeatherford** [comment]
No problem, please let us know if anything else is missing.
