### ISSUE TITLE
ARM Template Extension: Mapping JSON files to JSONC breaks IntelliSense

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-azurearmtools#100]
_From @erictorbenson on April 25, 2018 17:51_

I currently map the "JSON with Comments" language type to *.json to allow editing of ARM templates without flagging comments as errors. When I do this, IntelliSense for the ARM template does not suggest completions. I can't find a setting that looks like it would let me override this behavior.

Steps to Reproduce:
1. Install a fresh copy of VS Code and install the ARM Tools Extension.
2. Add the following to the User Settings and reload VS Code:
`{
    "files.associations": {
        "*.json":"jsonc"
    }
}`
3. Load an ARM template and attempt to auto-complete a parameter, variable, etc. IntelliSense window will not appear.
4. Comment out the line above and reload, functionality returns.

_Copied from original issue: Microsoft/vscode#48696_

**Comment by aeschli** [comment]
_From @vscodebot[bot] on April 25, 2018 17:51_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Can we not flag comments in ARM JSON files as errors? (#46114)](https://www.github.com/Microsoft/vscode/issues/46114)

**Comment by aeschli** [comment]
@erictorbenson Do you use the https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools?

**Comment by aeschli** [comment]
_From @erictorbenson on May 2, 2018 19:4_

Yes I do, version 0.4.0.

[cid:image001.jpg@01D3E226.DD429800]

**Comment by StephenWeatherford** [comment]
@aeschli Grüezi wohl!  This has been fixed as #24, but the new extension version hasn't been released yet.  That will probably happen next week.  Thanks for reporting.
