### ISSUE TITLE
Release cadence?

### ISSUE THREAD

**Issue by DonKarlssonSan** [Microsoft/vscode-azurearmtools#101]
Sorry for opening an issue that is really a question. (Where should I ask next time? Who should I contact?)

I'm wondering what the release cadence is? When is the next planned release?

Thanks for your good work! I like this VS Code Extension! =)

**Comment by StephenWeatherford** [comment]
Thanks!

This is as good a place as any to ask.  We should be releasing again soon (hopefully this week).  Our regular cadence is about every month, depending on features/fixes and our other extensions.

FYI @fiveisprime, @PrashanthCorp

**Comment by DonKarlssonSan** [comment]
Ok, great! Thank you!
