### ISSUE TITLE
sd

### ISSUE THREAD

**Issue by tummelumme** [microsoft/vscode-azurearmtools#1024]
Does this occur consistently? 
Repro steps:

1.
2.

Action: reportDeploymentParametersErrors
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'c:\users\tumme\desktop\sdc\tempalte\nordcloudrepo\vm_deploy_domain.json'

Version: 0.12.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.3
Language: en

**Comment by StephenWeatherford** [comment]
@tummelumme This happens when you delete or rename the template file and then open the parameter file, right?  It should be fixed in the shortly upcoming release by #952.  Thanks!
