### ISSUE TITLE
Autocomplete for resource type doesn't list all types

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurearmtools#103]
This is what I get for autocomplete of resource type:
![screen shot 2018-05-08 at 3 25 33 pm](https://user-images.githubusercontent.com/11282622/39786225-6fa2dbce-52d4-11e8-9bd7-8ccbd2bd1f4f.png)

Also if it's not going to list all types - I would at least expect it to list common types. These don't seem common at all

**Comment by StephenWeatherford** [comment]
That's not controlled by the extension - it's from the Azure JSON schemas.

**Comment by EricJizbaMSFT** [comment]
VS lists all types - we should be able to do it too :)

**Comment by StephenWeatherford** [comment]
It's not our code at all - it's VS Code.  Disable the extension and you'll see what I mean.

**Comment by StephenWeatherford** [comment]
The extension handles variables, parameters and expressions inside string values.

**Comment by EricJizbaMSFT** [comment]
Tbh I don't really care where the current support comes from. From a user's perspective, all I know is that autocomplete for my ARM templates is lacking. You're welcome to file an issue on VS Code if you don't think the extension can/should fix this

**Comment by jangelfdez** [comment]
I believe the issue is with Azure Schema not providing the proper information to VSCode to process it and give the suggestions to the user, isn't it?

**Comment by StephenWeatherford** [comment]
Yes, although Eric says VSCode and VS provide different lists, which might be an issue.

**Comment by StephenWeatherford** [comment]
We are working on improving the experience here which will probably not happen in this extension. Nothing we can do in the meantime in the extension.
