### ISSUE TITLE
"Go to definition" should work when cursor is in 'parameters' or 'variables'

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurearmtools#104]
I couldn't figure out why "Go to definition" wasn't working for me:
![screen shot 2018-05-08 at 3 35 06 pm 2](https://user-images.githubusercontent.com/11282622/39786441-7870c9cc-52d5-11e8-9406-ba11e68b2141.png)

Until I realized my cursor had to be inside "nicName". A pretty minor thing, but can we make it work when my cursor is inside "variables(nicName)"?

**Comment by leomwa** [comment]
Seems like it completely stopped working for me. Holding shift on a variable or parameter does not underline what I'm on and doesn't navigate to it's definition when I click on it.
Release v0.4.2

**Comment by StephenWeatherford** [comment]
@leomwa Sorry, missed your comment.  Were you able to get this working?

**Comment by leomwa** [comment]
@StephenWeatherford Yes this is now working. I'm afraid I don't remember if it was fixed by me reinstalling Code or a subsequent update.

**Comment by neilpeterson** [comment]
Closing for now due to existing priorities. Will re-evaluate if time allows.
