### ISSUE TITLE
Move the JSON Outline view to the activity bar

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vscode-azurearmtools#105]
Thoughts on moving the Json outline view from the file explorer to the activity bar with the latest release? See https://code.visualstudio.com/updates/v1_23#_extension-authoring

**Comment by StephenWeatherford** [comment]
@damienpontifex (cc @fiveisprime, @EricJizbaMSFT, @nturinski) We were wondering if moving to the Azure activity bar made sense for this extension or not. Unlike the other Azure extensions, the JSON outline doesn't show anything from Azure itself.  Instead, it shows information from the local file.  Thus we were thinking it might make more sense in the current file view.

Thoughts?

**Comment by EricJizbaMSFT** [comment]
I still think the file view makes the most sense. But if there's any debate at all, we should probably provide a user setting to control this

**Comment by damienpontifex** [comment]
I'm pretty happy either way. Just saw it in the release notes and thought it might be something interesting to bring up/explore. 

Agreed that it's not such a component that has influence outside the current file so agree with @StephenWeatherford that the file view is the most logical place.

**Comment by StephenWeatherford** [comment]
We appreciate the suggestion.  We'll leave this one in the file explorer for now and see if other react negatively.
