### ISSUE TITLE
Extension causes high cpu load with large numbers of variables/parameters/resources

### ISSUE THREAD

**Issue by konopkap** [microsoft/vscode-azurearmtools#1051]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.13.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.0`

[msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-azurearmtools/files/5376370/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt)

**Comment by StephenWeatherford** [comment]
https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
Hmmm, perf tools don't seem to like this file, although I don't see anything obviously wrong with it.  Will have to try on another computer.

**Comment by StephenWeatherford** [comment]
Taking a long time in visitAllReachableStringValues

@konopkap Did this happen one time, or does it happen frequently?  Is it a particularly large file?  Is it possible to get a copy of it or at least a description (how many lines, resources, etc.)?  You can mail me directly if you'd like @ my first name then a period then my last name then at microsoft of course dot com.  Thanks!

**Comment by StephenWeatherford** [comment]
* ~180KB, ~4,3k lines
* 400 variables
* One of the resources has 4K lines

**Comment by StephenWeatherford** [comment]
@konopkap If you'd like, you can try out the fix here: https://github.com/microsoft/vscode-azurearmtools/releases/tag/v0.14.0-alpha.  Download the VSIX, then use F1 -> Install from VSIX... inside vscode to install the new version.  While you're at it, feel free to give feedback on the preview "Extract to variable/parameter" functionality!

Thanks!
Stephen

**Comment by konopkap** [comment]
@StephenWeatherford Now it works without any lags. Big thank you! To be honest I don't know how to use this new functionality. Could you tell me how can I use it?

**Comment by StephenWeatherford** [comment]
@konopkap Sorry, was out yesterday.  I would start with our Getting Started info at https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools, then feel free to ask additional questions.
