### ISSUE TITLE
dateTimeAdd() in certain scenarios gives a template validation error

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#1056]
This is straight out of the docs (https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-date#datetimeadd):

Template: https://raw.githubusercontent.com/StephenWeatherford/template-examples/master/1056-dateTimeAdd.json
Parameters: https://raw.githubusercontent.com/StephenWeatherford/template-examples/master/1056-dateTimeAdd.parameters.json (only needed to turn on full validation)

Error: Template validation failed: The template variable 'add3Years' is not valid: The template function 'dateTimeAdd' is not valid. Please see https://aka.ms/arm-template-expressions for usage details.. Please see https://aka.ms/arm-template-expressions for usage details.

EXPECTED: no errors
Deployment works fine:

stephenweatherford@Stephens-MacBook-Pro template-examples % ./deploy-rg.sh 1056-dateTimeAdd.json 1056-dateTimeAdd.parameters.json
{- Finished ..
  "id": "/subscriptions/e5ef2b13-6478-4887-ad57-1aa6b9475040/resourceGroups/deleteme/providers/Microsoft.Resources/deployments/1056-dateTimeAdd",
  "location": null,
  "name": "1056-dateTimeAdd",
  "properties": {
    "correlationId": "1628fa0c-e2d3-45d8-a7bb-c00258655f05",
    "debugSetting": null,
    "dependencies": [],
    "duration": "PT1.6347238S",
    "mode": "Incremental",
    "onErrorDeployment": null,
    "outputResources": [],
    "outputs": {
      "add3Years": {
        "type": "String",
        "value": "2023-10-16T18:29:01Z"
      }
    },
    "parameters": {
      "baseTime": {
        "type": "String",
        "value": "2020-10-16 18:29:01Z"
      }
    },
    "parametersLink": null,
    "providers": [],
    "provisioningState": "Succeeded",
    "template": null,
    "templateHash": "14462041680041500311",
    "templateLink": null,
    "timestamp": "2020-10-16T18:29:03.395443+00:00"
  },
  "resourceGroup": "deleteme",
  "type": "Microsoft.Resources/deployments"
}

**Comment by StephenWeatherford** [comment]
Fixed in validation assembly

**Comment by jorgecotillo** [comment]
We have a fix in place in the upcoming template engine package.

**Comment by StephenWeatherford** [comment]
Fixed by validation v14
