### ISSUE TITLE
Does ARM Tools Preview include ARM TTK? 

### ISSUE THREAD

**Issue by MSEvanhi** [microsoft/vscode-azurearmtools#1058]
Does ARM Tools Preview include [ARM TTK](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/test-toolkit)? I think this should be included so partners can see best practices up front.

**Comment by StephenWeatherford** [comment]
We've discussed this in the past but it hasn't happened yet.  Will investigate where this stands.

**Comment by StephenWeatherford** [comment]
FWIW, I'd love to see this, too.

**Comment by MarcusFelling** [comment]
Given other priorities, I'm going to close this out as "Won't Fix"
