### ISSUE TITLE
Validation of template function "deployment"

### ISSUE THREAD

**Issue by reijoh** [microsoft/vscode-azurearmtools#1060]
The [ARM template documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-deployment#deployment) for deployment() ARM template function states that when you deploy to an Azure subscription, management group, or tenant, the return object includes a location property.

When using this property in an ARM template in VSCode, validation fail with the message:

> Template validation failed: The template resource 'location' at line '17' and column '17' is not valid: The language expression property 'location' doesn't exist, available properties are 'name, properties'.. Please see https://aka.ms/arm-template-expressions for usage details.

Validation should take into account the schema used by the template and only fail validation for deployment().location if deploying to a resource group.

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-08-01/managementGroupDeploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "policyDefinitionId": {
      "type": "string"
    },
    "parameters": {
      "type": "object"
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Authorization/policyAssignments",
      "apiVersion": "2019-09-01",
      "name": "mgname-test",
      "location": "[deployment().location]",
      "properties": {
        "displayName": "test",
        "description": "test",
        "scope": "/providers/Microsoft.Management/managementGroups/mgname",
        "policyDefinitionId": "[parameters('policyDefinitionId')]",
        "parameters": "[parameters('parameters')]",
        "metadata": {
          "assignedBy": "test"
        },
        "enforcementMode": "Default"
      }
    }
  ]
}
```

**Comment by StephenWeatherford** [comment]
@reijoh Thanks for taking the time to enter.  I would like to be able to distinguish these scenarios, sounds like it's time to make it happen.

**Comment by StephenWeatherford** [comment]
@jorgecotillo Turns out this is a validation message, not a message from the extension.  Is this something that has already been fixed?

**Comment by StephenWeatherford** [comment]
@jorgecotillo Still repros in the last private build you sent me

**Comment by StephenWeatherford** [comment]
https://raw.githubusercontent.com/StephenWeatherford/template-examples/master/bugs/1060/1060.json

**Comment by jorgecotillo** [comment]
was able to repro and is getting fixed along with @831

**Comment by jorgecotillo** [comment]
Btw @StephenWeatherford in case you are not already doing so, I'll need a deployment object to be passed in the metadata, it can contain any property but the object must exist like resourceGroup or subscription

**Comment by StephenWeatherford** [comment]
Already doing that, thanks!  But it looks like it needs to be updated for other scopes (e.g. "location" not currently included).  I can do that once you provide a build.

```
        private readonly static string DeploymentObject =
        // See https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-deployment#deployment
        ObjectToString(new (string, string)[] {
                        ("name", Quote("deploymentName")),
                        ("properties", ObjectToString(new (string,string)[]
                        {
                            ("templateLink", ObjectToString(new (string,string)[] {
                                ("uri", Quote("https://fake/uri.json"))
                            })),
                            ("template", ObjectToString(new (string, string)[]
                            {
                                ("$schema", Quote("fakeSchema")),
                                ("contentVersion", Quote("fakeContentVersion")),
                                ("parameters", EmptyObject),
                                ("variables", EmptyObject),
                                ("resources", EmptyArray),
                                ("outputs", EmptyObject)
                            })),
                            ("parameters", EmptyObject),
                            ("mode", Quote("fakeMode")),
                            ("provisioningState", Quote("fakeProvisioningState")),
                            ("templateHash", Quote("fakeHash")),
                        }))
        });
```
