### ISSUE TITLE
couldnt start client ARM template

### ISSUE THREAD

**Issue by s3nthl** [microsoft/vscode-azurearmtools#1061]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: ARM Template Language Server: An error occurred starting the language server.

spawn EPERM

Version: 0.13.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:349403extension.bundle.js:16:349403
rejected extension.bundle.js:16:346667
```

</details>

**Comment by MarcusFelling** [comment]
Can you please try [ 0.14.0 ](https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools)and see if you still run into the issue?
