### ISSUE TITLE
Images not rendering in marketplace

### ISSUE THREAD

**Issue by dereklegenzoff** [microsoft/vscode-azurearmtools#1073]
The images in the README aren't rendering on the VS Code marketplace page: https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools

**Comment by StephenWeatherford** [comment]
Thanks for letting us know.  Turns out vscode had a hard-coded link to the master branch for this.  Reinstated master until I ca npush out a fix.

**Comment by StephenWeatherford** [comment]
Will push fix with 0.14.0
