### ISSUE TITLE
Error due to .net issue

### ISSUE THREAD

**Issue by santoshdata** [microsoft/vscode-azurearmtools#1074]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:166:60234
Object.<anonymous> extension.bundle.js:239:55780
fulfilled extension.bundle.js:239:54595
```

</details>

**Comment by StephenWeatherford** [comment]
@santoshdata Hey, thanks for letting us know.  Did the troubleshooting tips work?  If not, we would love to know what you tried and what worked or didn't work.  thanks!

**Comment by StephenWeatherford** [comment]
@santoshdata Also, do you get another error message?  That one may have more info.

**Comment by StephenWeatherford** [comment]
Also, I've improved the troubleshooting instructions at https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition.
