### ISSUE TITLE
The lightbulb doesn't display when selecting the multi-line string inside the double quotes

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#1075]
**OS:** All
**Build Version:** 20201025.1

**Repro Steps:**

1. Open the "new-vm.json" template file in VS Code.
2. Select the entire text inside the double quotes(without the double quotes).
3. Display a lightbulb on that line.
4. Select the multi-line string inside the double quotes(without the double quotes),such as the below.
![image](https://user-images.githubusercontent.com/57662131/97154898-7daae700-17af-11eb-8e0a-557841f6d5ad.png)
5. Check the result.

**Expect:**
Display a lightbulb on that line.
![image](https://user-images.githubusercontent.com/57662131/97154944-8ef3f380-17af-11eb-9944-d552bf02e85c.png)

**Actual:**
The lightbulb doesn't display on that line.
![image](https://user-images.githubusercontent.com/57662131/97154998-a206c380-17af-11eb-842e-043cefb877ad.png)

**More Info:**
1. This issue doesn't reproduce when placing cursor anywhere inside the multi-line string.
![image](https://user-images.githubusercontent.com/57662131/97155319-28230a00-17b0-11eb-9aba-9517d877c0d8.png)

**Comment by StephenWeatherford** [comment]
Added to testcase:

![image](https://user-images.githubusercontent.com/6913354/97234260-af1ab700-179d-11eb-8371-b98aabedbec9.png)

Thanks!
