### ISSUE TITLE
.NET core installed and verified but still getting error

### ISSUE THREAD

**Issue by kaavik** [microsoft/vscode-azurearmtools#1081]
Does this occur consistently? 
Repro steps:

1. Install latest .NET core SDK from Microsoft on MacBook Pro 16
2. In VS Code, install Azure Resource Manager extension. This will also auto-install the .NET Install Tool for Extension Authors.
3. [Re]start VS Code and open azuredeploy.json with content as below:

`{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts",
      "apiVersion": "2019-04-01",
      "name": "popboxitTutorial",
      "location": "eastus2",
      "sku": {
        "name": "Standard_LRS"
      },
      "kind": "StorageV2",
      "properties": {
        "supportsHttpsTrafficOnly": true
      }
    }
  ]
}`

4. Without taking any further action, the error pops up in VS Code reporting "An error occurred while installing .NET: Dotnet Core Acquisition Failed: undefined
###

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined"

Version: 0.13.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:166:60234
Object.<anonymous> extension.bundle.js:239:55780
fulfilled extension.bundle.js:239:54595
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by StephenWeatherford** [comment]
@kaavik Did the troubleshooting steps help?  Thx.

**Comment by kaavik** [comment]
Hi Stephen,

Unfortunately, I the troubleshooting steps have not helped and I am still getting the messages below as soon as I open my Azure JSON file, even though from the terminal output on the left, you can clearly see that .NET core is successfully installed and in the default path for my bash shell. I also included the ‘which dotnet’ output in the screenshot below showing the full path to dotnet.

[cid:image001.png@01D6B10A.FB652EF0]

I would really like to get this sorted out.

Thanks,
CARTER

**Comment by StephenWeatherford** [comment]
@kaavik Unfortunately the image seems to not have made it through, so I might be missing some context, but try this...

The extension doesn't currently pick up dotnet from the path.  You can force it to use a local installation by going into settings in vscode and pointing it to the installation like this:

![image](https://user-images.githubusercontent.com/6913354/97910289-65caea00-1cfe-11eb-82fe-b7b4a20fa19f.png)
Once you restart, you should be able to find confirmation of the path used in the Output window:
![image](https://user-images.githubusercontent.com/6913354/97910380-81ce8b80-1cfe-11eb-9c0e-bc7f2a088960.png)

**Comment by kaavik** [comment]
Hi Stephen,

I followed your instructions and restarted. No errors!

Maybe silly question... what should be different now besides the lack of errors? Meaning, I was already starting to edit ARM templates and it seemed like it was working / had intellisense so I am wondering what the .NET Core functionality adds?

Regardless, it is great to not have errors when VS Code loads!

Thanks,
CARTER

**Comment by StephenWeatherford** [comment]
There are tons of additional features besides just schema intellisense.  See here for a quick summary, and you'll probably notice additional stuff once you start editing: https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools

Thanks for the info, and don't hesitate to ask additional questions!

**Comment by kaavik** [comment]
Thank you, Stephen!

CARTER
