### ISSUE TITLE
arm template issue

### ISSUE THREAD

**Issue by sjagadee** [microsoft/vscode-azurearmtools#1082]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.13.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.49.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:166:60234
Object.<anonymous> extension.bundle.js:239:55780
fulfilled extension.bundle.js:239:54595
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by StephenWeatherford** [comment]
@sjagadee Would love to know how you were able to resolve this.  Did you set the azureResourceManagerTools.languageServer.dotnetExePath setting, or something else?  Thanks!
