### ISSUE TITLE
[Suggestion] Add the "Go to Bracket" action in context menu for template file

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#1087]
**OS:** Windows 10
**Build Version:** 20201028.3

**Repro Steps:**
Check the context menu in a template file.

**Actual:**
There is no "Go to Bracket" action in context menu.
![image](https://user-images.githubusercontent.com/45614674/97972276-3c45b780-1dff-11eb-9820-7ac7b52f10ac.png)

**Suggestion:**
Add the "Go to Bracket" action in context menu, like the command palette. 
![image](https://user-images.githubusercontent.com/45614674/97972236-2cc66e80-1dff-11eb-9b92-b2041d05cde9.png)

**Comment by MarcusFelling** [comment]
To bring attention to the "Go to Bracket" cmd, I have added a mention of this to the README.
