### ISSUE TITLE
Installing .Net: Dot Net Core

### ISSUE THREAD

**Issue by ashutoshkrm** [microsoft/vscode-azurearmtools#1088]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.13.0
OS: darwin
OS Release: 17.7.0
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:166:60234
Object.<anonymous> extension.bundle.js:239:55780
fulfilled extension.bundle.js:239:54595
propagateAslWrapper async-listener/index.js:504:23
async-listener/index.js:541:70
```

</details>

**Comment by StephenWeatherford** [comment]
@ashutoshkrm I see you're on a Mac.  We've discovered an issue with installation on the Mac.  Please see https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition#mac-wget-not-found for help, and please let us know if this solves the problem.  Thanks!

**Comment by utami1511** [comment]
@StephenWeatherford  I am having similar issue Error acquiring .NET runtime #1094 which you closed.
You suggested to install wget in my linux wsl, and I have installed it as shown below;

 dpkg -l | grep wget
ii  wget                               1.19.4-1ubuntu2.2                   amd64        retrieves files from the web

it is still not working, is there any other steps I should do?

**Comment by StephenWeatherford** [comment]
First step, try again one more time (make sure you close and restart vscode first), I just got word that the wget fix for the dotnet scripts has gone live.  If it's still not working, could you please press F1 and then execute the following command:
![image](https://user-images.githubusercontent.com/6913354/98711609-0beba500-233a-11eb-9865-e6ed5157dd3d.png)
You'll need to make sure to attach the log file as requested.  @sfoslund will be able to help analyze the problem at that point.  Thanks!  It would be great if you could reference to the new bug here so we know if it gets resolved.
