### ISSUE TITLE
[Codespaces] There is no icon for resource items in the "ARM Template Outline" view

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#1091]
**Build Version:** 20201028.3
**Environment:** GitHub Codespaces (remote/browser)

**Repro Steps:**
1. Open a template file which has resource items.
2. Open the "ARM Template Outline" view and check the resource items.

**Expect:**
All resource items have icons.
![image](https://user-images.githubusercontent.com/45614674/98091825-e33e5800-1ec0-11eb-9117-b8016f3067eb.png)

**Actual:**
There is no icon for resource items.
![image](https://user-images.githubusercontent.com/45614674/98091892-f81aeb80-1ec0-11eb-953d-3de7da44f81c.png)

**Comment by MarcusFelling** [comment]
Unable to reproduce:
![image](https://user-images.githubusercontent.com/6855361/105404985-3ab2b100-5bf0-11eb-8b55-2f6fde861cda.png)
