### ISSUE TITLE
Error acquiring .NET runtime

### ISSUE THREAD

**Issue by utami1511** [microsoft/vscode-azurearmtools#1094]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.13.0
OS: linux
OS Release: 4.19.128-microsoft-standard
Product: Visual Studio Code
Product Version: 1.51.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:166:60234
Object.<anonymous> extension.bundle.js:239:55780
fulfilled extension.bundle.js:239:54595
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by StephenWeatherford** [comment]
@utami1511 There's a known issue with Mac/Linux that is currently being fixed.  In the meantime, you should be able to work around it by installing wget (e.g. https://www.tecmint.com/install-wget-in-linux/#:~:text=How%20to%20Install%20Wget%20in%20Linux.%201%20Install,OpenSUSE.%20%204%20Install%20wget%20on%20ArchLinux.%20).  Please let us know if this doesn't work, thanks!
