### ISSUE TITLE
Support validating subproperties of functions that return objects

### ISSUE THREAD

**Issue by bmoore-msft** [Microsoft/vscode-azurearmtools#11]
See: https://github.com/Microsoft/vscode-azurearmtools/blob/master/assets/ExpressionMetadata.json#L108

The return members on the function are: 
name
properties

And then the properties object contains these return members
properties.template
properties.templateLink
properties.parameters
properties.mode
properties.provisioningState

and some of those members also have children, see: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-deployment#deployment

Not sure if the extension supports it or how to author that in the expression metadata so I'm going to submit a PR to just fix the top level members...  Use this issue to track the remaining corrections.

**Comment by StephenWeatherford** [comment]
It doesn't look like this level of details is supported, just the top-level return values.  I.e., to add support for XXX in [template(...).properties.XXX] would require feature work.

**Comment by bmoore-msft** [comment]
That was my eval as well...

**Comment by PrashanthCorp** [comment]
Closing this. We'll wait for more external feedback regarding this.

**Comment by bmoore-msft** [comment]
What kind of feedback are you expecting?  As implemented this provides no value...  and I don't see much "feedback" around other issues that are being addressed, so I'm confused as to  what the bar is here.

**Comment by StephenWeatherford** [comment]
It's a question of priorities and resources. If customers need this kind of supports deeper into the tree than we currently support, and indicate so via feedback, we'll consider adding it.  But it would not be cheap to add it, and I'd say there are more important things.

**Comment by bmoore-msft** [comment]
How are we prioritizing?  I'm not seeing much feedback on a number of other items flowing through the repo either, but those are still being done.  Perhaps "Future" is a better way to direct this than dismissing it.
