### ISSUE TITLE
Error While loading ARM extension in VS code

### ISSUE THREAD

**Issue by chiragce17** [microsoft/vscode-azurearmtools#1100]
Does this occur consistently? 
Repro steps:

1. Tried to reinstall the ARM extension but doesn't load.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:166:60234
Object.<anonymous> extension.bundle.js:239:55780
fulfilled extension.bundle.js:239:54595
```

</details>

**Comment by StephenWeatherford** [comment]
@chiragce17 Did the troubleshooting tips help?  I recently updated them (https://aka.ms/vscode-armtools-dotnet).  If that doesn't help, could you please use F1 to execute the following command to enter an issue that the dotnet team can debug?
![image](https://user-images.githubusercontent.com/6913354/98983025-12625400-24d5-11eb-8389-67b80eca409c.png)
You'll need to include the log file as requested.  These instructions are also in the troubleshooting guide.

Thanks!

**Comment by StephenWeatherford** [comment]
Feel free to reactivate if you have more questions.
