### ISSUE TITLE
The parameter name in template file isn't highlighted when selecting it from the references list

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#1103]
**OS:** Win 10
**Build Version:** 20201111.14

**Repro Steps:**
1. Open a template file and create a parameter file for it.
2. Navigate to the parameter file -> Click on a parameter name -> Shift+F12.
3. Select one reference of the template file from the references list.
4. Check the left side of the references list.

**Expect:**
The parameter name in template file is highlighted, like it in parameter file.
![image](https://user-images.githubusercontent.com/45614674/99045205-f42b4f80-25cb-11eb-8b1e-bcabe948f60b.png)

**Actual:**
The parameter name in template file isn't highlighted.
![image](https://user-images.githubusercontent.com/45614674/99045185-eaa1e780-25cb-11eb-8b3b-d57fdac11847.png)

**More Info:**
This issue does not reproduce if get the references list from template file.

**Comment by StephenWeatherford** [comment]
Not sure why the difference, but we don't control this so couldn't fix it either way. Thanks.
