### ISSUE TITLE
The completions list changes from the parameter list to the function list when typing a letter for the parameter

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1104]
**OS:** All
**Build Version:** 20201111.14

**Repro Steps:**

1. Open new-vm,json template file in VS Code.
2. Find a parameter -> Remove the contents of the string -> Type CTRL+SPACE.
3. Check the completions list of parameter.
4. Type "a" into this brackets.
5. Check the completions list.

**Expect:**
You should only see the item contained "a" in the completions list of parameter.

**Actual:**
The completions list changes from the parameter list to the function list.
![arm](https://user-images.githubusercontent.com/62053665/99044491-cc87b780-25ca-11eb-9e45-18aa5f260516.gif)

**More Info:**

1. This issue also reproduces for variables.
2. This issue doesn't reproduce for functions.
3. This issue doesn't reproduce when typing apostrophe -> type"a".
  ![arm1](https://user-images.githubusercontent.com/62053665/99044826-58014880-25cb-11eb-910e-8628587f2bbc.gif)

**Comment by StephenWeatherford** [comment]
Filtering does work here if you first type a single quote and then start typing characters.  I'm personally okay with this, but we should discuss...

**Comment by MarcusFelling** [comment]
Showing functions is intentional
