### ISSUE TITLE
[Suggestion] Change the oldest VS Code version that the latest ARM extension supported

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#1105]
**OS:** Windows 10
**Build Version:**20201111.14
**VS Code Version:** 1.41.1

**Repro Steps:**
1. Figure out the oldest VS Code version that the ARM extension supported-->1.41.0
2. Install an older VS Code 1.41.1.
3. Install ARM extension to VS Code 1.41.1.
4. Open a template file and create associated parameter files for it.
5. Check the parameter files in user setting "Azure Resource Manager Tools: Parameter Files".

**Actual:**
There is no parameter file in the user setting "Azure Resource Manager Tools: Parameter Files".
![image](https://user-images.githubusercontent.com/45614674/99066084-5fcce700-25e3-11eb-9aa1-5cacb0a6da64.png)

**Suggestion:**
Change the oldest VS Code version that the ARM extension supported in ARM extension.

**Comment by StephenWeatherford** [comment]
That's okay, they still supported the setting.  They just didn't used to support editing it directly inside the settings editor, you had to click "Edit in settings.json" to edit it there.

**Comment by StephenWeatherford** [comment]
I will note that I can't install anything earlier than feb 2020 (1.43) with Catalina installed, so it would be hard for me to support before that.  Maybe it's worth updating to 1.43 because of that.
