### ISSUE TITLE
Unknown error on ARM template extension

### ISSUE THREAD

**Issue by akorany** [microsoft/vscode-azurearmtools#1107]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.13.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:166:60234
Object.<anonymous> extension.bundle.js:239:55780
fulfilled extension.bundle.js:239:54595
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by StephenWeatherford** [comment]
Please do F1 and then run the following command:

![image](https://user-images.githubusercontent.com/6913354/99117920-6e97a780-25ab-11eb-9501-776e2b0d7428.png)

That will report the issue to the correct team.  Thanks!
