### ISSUE TITLE
The options contained "o" are incomplete in the completion list 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1110]
**OS:** All
**Build Version:** 20201113.10

**Repro Steps:**

1. Create a template file with these contents:
```
		{
		"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
		"contentVersion": "1.0.0.0",
		"variables": {
		"abc": {
		"one": 1,
		"two": {
		"three": 2
		}
		},
		"v1": "[variables('abc').two.three]",
		"v2": "[parameters('def')]"
		},
		"parameters": {
		"def": {
		"type": "object",
		"defaultValue": {
		"one": 1,
		"two": {
		"three": 2
		}
		}
		}
		},
		"resources": [],
		"outputs": {
		"a": {
		"type": "string",
		"value": "[concat(variables('v1'),variables('v2'))]"
		}
		}
		}	
```
2. Click right after the closing parenthesis after variables('abc') in "v1" and type a period (".") -> Type "o".
3. Check the options in the completion list.

**Expect:**
Show all options contained "o" in the completion list, something like below.
![image](https://user-images.githubusercontent.com/62053665/99509024-371c6700-29c0-11eb-84cd-a462560782ac.png)

**Actual:**
There is only "one" in the completion list.
![a rm1](https://user-images.githubusercontent.com/62053665/99504144-0df8d800-29ba-11eb-959f-c4a5f965dbad.gif)

**More Info:**
This issue also reproduces for GitHub Codespaces.

**Comment by StephenWeatherford** [comment]
Weird, that should work.  But it's a minor scenario, not worth fixing.
