### ISSUE TITLE
The "Select or create a parameter file to enable full validation..." does not appear after selecting "arm!"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1111]
**OS:** All
**Build Version:** 20201113.10

**Repro Steps:**

1. Create a new template file but don't save it in VS Code -> Type "arm" and CTRL+SPACE -> Select "arm!".
2. Check whether "Select or create a parameter file to enable full validation..." appears or not.

**Expect:**
The "Select or create a parameter file to enable full validation..." appears after step 1.

**Actual:**
The "Select or create a parameter file to enable full validation..." does not appear after step 1.
![a rm3](https://user-images.githubusercontent.com/62053665/99515781-5f0fc880-29c8-11eb-865d-fe29575dd7e5.gif)

**More Info:**
The "Select or create a parameter file to enable full validation..." appears after scrolling mouse.

**Comment by StephenWeatherford** [comment]
Thanks. Looks like a vscode problem.  Either way, not a major issue.
