### ISSUE TITLE
There are options do not contain the letter in the completion list when typing a letter in double quote

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1113]
**OS:** All
**Build Version:** 20201113.10

**Repro Steps:**

1. Open dependon-with-copy2.json file in VS Code -> Click on the second resource and delete the existing dependsOn property  -> Type a letter, e.g. "o".
2. Check the completions list.

**Expect:**
Show all options contained the letter in the completion list.

**Actual:**
There are two options do not contain the letter in the completion list, e.g. "o".
![image](https://user-images.githubusercontent.com/62053665/99781664-1df7ef80-2b53-11eb-8632-7f89dfb40dde.png)

**Comment by StephenWeatherford** [comment]
The search also occurs on information that doesn't appear in the title (description, etc.).  So this is desired if not ideal behavior.

**Comment by v-mengwe** [comment]
@StephenWeatherford Sorry I don't understand what you mean.

> The search also occurs on information that doesn't appear in the title (description, etc.). So this is desired if not ideal behavior.

When typing a letter "o", the completion list displays as the following:
![image](https://user-images.githubusercontent.com/62053665/99932180-47eb2500-2d92-11eb-9236-6b42ae98dc2a.png)
When typing a letter "l", the completion list displays as the following:
![image](https://user-images.githubusercontent.com/62053665/99932332-a1535400-2d92-11eb-9fd6-577b5b0399ce.png)
When typing a letter "j", the completion list displays as the following:
![image](https://user-images.githubusercontent.com/62053665/99932102-09ee0100-2d92-11eb-978f-b9a1ac9c4642.png)
There is no rule between the completion list and the letters typed.
