### ISSUE TITLE
The typed letters in the completions list are not highlighted

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1114]
**OS:** All
**Build Version:** 20201113.10

**Repro Steps:**

1. Open dependon-with-copy2.json file in VS Code -> Click on the second resource and delete the existing dependsOn property -> Type a letter, e.g. "c".
2. Check the completions list.

**Expect:**
The letters "c" in the completions list are highlighted.

**Actual:**
The letters "c" in the completions list are not highlighted.
![image](https://user-images.githubusercontent.com/62053665/99785789-9a410180-2b58-11eb-80b8-fa8e761920fd.png)

**More Info:**
This issue doesn't reproduce for resources/variables/parameters/functions/outputs.
![image](https://user-images.githubusercontent.com/62053665/99785613-564dfc80-2b58-11eb-8c2e-96307e926517.png)
![image](https://user-images.githubusercontent.com/62053665/99785665-682f9f80-2b58-11eb-9d61-227542bb157f.png)

**Comment by StephenWeatherford** [comment]
Don't know why this is doing that, but not worth the effort to fix, I think.
