### ISSUE TITLE
[Suggestion] It’s friendly to add a right arrow when hovering over the right-hand side of the completion list

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1115]
**OS:** All
**Build Version:** 20201113.10

**Repro Steps:**

1. Open a template file in VS Code -> The cursor in a parameter -> Press CTRL+SPACE.
2. Hover over the right-hand side of the completions list -> Check the result.

**Actual:**
There is no right arrow.
![image](https://user-images.githubusercontent.com/62053665/99787451-b80f6600-2b5a-11eb-9cdc-c252ade4153d.png)

**Suggestion:**
It’s friendly to add a right arrow when hovering over the right-hand side of the completion list, especially there are too many options in the completions list.

**More Info:**
 It will be fixed when selecting and hovering over a option.
![image](https://user-images.githubusercontent.com/62053665/99787325-91512f80-2b5a-11eb-995d-6c471610e26c.png)

**Comment by StephenWeatherford** [comment]
Sorry, we don't control this, vscode does.
