### ISSUE TITLE
There is a new error after executing "Extract Parameter" action for a "type" string inside the errors.json template file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1117]
**OS:** All
**Build Version:** 20201120.3

**Repro Steps:**

1. Open the `errors.json` template file in VS Code -> Place the cursor inside the "type" string somewhere inside the "resources" section of a template -> Click the lightbulb -> Click "Extract Parameter..." -> Type a parameter name -> Type a description.
2. Check whether there is a new error or not.

**Expect:**
There is no new error.

**Actual:**
There is a new error.
![image](https://user-images.githubusercontent.com/62053665/99945432-95c25600-2daf-11eb-9506-556aa310ea45.png)

> `Template validation failed: The template resource '[parameters('automationAccountName')]' at line '84' and column '36' is not valid. The type property cannot be an expression. Please see https://aka.ms/arm-template/#resources for usage details.`

**More Info:**

1. This issue doesn't reproduce for other template files.
2. This issue also reproduces for `object-variable-properties.json` template file.
   ![image](https://user-images.githubusercontent.com/62053665/99942348-81c82580-2daa-11eb-816d-6496efbe7865.png)
3. This issue also reproduces after executing "Extract Variable..." action.
4. The error message does not correspond to the error location if this error is by design.
   ![image](https://user-images.githubusercontent.com/62053665/99943015-922cd000-2dab-11eb-8d15-591c09bfbd91.png)![image](https://user-images.githubusercontent.com/62053665/99939945-301d9c00-2da6-11eb-81ac-67c68ddbd3ea.png)

**Comment by StephenWeatherford** [comment]
@jorgecotillo This didn't used to be required, right?  Is this a change?

**Comment by StephenWeatherford** [comment]
This is an expected error - see this note in the testcase:
![image](https://user-images.githubusercontent.com/6913354/105429385-2da0bc80-5c06-11eb-9fbf-ae5913d92f09.png)

Ideally we shouldn't show the lightbulb for extract inside this string, but that works is probably not worth the effort.  Thx.
