### ISSUE TITLE
The variable definition isn't changed if rename the variable definition only with spaces

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1120]
**OS:** Win10
**Build Version:** 20201120.3

**Repro Steps:**

1. Open a template file in VS Code -> Click on a variable definition -> F2 -> Rename variable definition with spaces.
2. Check whether rename the variable definition successfully.

**Expect:**
The variable definition is changed to spaces.

**Actual:**
The variable definition isn't changed.
![aaa](https://user-images.githubusercontent.com/62053665/101134294-19e4cb00-3645-11eb-9c36-6c843ef9217d.gif)

**More Info:**

1. This issue doesn't reproduce when typing "spaces+letters", e.g "  aa" or "aa  ".
  ![image](https://user-images.githubusercontent.com/62053665/101134644-abecd380-3645-11eb-9627-902105d05e27.png)
3. This issue also reproduces for a parameter definition.

**Comment by StephenWeatherford** [comment]
Wouldn't expect this to work. Spaces before/after not worth worrying about, thanks.
