### ISSUE TITLE
The result of renaming is inconsistent with the typed value

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1121]
**OS:** Win10
**Build Version:** 20201120.3

**Repro Steps:**

1. Open a template file in VS Code -> Click on a variable definition -> F2 -> Rename variable definition with `'test'aa`.
2. Check whether rename the variable definition successfully.

**Expect:**
The variable definition has changed to `'test'aa`.

**Actual:**
The variable definition has changed to `test`.
![aa](https://user-images.githubusercontent.com/62053665/101132026-3aab2180-3641-11eb-9dff-795db6281792.gif)

**More Info:**
This issue also  reproduces for a parameter definition.
Details for other situations of renaming:
![image](https://user-images.githubusercontent.com/62053665/101132980-de490180-3642-11eb-9f8e-94fe27321bf7.png)

**Comment by StephenWeatherford** [comment]
test'aa is not a valid variable name, so not worth fixing.  Thanks.
