### ISSUE TITLE
No location given for errors in evaluating linked template parameter values

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#1124]
```
{
    // Verify correct scope of expressions, variables, parameters

    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [ 
        {
            "name": "linkedDeployment1",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2019-10-01",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "relativePath": "child.json"
                },
                "parameters": {
                    "intParam": {
                        "value": "[concat(parameters('missingParam'))]"
                    }
                }
            }
        }
    ]
}
```
EXPECTED: The error should give an indication of where it occurred.
ACTUAL:
We get this error:
{
	"resource": "/Users/stephenweatherford/repos/vscode-azurearmtools/test/templates/linkedTemplates/tc12/tc12.json",
	"owner": "ARM Template Language Server diagnostics",
	"severity": 8,
	"message": "Template validation failed: The template parameter 'mainTemplateParam' is not found. Please see https://aka.ms/arm-template/#parameters for usage details.",
	"source": "arm-template (validation)",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

![image](https://user-images.githubusercontent.com/6913354/101668685-aefd1080-3a05-11eb-8a75-bee98b1f922d.png)

**Comment by jorgecotillo** [comment]
Is 'mainTemplateParam' from child.json? Or from the main template? In the main template I see this:
"value": "[concat(parameters('missingParam'))]" so I'd expect the error message to say 'missingParam' not found instead.

I'll investigate why it says line: 0, it should provide "properties" line number.

**Comment by StephenWeatherford** [comment]
Sorry, seem to be missing some information, and I can't recreate it at the moment.  If it was important, it'll come up again and I'll re-enter.  Thanks!
