### ISSUE TITLE
Missing support for resources of type Microsoft.Subscription/aliases

### ISSUE THREAD

**Issue by m1no** [microsoft/vscode-azurearmtools#1127]
The type "Microsoft.Subscription/aliases" let the validation fail and stops the user from getting an outline. 

The resource type is defined here:
https://docs.microsoft.com/en-us/azure/templates/microsoft.subscription/aliases
to achieve this
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-microsoft-customer-agreement?tabs=rest-getBillingAccounts%2Crest-getBillingProfiles%2Crest-MCA

**Comment by StephenWeatherford** [comment]
This is only valid for deployment to a tenant, right?  The following template works for me.  *Note that the $schema must correctly point to a tenant deployment*:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-08-01/tenantDeploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {},
    "resources": [
        {
            "name": "string",
            "type": "Microsoft.Subscription/aliases",
            "apiVersion": "2020-09-01",
            "properties": {
                "displayName": "string",
                "workload": "Production",
                "billingScope": "string",
                "subscriptionId": "string",
                "resellerId": "string"
            }
        }
    ],
    "outputs": {}
}
```

**Comment by StephenWeatherford** [comment]
Please let me know if this doesn't address the issue, thanks!

**Comment by StephenWeatherford** [comment]
This warning is new in the current version:
![image](https://user-images.githubusercontent.com/6913354/105394555-979f6e80-5bd2-11eb-9887-0da702f88045.png)
