### ISSUE TITLE
Support for pickZones function

### ISSUE THREAD

**Issue by bgold09** [microsoft/vscode-azurearmtools#1130]
The extension currently does not recognize the [pickZones() function](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource?tabs=json#pickzones), resulting in false positives for syntax errors as well as missing Intellisense.

**Comment by StephenWeatherford** [comment]
@bgold09 Thanks for letting us know!  I'm currently out of office, but can get to this early next year.  Feel free to submit a PR for it yourself in https://github.com/microsoft/vscode-azurearmtools/blob/main/assets/ExpressionMetadata.json.

**Comment by StephenWeatherford** [comment]
@bgold09 Thanks!  Would you like access to an alpha version with the fix?

**Comment by bgold09** [comment]
That's alright, happy to wait for the normal release. Is there a regular release cadence?

**Comment by StephenWeatherford** [comment]
Not scheduled, no, but would like to do a point release soon (next week or two).  The next major release is several weeks away.  Will let you know when it comes out.

**Comment by StephenWeatherford** [comment]
@bgold09 This was just released, thanks again for your contribution!  Had intended to release earlier but got blocked by some schema regressions.

**Comment by bgold09** [comment]
No worries, I just updated to the latest version and it all works 😄
