### ISSUE TITLE
Schema validation for 'backupManagementType' is incorrect

### ISSUE THREAD

**Issue by RaphaelFrancisco** [microsoft/vscode-azurearmtools#1131]
When templating the deployment of _Microsoft.RecoveryServices/vaults/backupPolicies_ types, with _2016-12-01_ as API version, the values for property **backupManagementType** are not properly recognized.

The full explanation for that property is somehow missing from the _2016-12-01_ API version page:
https://docs.microsoft.com/en-us/azure/templates/microsoft.recoveryservices/2016-12-01/vaults/backuppolicies

However, it can be found in the _2016-06-01_ API version page:
https://docs.microsoft.com/en-us/azure/templates/microsoft.recoveryservices/2016-06-01/vaults/backuppolicies

Details for the **backupManagementType** are as follows:

Name | Type | Required | Value
-------|-------|-----------|-------
backupManagementType | string | Yes | This property will be used as the discriminator for deciding the specific types in the polymorphic chain of types. - AzureWorkload, AzureStorage, AzureIaasVM, AzureSql, GenericProtectionPolicy, MAB

However, the only value recognized by the ARM Tools schema validation is _AzureStorage_, as seen in the following screenshot:
![Imgur](https://i.imgur.com/HGo1enB.jpg)

Any other valid value (such as _AzureIaasVM_) entered for that property is received with a warning, as seen in the screenshot above. That is not a big issue, but for developers aiming to have code that is clean and free of warnings, it may be a nuisance.

More info on that specific schema can be found here:
https://schema.management.azure.com/schemas/2016-12-01/Microsoft.RecoveryServices.json#/resourceDefinitions/vaults_backupPolicies

**Comment by RaphaelFrancisco** [comment]
Same issue with **protectedItemType** when deploying _Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers/protectedItems_ types with _2016-12-01_ as API version. The ARM Tool schema validation says the value for that property must be _AzureIaasVMProtectedItem_, but it actually can be a range of different values.

![Imgur](https://i.imgur.com/ZsakUf4.jpg)

**Comment by MarcusFelling** [comment]
@RaphaelFrancisco Are you using the latest root schema ($schema value at top of template)? If not, try updating to https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json# I'm not able to recreate this, but I may be missing something...

![image](https://user-images.githubusercontent.com/6855361/103559804-57bf5400-4e7c-11eb-887a-b3a63174c338.png)

No warnings using AzureIaasVM:
![image](https://user-images.githubusercontent.com/6855361/103559871-76bde600-4e7c-11eb-8fc7-bf15d652b3fc.png)

Note: It looks like Microsoft.RecoveryServices RP schema is not yet set up for autogeneration: https://github.com/Azure/azure-resource-manager-schemas/pull/1229 

An explanation can be found here: https://github.com/Azure/azure-resource-manager-schemas/wiki/Unrecognized-Resource-API-Version

**Comment by RaphaelFrancisco** [comment]
@MarcusFelling thanks for taking the time to look into this. Yes, I am using the latest root schema (2019-04-01), but somehow I still see this issue. Values other than "AzureStorage" are not recognized as valid ones and a warning is thrown.

Other than the root schema, is there any other variable that may be responsible for the behavior I am seeing?
My ARM Tools is v0.14.0, that is the latest, right? Not sure whether this is relevant though.

**Comment by StephenWeatherford** [comment]
@RaphaelFrancisco Can you post a small template that repros this?  Thx.

**Comment by RaphaelFrancisco** [comment]
I still see this issue with the following single-resource template:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "rvName": {
            "type": "string"
        }
    },
    "resources": [
        {
            "apiVersion": "2016-12-01",
            "type": "Microsoft.RecoveryServices/vaults/backupPolicies",
            "name": "[concat(parameters('rvName'), '/DailyPolicy')]",
            "properties": {
                "backupManagementType": "AzureIaasVM",
                "timeZone": "UTC",
                "schedulePolicy": {
                    "scheduleRunFrequency": "Daily",
                    "schedulePolicyType": "SimpleSchedulePolicy",
                    "scheduleRunTimes": [
                        "13:00"
                    ]
                },
                "retentionPolicy": {
                    "retentionPolicyType": "LongTermRetentionPolicy",
                    "dailySchedule": {
                        "retentionDuration": {
                          "count": 180,
                          "durationType": "Days"
                        },
                        "retentionTimes": [
                            "13:00"
                        ]
                    }
                }
            }
        }
    ]
}
```

Here is an image showing the yellow squiggly line characteristic of the warning:
![Imgur](https://i.imgur.com/QolsH8Z.jpg)

**Comment by StephenWeatherford** [comment]
@RaphaelFrancisco Thanks for bringing this to our attention!  We've ported to bug to the Azure schemas repo.
