### ISSUE TITLE
There are extra items in the IntelliSense list after typing CTRL+SPACE in a parameter file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1133]
**OS:** Win 10
**Build Version:** 20201214.1

**Repro Steps:**

1. Open a parameter file in VS Code -> Place the cursor after the "}" at the end of the parameter value 
-> Type a comma (",") -> Type Enter -> Type CTRL+SPACE.
2. Check whether the IntelliSense list is correct.

**Expect:**
There are no extra items in the IntelliSense list.

**Actual:**
There are extra items in the IntelliSense list.
![image](https://user-images.githubusercontent.com/62053665/103080214-55553280-4610-11eb-8e9d-05e78845ebaa.png)

Details for steps:
![ar](https://user-images.githubusercontent.com/62053665/103080238-63a34e80-4610-11eb-9317-bfd492259a05.gif)

**Comment by StephenWeatherford** [comment]
We'd have to create a new langid for parameter files in order to fix. Not worth the effort.
