### ISSUE TITLE
contentVersion for linked/nested templates should be matched against the linked/nested template, not the main template

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#1145]
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.2.3.4",
    "variables": {
        "stringValue": "abc",
        "nestedDeployment2Name": "nestedDeployment2",
        "mode": "Incremental"
    },
    "resources": [
        {
            "name": "[variables('nestedDeployment2Name')]",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2017-05-10",
            "properties": {
                "mode": "[variables('mode')]",
                "templateLink": {
                    // THESE REFER TO THE TOP-LEVEL PARAMS/VARS
                    "uri": "https://abc.foo",
                    "contentVersion": "4.3.2.1"
                },
                "parameters": {
                    "linked2param1": {
                        "value": "[variables('stringValue')]"
                    }
                }
            }
        }
    ],
    "outputs": {},
    "functions": []
}
```
Gives error:
Template validation failed: The content version contained in the template '1.2.3.4' does not match the content version found in the deployment object's TemplateLink property '4.3.2.1'. Please see https://aka.ms/arm-deploy for usage details.

EXPECTED: should load the template and match 1.2.3.4 against the linked template, not the main template

**Comment by jorgecotillo** [comment]
@bmoore-msft can you please explain what is the purpose of contentVersion? I can speak for what I see in the code and the code is expecting the contentVersions to match, so from the code perspective we are returning the right error message.

**Comment by bmoore-msft** [comment]
I don't know of a purpose for it - but I think it's doing what what Stephen suggested, I don't think it's validating against it's parent contentVersion.  Of course, you would never know that from the error message.

It would be worth entertaining a conversation as to whether we should force them to match (as I know of no purpose for it) but it would be a breaking change.

**Comment by jorgecotillo** [comment]
That was my main mistake, the error message didn't specify which contentVersions are not matching and I thought it was against the main template. With the inclusion of TemplateSpecs (which can be versioned), not sure if we still need contentVersion, something to talk about.

**Comment by jorgecotillo** [comment]
@StephenWeatherford I have a fix in place with the corresponding tests, will create a PR next week.

**Comment by StephenWeatherford** [comment]
Thx.
