### ISSUE TITLE
Allow manual selection of "JSON"/"JSONC" language options in VSCode

### ISSUE THREAD

**Issue by anthony-c-martin** [microsoft/vscode-azurearmtools#1151]
If I have an ARM template open in VSCode, the ARM VSCode extension automatically detects that it's an ARM template, based on the fact that it's a JSON file, with a known ARM template schema.

Occasionally I'd like to have the ability to use the JSON/JSONC language service with the ARM features disabled, but when I manually set the language in VSCode to "JSON", it immediately gets reverted to "Azure Resource Manager Template".

To repro:
1. Open an ARM template JSON file in VSCode. VSCode automatically sets the language mode to "Azure Resource Manager Template".
2. Select "Change Language Mode" in the command palette, and select "JSON" or "JSONC".
3. The language mode (displayed in the bottom right of the window) is temporarily changed, but then reverted back to "Azure Resource Manager Template".

AFAIK this generally works with the other language options - if I try to manually override a .cs to "TypeScript", I'm able to.

**Comment by StephenWeatherford** [comment]
This has been a long-standing known issue, but you're the first to complain, so we haven't spent time on the fix.  As a work-around, you can temporarily turn off this setting:

![image](https://user-images.githubusercontent.com/6913354/106040827-d3817a80-608f-11eb-82da-0c8b778d8fc3.png)
