### ISSUE TITLE
Incorrect validation errors in user-defined functions when using recently added builtin functions (createObject etc.)

### ISSUE THREAD

**Issue by jberezanski-mdg** [microsoft/vscode-azurearmtools#1153]
It seems that the validation logic for user-defined functions does not recognize the four new builtin functions that have recently been added (https://github.com/MicrosoftDocs/azure-docs/commit/be56ab92a33c673e858fc812339ea0610dafcfc1, https://github.com/microsoft/vscode-azurearmtools/issues/1043#issuecomment-710433636).

This template

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [
        {
            "namespace": "test",
            "members": {
                "testNewFunctions": {
                    "parameters": [],
                    "output": {
                        "value": "[
                            createArray(
                                true(),
                                false(),
                                null(),
                                createObject('name', 'foo')
                            )]",
                        "type": "array"
                    }
                }
            }
        }
    ],
    "resources": [],
    "outputs": {
        "result": {
            "type": "array",
            "value": "[test.testNewFunctions()]"
        }
    }
}
```

triggers this warning in VSCode: `
Template validation failed: The template function 'testNewFunctions' at line '11' and column '31' is not valid. These function calls are not supported in a function definition: 'true,false,null,createObject'. Please see https://aka.ms/arm-template/#functions for usage details.`

but the deployment actually succeeds:

```
> New-AzResourceGroupDeployment -Name 'test' -ResourceGroupName 'test-rg' -TemplateFile .\test.json

DeploymentName          : test
ResourceGroupName       : test-rg
ProvisioningState       : Succeeded
Timestamp               : 2021-02-01 13:31:24
Mode                    : Incremental
TemplateLink            :
Parameters              :
Outputs                 :
                          Name             Type                       Value
                          ===============  =========================  ==========
                          result           Array                      [
                            true,
                            false,
                            null,
                            {
                              "name": "foo"
                            }
                          ]

DeploymentDebugLogLevel :
```

`msazurermtools.azurerm-vscode-tools` extension version: 0.14.0

**Comment by StephenWeatherford** [comment]
Repros with current bits.

**Comment by jorgecotillo** [comment]
As mentioned before, this issue is because the template validation code _**does not know**_ about true, false, null and createObject functions, these are new and not included in the validation code. For now, the fix is to port these over the validation code, the long term and suggested approach is to use the public Azure.Deployments.Expressions nuget package to avoid code duplication.

**Comment by StephenWeatherford** [comment]
Fixed in next release.

**Comment by StephenWeatherford** [comment]
@jberezanski-mdg This was released on Monday.  Let us know if you're still having problems, thanks.

**Comment by jberezanski-mdg** [comment]
Thank you, it seems to be working fine.
