### ISSUE TITLE
Linked deployment apiVersion that can handle relativePath is missing in schema

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#1174]
Confused, thought this worked...

Using 2020-10-01 for apiVersion gives a schema warning:
For full schema validation, consider updating the value to one of the following: "2015-01-01", "2015-11-01", "2016-02-01", "2016-07-01", "2016-09-01", "2017-05-10", "2018-02-01", "2018-05-01", "2019-03-01", "2019-05-01", "2019-05-10", "2019-07-01", "2019-08-01", "2019-10-01", "2020-06-01". It is possible that the current resource version is valid but that a schema has not been generated. For more information see https://aka.ms/arm-tools-apiversion.

BUT, using 2020-06-01 (which is what our snippets use, and which contains the relativePath property) gives this during deployment:

  "error": {
    "code": "InvalidTemplate",
    "message": "The deployment definition is invalid; TemplateLink RelativePath can only be used with a Uri in api-version '2020-10-01' or later."
  }

```
{
    // backslashes

    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {},
    "resources": [
        {
            "name": "linkedDeployment1",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2020-10-01",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "relativePath": "subfolder/child2.json"
                }
            }
        }
    ]
}

```

**Comment by StephenWeatherford** [comment]
@anthony-c-martin cc @MarcusFelling This will block us shipping linked template support.

Anthony - can you see why the 2020-10-01 version of Microsoft.Resources/deployments has not been published?  (It's possible it's not in my snapshot, I'll try updating that soon.). It's seems to be missing?

We updated our snippets to use the 2020-06-01 version, which supports the relativePath property.  However, when I tried deploying that yesterday, Azure said "The deployment definition is invalid; TemplateLink RelativePath can only be used with a Uri in api-version '2020-10-01' or later."  Why is relativePath accepted in 2020-06-01 if Azure won't allow it to be deployed?  (Is it possible this is a change?  This is the first I've noticed this problem.)

We need either 2020-06-01 deployment to work and/or the 2020-10-01 schema to be published.  Thanks!

**Comment by StephenWeatherford** [comment]
I updated the schema snapshot and still getting the same error.

**Comment by anthony-c-martin** [comment]
@StephenWeatherford I think https://github.com/Azure/azure-resource-manager-schemas/pull/1498 should unblock this. Is this now working?

**Comment by StephenWeatherford** [comment]
@anthony-c-martin Yes, thanks!
