### ISSUE TITLE
error

### ISSUE THREAD

**Issue by krolikowski80** [microsoft/vscode-azurearmtools#1179]
The issue text was copied to the clipboard.  Please paste it into this window.

Does this occur consistently? 
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: An error occurred in the ARM Template Language Server.

Cannot call write after a stream was destroyed

Version: 0.14.1
OS: linux
OS Release: 5.10.11-1.el8.elrepo.x86_64
Product: Visual Studio Code
Product Version: 1.53.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:239:56634
Object.callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:139015
WrappedErrorHandler.error extension.bundle.js:239:56427
LanguageClient.handleConnectionError vscode-languageclient/client.js:2064:55
errorHandler vscode-languageclient/client.js:2020:18
vscode-languageclient/client.js:35:36
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
writeErrorHandler vscode-jsonrpc/main.js:235:22
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageWriter.fireError vscode-jsonrpc/messageWriter.js:33:27
Socket.<anonymous> vscode-jsonrpc/messageWriter.js:57:51
Socket.emit events.js:315:20
errorOrDestroy destroy.js:108:12
onwriteError _stream_writable.js:418:5
onwrite _stream_writable.js:445:5
doWrite _stream_writable.js:399:11
writeOrBuffer _stream_writable.js:387:5
Socket.Writable.write _stream_writable.js:318:11
StreamMessageWriter.write vscode-jsonrpc/messageWriter.js:71:27
vscode-jsonrpc/main.js:810:35
Object.sendRequest vscode-jsonrpc/main.js:800:26
Object.shutdown vscode-languageclient/client.js:45:36
vscode-languageclient/client.js:1946:31
```

</details>

**Comment by MarcusFelling** [comment]
@krolikowski80 is this a reoccurring issue? Are there any additional details that would help us repro this?

**Comment by StephenWeatherford** [comment]
Also, if you could share the output from the Output tab when this happens, it would be helpful, thanks!

![image](https://user-images.githubusercontent.com/6913354/107692397-973e4480-6c61-11eb-9a5c-77b7c05efdb2.png)
