### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by abdelrazekrizk** [microsoft/vscode-azurearmtools#1184]
- Issue Type: `Bug`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.14.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by StephenWeatherford** [comment]
@abdelrazekrizk This bug report doesn't provide any information about the problem or what happened.  Did you forget to paste the data from the clipboard?  Thanks.
