### ISSUE TITLE
Microsoft.Instaights/autoScaleSettings not recognized as valid resource type.

### ISSUE THREAD

**Issue by jwittner** [Microsoft/vscode-azurearmtools#119]
I get 'Value is not accepted' for my resource which has:

```json
"type": "Microsoft.Insights/autoscaleSettings",
"apiVersion": "2015-04-01",
```

If someone can point me to where the extension is validating these values I'd be interested in contributing a fix. =)

**Comment by bmoore-msft** [comment]
resourceTypes come from the schemas, here: https://github.com/Azure/azure-resource-manager-schemas - that schema is missing so the resource gets flagged...  not an issue in VS Code - but filing an issue over there helps.

**Comment by StephenWeatherford** [comment]
Closing since this is not an issue with the extension itself.
