### ISSUE TITLE
The childTemplate.json file doesn't open by clicking "Relative linked template" when the cursor doesn't place on the "childTemplate.json"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#1196]
**OS:** Windows
**Build Version:** 20210218.5

**Repro Steps:**

1. Create a main.json template file --> CTRL+Click on "childTemplate.json" and choose "Create file" to create a new file.
2. Create a parameter file for main.json.
3. Navigate to main.json file and make sure the cursor doesn't place on the `"childTemplate.json"`.
![image](https://user-images.githubusercontent.com/57662131/108488324-33f48800-72db-11eb-9fc7-849f16cd12d6.png)
4. Click `Relative linked template:".\childTemplate.json"`.
5. Check whether the childTemplate.json file opens or not.

**Expect:**
The childTemplate.json file opens successfully.

**Actual:**
The childTemplate.json file doesn't open.
![save1](https://user-images.githubusercontent.com/57662131/108481912-bd07c100-72d3-11eb-9278-723bfbdba0b9.gif)

**More Info:**
The childTemplate.json file opens when the cursor places on the `"childTemplate.json"`.
![save2](https://user-images.githubusercontent.com/57662131/108481934-c2fda200-72d3-11eb-94ab-f4c0099663c8.gif)

**Comment by StephenWeatherford** [comment]
Fixed by #1217
