### ISSUE TITLE
Errors when there are none

### ISSUE THREAD

**Issue by yobyot** [Microsoft/vscode-azurearmtools#120]
I'd love to use this extension with vscode -- but it's not reliable.

Consider the screenshot attached. On the left is a template file with errors. On the right is a template file with no errors. The difference between the two is that I edited the template file on the left to change the names of the first two parameters.

After wasting an hour searching for the "error", I just deployed the template with its associated parameter file, which worked perfectly.

I also tried uninstalling and reinstalling the extension.

I wanna love ARM templates in vscode -- but if the vscode extension cannot reliably flag errors, it's worse than notepad.

![2018-06-28_13-54-44](https://user-images.githubusercontent.com/14332263/42052060-c63c81ae-7adb-11e8-8de3-7e239a9db03a.png)

**Comment by bmoore-msft** [comment]
@yobyot - Alex could you attach/gist the template that show the errors?

**Comment by StephenWeatherford** [comment]
@yobyot I would still love to see an actual template file with these errors so we can track it down. I've never seen this particular issue.  Note that the errors you're seeing don't actually come from the extension - they come from vscode's built-in JSON support (not that it matters to your scenario, but it helps it route to the correct place).

Based on the above, I assume the errors continued to exist even after restarting vscode. My best guess is that there's an invisible character in there somewhere (e.g. a CR maybe??).

**Comment by bmoore-msft** [comment]
I think the issue here is that the two json files are using 2 different schemas.  The one on the left is using the deploymentParameters.json schema (and it's a template file) where the one on the right is using the correct schema for a template file.

**Comment by StephenWeatherford** [comment]
@yobyot Yep, @bmoore-msft's comment explains it, the schema is wrong.  So there is no bug.  However, we'd still be very interested in ways the experience could be made better, or any other issues you find, just let us know!

Stephen
