### ISSUE TITLE
Issue with string that contains []

### ISSUE THREAD

**Issue by slavizh** [microsoft/vscode-azurearmtools#1203]
if you have a string like:

```
"policyAssignmentDisplayName": "[Preview]: Audit VMs with insecure password security settings",
```

You will get error message: Unrecognized function name 'Preview'.

The usage of [] in strings is documented here:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-expressions#escape-characters

and should not result in error.

**Comment by slavizh** [comment]
also a few more errors are generated because of this:

Missing function argument list.

Nothing should exist after the closing ']' except for whitespace. - generated for each word after ].

**Comment by StephenWeatherford** [comment]
https://github.com/microsoft/vscode-azurearmtools/issues/250

**Comment by StephenWeatherford** [comment]
@jorgecotillo Can you take a look?  Thanks.

**Comment by StephenWeatherford** [comment]
@slavizh Thanks Stan, I'll go ahead and get this fixed.

**Comment by StephenWeatherford** [comment]
@slavizh Closing this in favor of #250.  The tricky part is not messing up the experience of users that are in the middle of editing strings that may or may not be completed.  Have a couple of possible solutions that we'll try internally first, so this won't make it into 0.15.1.
