### ISSUE TITLE
scope parameter not recognized

### ISSUE THREAD

**Issue by slavizh** [microsoft/vscode-azurearmtools#1204]
I have the following resource:

```
...
 {
            "name": "[guid( parameters( 'exemptions' )[copyIndex()].name )]",
            "type": "Microsoft.Authorization/policyExemptions",
            "apiVersion": "[variables( 'apiVersions' ).policyExemptions]",
            "copy": {
                "name": "exemptionsCopy",
                "count": "[length( parameters( 'exemptions' ) )]"
            },
            "scope": "[if( empty( union( variables( 'defaultExemptionObject' ), parameters( 'exemptions' )[copyIndex()] ).scope ),
                    '',
                    union( variables( 'defaultExemptionObject' ), parameters( 'exemptions' )[copyIndex()] ).scope
                )]",
....
```

Error that is generated is:

Template validation failed: The template resource '[guid( parameters( 'exemptions' )[copyIndex()].name )]' at line '63' and column '19' is invalid. 'Scope' property is not supported. Please see https://aka.ms/arm-template/#resources for usage details.
Scope on extension resources is documented here:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/scope-extension-resources?tabs=azure-cli

**Comment by StephenWeatherford** [comment]
see https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/scope-extension-resources?tabs=azure-cli#apply-to-resource for an example that fails.

**Comment by StephenWeatherford** [comment]
@jorgecotillo Can you please take a look?

**Comment by StephenWeatherford** [comment]
Dup of https://github.com/microsoft/vscode-azurearmtools/issues/967 which is fixed in the next release.
