### ISSUE TITLE
ARM template user defined functions are not supported

### ISSUE THREAD

**Issue by Bassicaly** [microsoft/vscode-azurearmtools#122]
VSCode does not yet support ARM templates as definded here:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#functions

Please could this be implemented?

**Comment by fiveisprime** [comment]
Talked with an Ignite attendee who has run into this as well, here's his blog about how he's using functions and an example arm template that we could use to test this.

https://azurekid.blog/2018/06/17/arm-templates-and-azure-governance/
https://github.com/azurekid/blog/blob/master/virtualMachine.json

**Comment by Bassicaly** [comment]
Awesome

You talked to Rogier Dijkman. He and I are colleagues and we both worked on
this already :)

It would be great to have VSCodesupport it as well

**Comment by Tadimsky** [comment]
This would be awesome. 
It'd be really nice to have it show no more errors for our deployments :)

![image](https://user-images.githubusercontent.com/1149244/53044537-2ed87600-3440-11e9-9ddf-aaf5f544ddab.png)

**Comment by StephenWeatherford** [comment]
Thanks for the feedback. We still have to prioritize, so it's helpful to know how many people this would help.

**Comment by StephenWeatherford** [comment]
Good to know, thanks!

**Comment by lwajswaj** [comment]
+1; errors are also misleading as parameters consumed by the function are marked as missing as the extension confuses them template parameters

**Comment by ggirard07** [comment]
+1 too... having an error reported each time we use a function from a local namespace actually hide real error(s) on the same line

**Comment by Apholisha** [comment]
+1

**Comment by azurekid** [comment]
Shamelessly promoting my blog about user defined functions. Hopefully it inspires more to use it. 
https://azurekid.blog/2019/07/09/standardize-arm-templates

**Comment by StephenWeatherford** [comment]
@azurekid :-) Their usage appears to be somewhat low right now, but I agree they ought to be used more.

**Comment by twids** [comment]
+1. I think the biggest "issue" is that it is marked as errors in the file..
Parameter handling and stuff could be added "later" but removing the incorrect errors would be very appreciated

**Comment by StephenWeatherford** [comment]
I considered whether there was a way to just get rid of the false errors in a quick manner, but I think it's too complicated for that - for instance, we user-defined functions, you can have parameters defined in a scope not at the top level, which we don't understand yet.  About to start working on this, so hopefully in the next release (after the one about to ship).  Thanks for your patience.

**Comment by StephenWeatherford** [comment]
In progress...

**Comment by neilpeterson** [comment]
Fix went out today with this fix, thanks.
