### ISSUE TITLE
Punctuation/special symbols contained in variable/parameter couldn't be focused when double click the value of variable/parameter 

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-azurearmtools#123]
**Repro Steps**:
 1. Open one JSON file in VS Code.
 2. Rename one variable/parameter containing punctuation/special symbols such as colon, exclamation mark, etc. 
 3. Check whether punctuation/special symbols contained in variable/parameter can be focused when **double clicking the value of variable/parameter** or not.

**Expect**:
Punctuation/special symbols contained in variable/parameter also can be focused.

**Actual**:
Punctuation/special symbols contained in variable/parameter couldn't be focused. Please see the below picture:
![actual1](https://user-images.githubusercontent.com/37653604/43071371-26caa8ae-8e62-11e8-882b-43589f704b62.PNG)

**Comment by StephenWeatherford** [comment]
I don't think we have control of that, sorry.
