### ISSUE TITLE
Testcase error: The file's contents show incorrectly after copying the URL into a browser

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#1233]
**OS:** All
**Build Version:** v0.15.0-alpha3

**Repro Steps:**

1. Create a new template file with following contents --> Save it as `child.json`.
```
{
	"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
	"parameter1": {
	"type": "string",
	"metadata": {
	"description": "description"
	}
	},
	"parameter2": {
	"type": "int",
	"metadata": {
	"description": "description"
	}
	}
	},
	"functions": [],
	"variables": {
	"v1": "[parameters('unknown-parameter')]"
	},
	"resources": [],
	"outputs": {}
	}
```

2. Create a new storage account --> Create a new blob container.
3. Upload the `child.json` file to the blob --> Right-click on the uploaded file and Choose "Copy URL".
4. Copy this URL into a browser --> Enter.
5. Check whether the file's contents show correctly in the browser or not.

**Expect:**
The file's contents show correctly in the browser.

**Actual:**
The file's contents show incorrectly in the browser
![image](https://user-images.githubusercontent.com/57662131/109632192-b9045a80-7b81-11eb-8852-9429a40392f4.png)

**Comment by StephenWeatherford** [comment]
This was an error in the testcase.  I've updated it.

Note however the following known issue that occurs with some SAS tokens and not others:
> https://github.com/microsoft/vscode-azurearmtools/issues/1281
