### ISSUE TITLE
IntelliSense for schedule query rule condition operator recommends "Equals" instead of "Equal"

### ISSUE THREAD

**Issue by mderriey** [microsoft/vscode-azurearmtools#1257]
Hey there 👋

First, let me tell you how good the tooling is in VS Code.
I'm telling every single person I get to chat with about ARM templates.

I found a case today where the extension recommends an operator that is not valid:

```jsonc
{
  "type": "microsoft.insights/scheduledQueryRules",
  "apiVersion": "2020-05-01-preview",
  "name": "<some-name>",
  "location": "<some-location>",
  "properties": {
    // other properties
    "criteria": {
      "allOf": [
        {
          "query": "<kql-query>",
          "timeAggregation": "Count",
          "operator": "Equal",
          "threshold": 0,
          "failingPeriods": {
            "numberOfEvaluationPeriods": 1,
            "minFailingPeriodsToAlert": 1
          }
        }
      ]
    }
  }
}
```

This causes a warning squiggly for the `properties.criteria.allOf[0].operator` property that reads:

```
Value must be one of the following values: "Equals", "GreaterThan", "GreaterThanOrEqual", "LessThan", "LessThanOrEqual"
```

I first went with `Equals` and the deployment would fail, unfortunately with an error message that isn't useful:

```
Alert rule payload cannot be empty
```

After creating the scheduled query rule manually and exporting it from the Azure portal, I noticed that the generated template was using `Equal` instead of `Equals`; I gave it a go and it worked.

I'm not sure whether the issue is in the extension or in the JSON schema that the extension uses behind the scenes.

Thanks again!

**Comment by StephenWeatherford** [comment]
@mderriey Thanks for the kind remarks and also for letting us know about this issue.  This will be a schema issue, I've ported the bug over to https://github.com/Azure/azure-resource-manager-schemas/issues/1548.  When they fix it there, we'll pick it up in the next release.
