### ISSUE TITLE
Very high CPU & memory consumption in language server

### ISSUE THREAD

**Issue by anthony-c-martin** [microsoft/vscode-azurearmtools#1268]
I noticed my fans were spinning very loud and checked my Activity View (OSX):
![image](https://user-images.githubusercontent.com/38542602/112302472-8249cd80-8c71-11eb-85be-c51177cd8043.png)

As you can see in the above, it's using ~2 cores on my 4 core laptop, and consuming over 4Gb of memory.

Looking at open files, it seems clear this dotnet process is the ARM VSCode extension:
![image](https://user-images.githubusercontent.com/38542602/112302564-9d1c4200-8c71-11eb-9cec-45cc9cff727f.png)

I also see some VSCode render processes with high CPU when I look at the full view (note that PID 66808 is the parent of this dotnet process).
![image](https://user-images.githubusercontent.com/38542602/112302985-229ff200-8c72-11eb-94e4-676e7033181b.png)

I captured a perf trace by running `dotnet trace collect -p 68211 --providers Microsoft-DotNETCore-SampleProfiler` - will send this via email. Another interesting thing to note is that I didn't have any active editor windows with ARM template files.

**Comment by StephenWeatherford** [comment]
@anthony-c-martin I'm not seeing anything unexpected on the stack - parsing and validation of JSON for schema and backend.  Of course, it shouldn't be stuck there.  Is this something you can reproduce, or did it only happen once?

Also, I assume you had loaded some JSON template files before, right?  Did you happen to have any very large files open that might have been misinterpreted as template files?

**Comment by StephenWeatherford** [comment]
If it's something you can repro, you can force a lot of tracing info into the Output window with this setting:

![image](https://user-images.githubusercontent.com/6913354/112357215-8b946380-8c8c-11eb-9ab2-46dd3dde8409.png)

**Comment by anthony-c-martin** [comment]
> @anthony-c-martin I'm not seeing anything unexpected on the stack - parsing and validation of JSON for schema and backend. Of course, it shouldn't be stuck there. Is this something you can reproduce, or did it only happen once?
> 
> Also, I assume you had loaded some JSON template files before, right? Did you happen to have any very large files open that might have been misinterpreted as template files?

Unfortunately I only noticed it this one time, and don't have a repro for it. I definitely could have had other large-ish JSON files open; I wouldn't expect anything over 2k lines though.

**Comment by StephenWeatherford** [comment]
Closing for now, please let me know if you get more info, thanks.
