### ISSUE TITLE
autocomplete of params/var replaces needed code

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#127]
When using autocomplete for a param or variable name in the middle of an expression, too much code is removed upon completion.

Take the following expression:

`"[if('true', variables('one'), variables('two'))]"`

Now replace true with:

`parameters('`

this will bring up the autocomplete list, TAB select something from the list.  At this point everything up to the next single quote is replaced and you end up with:

`[if(parameters('enableBootDiags')one'), variables('two'))]`

If autocomplete stopped replacement at the comma or whitespace this would work perfectly.

**Comment by StephenWeatherford** [comment]
@bmoore-msft This appears to have been fixed with https://github.com/microsoft/vscode-azurearmtools/pull/551.  Can you verify this and the new intellisense experiences (parameter files and resourceId) in https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18384&view=results?  Thx.

**Comment by bmoore-msft** [comment]
Looks like it - very cool...

**Comment by StephenWeatherford** [comment]
Shipped yesterday
