### ISSUE TITLE
Microsoft.Resources/deploymentScripts warning

### ISSUE THREAD

**Issue by KenBenjamin** [microsoft/vscode-azurearmtools#1271]
ARM resource templates with:
`"type": "Microsoft.Resources/deploymentScripts"`

Are flagged with a warning:
`Value must be one of the following values: "Microsoft.HealthcareApis/services", "Microsoft.AppConfiguration/configurationStores", ...`

**Comment by StephenWeatherford** [comment]
Thanks for letting us know.  I assume you are referring to the ARM Tools extension inside vscode, right?  I’m not able to repro, the following gives me no warnings.

Can you check that you have v0.15.0 (latest) and that the schema you’re using is correct?  (Seems to only be valid in "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#")

{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Resources/deploymentScripts",
            "apiVersion": "2020-10-01",
            "name": "name",
            "location": "Australia East",
            "kind": "AzureCLI",
            "properties": {
                "azPowerShellVersion": "string",
                "azCliVersion": "string",
                "containerSettings": {
                    "containerGroupName": "string"
                },
                "storageAccountSettings": {
                    "storageAccountName": "string",
                    "storageAccountKey": "string"
                },
                "cleanupPreference": "Always",
                "primaryScriptUri": "string",
                "supportingScriptUris": [
                    "string"
                ],
                "scriptContent": "string",
                "arguments": "string",
                "environmentVariables": [
                    {
                        "name": "string",
                        "value": "string",
                        "secureValue": "string"
                    }
                ],
                "forceUpdateTag": "string",
                "retentionInterval": "string",
                "timeout": "string"
            }
        }
    ]
}


Thx,
Stephen


Von: Ken Benjamin ***@***.***>
Datum: Mittwoch, 31. März 2021 um 11:48 AM
An: microsoft/vscode-azurearmtools ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [microsoft/vscode-azurearmtools] Microsoft.Resources/deploymentScripts warning (#1271)

ARM resource templates with:
"type": "Microsoft.Resources/deploymentScripts"

Are flagged with a warning:
Value must be one of the following values: "Microsoft.HealthcareApis/services", "Microsoft.AppConfiguration/configurationStores", ...

**Comment by KenBenjamin** [comment]
I’m running 0.15.0. Changing the $schema to 2019-04-01 and deploymentScripts to 2020-10-01 leads to a new error. Here’s a block of stripped-down code that closely aligns with the WVDQuickStart deploy.json file I’m working with and yields the same errors:

`{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "type": "Microsoft.Resources/deploymentScripts",
            "apiVersion": "2020-10-01",
            "name": "createDevopsPipeline",
            "location": "string",
            "kind": "AzureCLI",
            "identity": {
                "type": "userAssigned",
                "userAssignedIdentities": {
                    "identity": {}
                }
            },
            "properties": {
                "forceUpdateTag": 1,
                "azCliVersion": "2.0.80",
                "arguments": "string",
                "primaryScriptUri": "string",
                "timeout": "PT30M",
                "cleanupPreference": "OnSuccess",
                "retentionInterval": "P1D"
            }
        }
    ]
}`

The error for this is:
`Value must conform to exactly one of the associated schemas
|   Value must be one of the following values: "AzurePowerShell" at #/resources/0/kind
|   Missing required property "azPowerShellVersion" at #/resources/0/properties
|   Value must be one of the following types: string at #/resources/0/properties/forceUpdateTag
|   or
|   Value must be one of the following types: string at #/resources/0/properties/forceUpdateTag`

According to the API (azure-resource-manager-schemas/Microsoft.Resources.json at ffa4141777f7370b649f9bbf5c9b6e2ba5e86ada · Azure/azure-resource-manager-schemas (github.com)<https://github.com/Azure/azure-resource-manager-schemas/blob/ffa4141777f7370b649f9bbf5c9b6e2ba5e86ada/schemas/2020-10-01/Microsoft.Resources.json>), “AzureCLI” is a valid “kind”.

Thanks,
Ken

**Comment by StephenWeatherford** [comment]
@KenBenjamin Does the resource as above deploy without error?  The message says you need the azPowerShellVersion tag.  Here's one from the quick-starts that gives me no errors:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "type": "Microsoft.Resources/deploymentScripts",
            "apiVersion": "2020-10-01",
            "name": "CreateAndDeployCertificates",
            "location": "westus",
            "kind": "AzurePowerShell",
            "properties": {
                "forceUpdateTag": "2",
                "azPowerShellVersion": "3.0",
                "scriptContent": "# Write the config to file\n$opensslConfig=@'\n[ req ]\ndefault_bits        = 4096\ndistinguished_name  = req_distinguished_name\nstring_mask         = utf8only\ndefault_md          = sha512\n\n[ req_distinguished_name ]\ncountryName                     = Country Name (2 letter code)\nstateOrProvinceName             = State or Province Name\nlocalityName                    = Locality Name\n0.organizationName              = Organization Name\norganizationalUnitName          = Organizational Unit Name\ncommonName                      = Common Name\nemailAddress                    = Email Address\n\n[ rootCA_ext ]\nsubjectKeyIdentifier = hash\nauthorityKeyIdentifier = keyid:always,issuer\nbasicConstraints = critical, CA:true\nkeyUsage = critical, digitalSignature, cRLSign, keyCertSign\n\n[ interCA_ext ]\nsubjectKeyIdentifier = hash\nauthorityKeyIdentifier = keyid:always,issuer\nbasicConstraints = critical, CA:true, pathlen:1\nkeyUsage = critical, digitalSignature, cRLSign, keyCertSign\n\n[ server_ext ]\nsubjectKeyIdentifier = hash\nauthorityKeyIdentifier = keyid:always,issuer\nbasicConstraints = critical, CA:false\nkeyUsage = critical, digitalSignature\nextendedKeyUsage = serverAuth\n'@\n\nSet-Content -Path openssl.cnf -Value $opensslConfig\n\n# Create root CA\nopenssl req -x509 -new -nodes -newkey rsa:4096 -keyout rootCA.key -sha256 -days 3650 -out rootCA.crt -subj '/C=US/ST=US/O=Self Signed/CN=Self Signed Root CA' -config openssl.cnf -extensions rootCA_ext\n\n# Create intermediate CA request\nopenssl req -new -nodes -newkey rsa:4096 -keyout interCA.key -sha256 -out interCA.csr -subj '/C=US/ST=US/O=Self Signed/CN=Self Signed Intermediate CA'\n\n# Sign on the intermediate CA\nopenssl x509 -req -in interCA.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out interCA.crt -days 3650 -sha256 -extfile openssl.cnf -extensions interCA_ext\n\n# Export the intermediate CA into PFX\nopenssl pkcs12 -export -out interCA.pfx -inkey interCA.key -in interCA.crt -password 'pass:'\n\n# Convert the PFX and public key into base64\n$interCa = [Convert]::ToBase64String((Get-Content -Path interCA.pfx -AsByteStream -Raw))\n$rootCa = [Convert]::ToBase64String((Get-Content -Path rootCA.crt -AsByteStream -Raw))\n\n# Assign outputs\n$DeploymentScriptOutputs = @{}\n$DeploymentScriptOutputs['interca'] = $interCa\n$DeploymentScriptOutputs['rootca'] = $rootCa\n",
                "timeout": "PT5M",
                "cleanupPreference": "OnSuccess",
                "retentionInterval": "P1D"
            }
        }
    ]
}
```

**Comment by StephenWeatherford** [comment]
Docs say its not required, but I suspect that either azPowerShellVersion or azCLIVersion is required, although if it deploys without them, technically it's a schema bug.

**Comment by KenBenjamin** [comment]
It does deploy without them, but I’ll update the scripts to clean it up. Thanks 😊

**Comment by KenBenjamin** [comment]
I did, in fact, have azCliVersion already. I still get the warning. Here’s the exact code block:

`        {
            "type": "Microsoft.Resources/deploymentScripts",
            "apiVersion": "2019-10-01-preview",
            "name": "createDevopsPipeline",
            "location": "[variables('location')]",
            "dependsOn": [
                "[concat('Microsoft.Automation/automationAccounts/', variables('autoAccountName'), '/jobs/', variables('jobGuid2'))]"
            ],
            "kind": "AzureCLI",
            "identity": {
                "type": "userAssigned",
                "userAssignedIdentities": {
                    "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities/', variables('identityName'))]": {}
                }
            },
            "properties": {
                "forceUpdateTag": 1,
                "azCliVersion": "2.0.80",
                "arguments": "[concat(variables('devOpsName'), ' ', variables('devOpsProjectName'), ' ', parameters('azureAdminUpn'), ' ', variables('keyvaultName'))]",
                "primaryScriptUri": "[concat(variables('_artifactsLocation'),'/ARMRunbookScripts/createDevopsPipeline.sh')]",
                "timeout": "PT30M",
                "cleanupPreference": "OnSuccess",
                "retentionInterval": "P1D"
            }
        }`

I think the issue is that the parser is confused. If it’s set to AzureCLI, it says it’s expecting AzurePowerShell; and if it’s set to AzurePowerShell it says it’s expecting AzureCLI.

**Comment by StephenWeatherford** [comment]
Unfortunately, the error message is difficult to read.  It comes from the way JSON validation works.  Here's the error again:
![image](https://user-images.githubusercontent.com/6913354/113341774-6d5ce200-92e2-11eb-9226-c9df29d16aaf.png)
Read it like this:

  Was expecting either:
    1) kind = "AzurePowerShell" and forceUpdateTag is a string.  But in this case, it's missing the required property azPowerShellVersion.
    or 2) (when kind = "AzureCLI") forceUpdateTag is a string.

So all that's wrong is that you need to change forceUpdateTag to be a string.

It deploys because the Azure backend (unfortunately) will magically convert strings to numbers and vice versa when needed.  This doesn't play well with JSON schema validation and we experimented with allowing that for the validation, but it caused too many problems and we decided to have the validation remain strict with data types.

**Comment by KenBenjamin** [comment]
Thanks. That does the trick. I agree with keeping the strict validation.
