### ISSUE TITLE
No dialog pops up to create the "childTemplate.json" file when CTRL+Clicking on "childTemplate.json"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#1273]
**OS:** Windows
**Build Version:** 20210401.1

**Repro Steps:**

1. Create a main.json template file --> CTRL+Click on "childTemplate.json". 
2. Check whether pop up a dialog to create the "childTemplate.json" file.

**Expect:**
Pop up a dialog to create the "childTemplate.json" file.
![image](https://user-images.githubusercontent.com/57662131/113388760-62c54a00-93c1-11eb-8916-27c3b30a9c0d.png)

**Actual:**
No dialog pops up to create the "childTemplate.json" file.

**Comment by StephenWeatherford** [comment]
I can't repro (at least on Mac). Can you take a video?  Does it repro on Mac or just Windows? Thanks.

![image](https://user-images.githubusercontent.com/6913354/113755984-c606f300-96c5-11eb-819b-fc11c73eee23.png)

**Comment by v-xinda** [comment]
@StephenWeatherford  Verified this issue on the bulid 20210401.1, it still reproduces just on Windows.
![child](https://user-images.githubusercontent.com/57662131/113834383-58d68900-97bd-11eb-9391-5733e0dd1bcb.gif)
But this issue doesn't reproduce on the latest build 20210406.1.

**Comment by StephenWeatherford** [comment]
Weird, thanks.
