### ISSUE TITLE
Issues with ARM plugin not being able to write settings

### ISSUE THREAD

**Issue by mhembrow** [microsoft/vscode-azurearmtools#1274]
Does this occur consistently? 
Repro steps:

1. Remove and reinstall the Microsoft ARM template plugin
2. Load ARM template in VSCode
3. Error message displays that it cant write to the settings file.
4.

Action: queryAddParameterFile
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.15.0
OS: win32
OS Release: 10.0.21343
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
w.reject workbench.desktop.main.js:2060:16779
file:/workbench.desktop.main.js:2060:20853
async w.doWriteConfiguration workbench.desktop.main.js:2060:13958
```

</details>

**Comment by StephenWeatherford** [comment]
@mhembrow I followed your repro steps but the problem didn't repro.  The most likely cause is that you have an error in your settings file.  Please try this:

1) F1 -> Preferences: Open Settings (JSON)
![image](https://user-images.githubusercontent.com/6913354/113618066-fe49fb00-960b-11eb-8f08-e0c455e76898.png)
2) Check in the problems pane if there are any syntax errors
![image](https://user-images.githubusercontent.com/6913354/113618137-1883d900-960c-11eb-8f71-a7e9d2186cbf.png)
3) If so, fix them and save.
4) try again

Let us know if that doesn't work.  Thanks.
