### ISSUE TITLE
Azure Resourece Manager Tempalte server crashed 5 times

### ISSUE THREAD

**Issue by dciborow** [microsoft/vscode-azurearmtools#1286]
Does this occur consistently? Yes
Repro steps:

1. Open VS Code
2. 
![image](https://user-images.githubusercontent.com/9027725/114808693-c31b9a80-9d76-11eb-87ad-3cd83362f93d.png)

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:239:61598extension.bundle.js:239:61598
Object.callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:142014
WrappedErrorHandler.closed extension.bundle.js:239:61444
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageReader.fireClose vscode-jsonrpc/messageReader.js:111:27
Socket.<anonymous> vscode-jsonrpc/messageReader.js:151:46
Socket.emit events.js:327:22
Pipe.<anonymous> net.js:674:12
```

</details>

**Comment by StephenWeatherford** [comment]
@dciborow Can you check the Output window, select "Azure Resource Manager Tools" in the dropdown, and post the contents here (be sure to remove anything that you might not want public)?  Thanks!
