### ISSUE TITLE
[Suggestion] Add the tooltip for the code lens or make the code lens adaptive to the screen

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#1289]
**OS:** Windows
**Build Version:** 20210415.8

**Repro Steps:**
1. Create a main.json template file with below content.
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {
        "childUri": "https://elsa001.blob.core.windows.net/test/child.json?sv=2020-04-08&st=2021-04-15T07%3A22%3A32Z&se=2021-04-16T07%3A22%3A32Z&sr=b&sp=racwdxt&sig=SBy1%2F7uZXGhQ508n2dVwTOz5Sui0BTcRODkSSjR%2BHR8%3D"
    },
    "resources": [
        {
            "name": "linkedDeployment1",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2020-10-01",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "uri": "[variables('childUri')]",
                    "contentVersion": "1.0.0.0"
                },
                "parameters": {
                }
            }
        }
    ],
    "outputs": {}
}
```
2. Hover on the longer code lens or drag the below progress bar.
3. Check whether all the code lens can be checked or not.

**Actual:**
There is no tooltip when hovering on the code lens and the code lens don't move with the progress bar.
![c1](https://user-images.githubusercontent.com/45614674/114838663-7fbd3c80-9e07-11eb-9be2-976ca85bc8b9.gif)

**Suggestion:**
Add the tooltip for the code lens or make the code lens adaptive to the screen.

**More Info:**
It is easy to check all the code lens if there is a tooltip or it adaptive to the screen.

**Comment by StephenWeatherford** [comment]
This is vscode behavior.  We don't draw the tooltips.
