### ISSUE TITLE
It takes more than 1 min to change the code lens after deleting the linked "childTemplate.json" file

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#1290]
**OS:** Windows
**Build Version:** 20210415.8

**Repro Steps:**
1. Create a new template file "test.json".
2. In the resource section, type "linked" and select the "Linked Deployment With Relative Path" snippet.
3. Click the code lens to create a new "childTemplate.json" file.
4. Use the "arm!" snippet to create a new child template file and save it.
5. Go back to "test.json" and delete the new created "childTemplate.json" file.
6. Check whether the code lens changes quickly or not.

**Expect:**
The code lens changes quickly after deleting the linked "childTemplate.json" file.
![image](https://user-images.githubusercontent.com/45614674/114850978-ec3e3880-9e13-11eb-84df-2c126487b025.png)

**Actual:**
It takes more than 1 min to change the code lens.

**Comment by MarcusFelling** [comment]
This is VS Code behavior, they don't close the file out immediately.
