### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sayd0003** [microsoft/vscode-azurearmtools#1299]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.15.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\anehl\AppData\Local\Temp\msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
@sayd0003 Thanks for the report, but I can't investigate if you don't attach the msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt file that the bug report asks for (see above).
