### ISSUE TITLE
Add generic message to "Try Bicep"

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/vscode-azurearmtools#1304]
ARM Tools should bring awareness to Bicep, the "Next generation of ARM templates", which simplifies the authoring experience by providing concise syntax, better support for code reuse, and improved type safety. Display a message to "Try Bicep", including the option to ignore the message.

aka link: https://aka.ms/bicep-install

Criteria
- Show every week until dismissed or closed out
- Only show if Bicep extension not installed
- Text: "Try the next generation of ARM templates, Azure Bicep"

**Comment by MarcusFelling** [comment]
Also, add blurb to README

**Comment by StephenWeatherford** [comment]
It'll pretty pretty unintrusive and go have a "never show again" button.
