### ISSUE TITLE
Formatter support for parameter files

### ISSUE THREAD

**Issue by RIKIKU** [microsoft/vscode-azurearmtools#1306]
The out of the box JSON formatter formats arrays differently to the Azure Resource Manager extension and it's frustrating to look at. Since the ARM extension doesn't detect parameter files, we end up with different formatting between the parameter files and the templates.   Can support be added for detecting and formatting the parameter files? 

How they are formatted in the parameter file:
```json
"MyParameterName": {
      "value": [
        {
          "Name": "something"
        }
      ]
```
How they are formatted by the Azure Resource Manager Extension:
```json
"MyParameterName": {
      "value": [{
          "Name": "something"
        }
      ]
```

**Comment by MarcusFelling** [comment]
@RIKIKU - I would suggest using an extension such as Prettier https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
