### ISSUE TITLE
The path returned for .net core does not exist:

### ISSUE THREAD

**Issue by CodebyJazz** [microsoft/vscode-azurearmtools#1309]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: The path returned for .net core does not exist: 

Version: 0.15.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:211271extension.bundle.js:16:211271
fulfilled extension.bundle.js:16:207702
```

</details>

**Comment by StephenWeatherford** [comment]
@CodebyJazz Can you run the following command via command palette (F1)?

![image](https://user-images.githubusercontent.com/6913354/121638937-a29f5200-ca40-11eb-89de-84e5ea38457b.png)

That will get an issue into the right repo with the info they need to investigate.  Thanks.
