### ISSUE TITLE
ARM Tool Extension Not Loading

### ISSUE THREAD

**Issue by mikebratton85** [microsoft/vscode-azurearmtools#1310]
Does this occur consistently? Yes
Repro steps:

1. Install ARM Tool Extension
2. Try to launch the tool

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.10.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.57.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:768795extension.bundle.js:218:768795
Object.callWithTelemetryAndErrorHandlingSync extension.bundle.js:1:253132
WrappedErrorHandler.closed extension.bundle.js:218:768663
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageWriter.fireClose vscode-jsonrpc/messageWriter.js:39:27
Socket.<anonymous> vscode-jsonrpc/messageWriter.js:58:46
Socket.emit events.js:315:20
Pipe.<anonymous> net.js:673:12
```

</details>

**Comment by StephenWeatherford** [comment]
Could you please copy what is in the Output window, in the "Azure Resource Manager Tools" section?  Thanks.

 
![image](https://user-images.githubusercontent.com/6913354/122095402-30bd6480-cdc2-11eb-95e4-0ee9bdd9a0d9.png)

**Comment by mikebratton85** [comment]
WARNING: azureResourceManagerTools.languageServer.dotnetExePath is
set. This overrides the automatic download and usage of the dotnet
runtime and should only be used to work around dotnet installation
issues. If you encounter problems, please try clearing this setting.

Using dotnet core executable at C:\Program Files\dotnet\dotnet.exe
Starting ARM Template Language Server at
c:\Users\mibratton\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.15.1\languageServer\Microsoft.ArmLanguageServer.dll
Language server nuget version: 3.0.0-preview.21215.3
Client options:
{
  "documentSelector": [
    {
      "language": "arm-template",
      "scheme": "file"
    },
    {
      "language": "arm-template",
      "scheme": "untitled"
    }
  ],
  "diagnosticCollectionName": "ARM Template Language Server diagnostics",
  "outputChannel": {
    "outputChannel": {
      "name": "Azure Resource Manager Tools",
      "extensionPrefix": "azureResourceManagerTools",
      "_outputChannel": {
        "name": "Azure Resource Manager Tools",
        "_channel": {}
      }
    }
  },
  "revealOutputChannelOn": 3,
  "synchronize": {
    "configurationSection": "azureResourceManagerTools"
  },
  "middleware": {}
}
Server options:
{
  "run": {
    "command": "C:\\Program Files\\dotnet\\dotnet.exe",
    "args": [
      "c:\\Users\\mibratton\\.vscode\\extensions\\msazurermtools.azurerm-vscode-tools-0.15.1\\languageServer\\Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  },
  "debug": {
    "command": "C:\\Program Files\\dotnet\\dotnet.exe",
    "args": [
      "c:\\Users\\mibratton\\.vscode\\extensions\\msazurermtools.azurerm-vscode-tools-0.15.1\\languageServer\\Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  }
}
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.26 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Error: The connection to the ARM Template Language Server got closed.
[Info  - 11:23:46 AM] Connection to server got closed. Server will restart.
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.26 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Error: The connection to the ARM Template Language Server got closed.
[Info  - 11:23:47 AM] Connection to server got closed. Server will restart.
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.26 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Error: The connection to the ARM Template Language Server got closed.
[Info  - 11:23:48 AM] Connection to server got closed. Server will restart.
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.26 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Error: The connection to the ARM Template Language Server got closed.
[Info  - 11:23:49 AM] Connection to server got closed. Server will restart.
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.26 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.2.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Error: The connection to the ARM Template Language Server got closed.
[Error - 11:23:49 AM] Connection to server got closed. Server will not
be restarted.

**Comment by StephenWeatherford** [comment]
@mikebratton85 Thanks!  Could you try removing the azureResourceManagerTools.languageServer.dotnetExePath vscode setting as noted here:
> WARNING: azureResourceManagerTools.languageServer.dotnetExePath is
set. This overrides the automatic download and usage of the dotnet
runtime and should only be used to work around dotnet installation
issues. If you encounter problems, please try clearing this setting.

Hopefully it's not longer needed.  If it is still needed, could you make sure it's pointing to a 3.1 installation of dotnet?

**Comment by mikebratton85** [comment]
I'm not completely sure how to remove that, can you tell me where to go to
do this? I'm new to DevOps and deploying ARM templates.

Thanks

**Comment by StephenWeatherford** [comment]
@mikebratton85 Sure, no problem. Open settings (ctrl+comma I think) and search for this setting:

![image](https://user-images.githubusercontent.com/6913354/122448255-6ba5d080-cf59-11eb-9f56-da7650c179e9.png)

The error message indicates you have this pointing to an existing dotnet installation on your machine.  First try setting it to blank and restart VS (the setting is a hack to work around some extension issues that were hopefully fixed).  if it still doesn't work, set it back to what it was (assuming dotnet still exists there) and you'll need to install the runtime for dotnet 3.1: https://dotnet.microsoft.com/download/dotnet/3.1
![image](https://user-images.githubusercontent.com/6913354/122449639-f0ddb500-cf5a-11eb-8a4d-fa0d21ebb6c3.png)

**Comment by mikebratton85** [comment]
Thanks, that worked. Appreciate all your help Stephen!

**Comment by StephenWeatherford** [comment]
Great to hear, thanks!
