### ISSUE TITLE
Add support for metadata links

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/vscode-azurearmtools#1321]
The extension already allows a template to be selected for validation of parameter files.

Over here, I've been working on using metadata links to allow parameter files to explicitly let CI tools know that the parameter file relates to a specific template.

https://azure.github.io/PSRule.Rules.Azure/using-metadata/#metadatalinks

It would be cool if this could also be leveraged for improving the authoring experience so when switching between multiple parameter files the correct template can be selected.

What do you think?

**Comment by MarcusFelling** [comment]
@BernieWhite - thank you for the feedback! It would be awesome if you wanted to contribute to implementing this via a PR https://github.com/microsoft/vscode-azurearmtools#contributing

**Comment by BernieWhite** [comment]
@MarcusFelling sure. Let me take a look at it.

**Comment by BernieWhite** [comment]
Got a working implementation but not sure how to approach the tests. If you're able to have a quick look at point me to a test file that is similar that would really help.

**Comment by MarcusFelling** [comment]
@StephenWeatherford is OOF this week. @bhsubra Are you able to lend a hand with tests?

**Comment by StephenWeatherford** [comment]
Sorry, been busy...
