### ISSUE TITLE
[Suggestion] It would be better if the "value" section of output created by "Insert Item" and "CRTL+SPACE" are consistent

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1322]
**OS:** Win10
**Build Version:** 20210702.1

**Repro Steps:**

1. Create a new template file -> Inside the "outputs" section -> Type enter -> Type CTRL+SPACE -> Select "new-output“ -> Check the "value" section of added output.
2. Right click on the editor -> Select "Insert Item..." -> Select "Output" -> Enter a name -> Select "String" -> Check the "value" section of added output.
3. Check whether the "value" section of the step 1 and step 2 are consistent.

**Actual:**
The "value" section of the step 1 and step 2 are inconsistent.
![image](https://user-images.githubusercontent.com/62053665/124252658-c21a2e00-db59-11eb-9c31-d12f76887656.png)

**Suggestion:**
It would be better if the "value" section of the step 1 and step 2 are consistent.

**More Info:**
This issue also reproduces for the "variables" section.
![image](https://user-images.githubusercontent.com/62053665/124254097-4e792080-db5b-11eb-9ba1-4a75c16ecaf7.png)

**Comment by StephenWeatherford** [comment]
low priority
