### ISSUE TITLE
Template validation failed: relativePath property cannot be a template expression

### ISSUE THREAD

**Issue by kilasuit** [microsoft/vscode-azurearmtools#1323]
This error should realistically not exist as it disables cleaner & eaiser to maintian coding practices 

Example simplified template

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        
    },
    "functions": [],
    "variables": {
        "templates": {
             "LogAnaltyics": ".\\..\\workingtemplates\\log-analystics.azuredeploy.json"
        }
    },
    "resources": [
        {
            "name": "Logs-IaaS-PaaS",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2020-10-01",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "relativePath": "[variables('templates').LogAnaltyics]",
                    "contentVersion": "1.0.0.0"
                },
                "parameters": {
                }
            }
        },
 ],
    "outputs": {
       
    }
}
```

It should also allow for full template validation to happen instead of failing like this 
![image](https://user-images.githubusercontent.com/6355225/124278360-11eafc00-db3e-11eb-9530-f6aeb4606be3.png)

**Comment by StephenWeatherford** [comment]
@kilasuit Does this deploy successfully?  My understanding is that it's not allowed in deployment.

**Comment by kilasuit** [comment]
Seeming no it doesn't which to me is surprising as I would expect it to do so with no issue

**Comment by StephenWeatherford** [comment]
I believe it was an intentional decision to restrict that to hard-coded values. @jorgecotillo might know more the reason, but I believe it's because this is related to template specs and they need the paths to be static and not depend on parameters or other indeterminate values so they can be uploaded before actual deployment.
