### ISSUE TITLE
Validation returns false positive for resourceGroup() function

### ISSUE THREAD

**Issue by TomaszOledzki** [microsoft/vscode-azurearmtools#1329]
Looks like there are false positives when validating resourceGroup() function usage in vscode-azurearmtools extension? Despite the validation error, templates are deploying successfully.

Using: vscode-azurearmtools v0.15.1

According to docs such usage of resourceGroup() function is allowed: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#remarks-2

Examples:
![image](https://user-images.githubusercontent.com/38130203/125194904-97b02b00-e253-11eb-8eed-c19992c6c4c7.png)
![image](https://user-images.githubusercontent.com/38130203/125195000-f8d7fe80-e253-11eb-8808-6c82c822f72b.png)
![image](https://user-images.githubusercontent.com/38130203/125195118-92071500-e254-11eb-967e-412f42049bc8.png)

**Comment by StephenWeatherford** [comment]
@TomaszOledzki According to those docs, such usage is only valid when deploying to a resource group:

> The resourceGroup() function can't be used in a template that is deployed at the subscription level. It can only be used in templates that are deployed to a resource group. 

The $schema I see above is for a subscription deployment.  Are you deploying to subscription or resource group?

Thx,
Stephen

**Comment by TomaszOledzki** [comment]
> The $schema I see above is for a subscription deployment. Are you deploying to subscription or resource group?

I'm deploying to a resource group. Yes, you're right, I forgot to check which schema I'm using.

**This is user error.**

Thanks
Tomasz

**Comment by StephenWeatherford** [comment]
Thanks for letting us know!
