### ISSUE TITLE
Only one error is displayed in the main template when there are multiple errors in the parameters portion

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1331]
**OS:** All
**Build Version:** 20210709.7

**Repro Steps:**

1. Create a child template with one or more parameters -> Create a main template with a linked template -> Click on the "parameters" in the main template and execute "Add missing required parameters".
2. Add a value for one of the parameters, but give it the wrong data type, e.g. `123` -> There is an error in the main template.
3. Add a value for a parameter that does not exist in the linked template to the main template.
4. Check whether all errors are displayed in the main template.

**Expect:**
All errors are displayed in the main template.
![image](https://user-images.githubusercontent.com/62053665/125276903-5ac36180-e343-11eb-93f3-bb96f108cac6.png)
![image](https://user-images.githubusercontent.com/62053665/125276926-64e56000-e343-11eb-8c93-03cc903986a0.png)

**Actual:**
Only one error is displayed in the main template.
![image](https://user-images.githubusercontent.com/62053665/125276849-48492800-e343-11eb-854f-2fa1dae53d1c.png)

**More Info:**
This issue also reproduces when change the "parameter/resources/..." to "parameter1/resources2/..." in the link template.
![image](https://user-images.githubusercontent.com/62053665/125277479-0c629280-e344-11eb-946e-5399ab9c6765.png)

**Comment by StephenWeatherford** [comment]
Unfortunately this is by design.  The errors that end with "arm-template (validation)" are provided by code that only ever shows one of these errors at a time.  Fix one and the next will show.  Thx.
