### ISSUE TITLE
Extension issThe extension 'YAML' took a very long time to complete its last operation and it has prevented other extensions from running.ue

### ISSUE THREAD

**Issue by abdelrazekrizk** [microsoft/vscode-azurearmtools#1339]
- Issue Type: `Bug`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.15.2`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by StephenWeatherford** [comment]
@abdelrazekrizk I'm not quite sure what to do with this.  First, are you sure this is the right extension, given that the message says "The extension 'YAML'..."  If you are sure, can you give steps to reproduce the scenario?  Where did you see the message?  Thanks.

**Comment by abdelrazekrizk** [comment]
I start to open an.IPYNB file
then there was a warning from vs code that some extension stop to work
then I open the extension page and there was many extension can not start and notice with that "The extension 'YAML prevent the extension from start"

**Comment by StephenWeatherford** [comment]
This extension is for ARM template files (.json).  We have nothing to do with .IPYNB or .YAML.  PIease try again to submit the bug through vscode - it should be able to help you figure out which extension you should be filing the bug against.
