### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by brobinson234** [microsoft/vscode-azurearmtools#1343]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.15.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\brobi\AppData\Local\Temp\msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
@brobinson234 I can't debug the problem unless you attach the cpuprofile file as instructed above.
