### ISSUE TITLE
Microsoft.Web/hostingEnvironments most apiVersions not recognized

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#1344]
```json
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "metadata": {
    "_generator": {
      "name": "bicep",
      "version": "0.4.1.14562",
      "templateHash": "15148121476737091609"
    }
  },
  "parameters": {
    "aseName": {
      "type": "string",
      "metadata": {
        "description": "Name of the App Service Environment"
      }
    },
    "location": {
      "type": "string",
      "defaultValue": "[resourceGroup().location]",
      "metadata": {
        "description": "Location of the App Service Environment"
      }
    },
    "existingSubnetName": {
      "type": "string",
      "metadata": {
        "description": "Subnet name that will contain the App Service Environment"
      }
    }
  },
  "functions": [],
  "resources": [
    {
      "type": "Microsoft.Network/virtualNetworks/subnets",
      "apiVersion": "2020-06-01",
      "name": "[parameters('existingSubnetName')]"
    },
    {
      "type": "Microsoft.Web/hostingEnvironments",
      "apiVersion": "2020-06-01",  // <<<<<<<<<<<
      "name": "[parameters('aseName')]",
      "kind": "ASEV2",
      "location": "[parameters('location')]",
      "properties": {
        "location": "[parameters('location')]",
        "name": "[parameters('aseName')]",
        "workerPools": [],
        "virtualNetwork": {
          "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', split(parameters('existingSubnetName'), '/')[0], split(parameters('existingSubnetName'), '/')[1])]"
        }
      },
      "dependsOn": [
        "[resourceId('Microsoft.Network/virtualNetworks/subnets', split(parameters('existingSubnetName'), '/')[0], split(parameters('existingSubnetName'), '/')[1])]"
      ]
    }
  ]
}
```
bicep accepts 
![image](https://user-images.githubusercontent.com/6913354/127412129-edb7c187-11a6-454a-a79f-dee0a77d5fd5.png)

**Comment by MarcusFelling** [comment]
@bmoore-msft - Any ideas as to what's going on here?

**Comment by bmoore-msft** [comment]
I'm guessing the issue is the 2021 apiversions not appearing in the tooling?  The schema shows them (which I presume Stephen checked) so something funky in the parsing of them...  IOW, no idea off the top.

**Comment by molotch** [comment]
I get the error below when loading the quickstart template in VS Code with the arm extension. Definitely seems to be something wonky with the schema parsing. I can load the schema in a browser no problem. I am running VS Code in WSL2.

Template file: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.compute/vm-simple-windows/azuredeploy.json

Error output:
"{
	"resource": "/azuredeploy.json",
	"owner": "ARM Template Language Server diagnostics",
	"severity": 8,
	"message": "There are problems with this document's schema impacting one or more items in the document. Please report this issue to schema owner.",
	"source": "arm-template (schema)",
	"startLineNumber": 2,
	"startColumn": 16,
	"endLineNumber": 2,
	"endColumn": 97
}"

**Comment by StephenWeatherford** [comment]
Fixed in next release:

![image](https://user-images.githubusercontent.com/6913354/141360345-44cfbc9b-dd33-46c5-90cc-019f04bc09aa.png)

I'm seeing some problems with some of the other resources in your sample template, though. Investigating...
