### ISSUE TITLE
i am unable to get the intellisence

### ISSUE THREAD

**Issue by gitbhushan** [microsoft/vscode-azurearmtools#1345]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.openParameterFile
Error type: Error
Error Message: cannot open file:///c%3A/users/bhush/desktop/armpractice/rgparam.json. Detail: Unable to read file 'c:\users\bhush\desktop\armpractice\rgparam.json' (Error: Unable to resolve non-existing file 'c:\users\bhush\desktop\armpractice\rgparam.json')

Version: 0.15.2
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
vscode-file:/workbench.desktop.main.js:2450:68098
```

</details>

**Comment by StephenWeatherford** [comment]
Sorry, I was on vacation.  Are you still having problems?  The error message is straightforward - try openening your template file, then using this context menu to set it to the right param file:
![image](https://user-images.githubusercontent.com/6913354/129952160-103181fa-06dc-4e3c-91d4-43025756de1d.png)

As far as Intellisense goes,  can you be more specific about what scenario is not working?  Thanks.
