### ISSUE TITLE
vscode-error to install Azure Resource Manager template

### ISSUE THREAD

**Issue by shantihy** [microsoft/vscode-azurearmtools#1346]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: Invalid path given for azureResourceManagerTools.languageServer.dotnetExePath setting. Must point to dotnet executable. Could not find file /usr/local/share/dotnet/dotnet

Version: 0.15.2
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:210758extension.bundle.js:16:210758
fulfilled extension.bundle.js:16:207702
```

</details>

**Comment by StephenWeatherford** [comment]
@shanalily Just as the error message says - you've got the azureResourceManagerTools.languageServer.dotnetExePath setting set to /usr/local/share/dotnet/dotnet, but that path is not valid.  I would first suggest resetting this setting to empty to allow us to try to download .net automatically.  Only if that doesn't work should you consider setting azureResourceManagerTools.languageServer.dotnetExePath to a local installation of .net.
