### ISSUE TITLE
Feature request: validate resource type in resourceId() call

### ISSUE THREAD

**Issue by mxplusb** [microsoft/vscode-azurearmtools#135]
I was pairing with @jorgecotillo on some ARM templates, and we were using this ARM output parameter:

```json
"outputs": {
    "pcf-subnet-nsg-id": {
      "type": "string",
      "value": "[resourceId('Microsoft.Network/networkSecurityGrops', variables('pcf-nsg-name'))]"
    }
  }
```

There is a typo in the resource provider that was causing this error in ARM:

```json
{
"code": "InvalidJsonReferenceFormat",
        "message": "Reference Id /subscriptions/cf0c53fb-06f5-4fe3-9c25-cabce6811cb1/resourceGroups/contoso-pcf-net-rg/providers/Microsoft.Network/networkSecurityGrops/pcf-nsg is not formatted correctly. The Id is expected to reference resources of type networkSecurityGroups. Path properties.subnets[0].properties.networkSecurityGroup."
}
```

It took us ~5-10 minutes to debug the issue because we missed the typo in the Resource Provider name. Once we fixed the typo, it resolved our issue.

By checking the validity of the Resource Provider that will help users be able to catch issues like ours much faster.

**Comment by StephenWeatherford** [comment]
This would require us to be able to evaluate expressions with variables/parameters, etc., which we do not currently do.

**Comment by StephenWeatherford** [comment]
Actually, we should be able to handle some specific scenarios.

**Comment by mxplusb** [comment]
Yay!

**Comment by StephenWeatherford** [comment]
Common scenarios could be handled in the extension or the validation (with extra code).

**Comment by StephenWeatherford** [comment]
Depends on https://github.com/microsoft/vscode-azurearmtools/issues/718
