### ISSUE TITLE
minLength validation on secure string wrong

### ISSUE THREAD

**Issue by BladeFireLight** [microsoft/vscode-azurearmtools#1350]
This ARM parameter

"password": {
      "type": "securestring",
      "minLength": 12,
      "maxLength": 72,
      "metadata": {
      }
      
Gets this validation error

{
	"resource": "/c:/git/arm_azure_network/arm/azure-3nic.json",
	"owner": "ARM Template Language Server diagnostics",
	"severity": 8,
	"message": "Template validation failed: The provided value for the template parameter 'password' at line '310' and column '21' is not valid. Length of the value should be greater than or equal to '12'. Please see https://aka.ms/arm-template/#parameters for usage details.",
	"source": "arm-template (validation)",
	"startLineNumber": 310,
	"startColumn": 21,
	"endLineNumber": 310,
	"endColumn": 21
}

It looks to be measuring the length of the string, not the size of the number.

**Comment by MarcusFelling** [comment]
Closing. Unfortunately, we do not have the engineering resources to prioritize this.
