### ISSUE TITLE
The snippets list will disappear after displaying several seconds

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#1352]
**OS:** Windows
**Build Version:** 20210821.4
**Regression:** Previous release(v0.15.2)

**Repro Steps:**

1. Create a new file in VS Code -> Type the following contents in it.
**NOTE:  Seems to only repro with a new unsaved file**
`{`
		`"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",`
		`"contentVersion": "1.0.0.0",`
		`"resources": [`
		`{`
		`"type": "Microsoft.AAD/domainServices",`
		`"apiVersion": "2017-01-01"`
		`}`
		`]`
		`}`

2. Place the cursor at the end of the "apiVersion" line -> Type a comma` , ` -> Type an Enter -> Type a double quote.
3. Check whether the snippets list displays forever.

**Expect:**
The snippets list displays forever.

**Actual:**
The snippets list will disappear after displaying several seconds.
![act2](https://user-images.githubusercontent.com/57662131/131081394-52fd6d8e-7b11-417a-903c-b994f5e31dd2.gif)

**More Info:**
This issue doesn't reproduce on the latest release build.

**Comment by StephenWeatherford** [comment]
@v-xinda Was this on Visual Studio Code or Visual Studio Code Insiders?  Can you try both and see if it repros on both?  Thanks!

**Comment by v-xinda** [comment]
@StephenWeatherford Verified this issue on the main build 20210821.4, It only reproduces on the Visual Studio Code Insiders(1.60.0-insider).

**Comment by StephenWeatherford** [comment]
@v-xinda Thanks.  Can you further try some things?  vscode thinks it's a bad extension.  Do you have any other extensions enabled?  Could you try disabling all extensions except Azure Resource Manager (ARM) Tools and .NET Install Tool for Extension Authors?  Once you've done that and restarted, can you see if it still repros?  

If it no longer repros when other extensions are installed, can you try re-enabling them one at a time and try to figure out which extension is causing the problem?  Thanks!

**Comment by v-xinda** [comment]
@StephenWeatherford I only install the Azure Resource Manager (ARM) Tools and .NET Install Tool extensions when verifying this issue.

**Comment by v-xinda** [comment]
@StephenWeatherford I verified the above test with following steps:
1. Create a new file saved on desktop with name "launch.json" and type the above contents. (Check the language ID is "JSON with Comments")
2. Delete the value of the property "type" then type a double quote, no snippets list pops up. 
![acutal1](https://user-images.githubusercontent.com/57662131/131814723-5aef72a3-959a-4c54-a088-89268fa4f980.gif)

**More Info:**
1. The snippets list will pop up and keep forever if press Ctrl+SPACE. 
2. The result is same when setting the language ID is "Azure Resource Manager Template".

**Comment by StephenWeatherford** [comment]
Added more info to https://github.com/microsoft/vscode/issues/131935

**Comment by StephenWeatherford** [comment]
Trying to narrow down: sw/disapparing-intellisense-bug

I *can* repro in the stable vscode right now.

**Comment by StephenWeatherford** [comment]
try to repro

**Comment by StephenWeatherford** [comment]
@v-xinda Does this still repro?  Thanks.

**Comment by v-xinda** [comment]
@StephenWeatherford   Verified this issue on the Visual Studio Code - insiders 1.72.0 withe the latest build 20220928.6, it doesn't reproduce for now.

**Comment by StephenWeatherford** [comment]
Thanks!
