### ISSUE TITLE
Snippets need to use updated apiVersions to show extendedLocation property in resources

### ISSUE THREAD

**Issue by junczhan** [microsoft/vscode-azurearmtools#1357]
![image](https://user-images.githubusercontent.com/89912021/131701280-f8d49924-f559-48a6-bc38-306baa367bef.png)

**Comment by junczhan** [comment]
could email me junczhan@microsoft.com for further discussion

**Comment by StephenWeatherford** [comment]
You need to update the existing RP schemas and get them uploaded.  When that happens (assuming https://github.com/microsoft/vscode-azurearmtools/issues/1324 is fixed - we had to temporarily stop picking up new schemas), we can pick them up and release with the new schemas.

**Comment by StephenWeatherford** [comment]
Need to update snippets.
