### ISSUE TITLE
ARM Template Language Server: An error occurred starting the language server

### ISSUE THREAD

**Issue by mohlyan** [microsoft/vscode-azurearmtools#1358]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: ARM Template Language Server: An error occurred starting the language server.

spawn EPERM

Version: 0.15.2
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.59.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:215681extension.bundle.js:16:215681
rejected extension.bundle.js:16:207763
```

</details>

**Comment by MarcusFelling** [comment]
@mohlyan Thanks for taking the time to file this! Can you check the Output window, select "Azure Resource Manager Tools" in the dropdown, and post the contents here (be sure to remove anything that you might not want public)?
