### ISSUE TITLE
"problems with schema" error for Microsoft.Web/sites "relays" when used as a child resource

### ISSUE THREAD

**Issue by Jernik** [microsoft/vscode-azurearmtools#1365]
I am attempting to have a [Microsoft.Web/sites/hybridConnectionNamespaces/relays](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/hybridconnectionnamespaces/relays?tabs=json) set up as a child resource of `Microsoft.Web/sites`

The tooltips correctly identify this as a valid type:
![image](https://user-images.githubusercontent.com/7637894/132408543-9be04093-9c50-41ae-af72-a289613dd791.png)
but this results in the following error at the schema level at the top of the file:
![image](https://user-images.githubusercontent.com/7637894/132408279-1229c8a5-5047-4c5b-bb82-5d754902176f.png)
This seems potentially related to #1344 or #570 

Changing `"type":"relays"` to `"type":"Microsoft.Web/sites/hybridConnectionNamespaces/relays"` causes this issue to disappear, but I believe I would then need to move these child resources out into a root resource level and I want to avoid that.

I am on Windows 10, using Visual Studio Code version 1.59.1 (user setup), and version v0.15.2 of the extension.

A cleaned up version of my `Microsoft.Web/sites` resource with associated child resource as a smallest replication:
```json
{
      "apiVersion": "2018-11-01",
      "name": "[parameters('name')]",
      "type": "Microsoft.Web/sites",
      "location": "[parameters('location')]",
      "tags": {},
      "dependsOn": [],
      "resources": [
       {
          "type": "relays",
          "apiVersion": "2020-12-01",
          "name": "[parameters('namespaces_SYRX_sql_relay_name')]",
          "location": "Central US"
       }
      ]
}
```

**Comment by StephenWeatherford** [comment]
Need to debug in language server

**Comment by Jernik** [comment]
Hi @StephenWeatherford, do you have a reason this one won't be fixed? It seems like an actual bug.

**Comment by StephenWeatherford** [comment]
Sorry, I agree it looks like a real bug, but as things shift to Bicep, I have less time to work on this extension.  So it's just a question of prioritization and we'll be closing out of lot of current bugs.  Feel free to comment on ones you feel we should reconsider, and also feel free to propose creating your own PR.  Thanks!
