### ISSUE TITLE
arm template crashing

### ISSUE THREAD

**Issue by BrishalKumar1** [microsoft/vscode-azurearmtools#1375]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.2
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.60.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:239:61005extension.bundle.js:239:61005
Object.callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:144558
WrappedErrorHandler.closed extension.bundle.js:239:60851
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageWriter.fireClose vscode-jsonrpc/messageWriter.js:39:27
Socket.<anonymous> vscode-jsonrpc/messageWriter.js:58:46
Socket.emit events.js:315:20
Pipe.<anonymous> net.js:673:12
```

</details>

**Comment by StephenWeatherford** [comment]
@BrishalKumar1 Thanks for taking the time to report this!  I've been having trouble tracking down the cause of this issue.  Do you get this frequently, or did it occur only once?  If frequently, could you please:

Open View->Output -> select "Azure Resource Manager Tools"
![image](https://user-images.githubusercontent.com/6913354/134570230-d5f1d770-a741-4793-a0fc-cef91cfcf64c.png)

![image](https://user-images.githubusercontent.com/6913354/134570153-081c2c9c-c3df-4723-9500-208610bcd2a3.png)

And if there are any errors there please copy them here (be sure to remove any sensitive information - e.g. possibly user names).  Thanks!
