### ISSUE TITLE
Subscription Level deployment schema does not work

### ISSUE THREAD

**Issue by slavizh** [Microsoft/vscode-azurearmtools#138]
Subscription Level deployment schema does not work. On a subscription level deployments when I put schema ```https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#``` I do not get any intellisense in VSC. Not even for simple things like parameters and variables.

**Comment by brianstringfellow** [comment]
Same problem here. The type (`"type": "Microsoft.Resources/resourceGroups"`) is not recognized.
![image](https://user-images.githubusercontent.com/22823524/48033798-a7295e80-e111-11e8-9922-573afe2b8cbd.png)

**Comment by bmoore-msft** [comment]
Not sure if the schema was updated since but I'm not seeing this... If you load this template: https://github.com/Azure/azure-quickstart-templates/blob/master/subscription-level-deployments/create-rg-lock-role-assignment/azuredeploy.json is the resource type still flagged?  (or can you gist a template?)

**Comment by slavizh** [comment]
@bmoore-msft  Below is the difference in intellisense. You can see that intellisense does not work at all on subscription level schema.

Subscription Level
![image](https://user-images.githubusercontent.com/11890856/49921247-a07ecb80-feb5-11e8-9420-58fc58aa9ceb.png)


Resource Group level
![image](https://user-images.githubusercontent.com/11890856/49921205-8513c080-feb5-11e8-851f-0b49ca7c288f.png)

**Comment by slavizh** [comment]
btw I also do not see the type with green line below it.

**Comment by bmoore-msft** [comment]
Ok - that's a slightly different issue than the original post.  The scenario in the original post is using the json schema for intellisense - this is handled by the JSON editor in VS Code (and should work (and does for me)).

The autocomplete that happens inside of property values is handled by the extension - and you're correct that the extension does not understand sub templates.  The extension is triggered off of the schema it finds in the json document and [obviously] doesn't recognize the new schema.  I think that code is here:
https://github.com/Microsoft/vscode-azurearmtools/blob/e6d65f7cde6bc6523b55b44bcebd21a2529b090c/src/Utilities.ts#L154-L156

But in any case 2 different issues according to the OP - do you mind opening a new issue for your scenario?

**Comment by jpjac** [comment]
Hi,

I have the same issue as the OP, i believe, the schema should be added to support templates that are targeted towards the Subscription (https://docs.microsoft.com/en-us/azure/azure-resource-manager/deploy-to-subscription)

**Comment by StephenWeatherford** [comment]
saw/subscription-deployment

**Comment by StephenWeatherford** [comment]
FYI, this was fixed in the 0.6.0 release on Thursday.  Thanks again for reporting.
