### ISSUE TITLE
Microsoft.Authorization/policyAssignments latest API unavailable.

### ISSUE THREAD

**Issue by SiebeDev** [microsoft/vscode-azurearmtools#1384]
The API version 2021-06-01 of in  `Microsoft.Authorization/policyAssignments`  is not available in VS Code.

![image](https://user-images.githubusercontent.com/81007986/135976853-9f979f79-5859-40dc-b0ee-f0ed6f447ae7.png)

latest version of VSCode, bicep etc. is used. 

Might be a schema issue?

**Comment by StephenWeatherford** [comment]
Fixed with https://github.com/microsoft/vscode-azurearmtools/pull/1400
![image](https://user-images.githubusercontent.com/6913354/141356920-39ff0f6a-6ac6-4627-abcc-c22b104a93ad.png)
