### ISSUE TITLE
No scaffolding in JSON file (WORK-AROUND: Press CTRL+SPACE)

### ISSUE THREAD

**Issue by GarthM9** [microsoft/vscode-azurearmtools#1390]
Issue Type: <b>Bug</b>

When I type arm! nothing happens. According to the documentation, I should see a scaffolding drop-down.

Extension version: 0.15.3
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.75GB (41.95GB free)|
|Process Argv|--crash-reporter-id 3052329e-c69b-4299-ba79-d87c9ec6b88b|
|Screen Reader|no|
|VM|44%|
</details>

**Comment by StephenWeatherford** [comment]
Indeed that should work...

**Comment by Satona75** [comment]
Thanks Garth. I am also experiencing this problem so I've just rolled back to 0.15.2.
