### ISSUE TITLE
Microsoft.Web/sites out of date

### ISSUE THREAD

**Issue by MikePennington** [microsoft/vscode-azurearmtools#1396]
It seems that the Microsoft.Web/sites resource is missing the last three versions. 

![image](https://user-images.githubusercontent.com/750344/136818985-d2b65865-40c2-4e08-aa98-3a02cd2c4772.png)
What I'm seeing in autocomplete seem to match the list here: https://github.com/microsoft/vscode-azurearmtools/blob/ff8fa82816d55d8ac125ab6c008e132069019b81/tools/resourceTypesAndVersions.txt#L5029-L5037

The following API versions seem to be missing:
- 2021-01-01
- 2021-01-15
- 2021-02-01
![image](https://user-images.githubusercontent.com/750344/136819183-65fb6b01-cefd-495c-8976-a16b32db5fa2.png)

Thanks for your assistance.

**Comment by StephenWeatherford** [comment]
Still seeing it
![image](https://user-images.githubusercontent.com/6913354/141356808-d9db8342-4ac2-4d9a-81a4-717cb3e583ec.png)
