### ISSUE TITLE
An extra tooltip "parameters" pops up when hovering over the "Insert Parameter..." icon next to the "parameters" node under the "ARM TEMPLATE OUTLINE"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1398]
**OS:** Win10
**Build Version:** 20211021.1

**Repro Steps:**

1. Open a template file in VS Code -> Expand "ARM TEMPLATE OUTLINE" -> Hover over the "Insert Parameter..." icon next to the "parameters" node.
2. Check the poped up tooltip.

**Expect:**
Only the tooltip "Insert parameter..." pops up.

**Actual:**
An extra tooltip "parameters" pops up.
![arm](https://user-images.githubusercontent.com/62053665/138424674-6e4d213b-326b-47fb-a35d-bb0f9d1a7b59.gif)

**More Info:**

1. This issue also reproduces in the "Sort Parameter/Insert Variable/Sort Variables/Insert Resource/Sort Resources/Sort Outputs/Insert Output" icon.
2. This issue doesn't reproduce in the "Sort Template/Insert Item" icon next to the "ARM TEMPLATE OUTLINE".
![arm11](https://user-images.githubusercontent.com/62053665/138431783-4eb9f3c7-a99b-417d-85ff-9f9f0164880a.gif)

**Comment by StephenWeatherford** [comment]
Appears to be new vscode behavior.  We don't actually control those tooltips.
