### ISSUE TITLE
Question: Comments in templates (jsonc) and the Azure CLI

### ISSUE THREAD

**Issue by martinoss** [Microsoft/vscode-azurearmtools#140]
I tried to make use of comments (// notation) in the templates. What is supported nicely by the extension and vs code does not seem to be supported by the Azure CLI (eg. when validating).
What is the purpose of the comments when I can't deploy the template without modifications?

**Comment by StephenWeatherford** [comment]
Very good question, we should file an issue with them.  Is this the PowerShell CLI or the "az" CLI?

**Comment by martinoss** [comment]
I tried it with the az CLI.
Is there an alternative that supports the comments?

**Comment by StephenWeatherford** [comment]
@PrashanthCorp Can you find out who to contact for CLI issues, if you're not out?  Thanks.

**Comment by PrashanthCorp** [comment]
I'm on the lookout. Many engineers seem out for the holidays. 
Meanwhile, it looks like the Azure CLI had a regression left unfixed due to lack of traction: 
https://github.com/Azure/azure-cli/issues/4802

Could that be the underlying issue?

**Comment by StephenWeatherford** [comment]
Thanks, @PrashanthCorp.  @martinoss I think you should chime in on the issue he found Azure/azure-cli#4802. Pretty sure the portal used to allow comments.

Either way, I think it makes sense for us to continue supporting comments in the extension, assuming some may choose to then use tooling to remove them before deploying.
