### ISSUE TITLE
Upgrade to .NET 6 when released (for Mac M1/arm64 compatibility)

### ISSUE THREAD

**Issue by xhale** [microsoft/vscode-azurearmtools#1403]
Anything I can do at the moment to run the extension on Apple Silicon using the macOS arm64 RC2 build of .NET6?

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' (arm64) was not found.
  - The following frameworks were found:
      6.0.0-rc.2.21480.5 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

**Comment by StephenWeatherford** [comment]
@xhale 

My understanding (could be wrong) was that M1 was supposed to have compatibility through a transition layer.  

But from the output I was suspect you have the following vscode setting set to point to an SDK installation?

  azureResourceManagerTools.languageServer.dotnetExePath

If so, please delete its value and try again.  It should download .net to a private folder in vscode.

**Comment by xhale** [comment]
azureResourceManagerTools.languageServer.dotnetExePath was not set
dotnetAcquisitionExtension.existingDotnetPath was set to /usr/local/share/dotnet/dotnet

I then installed .NET Core 3.1 manually which really upset things!  Removing both versions, then removing and reinstalling the extension seemed to work.  All ok now.

Looks like I might actually have encountered this bug in the .NET VSCode helper?  https://github.com/dotnet/vscode-dotnet-runtime/issues/330

**Comment by pszypowicz** [comment]
When I tried to run this  app on apple silicone m1 arm, I got this error:

(I'm copying all the errors to make it easier for other people to search this issue and provide them workaround)

```
This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire failed
See '.NET Runtime' in the output window for more information.
```

and

```
An error occurred while installing .NET (3.1): .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/pszypowicz/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.3.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/pszypowicz/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.20" -Version 3.1.20 -Runtime dotnet
dotnet_install: Error: Could not find `.NET Core Runtime` with version = 3.1.20
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```

And to solve it, I had to go and manually install old .net 3 runtime version from here:
https://dotnet.microsoft.com/download/dotnet

Finally you have to configure your vscode JSON settings, and add following line:
```
"azureResourceManagerTools.languageServer.dotnetExePath": "/usr/local/share/dotnet/dotnet"
```

And as we see in error: dotnet version `3.1.20` is required to be installed and unfortunately, this version is not compiled natively for arm mac processor. It will/may run on Rosseta 2 (which is a mac intel emulation). 

My request would be: the first version of .net runtime which will support natively mac arm CPU will be .net 6. Do you consider updating .net runtime to be able to make it work "out of a box" with a ' VSCode extension for acquiring .NET Core Tooling'?

**Comment by pszypowicz** [comment]
Related issue: https://github.com/dotnet/vscode-dotnet-runtime/issues/330

**Comment by StephenWeatherford** [comment]
@xhale Looks like it.  We'll switch when we can.

@bhsubra FYI.  Hopefully switching to .NET 6 won't be a problem with your current work...

**Comment by pszypowicz** [comment]
.NET 6 was release yesterday and it is a LTS version.

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by StephenWeatherford** [comment]
We ran into technical issues getting this to work.  It will probably be after the holidays before we can get to it seriously.

**Comment by radoslawcz** [comment]
any news on this?

**Comment by StephenWeatherford** [comment]
@bhsubra has been working on this.  Are you interested in verifying a new build for us?  She's OOF today but could hook you up next week.

**Comment by radoslawcz** [comment]
Yes, I have a macbook with m1 and can try to test the new build.

**Comment by bhsubra** [comment]
> Yes, I have a macbook with m1 and can try to test the new build.

@radoslawcz , could you please try the attached vsix and let us know if the issue still persists? Thanks!

[azurerm-vscode-tools-0.15.5.zip](https://github.com/microsoft/vscode-azurearmtools/files/7928271/azurerm-vscode-tools-0.15.5.zip)

**Comment by radoslawcz** [comment]
I just tested the plugin and it works properly. ARM Template Language Server starts using dotnet 6 - previously it tried to load dotnet 3 and failed.

Using dotnet core executable at /Users/radek/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.1/dotnet
Starting ARM Template Language Server at /Users/radek/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.5/languageServer/Microsoft.ArmLanguageServer.dll
Language server nuget version: 3.0.0-preview.22069.1

I loaded some ARM template and the resources recognized and clickable in the ARM template outline. I didn't experience any errors.

**Comment by StephenWeatherford** [comment]
@radoslawcz Thanks!  We will release this soon.

**Comment by bhsubra** [comment]
> @bhsubra
> 
> I just tested the plugin and it works properly. ARM Template Language Server starts using dotnet 6 - previously it tried to load dotnet 3 and failed.
> 
> Using dotnet core executable at /Users/radek/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.1/dotnet Starting ARM Template Language Server at /Users/radek/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.15.5/languageServer/Microsoft.ArmLanguageServer.dll Language server nuget version: 3.0.0-preview.22069.1
> 
> I loaded some ARM template and resources were recognized and were clickable in the ARM template outline. I didn't experience any errors.

@radoslawcz , thank you!
