### ISSUE TITLE
The typed `d` is not overwritten after selecting a resource's short name from the completion list

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1409]
**OS:** All
**Build Version:** 20211103.3

**Repro Steps:**

1. Open the `dependon-with-copy2.json` file in VS Code -> Expand "ARM TEMPLATE OUTLINE" -> Click on the second resource -> Delete the existing dependsOn property in the following picture -> Type `d` -> Select the "dscext" from the pop-up completion  list.
    ![image](https://user-images.githubusercontent.com/62053665/140713520-51abc17c-9d15-4d59-aa2b-29ae960fceb8.png)
2. Check whether the typed `d` is overwritten.

**Expect:**
The typed `d` is overwritten.

**Actual:**
The typed `d` is not overwritten.![arm gif](https://user-images.githubusercontent.com/62053665/140714324-299ae7e1-62f8-4428-8bef-393cbec378cc.gif)

**More Info:**

1. This issue also reproduces when typing other letters.
2. This issue doesn't reproduce when typing letters within double quotes.
    ![arm2](https://user-images.githubusercontent.com/62053665/140715285-c1261d36-4cc8-4c4b-865d-06f4444b610e.gif).

**Comment by StephenWeatherford** [comment]
Low priority.
