### ISSUE TITLE
Autocomplete Doesn't Add Closing Square-Bracket Inside Double-Quote for Property Value

### ISSUE THREAD

**Issue by brianstringfellow** [microsoft/vscode-azurearmtools#141]
The double-quote autocompletes but the square-bracket does not. After entering a `[` character, it is expected the `]` would be automatically included and the cursor ready to continue in between the two.

![image](https://user-images.githubusercontent.com/22823524/48034407-26b82d00-e114-11e8-94d8-58b88e3c48cf.png)

**Comment by StephenWeatherford** [comment]
Currently on vacation.

**Comment by StephenWeatherford** [comment]
I doubt we can do this until we take over the built-in JSON language server.

**Comment by StephenWeatherford** [comment]
This was actually fixed a while ago
