### ISSUE TITLE
[Suggestion] It would be better if the template file reopens and the dropdown list pops up to select a parameter file after clicking "Select" button

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1422]
**OS:** All
**Build Version:** 20211111.17

**Repro Steps:**

1. Create a template file and two or more parameter files with similar names, e.g. `template1.json`, `template1.params.json` and `template1.params.dev.json`
2. Open user settings and reset the "Parameter Files" setting for the ARM extension
3. F1 -> Azure Resource Manager Tools: Reset Global State -> Yes -> Reload Now
4. Open the template file -> Get a notification asking to select one of the parameter files.
5. Close the template file -> Click "Select..." button in the notification.
    ![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/62053665/141762649-8523a82b-a700-4371-9bae-9869d4d27912.png)
6. Check whether the template file reopens and the dropdown list pops up to select a parameter file.

**Actual:**
Pop up a warning.
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/62053665/141762625-0564c5a6-35f3-444d-8d49-fe3dea99fd70.png)

**Suggestion:**
It would be better if the template file reopens and the dropdown list pops up to select a parameter file after clicking "Select" button.

**Comment by StephenWeatherford** [comment]
I can't repro this.  I get:

![image](https://user-images.githubusercontent.com/6913354/162818264-6cc1100f-03d1-4cb1-9eed-c15755fc17e1.png)
