### ISSUE TITLE
[Suggestion] It would be better if  the full complete details can be displayed directly after clicking the right arrow

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1423]
**OS:** All
**Build Version:** 20211111.17

**Repro Steps:**

1. Open the dependon-with-copy2.json file in VS Code -> Expand "ARM TEMPLATE OUTLINE" -> Click on the second resource -> Delete the existing dependsOn property in the following picture -> Type CTRL+Space -> Get a completion list.
    ![image](https://user-images.githubusercontent.com/62053665/141780742-34c1869f-b675-4969-8c15-23764470eb3b.png)
2. Hover over the right-hand side of the completions list and click the right arrow.
    ![image](https://user-images.githubusercontent.com/62053665/141780828-26ab8870-6dca-425f-a60d-0d7d407f3554.png)
3. Check whether the full complete details easy to check.

**Actual:**
We need to drag the scroll bar to check the full complete details.
![actual](https://user-images.githubusercontent.com/62053665/141783094-0f6b9f54-1c7f-4d0f-910f-bcbaa572479e.gif)

**Suggestion:**
It would be better if  the full complete details can be displayed directly after clicking the right arrow.
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/62053665/141783504-d79e5434-fb52-42c3-9d27-5075f42a82aa.png)

**Comment by StephenWeatherford** [comment]
Sorry, this is vscode's behavior, we have no control over it.
