### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ChaaraouiMohammed** [microsoft/vscode-azurearmtools#1426]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.15.5`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.62.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Ilyass\AppData\Local\Temp\msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
@ChaaraouiMohammed Please follow the instructions above.  You need to attach the cpuprofile.txt file or I can't investigate.  You can simply drag/drop it here.

Also, was this a one-time thing, or does it frequently happen?  Thx.
