### ISSUE TITLE
Can't install the ARM Template extension in VS Code

### ISSUE THREAD

**Issue by stevenbowler** [microsoft/vscode-azurearmtools#1427]
Got this message:
[2021-11-29 11:49:32.377] [renderer1] [error] XHR failed: Download: XHR failed
![image](https://user-images.githubusercontent.com/56875138/143918831-f2f9077b-b197-4133-bbd6-b6db5e8690e5.png)

**Comment by StephenWeatherford** [comment]
@stevenbowler Thanks for taking the time to report this.  Did this occur once, or is this occurring every time and blocking you?

**Comment by stevenbowler** [comment]
It is occuring every time, only with ARM Tools extension msazurermtools.azurerm-vscode-tools.  All other extensions so far installing ok, currently have 7 Microsoft blue check extensions installed.   Thanks for the follow-up.  Cheers.

**Comment by stevenbowler** [comment]
Thought I could bypass the problem by installing Azure Tools extension ms-vscode.vscode-node-azure-pack, which includes ARM tools extension; however, same error.

**Comment by stevenbowler** [comment]
resolved, was a local firewall/whitelist setting.

**Comment by StephenWeatherford** [comment]
Thanks!  I appreciate you letting us know, may help others with the same problem.
