### ISSUE TITLE
listAccountSas is not recognized

### ISSUE THREAD

**Issue by mcollier** [Microsoft/vscode-azurearmtools#143]
The **listAccountSas** function is not recognized.  However, according to https://github.com/Microsoft/vscode-azurearmtools/blob/master/assets/ExpressionMetadata.json#L251, it would seem like it should be recognized.

<img width="1260" alt="vscode-azurearmtools-listaccountsas" src="https://user-images.githubusercontent.com/1142273/48174790-6d09b980-e2d7-11e8-8b3e-d163676a5084.png">

**Comment by StephenWeatherford** [comment]
Sorry, looks like we haven't released with that fix yet (https://github.com/Microsoft/vscode-azurearmtools/commit/672964f1d6b543cc1bef92d9394bd80d5ffabd21#diff-8483a224816d7c272b6910110c5cb189). I will be releasing it very soon, hopefully next week.
