### ISSUE TITLE
Какого хуя эта поебень перестает работать после каждого сраного обновления уебанского .net? Я ЗАЕБАЛСЯ каждый раз настраивать заново. Горите в аду!!!!

### ISSUE THREAD

**Issue by AndreiBurak** [microsoft/vscode-azurearmtools#1431]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: The path returned for .net core does not exist: /usr/local/share/dotnet

Version: 0.15.5
OS: darwin
OS Release: 21.2.0
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:211400
fulfilled extension.bundle.js:16:207809
```

</details>

**Comment by StephenWeatherford** [comment]
If you have the following vscode setting set to anything, please try resetting the value:

 
![image](https://user-images.githubusercontent.com/6913354/148261974-66af09c4-71ca-4b1c-bb8c-44c80ee912ac.png)
