### ISSUE TITLE
It is not possible to install dotnet 3

### ISSUE THREAD

**Issue by igork750** [microsoft/vscode-azurearmtools#1432]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.5
OS: darwin
OS Release: 21.2.0
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:239:61746
Object.callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:143366
WrappedErrorHandler.closed extension.bundle.js:239:61592
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageReader.fireClose vscode-jsonrpc/messageReader.js:111:27
Socket.<anonymous> vscode-jsonrpc/messageReader.js:151:46
Socket.emit events.js:327:22
Pipe.<anonymous> net.js:673:12
```

</details>

**Comment by StephenWeatherford** [comment]
@igork750 Thanks for the report.  Could you please follow the steps in https://github.com/microsoft/vscode-azurearmtools/issues/1393 so I have a better chance of analyzing the bug?  Thanks.
