### ISSUE TITLE
Resources no longer being rendered correctly from vscode 1.29.1

### ISSUE THREAD

**Issue by DigiBanks99** [Microsoft/vscode-azurearmtools#144]
The resources section is not displaying correctly since VSCode updated to 1.29.1.

![Imgur](https://i.imgur.com/IgBpzfk.png)

**Comment by surfboomerang** [comment]
The shortening of the label name goes wrong. If your resource name is not like 
"[parameters('resourcename')]" or "[variables('resourcename')]" it shows the value of the name element correct.

**Comment by liambarnett** [comment]
+1 please fix this, very frustrating with larger templates.

**Comment by liambarnett** [comment]
Link to the previous version of VSCode for anyone wanting to downgrade in the meantime- - https://vscode-update.azurewebsites.net/1.28.2/win32-x64-user/stable

**Comment by bmoore-msft** [comment]
@marcvaneijk - not sure if you have time to look at this...

**Comment by StephenWeatherford** [comment]
Sorry for the slow response, been really busy.

**Comment by StephenWeatherford** [comment]
Good news...  It's been fixed in vs insiders

1.29.1:
![image](https://user-images.githubusercontent.com/6913354/49909971-da0ff200-fe35-11e8-892d-dff0ffecdff7.png)
1.30.0-insider:
![image](https://user-images.githubusercontent.com/6913354/49910008-fc097480-fe35-11e8-8baa-7e67902efcd6.png)

**Comment by StephenWeatherford** [comment]
In the meantime, anyone that would rather not install vscode insiders or an older version of vscode can try out this private build that changes the <>

**Comment by StephenWeatherford** [comment]
@DigiBanks99, @surfboomerang, @liambarnett, @bmoore-msft Never mind the private build.  This is actually fixed in vscode 1.30.0 (non-insiders), so please update if you haven't.  Thanks.
