### ISSUE TITLE
Parameter file validation fails with: Unable to load schema from <snip> unexpected end of file.

### ISSUE THREAD

**Issue by robinmalik** [microsoft/vscode-azurearmtools#1441]
Hi,

I automatically generated my first parameter file today via this extension (having previously been passing data via a custom PSObject) but VSCode lists the following problem: 

`Unable to load schema from 'https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#': unexpected end of file. (768) [2, 16] `

The JSON referenced is valid, which is odd. 

I'm also suffering problems in the main template file with apiVersions when they're roughly 2021 onwards ("for full schema validation, consider updating the value to...") but I think you're tracking this already.

Any ideas? Thanks!

**Comment by StephenWeatherford** [comment]
Per the params file, can you check to make sure the parameter file's language in vscode is set to JSON and not arm-template?  That might fix it.
![image](https://user-images.githubusercontent.com/6913354/151281636-b9a37f3c-6178-482b-ad8b-8eabeb08b13b.png)

> I think you're tracking this already.
Is there a reason you don't use the updated schema?  The old one will not be updated to include new schemas.

**Comment by robinmalik** [comment]
Thanks for the reply. The parameters file is set to JSON just like you've shown:

![image](https://user-images.githubusercontent.com/8790561/151366963-a5cf8ce9-314e-4901-9e0c-db6ea4fe0b8f.png)

I don't know if the error is misleading but it suggests it's the schema json file on Microsoft's end (but as I mentioned this seems to be valid).

RE: Version. Is there a newer version? 2019-04-01 is the latest documented on Microsoft for the template file that I could see (https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/syntax).

**Comment by StephenWeatherford** [comment]
Sorry, misread your statement about schemas.  We'll be releasing a new version with updated schemas very soon (for template files, we snapshot the schemas to avoid various issues).  That should hopefully help with that.

For parameter files, we rely mostly on vscode's built-in JSON support, so we don't have any control over the parameters file schema loading.  I'm not seeing the problem myself.  It could be a CDN issue that will eventually resolve itself, we've seen those before.  I would try F1 and "JSON:  Clear schema cache".

If that doesn't work, I'm guessing there's not much that actually not working, right?  Our functionality (param snippets etc) doesn't depend on the schema loading.

**Comment by robinmalik** [comment]
Thanks for the reply again. I couldn't locate the Clear Schema Cache option under the F1 dropdown and as the problem remains I've just ditched the parameters file entirely (and am now just constructing a PS object and using that). Will close the case as I don't think anything can be done here.

**Comment by StephenWeatherford** [comment]
Thanks for letting us know.

**Comment by StephenWeatherford** [comment]
Turns out it's a vscode in version 1.63.0: https://github.com/microsoft/vscode/issues/140227.  It's been fixed in the Insiders version 1.64, if you don't mind installing vscode insiders (https://code.visualstudio.com/insiders/)

**Comment by Loknath-Das** [comment]
> Thanks for the reply again. I couldn't locate the Clear Schema Cache option under the F1 dropdown and as the problem remains I've just ditched the parameters file entirely (and am now just constructing a PS object and using that). Will close the case as I don't think anything can be done here.

Hi, I have faced the same issue and seems like the F1 and "JSON: Clear schema cache" method works well, also we need to restart the vscode after that, it worked for me. And using vscode insiders works as well. Thank you for the solution!

**Comment by StephenWeatherford** [comment]
@Loknath-Das Thanks for letting us know!  Note that you no longer need to use the Insiders version for the fix, it was integrated into stable long ago.
