### ISSUE TITLE
Unable to write in user settings

### ISSUE THREAD

**Issue by lgiuliani80** [microsoft/vscode-azurearmtools#1442]
Does this occur consistently? 
Repro steps:

1.
2.

Action: queryAddParameterFile
Error type: Error
Error Message: Non è possibile scrivere nelle impostazioni utente. Aprirlo per correggere eventuali errori/avvisi e riprovare.

Version: 0.15.5
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.63.2
Language: it

<details>
<summary>Call Stack</summary>

```
E.toConfigurationEditingError workbench.desktop.main.js:1887:13054
E.doWriteConfiguration workbench.desktop.main.js:1887:9876
```

</details>

**Comment by StephenWeatherford** [comment]
> You cannot write to user settings. Open it to fix any errors/warnings and try again.

Just like the error says, you probably have an error in your vscode settings file.  Open vscode's settings editor
![image](https://user-images.githubusercontent.com/6913354/151465732-85b5c128-592d-4892-a54c-804c2417234f.png)
In the upper right-hand corner there will be a button to open as JSON:
![image](https://user-images.githubusercontent.com/6913354/151465809-0bafd29e-8224-4607-8943-21329ff2f1df.png)
Click that and fix any errors you find.
You may need to check the workspace settings, too:
![image](https://user-images.githubusercontent.com/6913354/151465834-c5b1d734-9cc6-46a4-aee9-579104f604ea.png)
