### ISSUE TITLE
sdsd

### ISSUE THREAD

**Issue by MANIDEEP114** [microsoft/vscode-azurearmtools#1444]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.openParameterFile
Error type: Error
Error Message: cannot open file:///c%3A/users/manideepveldandi%28qua/music/template.parameters.json. Detail: Unable to read file 'c:\users\manideepveldandi(qua\music\template.parameters.json' (Error: Unable to resolve nonexistent file 'c:\users\manideepveldandi(qua\music\template.parameters.json')

Version: 0.15.5
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

<details>
<summary>Call Stack</summary>

```
vscode-file:/workbench.desktop.main.js:2363:75636
```

</details>

**Comment by StephenWeatherford** [comment]
Is this something that occurs regularly, or just once?  If regularly, I need instructions on how to reproduce.

It sounds like you have a parameters file associated with your template file that no longer exists.  If so, you can fix by clicking  in the bottom of vscode:
![image](https://user-images.githubusercontent.com/6913354/152446616-9da43096-9949-4a82-8dcd-7968e5fb6e44.png)
and selecting "None"
![image](https://user-images.githubusercontent.com/6913354/152446646-c3206ac0-d6e2-45a7-912a-523da32856e2.png)
