### ISSUE TITLE
Getting started with ARM Template. Using parameter file

### ISSUE THREAD

**Issue by AubinBakana** [microsoft/vscode-azurearmtools#1445]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.15.5
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.64.1
Language: en

<details>
<summary>Call Stack</summary>

```
w.toConfigurationEditingError workbench.desktop.main.js:1896:12622
w.updateConfiguration workbench.desktop.main.js:1896:9708
w.doWriteConfiguration workbench.desktop.main.js:1896:9554
```

</details>

**Comment by StephenWeatherford** [comment]
Please see comment in https://github.com/microsoft/vscode-azurearmtools/issues/1442.  If that doesn't solve the problem, let us know.  Thanks!
