### ISSUE TITLE
We should retitle the "JSON OUTLINE"

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurearmtools#145]
I've never liked that, it implies we're outlining generic JSON, but we're not.  It's especially weird now that there's an OUTLINE view:
![image](https://user-images.githubusercontent.com/6913354/48652338-dfebf200-e9b3-11e8-9a01-de3103c4721b.png)

Suggested: "TEMPLATE OUTLINE" and "TEMPLATE PARAMETERS OUTLINE"

**Comment by StephenWeatherford** [comment]
@fiveisprime I'd like to get this in the webpack release.  Do you agree with the suggestions?

**Comment by fiveisprime** [comment]
Yeah, maybe "TEMPLATE OUTLINE" makes sense or maybe "ARM TEMPLATE OUTLINE"?

**Comment by StephenWeatherford** [comment]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/6913354/52891998-98f0d280-3143-11e9-9581-a0f776d4d81b.png">
<img width="324" alt="image" src="https://user-images.githubusercontent.com/6913354/52892025-c5a4ea00-3143-11e9-9dba-023804a0ef5f.png">

Going with ARM TEMPLATE OUTLINE

**Comment by fiveisprime** [comment]
Nice, looks good. 👌
