### ISSUE TITLE
Invalid path error thrown while using .NET6

### ISSUE THREAD

**Issue by prnam** [microsoft/vscode-azurearmtools#1450]
Hey 👋 ,
ARM tools is throwing an error while using .NET 6.0. I have only latest .NET 6. installed with no older .NET (core) running along with it and I cannot install older version of .NET < 5. So requesting your instructions / help for an error free usage of this feature.

Does this occur consistently? Yes
Repro steps:

1. Configure dotnetPath as `/usr/local/share/dotnet/sdk/6.0.101/dotnet`
2. Quit VSCode and all its process.
3. Start VSCode and you will get this error popup

Action: startArmLanguageServer
Error type: Error
Error Message: Invalid path given for azureResourceManagerTools.languageServer.dotnetExePath setting. Must point to dotnet executable. Could not find file /usr/local/share/dotnet/sdk/6.0.101/dotnet

Version: 0.15.5
OS: darwin
OS Release: 21.3.0
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

Directory Details

```zsh
me@mycomputer sdk % pwd    
/usr/local/share/dotnet/sdk
me@mycomputer sdk % tree -L 1
.
├── 6.0.100
└── 6.0.101

2 directories, 0 files
me@mycomputer sdk % 
```

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:210887
fulfilled extension.bundle.js:16:207809
```

</details>

**Comment by StephenWeatherford** [comment]
@prnam Thanks for taking the time to report this.  We have a fix, but can't release it until next week due to our test team's schedule.  You can try it out here: https://github.com/microsoft/vscode-azurearmtools/releases/tag/v0.15.6.  Use F1 -> Install from VSIX...

Stephen
