### ISSUE TITLE
Add collapse all button to "ARM Template Outline" side bar component

### ISSUE THREAD

**Issue by Rabattkarte** [microsoft/vscode-azurearmtools#1451]
I really like the "ARM Template Outline" in my side bar. The only thing, I really miss is a button to collapse all elements again. Working with multiple resources, variables, parameters makes this really tedious if I have to collapse all elements again after opening many.

Please see the following two screenshots. One shows the way the HashiCorp Terraform extension handles this, and one shows `vscode-azurearmtools`:

**Terraform:**

Please notice the button marked in red.

![CleanShot 2022-02-18 at 13 57 58](https://user-images.githubusercontent.com/16440184/154688020-d361bedb-f96b-4528-88fe-073a90c25d7e.png)

**ARM Tools:**

Please add a button at the place of ‼️ 

![CleanShot 2022-02-18 at 13 58 24](https://user-images.githubusercontent.com/16440184/154688010-7473c460-c5ca-4e4d-bec1-fe619888dd1d.png)

**Comment by StephenWeatherford** [comment]
Released in https://github.com/microsoft/vscode-azurearmtools/releases/tag/v0.15.7 on 5/11.
