### ISSUE TITLE
The completions list is inconsistent for the `arm-vn` between automatic intellisense and typing CTRL+SPACE

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1452]
**OS:** All
**Build Version:** 20220214.10
**Regression:** Not a regression

**Repro Steps:**

1. Create a new template file -> Inside the "resources" section -> Type `arm-vn` -> Check the completions list.
2. Close the completions list by clicking elsewhere with the mouse -> Put the cursor to the right of `arm-vn`  -> Type CTRL+SPACE.
3. Check whether the completions list is consistent between the step 1 and step 2.

**Expect:**
The completions list is consistent between the step 1 and step 2.

**Actual:**
The completions list is inconsistent between the step 1 and step 2.
![image](https://user-images.githubusercontent.com/62053665/154933374-58777137-c7dd-41d3-a4d8-04645392e55d.png)

**Comment by StephenWeatherford** [comment]
This is vscode behavior.  We probably can't do anything about it.  The extra items in the first list come from text that vscode finds in editor.
