### ISSUE TITLE
User snippets

### ISSUE THREAD

**Issue by rsquarev** [microsoft/vscode-azurearmtools#1459]
I am not seeing many snippets for arm. And these can grow. So, until you add them here, I want to have a snippet created by me. 
Sorry, If you have this functionality available already please point me to that resource.

**Comment by StephenWeatherford** [comment]
@rsquarev Thanks for the suggestion. Most of our time right now is being spent on improving the Bicep extension, which is where current/future ARM template development is better.  Also, you can easily add your own [user-defined snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) to VS Code (granted, they're not context-sensitive in that scenario).  Given that, it doesn't seem practical to add ARM user-snippets functionality here.

We'd be happy, though, to see you submit snippets for consideration to add into the ARM extension yourself. They go here: https://github.com/microsoft/vscode-azurearmtools/blob/main/assets/resourceSnippets/Linked%20Deployment%20With%20URI.snippet.json.  I'd be happy to help massage tests, etc.  Or you can simply enter an issue here with your suggested snippet text.  

Thanks!
Stephen
