### ISSUE TITLE
Using JSON Comments in User Settings Breaks ARM Snippets

### ISSUE THREAD

**Issue by vhusker** [Microsoft/vscode-azurearmtools#146]
I don't know if there is anything that can be done about this, however when I add the code to my user settings file in VS Code to allow for comments in JSON, I can no longer use ARM Template Snippets in my JSON snippets file.  There is no error or anything, the snippets stop working, however comments in JSON work.

Comments section of User Settings:
`"files.associations": {
        // Use the following to also allow comments inside .json file
         "*.json": "jsonc"
    },`

How I setup snippets file:  https://github.com/Azure/azure-xplat-arm-tooling

**Comment by StephenWeatherford** [comment]
Currently on vacation.

**Comment by StephenWeatherford** [comment]
@vhusker Sorry for the delay.  You can handle this in two ways:
1) Follow the original instructions, and copy the snippets code to Preferences > User Snippets > JSONC as well as JSON
2) Preferences -> User Snippets -> New Global Snippets File...
a) In your new snippets file, copy the snippets as before.  These snippets will show up in files of all types.  If you want to restrict them to just json and json with comments, then you also need to add `"scope": "json,jsonc",` to *each* entry, like this:

{
	"Azure Resource Manager (ARM) Template": {
		**"scope": "json,jsonc",**    <<<<
		"prefix": "arm!",
		"body": [
			...
		],
		"description": "Skeleton ARM Template"
	},
	"Azure Resource Manager (ARM) Parameters Template": {
		"prefix": "armp!",
		**"scope": "json,jsonc",**   <<<<

**Comment by StephenWeatherford** [comment]
Let us know how this works out for you!
