### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Stallon-niranjan** [microsoft/vscode-azurearmtools#1460]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.15.6`
- OS Version: `Linux x64 5.13.0-35-generic`
- VS Code version: `1.65.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
@Stallon-niranjan I can't do anything to investigate unless you attach the cpuprofile file as mentioned in the instructions above.
