### ISSUE TITLE
Tooltip URL aka.ms/arm-tools-apiversion does not exist

### ISSUE THREAD

**Issue by ChrisRomp** [microsoft/vscode-azurearmtools#1461]
The schema validation tooltip references the vanity URL `https://aka.ms/arm-tools-apiversion`, but that URL does not exist.

Screenshot:
![image](https://user-images.githubusercontent.com/1683889/160207507-3c9f797f-9e9d-41d2-821e-3b28a7ece9bf.png)

**Comment by StephenWeatherford** [comment]
Huh.  Thanks for letting us know.
