### ISSUE TITLE
Parameter file not found 

### ISSUE THREAD

**Issue by Amitk2143** [microsoft/vscode-azurearmtools#1465]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.openParameterFile
Error type: Error
Error Message: cannot open file:///c%3A/users/amit/documents/azuredeploy.parameters.json. Detail: Unable to read file 'c:\users\amit\documents\azuredeploy.parameters.json' (Error: Unable to resolve nonexistent file 'c:\users\amit\documents\azuredeploy.parameters.json')

Version: 0.15.6
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.66.2
Language: en

<details>
<summary>Call Stack</summary>

```
a.$tryOpenDocument workbench.desktop.main.js:2666:77383
```

</details>

**Comment by StephenWeatherford** [comment]
@Amitk2143 Is the error message incorrect?  If the file doesn't exist, we won't be able to read it.  If you think this error is unexpected, please provide more details of what you were trying to do and what you expected to happen.  Thanks!
