### ISSUE TITLE
The template file does not associate automatically with the parameter file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1487]
**OS:** All
**Build Version:** 20220507.1
**Regression:** Not a Regression

**Repro Steps:**

1. Open a template file in VS Code -> Create a parameter file for it.
2. Use the status bar to associate the template file with "None".
3. Use the status bar to associate the template file with created parameter file -> Turn off the "Check For Matching Parameter File" setting and reset "Parameter File" setting -> F1 -> Developer: Reload Window -> Turn the "Check For Matching Parameter File" setting back on -> Open the template file.
4. Check whether the template file associates  automatically with the parameter file.

**Expect:**
The template file associates  automatically with the parameter file.

**Actual:**
The template file does not associate automatically with the parameter file.
https://user-images.githubusercontent.com/62053665/167808613-1f491569-a746-4aff-9aa1-8bccbbf61ee1.mov

**More Info:**
This issue does not reproduce if you do not execute the step 2.

**Comment by StephenWeatherford** [comment]
won't fix
