### ISSUE TITLE
The format of the added parameter is incorrect after clicking "Add... parameters" in main template file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1490]
**OS:** All
**Build Version:** 20220512.1
**Regression:** Preview Release

**Repro Steps:**

1. Open a child template with one or more parameters -> Create a main template with a linked template deployment using the linked template snippet.
2. Click on the "parameters" -> Click the light bulb -> Select "Add... parameters".
    <img width="274" alt="Screen Shot 2022-05-12 at 14 31 01" src="https://user-images.githubusercontent.com/62053665/168006313-5539e1a2-a6c1-494d-bdac-573026b44ed0.png">
3. Check whether the format of the added parameter is correct.

**Expect:**
The format of the added parameter is correct.

**Actual:**
The format of the added parameter is incorrect.
<img width="434" alt="Screen Shot 2022-05-12 at 14 31 43" src="https://user-images.githubusercontent.com/62053665/168006505-70f82693-7b17-4270-bda3-9c5819d76caf.png">

**Comment by StephenWeatherford** [comment]
@v-mengwe I don't see any errors, what exactly were you expecting?  Seems to match the testcase:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/6913354/182212668-13e83a36-4052-4300-ba9f-88e539ace5e7.png">

**Comment by StephenWeatherford** [comment]
Oh, you just mean the spacing.  Yeah, won't fix, thanks.
