### ISSUE TITLE
Typing "arm" does not produce a list of scaffolding snippets

### ISSUE THREAD

**Issue by eliassal** [microsoft/vscode-azurearmtools#1492]
Hi, I have this tool installed in VSC, I create a new jsnon file, type "arm" nothing happens, here is 2 snapshots one with arm producing nothing, 2nd the version of this tool in my environment

![armNoSnippets](https://user-images.githubusercontent.com/8447864/170441361-ca069fe1-e07d-4548-ad8e-91aade1fc753.jpg)

![armNoSnippets_ToolVer](https://user-images.githubusercontent.com/8447864/170441394-25ca15c6-831c-4ad6-839b-458493a614b0.jpg)

**Comment by eliassal** [comment]
I uninstalled the extension then reinstalled it, now I get an alert as follows

![armNoSnippets_NetInstallAlert](https://user-images.githubusercontent.com/8447864/170442870-586dee97-f6a0-4dd2-9b76-8b9fca5abe1e.jpg)

**Comment by StephenWeatherford** [comment]
That's definitely weird.  VSCode manages this dependency, not us.  What version of vscode are using you?  Stable or insiders?

You might want to try making sure the installation folder is removed completely for the extension(s).  On Mac, these are in ~/.vscode(-insiders)/extensions.  I believe on Windows they're in the %USERPROFILE% folder.

**Comment by eliassal** [comment]
Thanks for your response. In fact, 1 hour ago, VSC suggested a new release update, restarting it everything went OK and had "ARM template server starting....." message then was able to work with intellisense. Maybe something was missing.
I dont remember the version when I had the issue but my current version is 1.67.2

**Comment by StephenWeatherford** [comment]
Thanks for letting us know!  I frequently see weird issues when VS Code has downloaded an update but not installed it yet.
