### ISSUE TITLE
ARM Issue

### ISSUE THREAD

**Issue by suryat92** [microsoft/vscode-azurearmtools#1500]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: The path returned for .net core does not exist: c:\Users\sukeshri\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.7\dotnet.exe

Version: 0.15.7
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.69.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:289228extension.bundle.js:16:289228
fulfilled extension.bundle.js:16:285617
```

</details>

**Comment by StephenWeatherford** [comment]
@suryat92 Does this occur every time?  If so, could you please run the following command from the command palette:

.NET Install Tool: Report an issue with the .NET Install Tool for Extension Authors.

This will create an issue at https://github.com/dotnet/vscode-dotnet-runtime/issues where the right folks can look at the problem.  Thanks!
