### ISSUE TITLE
vsc code

### ISSUE THREAD

**Issue by joha7** [microsoft/vscode-azurearmtools#1503]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Go To Definition
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'c:\new folder\cvdc-infra\deployment\arm_cosmosdb\arm_cosmosdb.parameters.test.json'

Version: 0.15.7
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.69.2
Language: en

**Comment by StephenWeatherford** [comment]
@joha7 Could you please describe the actions you took?  This error could be completely normal, depending.  Were you expecting it to find the file?  Thanks.
