### ISSUE TITLE
Add support for Azure Automanage 

### ISSUE THREAD

**Issue by AndrewCS149** [microsoft/vscode-azurearmtools#1507]
**Azure Automanage** is a new service that is currently in public preview. We plan to have a GA launch date in October. Automanage **is** located in the Schema list [here](https://github.com/Azure/azure-resource-manager-schemas/blob/main/generator/autogenlist.ts). 

I've tested and verified that the ARM deployments do work with Automanage, however, there seems to be no support with the VSCode extension. Is there a way we can implement snippets for automanage and autocomplete for the Automanage properties? 

You can find an example of how to deploy the ARM template here: [ARM deployment](https://docs.microsoft.com/en-us/azure/automanage/virtual-machines-custom-profile)

Thank you for all the help!

**Comment by StephenWeatherford** [comment]
@AndrewCS149 We would love to have you submit snippet PRs.  The snippets files are in https://github.com/microsoft/vscode-azurearmtools/tree/main/assets/resourceSnippets.  Look at the existing ones for examples, and feel free to ask any questions, thanks!

**Comment by AndrewCS149** [comment]
Thank you @StephenWeatherford ! Ive created a PR there: https://github.com/microsoft/vscode-azurearmtools/pull/1508
