### ISSUE TITLE
Change the minimum VS Code version that the ARM extension supports

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#1519]
**OS:** Win10
**Build Version:** 20220928.6

**Repro Steps:**
1. Figure out the oldest vs code version that the extension supports, the version is 1.57.0.
2. Install VS Code 1.57.1 from https://code.visualstudio.com/updates.
3. Install the ARM extension from VSIX.
4. Check whether succeeds to install the ARM extension from VSIX or not.

**Expect:**
Succeed to install the ARM extension from VSIX.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/192967016-24dc3d95-7676-42f8-a66e-e5db423ea9f6.png)

**Comment by StephenWeatherford** [comment]
@v-xinda Could you please check this again?  I'm seeing that 1.62.0 is the oldest supported version:
```json
    "engines": {
        "$comment": "Must match version of @types/vscode in devDepndencies",
        "vscode": "^1.62.0"
    },
```

thx

**Comment by v-xinda** [comment]
@StephenWeatherford  I'm apologized to use the wrong version to test the oldest supported version. No issue occurs when testing the oldest supported version with version 1.62.3, so I close it.

**Comment by StephenWeatherford** [comment]
Thanks!
