### ISSUE TITLE
startArmLanguageServer

### ISSUE THREAD

**Issue by mla0146** [microsoft/vscode-azurearmtools#1522]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: Invalid path given for azureResourceManagerTools.languageServer.dotnetExePath setting. Must point to dotnet executable. Could not find file C:\Program Files\dotnet

Version: 0.15.7
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:288712extension.bundle.js:16:288712
fulfilled extension.bundle.js:16:285617
```

</details>

**Comment by StephenWeatherford** [comment]
@mla0146 Check your vscode settings and look for "azureResourceManagerTools.languageServer.dotnetExePath".  You must have it set to an invalid path.  Try resetting it (to no value) and see if that works.  If not, you'll need set it to point to dotnet.exe as mentioned.  Re-open if you still have problems, thanks!
