### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by holisticnetworking** [microsoft/vscode-azurearmtools#1526]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.openParameterFile
Error type: Error
Error Message: cannot open file:///Users/tomb/Dropbox/My%20Mac%20%28MacBook-Pro-3.local%29/Documents/AzureTraining/azuredeploy.parameters.json. Detail: Unable to read file '/Users/tomb/Dropbox/My Mac (MacBook-Pro-3.local)/Documents/AzureTraining/azuredeploy.parameters.json' (Error: Unable to resolve nonexistent file '/Users/tomb/Dropbox/My Mac (MacBook-Pro-3.local)/Documents/AzureTraining/azuredeploy.parameters.json')

Version: 0.15.7
OS: darwin
OS Release: 21.6.0
Product: Visual Studio Code
Product Version: 1.72.0
Language: en

<details>
<summary>Call Stack</summary>

```
r.$tryOpenDocument workbench.desktop.main.js:2775:76432
```

</details>

**Comment by StephenWeatherford** [comment]
@holisticnetworking It appears you asked the extension to open the matching parameters file but it no longer exists.  You can select a different parameter file using F1 and this command:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/6913354/194643009-a7689f3b-3e8d-4135-b274-b9fbff8d3b93.png">

Please let us know if this doesn't solve the issue, thanks!
