### ISSUE TITLE
There is no completion list when typing the "uri" property

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#1527]
**OS:** All
**Build Version:** 0.15.8

**Repro Steps:**
1. Start with a new or existing template.
2. In the resources sections, type "linked" and select the "Linked Deployment With URI" snippet, save the file.
3. Type the "uri" property with this:
`"uri": "[uri(deployment().properties.)]`
4. Check whether the completion list shows or not.

**Expect:**
The completion list shows well.
![image](https://user-images.githubusercontent.com/45614674/194848009-9010f072-9b17-48a2-8f48-5e658f9be67f.png)

**Actual:**
There is no completion list.

**More Info:**
The completion list shows after clicking "Ctrl+Space".

**Comment by StephenWeatherford** [comment]
Unfortunately we don't currently support more than one level after a function.  We're now concentrating on Bicep so it's unlikely we'd take on the cost to do this work.
