### ISSUE TITLE
startArmLanguageServer

### ISSUE THREAD

**Issue by Prudhvieee** [microsoft/vscode-azurearmtools#1541]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: Invalid path given for azureResourceManagerTools.languageServer.dotnetExePath setting. Must point to dotnet executable. Could not find file /usr/local/share/dotnet/dotnet

Version: 0.15.8
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:288712extension.bundle.js:16:288712
fulfilled extension.bundle.js:16:285617
```

</details>

**Comment by StephenWeatherford** [comment]
You need to open the vscode user settings and change the azureResourceManagerTools.languageServer.dotnetExePath setting.  First try making it empty.  If that doesn't work, set it to a valid path to dotnet.exe.  Let us know if you still have problems.
