### ISSUE TITLE
no

### ISSUE THREAD

**Issue by ah-ha-admin** [microsoft/vscode-azurearmtools#1544]
Does this occur consistently? 
Repro steps:

1.
2.

Action: getAvailableResourceTypesAndVersions
Error type: Error
Error Message: Language client is not ready yet

Version: 0.15.8
OS: linux
OS Release: 5.4.0-1094-azure
Product: Visual Studio Code - Insiders
Product Version: 1.74.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
LanguageClient.sendRequest extension.bundle.js:16:156551
extension.bundle.js:16:481783
fulfilled extension.bundle.js:16:480945
```

</details>

**Comment by StephenWeatherford** [comment]
@ah-ha-admin Looks like you can resolve this issue simply by waiting a bit for the language server to finish loading.  If not, please provide steps to reproduce the problem, thanks!
