### ISSUE TITLE
There are problems with this document's schema impacting one or more items in the document

### ISSUE THREAD

**Issue by jrspinella** [microsoft/vscode-azurearmtools#1547]
![image](https://user-images.githubusercontent.com/5787207/206911201-41b365c4-13fb-4255-8b36-099798510c32.png)

There are other errors in the document, not recognizing Microsoft.Insights/diagnosticSettings and some versioning. Intellisense does not work.

I am getting **Deployment template parse failed: 'Required property 'type' not found in JSON** when I deploy the template to Azure. 

I am on:
AZ CLI: 2.43.0
Bicep: 0.13.1
VS Arm Tools: 0.15,8

**Comment by StephenWeatherford** [comment]
@jrspinella Could you please post a minimal template that reproduces this problem?  The following shows no problems for me:
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {},
    "resources": [
        {
            "type": "microsoft.insights/diagnosticSettings",
            "apiVersion": "2016-09-01",
            "name": "service",
            "location": "westus",
            "properties": {

            }
        }
    ],
    "outputs": {}
}
```

**Comment by jrspinella** [comment]
Hi, 

I am using Azure NoOps Accelerator. You can use the repo that I am using http://aka.ms/azurenoops. Follow the instructions for the quickstart on the readme.

**Comment by jrspinella** [comment]
This has been fixed. [https://github.com/Azure/NoOpsAccelerator/issues/226](https://github.com/Azure/NoOpsAccelerator/issues/226)
