### ISSUE TITLE
Optimize with webpack (Extension causes high cpu load)

### ISSUE THREAD

**Issue by juvestig** [Microsoft/vscode-azurearmtools#155]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.4.2`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/skotkar/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by juvestig** [comment]
My bad. Attached bug report.

[msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-azurearmtools/files/2746554/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt)

**Comment by StephenWeatherford** [comment]
It would still be helpful to provide more info.  Is this always?  Only during certain operations?  Etc.

**Comment by StephenWeatherford** [comment]
In particular, is this during the extension activation?  We're working on big perf improvements around that for all of my group's extensions.

**Comment by juvestig** [comment]
I haven't seen this always. Just crashed like this one more time a few days ago when I clicked on a notification about Go extension.

**Comment by StephenWeatherford** [comment]
I've verified the profile is related to extension loading, so should be fixed by our planned webpack work.  Thanks for reporting.

**Comment by StephenWeatherford** [comment]
Fixed by #164
