### ISSUE TITLE
Parameter Error

### ISSUE THREAD

**Issue by rajat7nandi** [microsoft/vscode-azurearmtools#1551]
The issue text was

Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.openParameterFile
Error type: Error
Error Message: There is currently no parameter file for template file "\rajatcontainer\RajatARMTemplates"

Version: 0.15.8
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.74.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:136:101130extension.bundle.js:136:101130
extension.bundle.js:136:94844extension.bundle.js:136:94844
a extension.bundle.js:136:94530
openParameterFile extension.bundle.js:136:101047
AzureRMToolsExtension.<anonymous> extension.bundle.js:209:221030
extension.bundle.js:209:215129extension.bundle.js:209:215129
o extension.bundle.js:209:214815
extension.bundle.js:209:220879extension.bundle.js:209:220879
extension.bundle.js:16:606378extension.bundle.js:16:606378
Object.<anonymous> extension.bundle.js:16:248531
extension.bundle.js:16:247717extension.bundle.js:16:247717
a extension.bundle.js:16:247403
Object.callWithTelemetryAndErrorHandling extension.bundle.js:16:248439
extension.bundle.js:16:606159extension.bundle.js:16:606159
extension.bundle.js:16:605782extension.bundle.js:16:605782
a extension.bundle.js:16:605468
extension.bundle.js:16:606006extension.bundle.js:16:606006
s.h extensionHostProcess.js:94:107622
s.g extensionHostProcess.js:94:106522
s.executeCommand extensionHostProcess.js:94:106422
Object.executeCommand extensionHostProcess.js:115:30829
extension.bundle.js:136:100571extension.bundle.js:136:100571
fulfilled extension.bundle.js:136:94598
```

</details>
 copied to the clipboard.  Please paste it into this window.

**Comment by StephenWeatherford** [comment]
@rajat7nandi Please use this command from the command palette or right-click context menu to let the extension know what parameters file to use for this ARM template, thanks!

Please let me know if that doesn't solve your problem.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/6913354/217043170-dc50b04d-6d0e-41c3-a9e5-b85a1525a85f.png">
<img width="314" alt="image" src="https://user-images.githubusercontent.com/6913354/217043240-350a72e8-aab2-46ec-b0d7-5b5c61bd5d31.png">
