### ISSUE TITLE
Insert resource is not showing option for Microsoft.Databricks namespace related resources

### ISSUE THREAD

**Issue by mvvsubbu** [microsoft/vscode-azurearmtools#1552]
I am from Azure Databricks Product team, I am looking to author an ARM template for deploying Microsoft.Databricks/accessConnectors resource. I am using this extension, I am not able to see any of the resources present under our service namespace. 

![image](https://user-images.githubusercontent.com/11993108/216734364-c71f03f7-a819-4e90-869f-f42171e16606.png)

Can you add support for Microsoft.Databricks/workspaces, Microsoft.Databricks/accessConnectors resources as well.

**Comment by StephenWeatherford** [comment]
@mvvsubbu If you can provide best-practice snippets for these resources, I would be happy to add them.  Or you're welcome to submit a PR yourself (snippets are in assets/resourceSnippets).  Let me know if you have questions, thanks!

**Comment by mvvsubbu** [comment]
@StephenWeatherford I am giving sample templates from 101 template, which gives usage patterns. Let me know if have any questions. 

https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.databricks

**Comment by StephenWeatherford** [comment]
Which ones would be most useful?  I don't want to include them all.  Maybe 2-4?

**Comment by StephenWeatherford** [comment]
@mvvsubbu Haven't heard back from you. If you'd still like these snippets, please create a PR (I'd suggest just 1-4 snippets).  The following should show you the process.  Let me know if you have questions, I'm happy to help you along but don't currently have time to do it from scratch.  Thanks!

https://github.com/microsoft/vscode-azurearmtools/pull/1508

**Comment by mvvsubbu** [comment]
@StephenWeatherford I am heads down some important customer deliverables by next month end. If this is something that can't be done by your team feel free to close the issue with that comment. We are fine with that.
