### ISSUE TITLE
vscode issue with ARM

### ISSUE THREAD

**Issue by prafull74** [microsoft/vscode-azurearmtools#1554]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.15.8
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.75.1
Language: en

<details>
<summary>Call Stack</summary>

```
C.y workbench.desktop.main.js:2281:58233
C.o workbench.desktop.main.js:2281:55510
C.n workbench.desktop.main.js:2281:55401
async Object.factory workbench.desktop.main.js:2281:55151
```

</details>

**Comment by StephenWeatherford** [comment]
Just like the error message says (from vscode).  You need to open and fix your settings.json file first, it has an error in it.

![image](https://user-images.githubusercontent.com/6913354/218548056-7b8a4f89-5074-4729-83a0-5305768a5e5f.png)
then click this button, top right:
![image](https://user-images.githubusercontent.com/6913354/218548131-7e796db7-5aad-4039-8bed-274cca1cbe80.png)
Should open in the JSON editor.

Feel free to reopen if that doesn't work.
