### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by akishaha** [Microsoft/vscode-azurearmtools#156]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.4.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/akshayshaha/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
Working on webpack'ing to improve performance.

**Comment by StephenWeatherford** [comment]
Tracked by #155
