### ISSUE TITLE
Create ARM parametrers file in Mac

### ISSUE THREAD

**Issue by aniruddhaguha1993** [microsoft/vscode-azurearmtools#1584]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.15.10
OS: darwin
OS Release: 22.4.0
Product: Visual Studio Code
Product Version: 1.77.3
Language: en

<details>
<summary>Call Stack</summary>

```
E.y workbench.desktop.main.js:2297:54909
E.o workbench.desktop.main.js:2297:52186
E.n workbench.desktop.main.js:2297:52077
async Object.factory workbench.desktop.main.js:2297:51827
```

</details>

**Comment by StephenWeatherford** [comment]
Please do as the error message says:
```
Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.
```

Your JSON settings file in vscode has an error in it.
