### ISSUE TITLE
arm

### ISSUE THREAD

**Issue by Devops-Zone7** [microsoft/vscode-azurearmtools#1585]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.10
OS: linux
OS Release: 5.4.0-1106-azure
Product: Visual Studio Code
Product Version: 1.78.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:209:204152
callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:248270
WrappedErrorHandler.closed extension.bundle.js:209:204035
LanguageClient.handleConnectionClosed extension.bundle.js:16:170156
LanguageClient.handleConnectionClosed extension.bundle.js:209:71022
closeHandler extension.bundle.js:16:168118
CallbackList.invoke vscode-jsonrpc/events.js:55:39
Emitter.fire vscode-jsonrpc/events.js:117:36
closeHandler vscode-jsonrpc/connection.js:256:26
CallbackList.invoke extension.bundle.js:16:310204
Emitter.fire extension.bundle.js:16:310988
StreamMessageReader.fireClose extension.bundle.js:209:143245
Socket.<anonymous> extension.bundle.js:209:144905
```

</details>

**Comment by StephenWeatherford** [comment]
@Devops-Zone7 Do you get this every time?  Can you make sure you the azureResourceManagerTools.languageServer.dotnetExePath setting in vscode has its default value (null)?  Thx
