### ISSUE TITLE
Update .net core (was Requirements support)

### ISSUE THREAD

**Issue by ntbuddha** [microsoft/vscode-azurearmtools#1595]
.Net Core 3.1 ended support December 13, 2022.  Is this extension getting updated?  Out of support software is not safe to keep installed.

**Comment by StephenWeatherford** [comment]
@ntbuddha This extension uses dotnet 6.0, not 3.1.  6.0 has a good year left.

**Comment by StephenWeatherford** [comment]
Currently updating from 6.0 to 7.0.
