### ISSUE TITLE
The parameter name shows incorrectly after pasting Chinese Four Ext chars "𠀀𠀁𠣶𤆐𥽠𪛕𪛖" in VSCode

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#1600]
**OS:** M1 (Pro)
**Build Version:** V0.15.10
**Language:** Chinese Four Ext chars

**Repro Steps:**

1. Open a template file in VSCode.
2. Focus a parameter -> F2 -> Paste Chinese Four Ext chars "𠀀𠀁𠣶𤆐𥽠𪛕𪛖".
3. Check whether the parameter name shows correctly.

**Expect:**
The parameter name shows correctly.

**Actual:**
The parameter name shows incorrectly.
![image](https://github.com/microsoft/vscode-azurearmtools/assets/57662131/9aacaf36-b9cc-4845-94e2-02b84ec27668)

**More Info:**
1. The Chinese Four Ext chars shows consistently between the code lens and code.
![image](https://github.com/microsoft/vscode-azurearmtools/assets/57662131/172f14da-122a-409d-bc30-d6a740f45787)
2. This issue doesn't reproduce for other languages.

**Comment by StephenWeatherford** [comment]
VSCode bug.  Entered here: https://github.com/microsoft/vscode/issues/186452
