### ISSUE TITLE
ARM template extension started erroring out recently

### ISSUE THREAD

**Issue by zendu** [microsoft/vscode-azurearmtools#1606]
Does this occur consistently? Yes
Repro steps:
1. Open ARM template.

If there is any error in ARM template or parameter file, it should be highlighted instead of crashing the extension.

Action: Language Server Error
Error type: Error
Error Message: An error occurred in the ARM Template Language Server.

Expected ',' or ']' after array element in JSON at position 2853

Version: 0.15.10
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.80.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:209:203839extension.bundle.js:209:203839
callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:248270
WrappedErrorHandler.error extension.bundle.js:209:203669
LanguageClient.handleConnectionError extension.bundle.js:16:170735
errorHandler extension.bundle.js:16:168065
extension.bundle.js:16:168351extension.bundle.js:16:168351
CallbackList.invoke vscode-jsonrpc/events.js:55:39
Emitter.fire vscode-jsonrpc/events.js:117:36
readErrorHandler vscode-jsonrpc/connection.js:261:22
CallbackList.invoke extension.bundle.js:16:310204
Emitter.fire extension.bundle.js:16:310988
StreamMessageReader.fireError extension.bundle.js:209:143148
extension.bundle.js:209:145634extension.bundle.js:209:145634
```

</details>

**Comment by StephenWeatherford** [comment]
@zendu Can you provide a template or parameters file that causes this issue?  Thanks.
