### ISSUE TITLE
Error type: ENOENT

### ISSUE THREAD

**Issue by jeebitesh** [microsoft/vscode-azurearmtools#1607]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Go To Definition
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'c:\projects\ado-vmss-sf-agent\sdpresources-infra\image\imagedefinition.json'

Version: 0.15.10
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.80.2
Language: en

**Comment by StephenWeatherford** [comment]
@jeebitesh Was this unexpected behavior? If so, I"ll need repro steps like it asks for above, thanks.
