### ISSUE TITLE
Snippets are using old API versions

### ISSUE THREAD

**Issue by Meghna-Chauhan** [microsoft/vscode-azurearmtools#1608]
Azure Resource Manager (ARM) Tools extension for Visual studio code v0.15.10 IntelliSense capability which populates the Azure resource schema generates the templates with API versions that are obsolete.
![image](https://github.com/microsoft/vscode-azurearmtools/assets/58596529/69741bb2-94fe-437e-b082-28560ff1fc5f)

For e.g. here for both Storage accounts and Web Apps there are newer API versions than 2020-12-01 available with more features, this requires lot of manual additions of properties that otherwise could auto populate.
It's not something breaking but a suggestion to consider the feasibility of having new version of APIs integrated with the latest version of the ARM extension.

**Comment by StephenWeatherford** [comment]
I have a process to update, need to run it.
