### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rpus** [Microsoft/vscode-azurearmtools#163]
[msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-azurearmtools/files/2847810/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.4.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/khalidkhan/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
This fix will be released soon.
