### ISSUE TITLE
The 'Add Item' button is overlapped with 'item path' in 'Parameter Files' setting if there is at least one parameter file 

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurearmtools#1644]
**OS:** All
**Build Version:** 20230827.4

**Repro Steps:**

1. Open a template file in VS Code -> Create a parameter file for it.
2. Open user setting -> Navigate to `Azure Resource Manager Tools: Parameter Files`.
3. Check whether the `Add Item` button is not overlapped with `item path`.

**Expect:**
The `Add Item` button is not overlapped with `item path`.

**Actual:**
The `Add Item` button is overlapped with `item path`.
![image](https://github.com/microsoft/vscode-azurearmtools/assets/107091828/f6f03977-d69c-4783-8dba-994985f33bfc)

**Comment by StephenWeatherford** [comment]
@v-chenzha Thanks for finding and entering this bug.  However, this UI is owned by vscode, not by this extension.
