### ISSUE TITLE
Message: An error occurred in the ARM Template Language Server.

### ISSUE THREAD

**Issue by shivakumarg06** [microsoft/vscode-azurearmtools#1655]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: An error occurred in the ARM Template Language Server.

Unexpected token '/', ..."esource":[/* TODO: F"... is not valid JSON

Version: 0.15.11
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.82.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:29:203839extension.bundle.js:29:203839
callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:248270
WrappedErrorHandler.error extension.bundle.js:29:203669
LanguageClient.handleConnectionError extension.bundle.js:16:170735
errorHandler extension.bundle.js:16:168065
extension.bundle.js:16:168351extension.bundle.js:16:168351
CallbackList.invoke vscode-languageserver-protocol/vscode-jsonrpc/events.js:55:39
Emitter.fire vscode-languageserver-protocol/vscode-jsonrpc/events.js:117:36
readErrorHandler vscode-languageserver-protocol/vscode-jsonrpc/connection.js:261:22
CallbackList.invoke extension.bundle.js:16:310204
Emitter.fire extension.bundle.js:16:310988
StreamMessageReader.fireError extension.bundle.js:29:143148
extension.bundle.js:29:145634extension.bundle.js:29:145634
```

</details>

**Comment by StephenWeatherford** [comment]
@shivakumarg06 Can you provide a sample template that produces this error?  Otherwise nothing I can do to debug.  Thx.

**Comment by shivakumarg06** [comment]
the points is there no error in the file, any file opened on the window, this error message keeps up pop, tried few option didn't work, even im not sure why this message keeps popping up

**Comment by StephenWeatherford** [comment]
@shivakumarg06 Are you by any chance using the Remote Repos extension to open a file in a remote repository?

If not, can you please go to vscode settings, and set Azure Resource Manager Tools -> Language Server: Trace Level to "Trace", then open a file that causes the error, then go to View -> Output, select "Azure Resource Manager" in the dropdown, and look for "unhandled exception" or other exception messages?
<img width="1246" alt="image" src="https://github.com/microsoft/vscode-azurearmtools/assets/6913354/14b057bd-1a33-4e0c-8d90-0ab3147f469e">

<img width="1467" alt="image" src="https://github.com/microsoft/vscode-azurearmtools/assets/6913354/5f0fb0f2-35a9-4768-8f36-77c4ea551f84">

Thanks!
