### ISSUE TITLE
not able to generate parameters file

### ISSUE THREAD

**Issue by MotoeRam** [microsoft/vscode-azurearmtools#1668]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.codeLens.gotoParameterValue
Error type: Error
Error Message: cannot open file:///c%3A/users/nexus/azure-iac/azure-arm/parameters-file.json. Detail: Unable to read file 'c:\users\nexus\azure-iac\azure-arm\parameters-file.json' (Error: Unable to resolve nonexistent file 'c:\users\nexus\azure-iac\azure-arm\parameters-file.json')

Version: 0.15.11
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.83.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.$tryOpenDocument workbench.desktop.main.js:2343:37719
```

</details>

**Comment by StephenWeatherford** [comment]
@MotoeRam The error looks pretty self-explanatory.  If this was not an expected result, can you please share the exact repo steps so I can't try to reproduce?  Thanks.
