### ISSUE TITLE
cloud

### ISSUE THREAD

**Issue by takwamekki** [microsoft/vscode-azurearmtools#1674]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Go To Definition
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'c:\users\takwa\onedrive\bureau\azuredeploy.parameters.json'

Version: 0.15.10
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

**Comment by StephenWeatherford** [comment]
@takwamekki  Most likely this is not a bug but rather just an error message that the given file didn't exist.  Perhaps you deleted it, or perhaps you need to select a new params file:
![image](https://github.com/microsoft/vscode-azurearmtools/assets/6913354/f6f2dea7-f644-4104-b740-c4398c6f3554)

Feel free to reopen with more details.
