### ISSUE TITLE
Why it is asking for Windows exe on mac

### ISSUE THREAD

**Issue by jayantchy** [microsoft/vscode-azurearmtools#1675]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: The path returned for .net core does not exist: C:\Program Files\dotnet\dotnet.exe

Version: 0.15.11
OS: darwin
OS Release: 23.1.0
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:289228
fulfilled extension.bundle.js:16:285617
```

</details>

**Comment by StephenWeatherford** [comment]
Could you please make sure you don't have any values set for the following vscode settings:
![image](https://github.com/microsoft/vscode-azurearmtools/assets/6913354/84555a6e-a735-4465-9963-12cf0802fa49)
and
![image](https://github.com/microsoft/vscode-azurearmtools/assets/6913354/8252e4d8-4a01-4d92-8553-d92fd7454f68)
