### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by kunalbelkhede96** [microsoft/vscode-azurearmtools#1678]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.openParameterFile
Error type: Error
Error Message: cannot open file:///c%3A/ado%20codes/scripting-1/armtemplate/azuredeploy.parameters.json. Detail: Unable to read file 'c:\ado codes\scripting-1\armtemplate\azuredeploy.parameters.json' (Error: Unable to resolve nonexistent file 'c:\ado codes\scripting-1\armtemplate\azuredeploy.parameters.json')

Version: 0.15.11
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.$tryOpenDocument workbench.desktop.main.js:2308:77564
```

</details>

**Comment by StephenWeatherford** [comment]
@kunalbelkhede96 Most likely this is not a bug but rather just an error message that the given file didn't exist.  Perhaps you deleted it, or perhaps you need to select a new params file:
![image](https://github.com/microsoft/vscode-azurearmtools/assets/6913354/f6f2dea7-f644-4104-b740-c4398c6f3554)

Feel free to reopen with more details.
