### ISSUE TITLE
Continously getting Starting ARM Template Language Server in VScode 

### ISSUE THREAD

**Issue by Sagar-Mahamuni** [microsoft/vscode-azurearmtools#1681]
I'm continously getting Starting ARM Template Language Server  in VS code after installing the ARM Tool extension in VSCode

![ARM Template issue](https://github.com/microsoft/vscode-azurearmtools/assets/157232774/c343b14c-6bad-4ccf-8b92-d76515235991)

Due to this issue I'm not able to get the intellisense for ARM template.

**Comment by Paul234Code** [comment]
I have the same problem and i can't fix it

**Comment by Paul234Code** [comment]
> I'm continously getting Starting ARM Template Language Server in VS code after installing the ARM Tool extension in VSCode
> 
> ![ARM Template issue](https://private-user-images.githubusercontent.com/157232774/298295713-c343b14c-6bad-4ccf-8b92-d76515235991.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzUxMzQsIm5iZiI6MTcwNzI3NDgzNCwicGF0aCI6Ii8xNTcyMzI3NzQvMjk4Mjk1NzEzLWMzNDNiMTRjLTZiYWQtNGNjZi04YjkyLWQ3NjUxNTIzNTk5MS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMzAwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWMwZjAxN2Y5ODUwNDAxMjViODUzYTBiMWZhN2M2YWVmOTdiNGQ2ZWYyMTg0Nzk0NDZlN2I2YmRlZGY3MGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JDt6EcG43yzzowfkprtFg_xHXcqP2ach2wuPtWy6GKA)
> 
> Due to this issue I'm not able to get the intellisense for ARM template.

But i fixed it by uninstalling the ARM Templates Tools and now i get my intellisence

**Comment by Sagar-Mahamuni** [comment]
Hey Paul,

I tried that too on my machine nut I'm getting the same result. even i tried with uninstalling the VS code as well but getting same error.

**Comment by StephenWeatherford** [comment]
@Sagar-Mahamuni Any other info that might help us narrow it down?  Perhaps try uninstalling and also deleting the folder for it in %userprofile%\.vscode\extensions and/or %userprofile%\.vscode-insiders\extensions?  And then restarting vscode and reinstalling?

You should also make sure you do not have any values set for the following vscode settings:

![image](https://github.com/microsoft/vscode-azurearmtools/assets/6913354/84555a6e-a735-4465-9963-12cf0802fa49)
