### ISSUE TITLE
Template validation issue (n.filter is not a function)

### ISSUE THREAD

**Issue by akshayvidap128** [microsoft/vscode-azurearmtools#1684]
I am using UDT (user-defined type in Bicep). I have converted the Bicep into Arm JSON while I am deploying from custom deployment in Azure Portal. I am facing this error: **n.filter is not a function**. I am providing a snippet here and looking forward to its resolution.

{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "languageVersion": "2.0",
  "contentVersion": "1.0.0.0",
  "metadata": {
    "_generator": {
      "name": "bicep",
      "version": "0.25.53.49325",
      "templateHash": "6661625372774596112"
    }
  },
  "definitions": {
    "Credentials": {
      "type": "object",
      "properties": {
        "login": {
          "type": "string",
          "metadata": {
            "description": "Provide a username"
          }
        },
        "password": {
          "type": "securestring",
          "metadata": {
            "description": "Provide a Password"
          }
        }
      },
      "metadata": {
        "__bicep_export!": true
      }
    }
  },
  "resources": {}
}

**Comment by StephenWeatherford** [comment]
I'm sorry, we don't currently have resources or plans to support languageVersion 2.0 in this extension (which generally come from Bicep transpilation).  Please see https://github.com/microsoft/vscode-azurearmtools/issues/1669 for more information.

**Comment by alex-frankel** [comment]
This one is actually a dup of https://github.com/Azure/bicep/issues/11096 and is specific to the portal. Should be fixed soon.
