### ISSUE TITLE
Intellisense templatespec not working visual studio code

### ISSUE THREAD

**Issue by neok-g** [microsoft/vscode-azurearmtools#1688]
I have added 2 module aliases in bicep.config like shown below:

```  "moduleAliases": {
    "ts": {
      "specs": {
        "subscription": "subscriptionid-prd",
        "resourceGroup": "rg-templatespecs-prd-001"
      },
      "specs-nonprd": {
        ""subscription": "subscriptionid-non",
        "resourceGroup": "rg-templatespecs-nonprd-001"
      }
    }
  }
```

The resourcegroup for alias specs-nonprd contains 3 templatespecs:

<img width="947" alt="image" src="https://github.com/microsoft/vscode-azurearmtools/assets/3228810/ed9fd244-e745-4b71-966a-0ea3cd2395f9">

The intelissense is working for the alias part see below:
![image](https://github.com/microsoft/vscode-azurearmtools/assets/3228810/f170bf39-fea8-42b3-805a-3bb2d5305ba4)

However if the alias is entered intellissense does not work for the 3 templatespecs nor for their versions:

<img width="481" alt="image" src="https://github.com/microsoft/vscode-azurearmtools/assets/3228810/e55b1c90-a4e6-45f9-b26e-7484f2ad067b">

Is this by design or a known issue? 

Expected behavior would be similar as with Azure resources:

<img width="484" alt="image" src="https://github.com/microsoft/vscode-azurearmtools/assets/3228810/7462afab-686f-4e82-b40e-411174e6db4b">

**Comment by neok-g** [comment]
Anyone on this one?

**Comment by neok-g** [comment]
Is there any authoring on this repo? All issues seem to be unanswered...

**Comment by StephenWeatherford** [comment]
@neok-g Sorry for the delay.  Most of our resources are currently on Bicep, but we'll try to be more responsive in this repo.

Your scenario shows Bicep code.  Please move this issue to this repo: http://github.com/azure/bicep/issues

Pretty sure intellisense for templatespecs has not been implemented yet, but by adding a bug for it, it puts it on our radar.

Thanks!
Stephen

**Comment by neok-g** [comment]
@StephenWeatherford OK created the issue https://github.com/Azure/bicep/issues/14102
