### ISSUE TITLE
Need support to resolve

### ISSUE THREAD

**Issue by Moazzem-Hossain-pixel** [microsoft/vscode-azurearmtools#1697]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: EROFS
Error Message: EROFS: read-only file system, open '/Untitled-1.md.parameters.json'

Version: 0.15.11
OS: darwin
OS Release: 23.4.0
Product: Visual Studio Code
Product Version: 1.88.1
Language: en

**Comment by StephenWeatherford** [comment]
@Moazzem-Hossain-pixel Did this happen only one time, or is it consistently and blocking you?  The error doesn't necessarily indicate a bug.  It looks like you were somehow trying to associate a .json file with a params file that hadn't been saved.

Stephen
