### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Klundo** [Microsoft/vscode-azurearmtools#170]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.4.2`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\vdefr\msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
Thanks for reporting.  This is already fixed and should be shipping within a few days.
