### ISSUE TITLE
add

### ISSUE THREAD

**Issue by LLotme** [microsoft/vscode-azurearmtools#1706]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.

Version: 0.15.11
OS: darwin
OS Release: 23.5.0
Product: Visual Studio Code
Product Version: 1.89.1
Language: en

<details>
<summary>Call Stack</summary>

```
m.y workbench.desktop.main.js:2026:15727
m.o workbench.desktop.main.js:2026:13088
m.n workbench.desktop.main.js:2026:12979
async Object.factory workbench.desktop.main.js:2026:12729
```

</details>

**Comment by StephenWeatherford** [comment]
@LLotme The error is self-explanatory - open your vscode user settings file, you have a syntax error there somewhere.   Fix, save and retry, thanks.  Let us know if that doesn't solve the issue.
