### ISSUE TITLE
An error dialog pops up after closing one changed .json file

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurearmtools#173]
**Version:** 1.32.0-insider (user setup)
**Node.js**: 10.2.0
**OS:** All
**Extension Version**: [20190223.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3530)

**Steps to reproduce:**
1. Open one .json file from VS Code.
2. Change the contents of the opened file -> Try to close the opened tab.
3. Click 'Save' or 'Don't Save' on the popped confirmation dialog -> Check the result.

**Expect Experiment:**
No error occurs.

**Actual Experiment**:
Pop up an error dialog with the below message.
![image](https://user-images.githubusercontent.com/34729022/53319278-f47b3880-3886-11e9-9edb-5d2592a86872.png)

**Comment by StephenWeatherford** [comment]
Good catch.
