### ISSUE TITLE
Unable to change the reference of parameters/variables after pressing F2 for parameters/variables

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurearmtools#174]
**Version:** 1.32.0-insider (user setup)
**Node.js**: 10.2.0
**OS:** All
**Extension Version**: [20190223.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3530)

**Steps to reproduce:**
1. Click parameters or variables.
![image](https://user-images.githubusercontent.com/34729022/53319728-38bb0880-3888-11e9-912e-e31c4ae18809.png)
or
![image](https://user-images.githubusercontent.com/34729022/53319730-3ce72600-3888-11e9-9bec-0c431ec533dc.png)
2. Press F2(Or right click it -> Rename Symbol).
![image](https://user-images.githubusercontent.com/34729022/53319762-5be5b800-3888-11e9-9fde-22e3ab438287.png)
3. Change the values 'virtualMachineName' to others -> Press 'Enter'.

**Expect Experiment:**
The reference can be updated successfully.

**Actual Experiment**:
Unable to change the reference.
![image](https://user-images.githubusercontent.com/34729022/53319873-ba129b00-3888-11e9-9acb-fea67bcc6685.png)

**Comment by StephenWeatherford** [comment]
This was a mistake in the testcase.  You can only click on the actual parameter name.  I've corrected the testcase.
![image](https://user-images.githubusercontent.com/6913354/53441792-6b661d80-39bc-11e9-956e-fd43b69446cd.png)
