### ISSUE TITLE
Help needed: The path returned for .net core does not exist

### ISSUE THREAD

**Issue by Souroupl** [microsoft/vscode-azurearmtools#1749]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: The path returned for .net core does not exist: c:\Users\user\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.20~x64\dotnet.exe

Version: 0.15.12
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.91.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:16:286704extension.bundle.js:16:286704
fulfilled extension.bundle.js:16:283093
```

</details>

**Comment by StephenWeatherford** [comment]
@Souroupl Could you try two things:

1) make sure that the following setting in vscode is empty
![image](https://github.com/user-attachments/assets/239348e6-df00-4ad2-8f91-beeff21967f7)
2) uninstall the Azure ARM Tools extension, uninstall the .NET Install Tool extension, reload vscode, and reinstall Azure ARM Tools extension

Let us know if that works, thanks!
