### ISSUE TITLE
Unable to load ARM Schemas

### ISSUE THREAD

**Issue by nandh5886** [microsoft/vscode-azurearmtools#1758]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.15.12
OS: linux
OS Release: 6.5.0-1025-azure
Product: Visual Studio Code
Product Version: 1.93.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:29:183968
callWithTelemetryAndErrorHandlingSync extension.bundle.js:16:245746
WrappedErrorHandler.closed extension.bundle.js:29:183851
LanguageClient.handleConnectionClosed extension.bundle.js:16:167509
LanguageClient.handleConnectionClosed extension.bundle.js:29:50838
closeHandler extension.bundle.js:16:165471
CallbackList.invoke vscode-languageserver-protocol/vscode-jsonrpc/events.js:55:39
Emitter.fire vscode-languageserver-protocol/vscode-jsonrpc/events.js:117:36
closeHandler vscode-languageserver-protocol/vscode-jsonrpc/connection.js:256:26
CallbackList.invoke extension.bundle.js:16:307470
Emitter.fire extension.bundle.js:16:308254
StreamMessageReader.fireClose extension.bundle.js:29:123061
Socket.<anonymous> extension.bundle.js:29:124721
```

</details>

**Comment by StephenWeatherford** [comment]
@nandh5886 Could you look in the Output window
![image](https://github.com/user-attachments/assets/a1a1e82f-972a-4d0e-a27b-69c877cad080)
in the Azure Resource Manager pane
![image](https://github.com/user-attachments/assets/9845ae2f-1e63-4447-b584-109fa55e2e04)
and see if there is additional error information there?  Thx.
