### ISSUE TITLE
Azure rsource manager tools issues in vscode

### ISSUE THREAD

**Issue by vishnuk47** [microsoft/vscode-azurearmtools#1781]
when install ARM tools in vscode.when  you want to create a storage account suggestion for storage account is not showing.in the notification it is showing loading ARM schema and it is still loading. I disable the extension and restarted it even go with uninstalling vscode and reinstalling it .but the issue still persist.

**Comment by StephenWeatherford** [comment]
@vishnuk47 Just to make sure...  The number of schemas available has grown much larger and it takes a minute or two for the extension to finish loading.  After several minutes, do *any* resource suggestions show up?  Thx.

**Comment by StephenWeatherford** [comment]
And *does* it ever get past the Loading stage for Intellisense?  Also take a look at the Output pane, "Azure Resource Manager Tools" selected in dropdown, and see if there are any errors reported there.

**Comment by StephenWeatherford** [comment]
Do note this is being fixed: https://github.com/microsoft/vscode-azurearmtools/issues/1789
