### ISSUE TITLE
Detecting "listCredentials" as unrecognized function

### ISSUE THREAD

**Issue by prbans** [Microsoft/vscode-azurearmtools#187]
EXPECTED BEHAVIOR:

Should not detect "listCredentials" as unrecognized function

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource

![image](https://user-images.githubusercontent.com/42591144/54321080-baab7100-45ac-11e9-9e75-41f9ae2c42d0.png)

ACTUAL BEHAVIOR

Detecting "listCredentials" as unrecognized function

![image](https://user-images.githubusercontent.com/42591144/54321034-8637b500-45ac-11e9-8cd4-156f4a991487.png)

**Comment by StephenWeatherford** [comment]
Unfortunately it's difficult to keep up with these because the list* functions keep expanding.  

https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/listcredentials
