### ISSUE TITLE
ACR ARM template version syntax notification is outdated.

### ISSUE THREAD

**Issue by xuyuji9000** [Microsoft/vscode-azurearmtools#189]
![Screen Shot 2019-03-17 at 8 39 53 PM](https://user-images.githubusercontent.com/4877346/54490887-03d52b00-48f5-11e9-8157-9927bc8c192e.png)

Used `2017-10-01` here. is reporting error. But in the [documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerregistry/2017-10-01/registries), this version is already there.

**Comment by StephenWeatherford** [comment]
@xuyuji9000 That's actually an error in the schema file, which we can't do anything about in the extension. For the moment  you need to report it here: https://github.com/Azure/azure-resource-manager-schemas/issues/ (you'll need to be specific about exactly which resource type is affected).

We're considering improving our tooling experience here such that this would no longer be an issue, but I can't promise anything yet.

cc @bmoore-msft
