### ISSUE TITLE
Missing functions "format" and listAuthKeys

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#190]
- [x] format
- [ ] listAuthKeys

**Comment by StephenWeatherford** [comment]
Compare with this list:

"^\[(json|if|and|or|not|concat|parameters|variables|deployment|reference|resourceId|resourceGroup|subscription|list.*|base64|providers|copyIndex|padLeft|replace|toLower|toUpper|startsWith|endsWith|length|split|skip|take|contains|intersection|union|first|last|indexOf|lastIndexOf|add|sub|mul|div|mod|min|max|range|string|int|float|bool|trim|uri|uniqueString|substring|base64ToString|base64ToJson|uriComponentToString|uriComponent|dataUriToString|dataUri|array|createArray|coalesce|empty|less|lessOrEquals|greater|greaterOrEquals|equals|[\w\$]+\.[\w\$]+)\(.*\).*\]$"

from https://github.com/Azure/azure-resource-manager-schemas/blob/4e9e6d47a0ce491370b93ca8a1b576879214e8b4/schemas/2019-04-01/deploymentTemplate.json#L1436

**Comment by StephenWeatherford** [comment]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-string#format

**Comment by StephenWeatherford** [comment]
Other common ones:

listAuthKeys

**Comment by nilshedstrom** [comment]
It seems this issue was fixed in #408
