### ISSUE TITLE
Unrecognized function name listConnectionStrings

### ISSUE THREAD

**Issue by pietersap** [Microsoft/vscode-azurearmtools#192]
As in the [documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#reference), the cosmosDB DatabaseAccount resource supports a listConnectionStrings() expression. 

However, intellisense gives the notificiation "unrecognized function name 'listConnectionStrings'

**Comment by StephenWeatherford** [comment]
Thanks for reporting.

**Comment by StephenWeatherford** [comment]
FYI, this was fixed in the 0.6.0 release on Thursday.  Thanks again for reporting.
