### ISSUE TITLE
Developer README out of date

### ISSUE THREAD

**Issue by migrande** [Microsoft/vscode-azurearmtools#194]
The README.dev.md file needs to be updated.  The `gulp package` command doesn't work anymore.  I had to use `vsce package` to create the VSIX file.

**Comment by StephenWeatherford** [comment]
Thanks for letting us know!

I'd love to know why you're building the VSIX yourself.  I assume you're making private changes?  Is it something we should fix for everyone?  Thx.

**Comment by migrande** [comment]
Great question.  I wanted to add additional icons for the ARM Template Outline view as there are barely any PaaS services in the published version.  I was doing it locally to help with my own work, and would eventually submit it as a PR once I cleaned it up.

**Comment by StephenWeatherford** [comment]
That would be great, thanks!
