### ISSUE TITLE
Invalide parameter/variable definitions/references not highlighted in 0.5.0

### ISSUE THREAD

**Issue by mrblackistone** [Microsoft/vscode-azurearmtools#195]
0.5.0 does not highlight undefined parameter/variable references or parameters/variables never used.  However, 0.4.2 performs both functions properly.

0.4.2:
![image](https://user-images.githubusercontent.com/36547953/55098405-150bfd80-5094-11e9-87d8-d773519d75af.png)
0.5.0:
![image](https://user-images.githubusercontent.com/36547953/55098442-22c18300-5094-11e9-86c1-6876402424f9.png)

**Comment by StephenWeatherford** [comment]
@mrblackistone That's weird.  I'm not seeing this issue.:
![image](https://user-images.githubusercontent.com/6913354/55099245-9a83b380-507c-11e9-8f84-f3a085999b85.png)

Could you try a couple of things:
1) The obvious one - reinstall the extension, restart vs code
2) If still happening - could you send me the exact .json file you reference here?  Also, what version of vscode?

Thanks!

**Comment by StephenWeatherford** [comment]
Also, do you see the ARM TEMPLATE OUTLINE window in the file explorer when you have a template file opened?
![image](https://user-images.githubusercontent.com/6913354/55107063-a0ce5b80-508d-11e9-84b1-08c89f196748.png)
If not, the extension must not be loading somehow.

**Comment by mrblackistone** [comment]
Sorry for the delay.  There must have been some performance or interaction issue exclusive to my system that was different between the two versions, where the earlier one worked and the later one did not.  Though the issue was repeatable by switching back and forth between them,  I wound up rebuilding my system for unrelated reasons and the issue went away.

If you haven't already, please close out this issue.

Thank you.

________________________________

**Comment by StephenWeatherford** [comment]
Okay, thanks for letting us know!
