### ISSUE TITLE
The help signature still shows after removing the added comma on one .json file

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azurearmtools#196]
**OS: All
Extension Version:** The latest release build_0.5.0

**Steps to reproduce:**

1. Open one .json file like 'new-vm.json'.
2. Search for "targetResourceId" -> Add a comma after the parameters('virtualMachineName').
3. The help with the function signature will shows.
4. Remove the added comma -> Check whether the help signature still shows or not.

**Expected**:
The help signature will disappear.

**Actual**:
The help signature still shows unless moving the mouse.
![image](https://user-images.githubusercontent.com/34729022/55147537-ceee8280-5103-11e9-8ef2-b5dea1ab067e.png)

**Comment by ashemedai** [comment]
For all I know this functionality is how Visual Studio Code's IntelliSense works. As such it has nothing to do with the extension.

E.g. open a new file, set filetype fo Python:
```
import os

os.open(blah,
```

and then delete the comma and you will see the same behaviour as described above.

**Comment by StephenWeatherford** [comment]
Agreed, by design, thanks.
