### ISSUE TITLE
[Discussion] Temporarily lower engine to 1.20.0

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurearmtools#207]
We updated the minimum engine from 1.20.0 to 1.26.0 in this PR: https://github.com/Microsoft/vscode-azurearmtools/pull/200

But due to this issue we probably want to release a fix with the engine still at 1.20.0: https://github.com/Microsoft/vscode-azurearmtools/issues/206

@StephenWeatherford My first thought is just to temporarily move the engine to 1.20.0 and bump right after this release. Like I mentioned in the PR - we only needed 1.26.0 for wizard stuff and ARM doesn't use the wizard. Thoughts? Other option I see is a hot-fix release just for #206

**Comment by StephenWeatherford** [comment]
We're going to put out a hotfix instead.
