### ISSUE TITLE
Types not recognized at subscription level

### ISSUE THREAD

**Issue by slavizh** [microsoft/vscode-azurearmtools#236]
Now that we have subscription level deployment schema recognized by the extension certain types are not recognized.  Specifically the ones I have found:
Microsoft.Resources/resourceGroups
Microsoft.Resources/deployments

![image](https://user-images.githubusercontent.com/11890856/57062320-798c2f00-6cc8-11e9-9d61-42802abfecf5.png)

![image](https://user-images.githubusercontent.com/11890856/57062344-86108780-6cc8-11e9-8cf7-2a4ada4f68bd.png)

There is one strange thing. I see this behavior in one template but do not see it in another. I can share the templates in private only though.

**Comment by StephenWeatherford** [comment]
I'm not seeing this issue, for instance with this template:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Resources/resourceGroups",
      "name": "hello",
      "apiVersion": "2018-05-01",
      "location": "westus",
      "properties": {},
      "tags": "[parameters('baseParameters').tagValues]"
    },
    {
      "type": "Microsoft.Resources/deployments",
      "name": "name",
      "apiVersion": "2018-05-01"      
    }
  ]
}
```

I only see the error about missing baseParameters.

Note: The error you get about valid values is definitely frustrating - it's a limitation of standard JSON validation, though, nothing to do with the extension.  But we are working on ways to improve this experience.

In the meantime, can you double-check the spelling (including casing) of the resource types and api versions, and make sure you haven't specified any invalid properties?  Those can sometimes throw off schema validation.  If you're still having troubles, do you mind either:
1) removing everything except for the offending resources (renaming anything with sensitive info) and posting that, assuming it still repros
2) get them to me in private somehow?  My e-mail is Stephen dot Weatherford at microsoft period com is one option.

Thanks!  Hoping to help sort this out.

**Comment by slavizh** [comment]
Thanks for reaching @StephenWeatherford . I have send you the examples in private. Hoping they will help to find what is causing this.

**Comment by StephenWeatherford** [comment]
This has been fixed!
