### ISSUE TITLE
Microsoft.Network/publicIpAddresses: Wrong errormessage for capitalization

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/vscode-azurearmtools#238]
When I use wrong capitalization in a public IP address, I get a confusing warning.

### Steps to reproduce
Create a publicIP with wrong capitalization in the typename (it is provided in the templates from the portal this way)
```
 {
          "name": "example",
          "type": "Microsoft.Network/publicIpAddresses",
          "apiVersion": "2018-08-01",
          "location": "[parameters('location')]",
          "properties": {  },
      }
```

### Expected behavior
The message: Value is not accepted. Valid values: Microsoft.Network/publicIPAddresses
(although I would prefer a message stating to check capitalization, but not sure if that is possible).

### Actual behavior
The message: Value is not accepted. Valid values: "Microsoft.Network/expressRouteCircuits".

**Comment by StephenWeatherford** [comment]
cc @alex-frankel 

Thanks for reporting.  We're aware of this issue (it's due to schema validation, which is actually handled by vscode). We're investigating ways to solve this and improve the user experience.

**Comment by StephenWeatherford** [comment]
I've added this to our testing list, but closing for now since this should be fixed by future feature work.  Thanks!

**Comment by StephenWeatherford** [comment]
We no longer show an error for this scenario.
