### ISSUE TITLE
Extension doesn't work with jsonc file type

### ISSUE THREAD

**Issue by smflorentino** [Microsoft/vscode-azurearmtools#24]
Recently VSCode started highlighting `//comments` in JSON files as errors unless the `jsonc` file type is used.

But, the ARM template extension only runs when the file type is `json`

Can the extension also run on `jsonc` file types? We have comments in our ARM template (mostly for variables).

**Comment by EricJizbaMSFT** [comment]
FYI @smflorentino we just released an update that includes this fix

I believe you're already familiar with jsonc files in VS Code, but just wanted to mention this [existing bug](https://github.com/Microsoft/vscode/issues/48969) where VS Code opens files with the '.jsonc' extension as plain text. It has been [fixed](https://github.com/Microsoft/vscode/commit/ee3dd420b42354e7c899919ee2a3292fe7ce78f6) in VS Code Insiders and should be included in the next release. There's also workarounds mentioned in the bug.

**Comment by smflorentino** [comment]
Awesome, thanks!

And thanks for the link to the VS code bug. I did not know about that.
