### ISSUE TITLE
Parameters in User Defined Functions are now recognized as valid parameter

### ISSUE THREAD

**Issue by Apholisha** [microsoft/vscode-azurearmtools#248]
Hello,
I have a couple of User Defined Functions in some of the ARM templates.
The functions have parameters defined. But when I use the parameter in question it gets marked as an error. I think it's considers only the template defined parameters as valid ones.

**Comment by StephenWeatherford** [comment]
Thanks for the report. This is tracked by #122, we've been getting a lot of feedback about it, plan on implementing soon.

**Comment by Apholisha** [comment]
Thanks.

**Comment by Apholisha** [comment]
Thanks.
