### ISSUE TITLE
Invalid problems raised for user-defined functions in ARM template

### ISSUE THREAD

**Issue by afnw35342** [microsoft/vscode-azurearmtools#251]
1) Support using the in-built parameters('xyz') function in output.value of the user-defined function rather than raising the following problem...
a) Undefined parameter reference: 'xyz';

          "value": "[if(equals(parameters('SuppliedLocation'),'uksouth'), 'UKS', 'EUS')]"
 is valid

2) Support using user-defined functions rather than raising the following problems...
b) Unrecognised function name: 'xyz'; &
c) Expected the end of the string;

      "Region": "[RegionSelector.discriminate(parameters('pLocation'))]"
is valid

**Comment by StephenWeatherford** [comment]
@afnw35342 Thanks for taking the time to report this.  This is being tracked by #122, I'm hoping to get to it soon.
