### ISSUE TITLE
Show icons of common resource types

### ISSUE THREAD

**Issue by markgar** [microsoft/vscode-azurearmtools#253]
SVG files are only provided for a few resource types.  Can we add more?  This would really help quickly identify resources when their name is a parameter.

I've looked at the code and all that has to be done is SVG files with the same name as the "type" value need to be added to the repo.

I have a feeling these icons already exist.  For instance: https://github.com/amido/azure-vector-icons
![outline](https://user-images.githubusercontent.com/13386095/59035090-20b53680-8832-11e9-8726-2b2446a07437.png)

**Comment by StephenWeatherford** [comment]
Great resource, thanks!

**Comment by nilshedstrom** [comment]
I think this issue was somewhat fixed in #417 .
If someone can provide a list of resource types that are missing then I can try to find icons for those resource types

**Comment by neilpeterson** [comment]
Not a complete list, but here are some that I've identified.

```
Microsoft.Web/sites/extensions
Microsoft.Network/virtualNetworkGateways
Microsoft.Network/trafficManagerProfiles
Microsoft.Sql/servers/databases/extensions
Microsoft.Network/routeTables/routes
Microsoft.Network/networkSecurityGroups/securityRules
SuccessBricks.ClearDB/databases
Microsoft.Media/mediaServices
Microsoft.Network/publicIPPrefixes
Microsoft.Network/azureFirewalls
Microsoft.DocumentDB/databaseAccounts/apis/tables
Microsoft.DocumentDB/databaseAccounts/apis/databases
Microsoft.DocumentDb/databaseAccounts/apis/databases/containers
Microsoft.DocumentDB/databaseAccounts/apis/databases
Microsoft.DocumentDb/databaseAccounts/apis/databases/graphs
Microsoft.DocumentDB/databaseAccounts/apis/databases
Microsoft.DocumentDb/databaseAccounts/apis/keyspaces/tables
Microsoft.DocumentDB/databaseAccounts/apis/keyspaces"
Microsoft.ContainerInstance/containerGroups
Microsoft.Automation/automationAccounts/schedules
Microsoft.Automation/automationAccounts/modules
Microsoft.Automation/automationAccounts/jobSchedules
Microsoft.Insights/components
Microsoft.Insights/autoscalesettings
```

**Comment by nilshedstrom** [comment]
Added icons for most of the resource types in #503

**Comment by StephenWeatherford** [comment]
Fixed by #503

**Comment by StephenWeatherford** [comment]
Just FYI, we've had some issues with the Azure schema CDN and some other things that have delayed this release.  Will have it out as soon as possible, hopefully next week.

**Comment by neilpeterson** [comment]
Fix went out today with this fix, thanks.
