### ISSUE TITLE
"Microsoft.Authorization/policyAssignments" and "Microsoft.Authorization/policyDefinitions" not recognized type

### ISSUE THREAD

**Issue by Apholisha** [microsoft/vscode-azurearmtools#254]
Hi,
The "Microsoft.Authorization/policyAssignments" and "Microsoft.Authorization/policyDefinitions" are not being recognized as type.
Because of that I also get a bunch of "issues" because it doesn't have "location", "severity" and so on properties... and properties suggested by the intellisense are.. well "all possible" from what I can tell :)

**Comment by StephenWeatherford** [comment]
Thanks for filing!  This appears to be a bug in the Azure schemas, which is being tracked inhttps://github.com/Azure/azure-resource-manager-schemas/issues/445 and which I will start pushing harder on.
