### ISSUE TITLE
Microsoft.Resources/deployments Validation issue

### ISSUE THREAD

**Issue by drewkg** [microsoft/vscode-azurearmtools#256]
The following snippet shows a validation error for the apiVersion, and reporting the only valid value are 2015-01-01.   
 {
      "apiVersion": "2018-05-01",
      "name": "linkedTemplate_Solutions",
      "type": "Microsoft.Resources/deployments",
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri": "[concat(parameters('_artifactsLocation'), 'solutionDeploy.json', parameters('_artifactsLocationSasToken'))]"
        }
      }
    }

The value of 2015-01-01 is not currently listed in the documentation, whilst this apiVersion shows as supporting deployment resource (https://docs.microsoft.com/en-au/azure/templates/microsoft.resources/allversions)

**Comment by StephenWeatherford** [comment]
Bug in the Azure schemas, reported it there.

**Comment by simonethreechillies** [comment]
Tested today with the latest api 2019-05-01 but it shows the warning "Value is not accepted. Valid values: "2017-05-10".(1)"

```
"resources": [{
        "type": "Microsoft.Resources/deployments",
        "apiVersion": "2019-05-01",
        ....
```

**Comment by StephenWeatherford** [comment]
Thanks, added it to the bug.

**Comment by StephenWeatherford** [comment]
Closed: https://github.com/Azure/azure-resource-manager-schemas/issues/625#event-2738088903

**Comment by StephenWeatherford** [comment]
This has been fixed by the schema guys.
