### ISSUE TITLE
The matched }/]/) doesn't appear when trying to type {/[/( in the .json file

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-azurearmtools#264]
**Extension Build:** [0.6.1-alphalangserv](\\scratch2\scratch\stephwe\ARM\VSIX\2019-08-15a-json-completion)
**OS**: All

**Steps to reproduce:**
1. Open one json file then type '{'
2. Check whether the matched '}' appears or not.

**Expect Experience:**

The matched '}' appears.

**Actual Experience:**

The matched '}' doesn't appear.

**More info:**

This issue also reproduces when typing [/(/'/".

**Comment by v-dantch** [comment]
Verified on the new [build ](\\scratch2\scratch\stephwe\ARM\VSIX\20190909.7-pos-within-string). 
There is no matching "}" after typing "{". And this issue doesn't repro after typing "(" and "[".
