### ISSUE TITLE
Pop up an error "Couldn't start client ARM Language Server" as long as an ARM deployment file is opened

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#265]
**OS**: Mac & Linux
**Build Version**: [0.6.1-alphalangserv](\\scratch2\scratch\stephwe\ARM\VSIX\2019-08-15a-json-completion)
**Regression**: Not a Regression

**Repro Steps:**
1. Install the ARM Tools Extension in VS Code.
2. Open one deployment file -->Check the result.

**Expect:**
Succeed to open the deployment file without any error.

**Actual:**
Pop up an error even though the deployment file is opened successfully.
![image](https://user-images.githubusercontent.com/34729092/63332599-75b11500-c36a-11e9-9347-90b1c43ce760.png)
![image](https://user-images.githubusercontent.com/34729092/63332606-78136f00-c36a-11e9-9c0a-18ae186fc61e.png)

**More Info:**
No error pops up when opening a deployment file on Windows

**Comment by StephenWeatherford** [comment]
Same as the other Mac/Linux bugs.

**Comment by StephenWeatherford** [comment]
Fixed by #263
