### ISSUE TITLE
Display "Error acquiring .NET Core tooling!" as long as an ARM deployment file is opened 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#267]
**OS**: Mac & Linux
**Build Version**: [0.6.1-alphalangserv](\\scratch2\scratch\stephwe\ARM\VSIX\2019-08-15a-json-completion)
**Regression**: Not a Regression

**Repro Steps:**
1. Install the ARM Tools Extension in VS Code.
2. Open one deployment file -->Check the VS Code pane.

**Expect:**
No error displays after the deployment file is opened.

**Actual:**
Display an error "Error acquiring .NET Core tooling!".
![image](https://user-images.githubusercontent.com/34729092/63332969-26b7af80-c36b-11e9-94cb-087765b83bfd.png)

**More Info:**
No error pops up on Windows.

**Comment by StephenWeatherford** [comment]
This is an issue with how the VSIX was built (needs to be built on Linux or Mac).

**Comment by StephenWeatherford** [comment]
Fixed by #263
