### ISSUE TITLE
Miss double quotes when executing rename symbols

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azurearmtools#268]
**OS:** All
**Extension Version:** [0.6.1-alphalangserv](\\scratch2\scratch\stephwe\ARM\VSIX\2019-08-15a-json-completion)

**Steps to reproduce:**
1. Open any template file, e.g. new-vm.json
2. Rename parameter definition -> Click on a parameter definition -> Right click -> Rename Symbol.
3. Observe the result.

**Expected:**
The double quotes is selected.
![image](https://user-images.githubusercontent.com/41351993/63332708-a6914a00-c36a-11e9-9107-63ff9142d80f.png)

**Actual:**
Miss double quotes.
![image](https://user-images.githubusercontent.com/41351993/63330838-1a315800-c367-11e9-9507-71a3ede1879e.png)

**Comment by StephenWeatherford** [comment]
Huh.  I want to investigate what caused the change in behavior, but this is actually good.

**Comment by StephenWeatherford** [comment]
vscode fixed this or it's something to do with having a language server.  Either way, it's great new behavior and I've updated the repro steps.  Thanks!
