### ISSUE TITLE
Add the ability to deploy a template

### ISSUE THREAD

**Issue by marcvaneijk** [microsoft/vscode-azurearmtools#27]
Add the following capability to the extension:

1. Authenticate to a cloud (Azure, German, China, Governmental and Azure Stack clouds)
2. Select a subscription
3. Select an existing or create a new resource group
4. Deploy a template
5. Select an existing parameter file as input or ask for input values at deployment time
6. Verbose logging of deployment

**Comment by chrmarti** [comment]
Related feature request for signing in to national clouds: https://github.com/Microsoft/vscode-azure-account/issues/23

**Comment by neilpeterson** [comment]
@StephenWeatherford, just jotting down a thought for later consideration. Might we be able to use some of [the parameter file validation work](https://github.com/microsoft/vscode-azurearmtools/issues/394) here? If a tempalte has been associated with a parameters file, use that association during deployment.

**Comment by StephenWeatherford** [comment]
I saw this yesterday too and was thinking along the same lines.  We simply open a terminal with a command that they can customize.  Moved to 0.10.0

**Comment by StephenWeatherford** [comment]
https://dev.azure.com/devdiv/DevDiv/_boards/board/t/ARM%20Template%20Authoring/Stories

**Comment by MarcusFelling** [comment]
Closing and tracking in #1236
