### ISSUE TITLE
Expressions in strings are still colorized after removing the schema of the top line

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azurearmtools#271]
**OS:** All
**Extension Version:** [0.6.1-alphalangserv](\\scratch2\scratch\stephwe\ARM\VSIX\2019-08-15a-json-completion)

**Steps to reproduce:**

1. Load a template file (e.g. new-vm.json)
2. Verify that expressions in strings are colorized
3. Remove the 'http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#' schema at the top of the line.
4. Check whether the expressions in strings are *not* colorized.

**Expected:**
The expressions in strings are *not* colorized any more.

**Actual:**
The expressions in strings are still colorized.

**More Info:**
The ARM TEMPLATE OUTLINE doesn't disappear after removing the schema of the top line.

**Comment by StephenWeatherford** [comment]
This is the correct new behavior, I just haven't finished updating the testcases.  The new behavior is that you should get colorization and the outline view when the language is ARM Deployment Template and they should go away when the language is anything else.  The schema controls whether we automatically change to ARM Deployment Template, but the actual functionality is enabled only based on the language, not the contents.

**Comment by StephenWeatherford** [comment]
Updated testcase, thanks!
