### ISSUE TITLE
A notification dialog pops up when executing 'Format Document' from Command

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-azurearmtools#272]
**OS:** Mac / Linux
**Extension Version:** [0.6.1-alphalangserv](\\scratch2\scratch\stephwe\ARM\VSIX\2019-08-15a-json-completion)

**Steps to reproduce:**
1. Open a file with which language is 'ARM Deploymnet Template'.
2. F1 -> Type 'Format Document' and execute it.
3. Check the result.

**Expected:**
No error occurs and the command is executed successfully.

**Actual:**
A notification dialog pops up.
![image](https://user-images.githubusercontent.com/41351993/63332780-c45eaf00-c36a-11e9-82b0-8633859895b8.png)

**More Info:**
1. There no 'Format Document' displays on the context menu.
2. Show 'No extensions found' after click 'Install Formatter....'.
![image](https://user-images.githubusercontent.com/41351993/63333188-94fc7200-c36b-11e9-94ef-b459a0e431f0.png)
3. This issue doesn't reproduce for a file which language is JSON/ JSON with Comments.

**Comment by StephenWeatherford** [comment]
Same issue as the other Mac/Linux bugs (language server didn't start)

**Comment by StephenWeatherford** [comment]
Fixed by #263
