### ISSUE TITLE
The selected characters are removed when typing an apostrophe 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#273]
**OS**: Mac & Linux & Windows
**Build Version**: [0.6.1-alphalangserv](\\scratch2\scratch\stephwe\ARM\VSIX\2019-08-15a-json-completion)
**Regression**: Not a Regression

**Repro Steps:**
1. Open one deployment file -->Double click to select a set of characters insider a string express.
2. Type an apostrophe (').
3. Check the result.

**Expect:**
The set of characters selected is surrounded by on both sides by an apostrophe.
![image](https://user-images.githubusercontent.com/34729092/63334580-4ac8c000-c36e-11e9-9eda-ea3d6e9ab3be.png)

**Actual:**
The selected characters are removed not surrounded by on both sides by an apostrophe.

**Comment by ashemedai** [comment]
Tried this with Visual Studio Code 1.37.0 and extension version 0.6.0 and I cannot reproduce this. When I select either unquoted or quoted text, the editor will add a single quote on both sides in both cases. This results in single-quoted text or double single-quoted text. Text has not been deleted or replaced.

Tried it with a `"[concat()]"` as well as a `"[parameters()]"`, FWIW.

So if this happens in 0.6.1 it would be a regression from 0.6.0.

**Comment by StephenWeatherford** [comment]
Yep, it's an issue with a pre-release version (not even in master yet), thanks.
