### ISSUE TITLE
Use of expressions raises problems in some resource properties

### ISSUE THREAD

**Issue by ashemedai** [microsoft/vscode-azurearmtools#277]
I think this is different from #122 — unless I misunderstood the issue. And also hoping this has to do with the extension and not the schemas.

Using Visual Studio Code 1.37.0 and extension 0.6.0.

While writing templates I encountered the case that using

```
        {
            "name": "[parameters('resourceGroup')]",
            "type": "Microsoft.Resources/resourceGroups",
            "apiVersion": "2018-05-01",
            "location": "location",
            "properties": {}
        }
```

and

```
        {
            "name": "deployment1",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2018-05-01",
            "resourceGroup": "[parameters('resourceGroup')]",
            "properties": {
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "parameters": {},
                    "variables": {},
                    "resources": [],
                    "outputs": {}
                },
                "parameters": {}
            }
        }
```

both complain about `[parameters('resourceGroup')]` not conforming to the regexp of `^[-\w\._\(\)]+$`. So it seems that these fields are not annotated to allowing functions there. But this passes validation and you can deploy them.

**Comment by StephenWeatherford** [comment]
These are issues with the schema.  

1) deployments' resourceGroup property: Also entered as https://github.com/Azure/azure-resource-manager-schemas/issues/443, will try to push it along.
2) resourceGroups' name: new bug https://github.com/Azure/azure-resource-manager-schemas/issues/700

**Comment by StephenWeatherford** [comment]
They tell me they're working on https://github.com/Azure/azure-resource-manager-schemas/issues/443

**Comment by ashemedai** [comment]
Thanks @StephenWeatherford — should have known it was schema, I somehow missed that existing issue while checking the schema issues. Appreciated.

**Comment by StephenWeatherford** [comment]
This has been fixed!
