### ISSUE TITLE
No validation on outputs' names

### ISSUE THREAD

**Issue by ashemedai** [microsoft/vscode-azurearmtools#280]
Apologies if this is a schema thing, but this seemed the most logical repository in my mind.

Right now when working in Visual Studio Code with the extension, I am allowed to create outputs with named keys that are not supported. Reading through the [appropriate documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates#outputs) it seems that the names are limited to the [JavaScript identifiers specification](https://developer.mozilla.org/en-US/docs/Glossary/Identifier), to be specific: `^[^0-9][\D\$_0-9]+$`. Maybe this is obvious when you consider the case how you use it, but since we do so much other handholding and validation, why not warn on this as well?

Reproduce:

Create an output like:
```
"outputs": {
    "database-subnet": {
        "type": "string",
        "value": "[parameters('databaseSubnet')]"
    }
}
```

This passes azure cli validation, you can even deploy this and get the outputs defined in ARM, so the problem is a bit broader in scope even now that I think about it.

![image](https://user-images.githubusercontent.com/610865/63775291-50c71f80-c8df-11e9-8c2a-5ee5b77e4dd1.png)

**Comment by ashemedai** [comment]
It depends on how you want to define problems. :)

If you want to use the outputs in another template you will be using something similar to:

`"subnetResourceId": "[reference(variables('subnetResourceId'), '2018-05-01').outputs.public-subnet.value]"`

If you thought you could use any identifier, this is the place where the problem will arise when you see that the name after `outputs` needs to be conforming. The moment you type it with a dash you will get a partial red coloured text, but it might not be clear just why it is wrong. And then you get to play the refactor dance. Not a huge problem, but annoying nonetheless. Especially since ARM's deployment swallows it without complaint on both validate and create.

**Comment by StephenWeatherford** [comment]
To make sure I understand, Azure deployed without any problems with your last example, it's just the tool that is confused by the property notation with hyphens, correct?  In other words, what I'm hearing is that Azure has no problems with this, but the extension is confused?

**Comment by ashemedai** [comment]
Sorry for the delay @StephenWeatherford. Partially correct, Azure allowed me to deploy the template in the first place and those outputs got defined with those non-confirming names. But then trying to use these names in any way in another template fails validation because of the non-conforming names.

**Comment by StephenWeatherford** [comment]
@bmoore-msft Thoughts on this?  Is there a way to legally reference an output from another deployment that has a hyphen in it?  If not, should Azure be allowing them?

**Comment by StephenWeatherford** [comment]
Similar issue:
```json
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "my-location": {
            "type": "string",
            "defaultValue": {
                "myprop": "myvalue",
                "my-prop": "my-value"
            }
        }
    },
    "resources": [
    ],
    "outputs": {
        "location": {
            "type": "string",
            "value": "[parameters('my-location').my-prop]" <<< doesn't work, but we do completion for it
        }
    }
}
```

**Comment by bmoore-msft** [comment]
ARM seems to handle things fine (for outputs) it seems like the template language doesn't though (for any property name that has a hyphen).  I wouldn't do anything in the extension for now, until we figure out what's going on with the parser.

**Comment by alex-frankel** [comment]
If there is a hyphen in the output name, you can use this syntax:
`*.outputs['my-hyphen-output']`. So this works:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {},
    "resources": [
        {
            "name": "nestedDeployment1",
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2017-05-10",
            "properties": {
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "resources": [],
                    "outputs": {
                        "test-hyphen": {
                            "type": "string",
                            "value": "alex"
                        }
                    }
                }
            }
        }
    ],
    "outputs": {
        "my-output": {
            "type": "string",
            "value": "[reference('nestedDeployment1').outputs['test-hyphen'].value]"
        }
    }
}
```

That works for your example too @stephenweatherford:

```json
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "my-location": {
            "type": "object",
            "defaultValue": {
                "myprop": "myvalue",
                "my-prop": "my-value"
            }
        }
    },
    "resources": [
    ],
    "outputs": {
        "location": {
            "type": "string",
            "value": "[parameters('my-location')['my-prop']]"
        }
    }
}
```

We can probably close this issue, but we need to get this doc'd @tfitzmac

**Comment by neilpeterson** [comment]
Thanks for confirming @alex-frankel.
