### ISSUE TITLE
No errors for duplicate properties

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurearmtools#288]
<img width="1048" alt="Screen Shot 2019-09-13 at 3 39 30 PM" src="https://user-images.githubusercontent.com/22795803/64898625-b3891c80-d63c-11e9-92d9-9b6177a1e998.png">

**Comment by StephenWeatherford** [comment]
Fixed.  https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10205
