### ISSUE TITLE
Add configuration option to control the primary resource attribute displayed in sidebar

### ISSUE THREAD

**Issue by skeeler** [Microsoft/vscode-azurearmtools#29]
Per the title, often we'll have a "copy" resource whose "name" is constructed in the copy loop and may contain text such as: "[variables('refname')[copyIndex()].attrib]". It would be helpful to be able to control which attribute gets displayed for resources in the sidebar window. For example, if I could specify "comments" and enter appropriate free-form text there, it would be much easier to identify entries in the JSON Outline view.

**Comment by StephenWeatherford** [comment]
@skeeler Would you want to show only a single attribute there, or a combination?  Do you have a suggestion for how this might look in the settings?  Thanks.
