### ISSUE TITLE
Inset the selected completion directly 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#296]
**OS**: Darwin x64 17.7.0
**Build Version:** [20190919.7 ](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10205)

**Repro Steps**:
1. Open one template file like [new-vm.json]("\\trinlab2\BAQAFiles\CloudTools\VS Code Extension\Resources\Test templates for ARM Tools\vscode\new-vm.json") . 
2. Put the cursor anywhere inside an existing property name anyone in the file --> Press "Ctrl+ Space" --> Show valid completions that match the existing portion of the property name.
3. Select one --> Check the result.

**Expect:**
Show up correctly as before.

**Actual:**
Inset the selected completion directly.
![image](https://user-images.githubusercontent.com/34729092/65322593-d89c0300-dbd9-11e9-9cfe-a4058f1740a8.png)

**More Info:**
1. Also repro for the property value.
![image](https://user-images.githubusercontent.com/34729092/65322453-79d68980-dbd9-11e9-9249-8b5e149d1fb0.png)
2. This issue only reproduces on Mac.

**Comment by StephenWeatherford** [comment]
I can’t reproduce this (Windows or Mac).  However, the symptoms seem to indicate that the language server has not started.  Can you make sure the language is set to Azure Resource Manager Template?  Also, can you look at the Output window in the Azure Resource Manager Tools and Azure Resource Manager Template tabs and show me what they say?  I expect something like this:

Azure Resource Manager Tools:
Using dotnet core from c:\Users\stephwe\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5\dotnet.exe
Starting ARM Template Language Server at c:\Users\stephwe\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.7.0\languageServer\Microsoft.ArmLanguageServer.dll
Client options:
{
  "documentSelector": [
    {
      "language": "arm-template",
      "scheme": "file"
    }
  ],
  "diagnosticCollectionName": "ARM Template Language Server diagnostics",
  "revealOutputChannelOn": 3
}
Server options:
{
  "run": {
    "command": "c:\\Users\\stephwe\\AppData\\Roaming\\Code\\User\\globalStorage\\msazurermtools.azurerm-vscode-tools\\.dotnet\\2.2.5\\dotnet.exe",
    "args": [
      "c:\\Users\\stephwe\\.vscode\\extensions\\msazurermtools.azurerm-vscode-tools-0.7.0\\languageServer\\Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  },
  "debug": {
    "command": "c:\\Users\\stephwe\\AppData\\Roaming\\Code\\User\\globalStorage\\msazurermtools.azurerm-vscode-tools\\.dotnet\\2.2.5\\dotnet.exe",
    "args": [
      "c:\\Users\\stephwe\\.vscode\\extensions\\msazurermtools.azurerm-vscode-tools-0.7.0\\languageServer\\Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  }
}


Azure Resource Manager Template:
[Info  - 11:02:47 AM] Finding descriptor for initialize
[Info  - 11:02:47 AM] Starting: Routing Request (0) initialize
[Info  - 11:02:47 AM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 11:02:47 AM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 11:02:47 AM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 11:02:47 AM] Finished: Routing Request (0) initialize in 45ms
[Info  - 11:02:47 AM] Finding descriptor for initialized
[Info  - 11:02:47 AM] Starting: Routing Notification initialized
[Info  - 11:02:47 AM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams

**Comment by v-dantch** [comment]
After resetting the Mac, verified this issue again and it doesn't reproduce for now. And we will try to avoid the machine issue in future.

**Comment by StephenWeatherford** [comment]
Thx
