### ISSUE TITLE
The matched "}" doesn't appear when trying to type "{" in the .json file

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#297]
**OS**: All
**Build Version:** [20190919.7 ](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10205)

**Repro Steps:**
1. Open one json file then type '{'
2. Check whether the matched '}' appears or not.

**Expect:**
The matched '}' appears.

**Actual:**
The matched '}' doesn't appear.

**More Info:**
This issue does not reproduce when typing "(" and "[".

**Comment by StephenWeatherford** [comment]
I can’t reproduce this one, either (Windows or Mac).  Maybe it’s related to the ARM language server not starting like in #296?

**Comment by v-dantch** [comment]
After resetting the Mac, verified this issue again and it doesn't reproduce for now. And we will try to avoid the machine issue in future.

**Comment by StephenWeatherford** [comment]
Thx
