### ISSUE TITLE
Loading extension fails when path contains whitespace

### ISSUE THREAD

**Issue by jorgecotillo** [microsoft/vscode-azurearmtools#301]
Repro steps:

1.
2.

Action: acquireDotnet
Error type: 1
Error Message: Command failed: c:\Users\Jorge Cotillo\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.7.0\assets\scripts\dotnet-install.cmd -InstallDir 'c:\Users\Jorge Cotillo\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
'c:\Users\Jorge' is not recognized as an internal or external command,
operable program or batch file.

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:299:12
ChildProcess.emit events.js:182:13
maybeClose child_process.js:962:16
Socket.ChildProcess.spawn.stream.socket.on child_process.js:381:11
Socket.emit events.js:182:13
Pipe.Socket._destroy._handle.close net.js:606:12
```

</details>

**Comment by StephenWeatherford** [comment]
Great catch, thanks!  Have seen a similar issue before, thought it was fixed...

**Comment by StephenWeatherford** [comment]
This is actually weird, I can't repro this.  What build of the extension are you using, or where did you get it?  Was it forwarded to you via e-mail from AlexF?

**Comment by StephenWeatherford** [comment]
I can repro now
