### ISSUE TITLE
The JSON OUTLINE doesn't display when open a parameters file

### ISSUE THREAD

**Issue by v-amyang** [Microsoft/vscode-azurearmtools#31]
Repro Steps:
1.Open an AzureResourceGroup1 solution [AzureResourceGroup1.zip](https://github.com/Microsoft/vscode-azurearmtools/files/1746910/AzureResourceGroup1.zip) which contains 2 json files
2.Click the LoadBalancedVirtualMachine.json file and LoadBalancedVirtualMachine.parameters.json file one by one

Expect:
The JSON OUTLINE display when click either of them.
![expect](https://user-images.githubusercontent.com/34874231/36525346-79d74468-17a1-11e8-8013-132a156a1b5a.PNG)
Actual:
The JSON OUTLINE doesn't display when open a json file which contains no items
![actual](https://user-images.githubusercontent.com/34874231/36525183-c40297dc-17a0-11e8-92ff-87271216c34a.PNG)

**Comment by StephenWeatherford** [comment]
These are parameter files, not template files. Not sure if this should work or not, but I suppose there's no reason it shouldn't.

**Comment by StephenWeatherford** [comment]
By design.
