### ISSUE TITLE
Template validation failing in v0.7.0

### ISSUE THREAD

**Issue by bkonicek-cs** [microsoft/vscode-azurearmtools#314]
This may have been introduced with the Language Server. In a brand new template, I can add the skeleton template with the `arm!` shortcut. When trying to add a resource snippet to the template, it is picking up the `arm-` text as invalid and fails to find any snippets. I get several errors on this example template:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
    },
    "variables": {
    },
    "resources": [
        arm-
    ],
    "outputs": {
    }
}
```

```
Template validation failed: Unexpected character encountered while parsing value: a. Path 'resources', line 9, position 8.

Unexpected character sequence in array element value.

Value must conform to exactly one of the associated schemas

Value must be one of the following types: object
```

If I delete the contents of the template to try and start over, the `Template validation failed` error remains, and I can no longer even add the skeleton snippet. I have to completely delete the template and create a new file in order to get even that functionality back.

When I revert the extension back to v0.6.0 or earlier the snippets work as expected.

**Comment by StephenWeatherford** [comment]
@bkonicek-cs 
You're using the "Azure Resource Manager Snippets" extension by Sam Cogen, right?  Can you make sure you're on the most recent version of it (1.4.19)?  That should support the new language id of arm-template which we're using.

An empty template is not a valid ARM template, so seeing a template validation error is expected.

Thanks for trying out the new extension!

BTW, if you need to compare the old behavior, you can set the azureResourceManagerTools.autoDetectJsonTemplates setting to false, then you can control seeing the new behavior/old behavior by changing the language to json/jsonc or Azure Resource Manager Template.

cc @alex-frankel

**Comment by bkonicek-cs** [comment]
Thanks @StephenWeatherford - I had the snippets extension disabled to troubleshoot and had manually added the snippets from github. I just tried re-enabling the extension and it appears to be working now - it's possible that my Snippets extension hadn't updated to the latest version.

Thanks for your help!

**Comment by StephenWeatherford** [comment]
Glad to hear, thanks for letting us know.
