### ISSUE TITLE
reference TLE signature intellisense out of date

### ISSUE THREAD

**Issue by mtnrbq** [Microsoft/vscode-azurearmtools#32]
The intellisense for the `reference()` resource function expects only 2 parameters
`reference(resourceName/resourceIdentifier, [apiVersion])` however the specification at [https://docs.microsoft.com/...](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#reference) has the signature 
`reference(resourceName or resourceIdentifier, [apiVersion], ['Full'])` , i.e. 3 parameters

**Comment by EricJizbaMSFT** [comment]
FYI @mtnrbq we just released an update that includes this fix
