### ISSUE TITLE
Azure Resource Manager Tools for Visual Studio Code (Preview)--无法安装

### ISSUE THREAD

**Issue by si7eka** [microsoft/vscode-azurearmtools#322]
Repro steps:

1.
2.

Action: acquireDotnet
Error type: 1
Error Message: Command failed: "c:\Users\zhenglif\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.7.0\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\zhenglif\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
Could not find/download: ".NET Core Runtime" with version = 2.2.5
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
����λ�� C:\Users\zhenglif\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.7.0\assets\install scripts\dotnet-i
nstall.ps1:596 �ַ�: 5
+     throw "Could not find/download: `"$assetName`" with version = $Sp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find/download: ".NET Core Runtime" with version = 2.2.5
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
 

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: zh-cn

**Comment by StephenWeatherford** [comment]
@si7eka What happens if you do the following from command window:

`curl -o dotnet-install.ps1 https://dot.net/v1/dotnet-install.ps1`

Does it download dotnet-install.ps1 into your current directory?

If yes, can you try running `powershell .\dotnet-install.ps1`?  Does it succeed in installing dotnet?

**Comment by si7eka** [comment]
PS C:\WINDOWS\system32> curl -o dotnet-install.ps1 https://dot.net/v1/dotnet-install.ps1
curl : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ curl -o dotnet-install.ps1 https://dot.net/v1/dotnet-install.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

--------
Maybe I'm a regulated network

**Comment by si7eka** [comment]
C:\Users\zhenglif> curl -o dotnet-install.ps1 https://dot.net/v1/dotnet-install.ps1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24378  100 24378    0     0  11065      0  0:00:02  0:00:02 --:--:-- 11065
----
I tried it once in CMD. EXE and it can be downloaded

**Comment by StephenWeatherford** [comment]
Have you tried restarting vscode and seeing if it works the second time?  If no, can you do "F1" then "Azure Resource Manager Tools: Uninstall dotnet core for this extension", restart and try again?

thanks!

**Comment by si7eka** [comment]
Azure Resource Manager Tools for Visual Studio Code (Preview) extension, I have reinstalled, but it still does not work properly;
Now whenever I start vscode, it will display "Downloading .NET Core tooling version(s) 2.2.5 ......................... ................", but will not succeed;

**Comment by StephenWeatherford** [comment]
Did you try this from above?
> Press "F1" then select "Azure Resource Manager Tools: Uninstall dotnet core for this extension", restart and try again?
