### ISSUE TITLE
Language server using lots of memory

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#324]

**Comment by amrik2309** [comment]
Stephen, First of all thanks for replying my response on the vscode extension forum at : https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools&ssr=false#review-details
[azure_prdmvc.zip](https://github.com/microsoft/vscode-azurearmtools/files/3710860/azure_prdmvc.zip)
Indeed the template is too big and there are around 3000 lines roughly with too many resources. I have attached the template in zip format. Let me know if there is anything needed from my side to make this tool better.

**Comment by paule96** [comment]
I have the same problem. With my ARM template, it consumes up to 10GB of memory. Please fix this thing. This is a very annoying thing because everything takes years to open.

**Comment by danstis** [comment]
For me a fairly simple 1400 line template consumes approx 1GB of RAM to open, after working on the template for 15-20 minutes the memory usage will be 5-6GB, with my machine paging desperately to attempt to keep up.

**Comment by StephenWeatherford** [comment]
Sorry for the incovenience, we are working on the fix.

**Comment by paule96** [comment]
if you need any examples ore something that helps to resolve this issue please ping me :) I have many templates.

**Comment by paule96** [comment]
What I see is it only happens if you use the autocomplete. If you only "browse" a template it is "okay". Only to 2 - 3 GB but that very stable. But if you start typing it explodes and eats the RAM.

**Comment by StephenWeatherford** [comment]
Expecting to have this out next week.

**Comment by StephenWeatherford** [comment]
Sorry this took so long, but this is fixed in 0.8.0.
