### ISSUE TITLE
Value must be one of the following values: "Microsoft.ContainerRegistry/registries/buildTasks/steps"

### ISSUE THREAD

**Issue by pagyP** [microsoft/vscode-azurearmtools#326]
That error is shown on this part of the template:

![image](https://user-images.githubusercontent.com/34237608/66555180-24d9c380-eb46-11e9-8ec5-78e6ec040bbf.png)

Is that a problem with the extension or something else?

Thanks

**Comment by StephenWeatherford** [comment]
Technically it's a problem with the current Azure schema, but we're working on a much better experience.

**Comment by pagyP** [comment]
Okay, thank you

**Comment by timmkrause** [comment]
Quick question in between: From the supplied screenshot you can see `"apiVersion"` also has squiggly lines saying `Value must be one of the following values: "201xx-xx-xx"`. In my case it also mentions an earlier version or even `-preview` versions. Why are these warnings shown? Is this something I have to address?
My first assumptions was that `apiVersion`s have to be aligned but after some reading I found out that this is not the case.

Am I doing something wrong or is this a false positive?

**Comment by timmkrause** [comment]
I guess it's because I upgraded to a version which is not part of the schema which I am using:

https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2015-01-01/deploymentTemplate.json

OK, makes sense...

**Comment by StephenWeatherford** [comment]
You're doing nothing wrong.  Many current tools don't handle the full schema with all versions (there are just too many of them), and JSON schema validation wasn't really intended for this kind of scenario.  We're working on an improved approach, we expect it to be available very soon.
