### ISSUE TITLE
The connection to the ARM Template Language Server got closed.

### ISSUE THREAD

**Issue by slavizh** [microsoft/vscode-azurearmtools#327]
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.1
Language: en

<details>
<summary>Call Stack</summary>

```
n.callWithTelemetryAndErrorHandlingSync.e extension.bundle.js:218:772819
Object.t.callWithTelemetryAndErrorHandlingSync extension.bundle.js:1:193147
WrappedErrorHandler.closed extension.bundle.js:218:772687
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageReader.fireClose vscode-jsonrpc/messageReader.js:111:27
Socket.readable.on vscode-jsonrpc/messageReader.js:151:46
Socket.emit events.js:187:15
Pipe._handle.close net.js:606:12
```

</details>

**Comment by StephenWeatherford** [comment]
@slavizh Thanks for entering.  Unfortunately, the bug info doesn't tell us much.  Did this happen just once, or every time, or...?

**Comment by slavizh** [comment]
It happened once so far. .Net Core service was also using too much memory as well. I thought that the trace was enough as basically the UI gave me option to open link and log this directly. Something like debug procedure.

**Comment by StephenWeatherford** [comment]
We will have a fix soon for the memory usage issue, hopefully that will solve this.
