### ISSUE TITLE
The icons of the .deployproj file are inconsistent for one opened ARM project

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-azurearmtools#33]
Repro Steps:
1. Open an ARM solution 'AzureResourceGroup1'.
2. Expand the 'AzureResourceGroup1' and check the icon of **AzureResourceGroup1.deployproj** file.
3. Check the opened icon for the **AzureResourceGroup1.deployproj** file.

Expect:
These two icons are conistent.

Actual:
These two icons are inconstent. Please see the below attachment.
![icons](https://user-images.githubusercontent.com/34729022/36832060-f535255a-1d21-11e8-88be-a9e6838693e9.png)

More info:
This issue doesn't reproduce for one new created .deployproj file.

**Comment by StephenWeatherford** [comment]
This is VS Code behavior.
