### ISSUE TITLE
Blocked by software restriction policies

### ISSUE THREAD

**Issue by venkatx5** [microsoft/vscode-azurearmtools#331]
Repro steps:

1. Open ARM template JSON file.

Action: acquireDotnet
Error type: string
Error Message: & : File C:\Users\guestuser\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.7.0\assets\install scripts\dotnet-i
nstall.ps1 cannot be loaded because its operation is blocked by software restriction policies, such as those created by
 using Group Policy.
At line:1 char:128
+ ... ture = '';& 'C:\Users\guestuser\.vscode\extensions\msazurermtools.azur ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

Version: 0.7.0
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

**Comment by StephenWeatherford** [comment]
Does dotnet install work if you install it manually?
1) curl https://dot.net/v1/dotnet-install.ps1 -o dotnet-install.ps1
2) powershell .\dotnet-install.ps1
