### ISSUE TITLE
type of 'Microsoft.Storage/storageAccounts/fileServices/shares' not recognized

### ISSUE THREAD

**Issue by cwbuege** [microsoft/vscode-azurearmtools#333]
Hello - 

I wanted to report that the above listed 'type' isn't recognized by this plugin.  Neither is the simpler version of 'Microsoft.Storage/storageAccounts/fileServices'.

If I run my ARM template using fileServices or fileServices/shares to create my share, it does work fine so I know there isn't a mistake there.

Just wanted to pass this along.

Charles

**Comment by StephenWeatherford** [comment]
Thanks for letting us know!  We're currently working on this and related issues.

**Comment by StephenWeatherford** [comment]
This is a schema issue and was reported here: https://github.com/Azure/azure-resource-manager-schemas/issues/793

**Comment by neilpeterson** [comment]
@cwbuege thanks again for raising this. I am looking broadly at schema generation and issues like this. I have added an additional note on the schema issue, will continue to track in that project, and close this issue.

Thanks again.
