### ISSUE TITLE
type of 'Microsoft.ManagedServices/registrationAssignments' not recognized

### ISSUE THREAD

**Issue by eadams1971** [microsoft/vscode-azurearmtools#342]
Lighthouse is going to be a big, big deal and deploying through ARM templates is going to be commonplace so it would good if the schema recognized the new managed services types:

Microsoft.ManagedServices/registrationAssignments
Microsoft.ManagedServices/registrationDefinitions

**Comment by eadams1971** [comment]
The actual error messages from the Output window are:

Value must conform to exactly one of the associated schemas arm-template (schema)

**Comment by eadams1971** [comment]
Ignore the close.  Didn't mean to close the issue.

**Comment by eadams1971** [comment]
The actual error message received is:
{
	"resource": "/c:/Users/XXXXX/Documents/Lighthouse/delegatedResourceManagement.json",
	"owner": "ARM Template Language Server diagnostics",
	"code": "",
	"severity": 4,
	"message": "Value must conform to exactly one of the associated schemas",
	"source": "arm-template (schema)",
	"startLineNumber": 39,
	"startColumn": 9,
	"endLineNumber": 39,
	"endColumn": 10
}

**Comment by StephenWeatherford** [comment]
@eadams1971 The schemas are there (we don't know these), for instance the following works for me without errors:
```json
    "resources": [
        {
            "type": "Microsoft.ManagedServices/registrationAssignments",
            "apiVersion": "2019-06-01",
            "properties": {
                "registrationDefinitionId": ""
            },
            "name": "this is my name"
        }
    ]
```
However, due to the way json schema validation works, we currently get very unhelp error messages and intellisense.  That will be changing *very soon*, in our next release.

**Comment by neilpeterson** [comment]
Fix went out today with this fix, thanks.
