### ISSUE TITLE
Exactly 1 match required, but found more than 1 | arm-template (schema)

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurearmtools#348]
<img width="1046" alt="Screen Shot 2019-10-25 at 2 56 00 PM" src="https://user-images.githubusercontent.com/22795803/67606971-d6c4e280-f737-11e9-8283-82fafad93a78.png">

**Comment by StephenWeatherford** [comment]
Most of these issues were fixed in 0.8.1, released 2 days ago.
