### ISSUE TITLE
autocomplete list for child resources should be filtered based on the parent

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#350]
If I'm adding a child resource to the vnet, the autocomplete list should be restricted to child resources of the parent.

**Comment by StephenWeatherford** [comment]
https://dev.azure.com/devdiv/DevDiv/_boards/board/t/ARM%20Template%20Authoring/Stories/?workitem=1055499

**Comment by neilpeterson** [comment]
Example:

![image](https://user-images.githubusercontent.com/7844635/76561246-21819580-6460-11ea-8e60-376696735440.png)

**Comment by StephenWeatherford** [comment]
Just FYI, we've had some issues with the Azure schema CDN and some other things that have delayed this release.  Will have it out as soon as possible, hopefully next week.

**Comment by neilpeterson** [comment]
Fix went out today with this functionality, thanks.
