### ISSUE TITLE
autocomplete list for apiVersions on child resources is empty

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#351]
If I have a child resource and on the apiVersion property try to bring up the completion list an empty list is returned, e.g.

      "resources": [
        {
          "type": "subnets",
          "apiVersion": "",

I suspect because we're looking for an exact type match - we'd need to include parent type when building the list.

**Comment by StephenWeatherford** [comment]
This no longer repros, although I'm not sure if the list that we get is correct.

**Comment by StephenWeatherford** [comment]
https://dev.azure.com/devdiv/DevDiv/_boards/board/t/ARM%20Template%20Authoring/Stories/?workitem=1055500

**Comment by neilpeterson** [comment]
Here is a demo which seems to confirm @bmoore-msft assumption. I might also assume that if the child resource does not have a matching apiVersion, the list may be empty.

![image](https://user-images.githubusercontent.com/7844635/74467017-29dcb580-4e4d-11ea-83df-2dc54a17ba4b.png)

![image](https://user-images.githubusercontent.com/7844635/74467095-4c6ece80-4e4d-11ea-9b0e-18d69615adc6.png)

When decoupled, the child resource returns all potential apiVersions.

![image](https://user-images.githubusercontent.com/7844635/74467209-7c1dd680-4e4d-11ea-8a0c-51a5218b6aee.png)

**Comment by neilpeterson** [comment]
Update on this one. The code updates have been completed. We will test soon and have the fix in the next release.

**Comment by StephenWeatherford** [comment]
@neilpeterson This is fixed, too, right?  Please close.

**Comment by neilpeterson** [comment]
Yep, fixed.

**Comment by StephenWeatherford** [comment]
Just FYI, we've had some issues with the Azure schema CDN and some other things that have delayed this release.  Will have it out as soon as possible, hopefully next week.

**Comment by neilpeterson** [comment]
Fix went out today with this fix, thanks.
