### ISSUE TITLE
schema validation / completion for extension resources

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#352]
Just a place holder but we will need to figure out a solution for intellisense/autocomplete for extension resources

**Comment by StephenWeatherford** [comment]
Could you elaborate?

**Comment by StephenWeatherford** [comment]
@bmoore-msft?

**Comment by bmoore-msft** [comment]
Extension resources will have a type like:

namespace/type[/subtype/subtype]/providers/namespace/type/...

Where the shape of the resource will be determined by whatever is after /providers/ -- and it can be anything before /providers/ and anything can be after it.

I think it might be as simple as just stripping off the "*/providers/" and using that.

**Comment by neilpeterson** [comment]
@bmoore-msft can you provide an example?

I am most familiar with the vm extension resource, which appears to work well with schema validation / completions.

Thanks

**Comment by bmoore-msft** [comment]
vm extensions are a child resource - extension resources are different... you can spot them because you'll see 2 distinct providers in the resourceID.  In a template, it means you'll see it in the type property, e.g.

https://github.com/Azure/azure-quickstart-templates/blob/master/101-redis-cache/azuredeploy.json#L88

**Comment by neilpeterson** [comment]
Perfect thanks. 

Do extension resource have a swagger generated schema? Using the provided sample, I am not finding a schema for _diagnosticsettings_ in either the _2017-05-01-preview_, _2015-08-01_ and I am not finding reference to _diagnosticsettings_ in the [Microsoft.Cache/Redis@2015-08-01](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2015-08-01/Microsoft.Cache.json).

**Comment by bmoore-msft** [comment]
no, because it's an extension - any RP could support any extension resource.  They don't all, so we could probably spec it somehow but I don't know that swagger accounts for it.

That's why I was thinking above, the schema probably just needs to kick in on the segments after /providers/ - from there it will be the schema from that RP we need to validate against.

**Comment by neilpeterson** [comment]
Ok, this is making more sense. It appears that for the following example resource we could use the `Microsoft.Insights/diagnosticsettings@2017-05-01-preview` schema?

```
        {
          "apiVersion": "2017-05-01-preview",
          "type": "Microsoft.Cache/redis/providers/diagnosticsettings",
          "name": "[concat(parameters('redisCacheName'), '/Microsoft.Insights/', parameters('redisCacheName'))]",
          "location": "[resourceGroup().location]",
          "dependsOn": [
            "[concat('Microsoft.Cache/Redis/', parameters('redisCacheName'))]"
          ],
          "properties": {
            "storageAccountId": "[parameters('existingDiagnosticsStorageAccountId')]",
            "metrics": [
              {
                "timeGrain": "AllMetrics",
                "enabled": "[parameters('diagnosticsEnabled')]",
                "retentionPolicy": {
                  "days": 90,
                  "enabled": "[parameters('diagnosticsEnabled')]"
                }
              }
            ]
          }
        }
```

I see that the namespace `Microsoft.Insights` is specified in the resource name. Is it a requirement for the namespace of the resource extension is specified in the name?

I've found [this doc](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2017-05-01-preview/diagnosticsettings) that lists all extension resources. Do we have any others that cover usage, things like naming, examples etc.?

Thanks

**Comment by bmoore-msft** [comment]
Yes, you have to pair the name and type segments as you would when building a resourceId...  so if you see "providers" in the type, then need to pull the matching segment from the name.

I don't know of a doc that lists all of these, it's generic construct in ARM.  There are only certain resources that it works for (roleAssignments, diags are ones I know off the top) but I think from a tooling perspective we probably don't care about that...  That does mean someone could author something that doesn't work and tooling wouldn't be able to tell them it won't work, but it's an obscure enough pattern that it's unlikely to happen  accidentally.

**Comment by neilpeterson** [comment]
@bmoore-msft this one is quite old and we have not had any customer engagement on it. I am going to label it with _needs upvote_ and close it for now. We will re-engage when priority aligns and / or we find ourselves with extra time / engineering resources.

Thanks
