### ISSUE TITLE
Revisit apiVersion validation

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurearmtools#353]
`apiVersion` on line 246 in [variables-object-use-determination.json.zip](https://github.com/microsoft/vscode-azurearmtools/files/3774034/variables-object-use-determination.json.zip) produces a warning

**Comment by neilpeterson** [comment]
@wwlorey we have a few dupes on this issue. I'm going to close this one and will track the issue here:

https://github.com/microsoft/vscode-azurearmtools/issues/485

Thanks
