### ISSUE TITLE
File explorer icons change with file focus

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurearmtools#354]
![icons](https://user-images.githubusercontent.com/22795803/67609313-ebf23f00-f740-11e9-953c-90f987697c74.gif)

**Comment by neilpeterson** [comment]
Thanks for taking the time to enter this issue. I do not think that we are going to be able to prioritize this one for the foreseeable future.

I'm going to close for now but if we receive enough interest / feedback we will certainly revisit.
