### ISSUE TITLE
opening bracket does not trigger expression handling

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#357]
If you edit a property to turn it into an expression by placing an opening bracket at the start of the string, it is still treated as a plain string (i.e. non-expression) and not intellisense, autocomplete, colorization is applied.  You have to put in an ending bracket first.

Since ARM will treat the opening bracket as an expression (and give an error on the missing bracket) we should either 
1) add the ending bracket at the end of the string (I think this is preferred)
2) treat it as an expression and flag the missing closing bracket as a problem

**Comment by jimmylewis** [comment]
1. Completely agree, this is the preferable approach.
2. Not necessarily.  According to [the documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/template-expressions#escape-characters) it's a valid non-expression token to start with `[` and end with anything not `]`

**Comment by StephenWeatherford** [comment]
Correct, we don't want to do #2.  A real-life example we hit was this:
```
"value": "[ChefInSpec]InstalledApplicationLinuxResource1;AttributesYmlContent"
```

**Comment by bmoore-msft** [comment]
I'm good with option 1

**Comment by StephenWeatherford** [comment]
We already have the behavior for #1 described above.

**Comment by bmoore-msft** [comment]
not in the latest drop I have... (private you gave me).  When I go to a string property value and at the beginning of the string I add the opening bracket [ , no closing bracket is added to the end of the string...  we do, add an error/red squiggly saying we don't recognize the function (of it's not recognized) but whe something is recognized, we don't enable colorization until you manually add the closing ]
