### ISSUE TITLE
variable autocomplete does not show variables without quotes

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#361]
When autocompleting a variable, the function name will autocomplete with:

variables()

and the cursor is between the parens...  If you start typing, the list of variables does not appear, but a generic list.  You have to type a single quote before you get the variable list...  Seems like it would make more sense to show the variable list without requiring the single quote? That will be the common case, generic list is probably never helpful here.

**Comment by StephenWeatherford** [comment]
Shipped yesterday
