### ISSUE TITLE
VS code incorrectly matching "resourceGroup" parameter

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/vscode-azurearmtools#37]
For some reason VScode complaints about parameter name

![image](https://user-images.githubusercontent.com/13176884/37107296-9163664a-21f9-11e8-8aa2-7f50da16ddfc.png)

**Comment by StephenWeatherford** [comment]
@artisticcheese Does this still repro?  I haven't been able to find/create a deployment template that has this issue.  It's possible the schema has been corrected in the cloud.

I fixed reference so it can take three arguments.

Please let me know if you still see this issue, thanks.  See attached for (non-functional) template that was the closest I could come up with.
[101-vm-with-data-management-gateway.zip](https://github.com/Microsoft/vscode-azurearmtools/files/1909808/101-vm-with-data-management-gateway.zip)

**Comment by artisticcheese** [comment]
Yes, it still happens example template below which shows this 

```

**Comment by StephenWeatherford** [comment]
@artisticcheese Thanks!  This is a problem in the Azure schemas.  I've reported it [here](https://github.com/Azure/azure-resource-manager-schemas/issues/443).

**Comment by StephenWeatherford** [comment]
There's nothing I can do in the extension to fix this - this is handled by the built-in language service and the schemas.  We are considering work outside the extension to improve this experience, but there's nothing I can do in the extension.
