### ISSUE TITLE
[Suggestion]Navigate to an appropriate link then list the prompting dialog again

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#373]
**OS**: All
**Build Version**: [20191101.29](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11981)
**Regression:** Not a Regression

**Repro Steps:**
1. Open a template file with below schema:
"$schema": "https://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#"
2. Pop up a prompting dialog like below:
![image](https://user-images.githubusercontent.com/34729092/68112114-9b8e9480-ff2b-11e9-9263-9ca0de0fe59c.png)
3. Click "Learn more".

**Actual:**
This prompting dialog pops up again , then navigate to the https://github.com/microsoft/vscode-azurearmtools/wiki.

**Suggestion:**
Navigate to an appropriate link then list the prompting dialog again.

**More Info:**
There is no any message for now of https://github.com/microsoft/vscode-azurearmtools/wiki.

**Comment by StephenWeatherford** [comment]
@v-dantch I'm confused...  I think there are two issues:
1) The link we take you to doesn't currently have any info.  That's a known issue, but thanks for being thorough and point it out.
2) I think you're saying that after we take you to the link, the dialog does not come up again, is that correct?  I don't think that's the case - the dialog does come up again.  Have you checked that it has not been hidden by vscode (it does that after a wait) and moved to the notification area?
![image](https://user-images.githubusercontent.com/6913354/68166477-53fe0d80-ff17-11e9-8db5-f2b02d0fda63.png)

Thanks.

**Comment by v-dantch** [comment]
Hi Stephen, thanks for your quick response. 
About the second issue, Does it make sense to take the users to the link firstly , then the dialog comes up again and list here when back to VS Code. 
It is a bit weird that the dialog comes up again firstly after clicking "Learn more", then do this action.

**Comment by StephenWeatherford** [comment]
Sorry, won't fix.
