### ISSUE TITLE
An error occurred starting the language server.

### ISSUE THREAD

**Issue by nidhijwt** [microsoft/vscode-azurearmtools#377]
Repro steps:

1.
2.

Action: startArmLanguageClient
Error type: Error
Error Message: ARM Template Language Server: An error occurred starting the language server.

spawn EPERM

Version: 0.8.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1:502716extension.bundle.js:1:502716
a extension.bundle.js:1:500428
```

</details>

**Comment by StephenWeatherford** [comment]
@nidhijwt Does this happen every time, or was it only once?  If it's still happening, can you check if there is additional info in the output pane (Azure Resource Manager Tools and Azure Resource Manager Template dropdowns)?  Thx.
