### ISSUE TITLE
Error loading schema: https://schema.management.azure.com

### ISSUE THREAD

**Issue by Anthony-Breneliere** [microsoft/vscode-azurearmtools#388]
Hello,

I just installed the extension on the new 1.4 version of Visual Studio code, and those following errors are displayed to the output:

> [Info  - 02:55:34] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams
> [Error - 02:55:36] Error loading schema: https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json
> [Error - 02:55:36] Error loading schema: https://schema.management.azure.com/schemas/2019-08-01/tenantDeploymentTemplate.json

Schemas urls can be loaded from a browser.

Is there an authorization do disable in order for this extension to work ?

**Comment by StephenWeatherford** [comment]
@Anthony-Breneliere Whenever we've seen this, it's just been sporadic failures.  They're supposed to be working on improving the reliability of the schema downloads.  Can you reload vscode and try again?  It might be necessary to clear the cache manually (we have an issue to handle this better) by deleting the following folder:

Win: %LocalAppData%\Microsoft\ARMLanguageServer
Mac/Linux: I believe it was ~/.local/shared/Microsoft/ARMLanguageServer

Please let us know if that works, thanks!
