### ISSUE TITLE
Handle ARM parameters.json files.

### ISSUE THREAD

**Issue by MikeyMJCO** [microsoft/vscode-azurearmtools#394]
It'd be great if the extension could handle linting/checking/schema updating for the deploymentParameters file/schemas. 

Ideally this would link to the deployment json file to lint in concert with the deployment itself. 

e.g:

I have `azuredeploy.json` and `azuredeploy.parameters.json` when creating `azuredeploy.parameters.json` it would be great to lint/check this in the context of `azuredeploy.json` i.e. "The parameter adminUsername exists in the parameters file but is not used in the deployment file".

I appreciate that this may be very complex and there would need to be an understanding of how to relate a deployment file to a template. [This repository shows an example of our structure.](/MJCO/civicrm-buildkit-azuredeploy)

**Comment by StephenWeatherford** [comment]
Wow, you have excellent timing!  We were just discussing the possibility of linking to the params file for additional validation in the deployment file (similar but not quite what you're asking).  I was about to ask what your repo looks like, and I see you've already included it.  Thanks!

Do you frequently have multiple params files for a template file?  Are they usually in the same place?  Thx.

**Comment by MikeyMJCO** [comment]
Hi Stephen,

We don't often have more than one params file for a template file at the same time - we'll have one params file per deployment.

Pleased to say the previous issue with the catastrapostrophe has been resolved - built a local copy of 0.8.3 alpha to test!

If I can provide any more information to help with this let me know!

**Comment by StephenWeatherford** [comment]
> Pleased to say the previous issue with the catastrapostrophe has been resolved - built a local copy of 0.8.3 alpha to test!

Great, appreciate that!

**Comment by ajklotz** [comment]
I would like to see this working. I am in the process of building an ARM template for function apps that will be deployed to several environments (CI, DEV, QA, PROD) and I'll be creating a *.parameters-environment.json for each environment. 

The parameter.json and template.json exist in the same directory (for now). When I reference parameters from the parameter.json file, VS Code highlights the parameter stating that it is an undefined parameter reference, because it doesn't know about my parameters.json file for the template.

**Comment by StephenWeatherford** [comment]
> When I reference parameters from the parameter.json file, VS Code highlights the parameter stating that it is an undefined parameter reference, because it doesn't know about my parameters.json file for the template.

Am I misunderstanding something?  The parameter still has to be defined in the deployment file, so showing an error for undefined parameter is correct no matter whether a params file is specified or not.

**Comment by ajklotz** [comment]
> > When I reference parameters from the parameter.json file, VS Code highlights the parameter stating that it is an undefined parameter reference, because it doesn't know about my parameters.json file for the template.
> 
> Am I misunderstanding something? The parameter still has to be defined in the deployment file, so showing an error for undefined parameter is correct no matter whether a params file is specified or not.

Thanks for pointing that out. You're right, you _are_ supposed to define those parameters in the deployment file. I read the [documentation ](https://github.com/Azure/azure-cli/issues/11600) again and it does say that.

> The first detail to notice is the name of each parameter. The values in your parameter file must match the names.

**Comment by StephenWeatherford** [comment]
> I thought that the parameters file would be magically imported when you run Azure CLI or define the VSTS task to include the parameter file.

It's like defining parameters for a function and then calling a function with particular values for those parameters.  We are working on the ability to specify the params file and validate based on those together.  I would love to eventually add some help for, say, automatically creating a params file from the template file and similar things.  Let me know if you have additional ideas.

Note that there are snippets that can make this a little easier: arm-param (inside the template file) and arm-param-value (inside the params file).  Note also that if you have defaultValue set in the template file, you're not required to fill it in in the params file.

**Comment by StephenWeatherford** [comment]
Currently working on first part: Associating a params file with the template being edited.

**Comment by StephenWeatherford** [comment]
The first step will be shipping with the next release soon.  We'll be adding more features as time goes by...

**Comment by StephenWeatherford** [comment]
Just FYI, we've had some issues with the Azure schema CDN and some other things that have delayed this release.  Will have it out as soon as possible, hopefully next week.

**Comment by neilpeterson** [comment]
Fix went out today with this functionality, thanks.

**Comment by MikeyMJCO** [comment]
Thanks @neilpeterson and @StephenWeatherford - glad this was able to be implemented - look forward to testing this soon!

**Comment by StephenWeatherford** [comment]
We will be adding intellisense support in 0.10.9
