### ISSUE TITLE
Some functions to consider adding metadata for (from telemetry)

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#395]
![image](https://user-images.githubusercontent.com/6913354/68894470-35003800-06dc-11ea-86ff-51389c7624b5.png)

listAuthKeys
listQueryKeys
ListSyncFunctionTriggerStatus

Less than 10 users:
listClusterAdminCredential
listCredential
resource   (?)
listChannelWithKeys

**Comment by alex-frankel** [comment]
This is a great piece of telemetry. I definitely think it's worth adding this to metadata.

**Comment by bmoore-msft** [comment]
See: https://github.com/microsoft/vscode-azurearmtools/pull/408

**Comment by StephenWeatherford** [comment]
Fixed by #408
