### ISSUE TITLE
Getting tired of continuously updating

### ISSUE THREAD

**Issue by gherik** [microsoft/vscode-azurearmtools#399]
Almost every time I start Code (yes I don't use it that often) I am confronted with updates, also the extension I have installed. now I updated my OS an PwSH, TerraForm etc don't work anymore.
Using the package manager Brew is not easy to install all that voodoo on the comandline, why don't you just include it in the AppStore. 
This will make live easy!
I am willing to pay for it if it comes from the AppStore, as it takes to much time to make everything work again. I am tired of this!

Repro steps:

1.
2.

Action: queryUpdateSchema
Error type: Error
Error Message: TextEditor#edit not possible on closed editors

Version: 0.8.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
d.edit extensionHostProcess.js:493:41
AzureRMTools.<anonymous> extension.bundle.js:127:181867
extension.bundle.js:127:174871
new WrappedPromise async-listener/es6-wrapped-promise.js:13:18
n extension.bundle.js:127:174619
AzureRMTools.replaceSchema extension.bundle.js:127:181575
AzureRMTools.<anonymous> extension.bundle.js:127:181275
o extension.bundle.js:127:174675
propagateAslWrapper async-listener/index.js:504:23
async-listener/glue.js:188:31
async-listener/index.js:541:70
async-listener/glue.js:188:31
```

</details>

**Comment by StephenWeatherford** [comment]
@gherik I've been out of town.  Sorry you're having trouble.  To be clear, I believe the following comment:
> now I updated my OS an PwSH, TerraForm etc don't work anymore.
> Using the package manager Brew is not easy to install all that voodoo on the comandline, why don't you just include it in the AppStore.
> This will make live easy!
> I am willing to pay for it if it comes from the AppStore, as it takes to much time to make everything work again. I am tired of this!

is referring to vscode itself, and not our extension, right?  I'm going to transfer that issue to github.com/microsoft/vscode.

As for the specific error mentioned here (TextEditor#edit not possible on closed editors), the issue has been fixed but not yet released.  For the moment, updating the schema will work if you don't change tabs or close the editor before clicking on yes to update the schema.  Expecting to release soon after Thanksgiving holiday.

**Comment by StephenWeatherford** [comment]
@gherik Please respond to the request for more info at https://github.com/microsoft/vscode/issues/85731
