### ISSUE TITLE
error: PowerShell not found

### ISSUE THREAD

**Issue by SirArthur30** [microsoft/vscode-azurearmtools#400]
Repro steps:

1.
2.

Action: acquireDotnet
Error type: 1
Error Message: Command failed: "C:\Users\themi\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.2\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\themi\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
'PowerShell' is not recognized as an internal or external command,
operable program or batch file.

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:299:12
ChildProcess.emit events.js:182:13
maybeClose child_process.js:962:16
Process.ChildProcess._handle.onexit child_process.js:251:5
```

</details>

**Comment by StephenWeatherford** [comment]
@SirArthur30 Sorry for slow response, I've been out of town.  I'm looking at how to make our dependence on dotnet core installation more stable, and this has been a common error.  Could you tell me what version of Windows you're using?  Am I correct in assuming that you have PowerShell disabled?

In the meantime, the easiest work-around for you will be to install dotnet core runtime manually (https://dotnet.microsoft.com/download/dotnet-core/current/runtime), and then set the `azureResourceManagerTools.languageServer.dotnetExePath` setting to point to dotnet.exe where you installed it.  Please let us know if this works for you!

Thanks,
Stephen

**Comment by StephenWeatherford** [comment]
This is now being tracked by https://github.com/dotnet/vscode-dotnet-runtime/issues/51
