### ISSUE TITLE
Schema validation diagnostic settings

### ISSUE THREAD

**Issue by drewkg** [microsoft/vscode-azurearmtools#401]
This might be a ARM schema validation issue, but in VS Code if I create a resource of type - 

"type": "Microsoft.KeyVault/vaults/providers/diagnosticSettings" or child type of 
"type": "providers/diagnosticSettings"

as per - https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings-template

Then I get a validation error of 'Value must be one off the following values'.

I can create a full arm template as a sample if it will help the investigation.

**Comment by alex-frankel** [comment]
This issue is not specific to the extension, but rather the published schemas. I believe it's the issue that was opened here: https://github.com/Azure/azure-resource-manager-schemas/issues/548

**Comment by StephenWeatherford** [comment]
Closing since this is represented in the schema repo issues.  Thanks for reporting.
