### ISSUE TITLE
Pop up 2 dialogs when renaming a resource that can't be renamed 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#407]
**OS:** Win 10 & Mac
**Build Version**: [20191205.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12885)
**Regression**: Not a Regression

**Repro Steps:**
1. Open a deployment file like variable-use.json from https://github.com/bmoore-msft/arm-template-language-samples.
2. Rename a resource that cannot be renamed.

**Expect:**
Pop up one dialog telling the users that the resource cannot be renamed and only parameters, variables, user namespace and user functions can be renamed.

**Actual:**
Pop up 2 dialogs like below:
 ![image](https://user-images.githubusercontent.com/34729092/70303971-d0984a80-183b-11ea-8dce-2e3581def566.png)

**Comment by StephenWeatherford** [comment]
Fixed by 527ac16f02ab3d8680c3a7f181b67a26c9084e76
