### ISSUE TITLE
Any *.parameters.json files with a closed "parameters" section does not present an error

### ISSUE THREAD

**Issue by rokeno** [microsoft/vscode-azurearmtools#409]
Ok, 
so lemme elaborate on this error. Spent two hours on it just to randomly find it.

Our API Management service templates are using nested templates (somewhat irrelevant to our issue).
The .parameters.json file was looking like this:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
  },
    "sp-apim": {
      "value": {
        "name": "#{env-apim-name}#",
        "resourceGroupName": "#{env-apim-rg-name}#",
        "loggerName": "#{env-ai-loggers-name}#"
      }
    }
}
```
The extension says there is no issue here because the schema section is closed, the parameters section is closed and so is the parameter itself.
But this should not happen because the parameter in this case is NOT a parameter. I don't know what it is, actually.
I've moved the '}," at the end of the file now having 4 squiggly brackets instead of 3, and the code should look like this:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "sp-apim": {
      "value": {
        "name": "#{env-apim-name}#",
        "resourceGroupName": "#{env-apim-rg-name}#",
        "loggerName": "#{env-ai-loggers-name}#"
      }
    }
}
}
```
Now my "sp-apim" parameter is considered a paramter and VSTS can now solve my tokens.
The error i had in deployment was: 
```
Validation returned the following errors:
: Deployment template validation failed: 'The template resource '/' for type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Common.Entities.TemplateGenericProperty`1[System.String]' at line '33' and column '52' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.

```
Actually, the deployment was not validating the section 
```
(line 33)      "type": "Microsoft.ApiManagement/service/apis",
(line 34)      "name": "[concat(parameters('sp-apim-name'), '/', parameters('sp-name'))]",

```
**(ignore (line 33) and (line 34), added by me to show you the line number)**
...because there were not values coming from the *.parameters.json file.

How can this be approached for the extension to see that the parameters section has no parameters the the .... objects below are orphan somehow?

Thanks.

**Comment by StephenWeatherford** [comment]
This is an issue with the schema, so I've moved it to https://github.com/Azure/azure-resource-manager-schemas/issues/821.  Thanks for reporting!

**Comment by StephenWeatherford** [comment]
The related bug was marked fix (to be deployed in about a week).
