### ISSUE TITLE
help

### ISSUE THREAD

**Issue by SirArthur30** [microsoft/vscode-azurearmtools#414]
Repro steps:

1.
2.

Action: acquireDotnet
Error type: 1
Error Message: Command failed: "c:\Users\themi\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.2\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\themi\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
'PowerShell' is not recognized as an internal or external command,
operable program or batch file.

Version: 0.8.2
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:303:12
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by StephenWeatherford** [comment]
@SirArthur30 Thanks for reporting. Right now we rely on PowerShell to install dotnet (needed for the language service), and are discussing what to do in this scenario.  So I take it  you do not have PowerShell installed?  This is a personal choice, or maybe company policy?

In the meantime, you can work around this by manually installing ASP.NET Core Runtime 2.2.8 from https://dotnet.microsoft.com/download/dotnet-core/2.2, then setting the vscode setting azureResourceManagerTools.languageServer.dotnetExePath to point to the path to dotnet.exe after it's installed.

Please let us know if this works for you.
