### ISSUE TITLE
"Functions" entry in treeview is missing icons

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#421]
![image](https://user-images.githubusercontent.com/6913354/70840045-b4108b00-1dc4-11ea-8ee8-f5d0effb6bba.png)

**Comment by nilshedstrom** [comment]
This issue is solved in pr #417 
In your screenshot I notice that there is no label for the function (instead of {...}).
Maybe get the label from the namespace for functions?

**Comment by StephenWeatherford** [comment]
Partially fixed by #417

**Comment by nilshedstrom** [comment]
Which part is not fixed?

**Comment by StephenWeatherford** [comment]
![image](https://user-images.githubusercontent.com/6913354/70939855-fbce2700-1ffd-11ea-8537-bbe094b2548d.png)

- [ ] Need icons for namespace, individual functions, parameters, outputs, etc.
- [ ] Need to better populate the tree with understanding of functions (for instance understanding that the {...} object is a namespace and labeling it properly, as Nils points out above)

**Comment by nilshedstrom** [comment]
I tried to fix this issue in #427

**Comment by StephenWeatherford** [comment]
Fixed by #427

**Comment by neilpeterson** [comment]
Release went out today with this fix - thanks.
