### ISSUE TITLE
Error downloading dotnet - VERSION_ID: unbound variable

### ISSUE THREAD

**Issue by cdunford** [microsoft/vscode-azurearmtools#422]
Repro steps:

1. Install extension
2. File > New File
3. Change language mode to ARM Template

Action: acquireDotnet
Error type: string
Error Message: /home/cdunford/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.8.2/assets/install scripts/dotnet-install.sh: line 147: VERSION_ID: unbound variable
/home/cdunford/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.8.2/assets/install scripts/dotnet-install.sh: line 205: VERSION_ID: unbound variable

Version: 0.8.2
OS: linux
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

**Comment by StephenWeatherford** [comment]
See https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition#version_id-unbound-variable

**Comment by neilpeterson** [comment]
@cdunford are you still having issues here. Did the workaround that Stephen provided work for you?

Thanks

**Comment by cdunford** [comment]
@neilpeterson - yes the workaround work; sorry for taking a while to respond.

**Comment by neilpeterson** [comment]
@cdunford hey no worries at all, thanks for getting back. We are tracking the uber-issue at the below link.

https://github.com/dotnet/vscode-dotnetcore/issues/11

I will close this one now.

Thanks again.

**Comment by StephenWeatherford** [comment]
FYI, the fix for this bug has just been released in v0.8.4 (by picking up new dotnet installation scripts). I haven't been able to actually tested this for myself, though.
