### ISSUE TITLE
Reload cached schemas does not give completion notification on Mac/Linux, nor says the users needs to reload

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#423]
**OS:** All
**Build Version:** [20191215.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13140&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Disable network connection --> Open a deployment file.
2. Check the Output window --> Display an error "Error loading schema : http://json-schema.org/draft-04/schema".
3. F1 --> Type and select "Azure Resource Manager Tools: Reload Cached Schemas".
4. Check the "Azure Resource Manager Tools" window --> Display "Reloading schemas".

**Actual:**
Keep displaying "Reloading schemas" more than 5 mins.
![image](https://user-images.githubusercontent.com/34729092/70901855-89c60400-2036-11ea-8789-7d21b4ddbe49.png)

**Suggestion:**
Add a notification when completed to reload cached schemas.

**Comment by StephenWeatherford** [comment]
@alexgav Please https://devdiv.visualstudio.com/DevDiv/_boards/board/t/ARM%20Template%20Authoring/Stories/?workitem=1052916.  I'm not sure that clearing the cache is working on Mac.  On Windows I see the notification that it's completed, but not on Mac.  Linux?

**Comment by StephenWeatherford** [comment]
I verified that the cache *is* getting cleared on Mac, but the user never sees the notification saying it completed.

**Comment by neilpeterson** [comment]
@v-dantch Both @StephenWeatherford and myself looked at this today and it no longer repros.

![image](https://user-images.githubusercontent.com/7844635/74388778-23006500-4db1-11ea-82f9-505b64be256a.png)

I'm going to close the issue, thanks.
