### ISSUE TITLE
The error and warning about schema also exist in 'PROBLEMS' after executing the command "Reload Cached Schemas"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#424]
**OS:** Win 10 & Ubuntu 18.04
**Build Version:** [20191215.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13140&view=results)

**Repro Steps:**
1. Disconnect the network for machine.
2. Launch VS Code and open a .json file.
3. Check the error and warning in "PROBLEMS".
4. Execute the command "Reload Cached Schemas" and then check the error in "PROBLEMS" again.

**Expect:**
There is no error and warning about schema in "PROBLEMS" after executing the command "Reload Cached Schemas".
![image](https://user-images.githubusercontent.com/45614674/70902174-330cfa00-2037-11ea-9476-31ad802bea09.png)

**Actual:**
The error and warning about schema also exist in "PROBLEMS".

**Comment by StephenWeatherford** [comment]
@v-ruizh Can you attach the template file?

**Comment by v-ruizh** [comment]
@StephenWeatherford Please get the template file from \\trinlab2\BAQAFiles\CloudTools\VS Code Extension\Resources\Test templates for ARM Tools\new-vm.json.

**Comment by StephenWeatherford** [comment]
You're using the tenant $schema, please change the schema back to "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#" for these resources to be correct.

After doing that, I now get this:
```
Value must be one of the following values: "2016-05-15", "2018-09-15"
OneOf (Require 1 match, following 2 not matched):
    Value must be one of the following values: "2016-12-01"
    string
Value must be one of the following values: "2016-12-01"
Exactly 1 match required, but found more than 1
```

The apiVersion complaint seems to be valid, but the "Exactly 1 match required" errors indicate a problem with the schema (using oneOf expression or object, when it should be anyOf).

**Comment by StephenWeatherford** [comment]
Here's a condensed version of the json file with the oneOf problems: 

[424.zip](https://github.com/microsoft/vscode-azurearmtools/files/4078780/424.zip)

**Comment by v-ruizh** [comment]
This issue also reproduces on Windows/Mac/Linux with the new extension build [20200206.10](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14457&view=results) installed. Need to restart VS Code after executing the command "Reload Cached Schemas", but restart can't fix this issue.
![image](https://user-images.githubusercontent.com/45614674/73919665-ee972f80-48fe-11ea-9a2a-332041c05633.png)

**Comment by StephenWeatherford** [comment]
@neilpeterson I believe the OneOf error is a schema problem.

**Comment by neilpeterson** [comment]
thanks @StephenWeatherford, on it.

**Comment by neilpeterson** [comment]
From what I can tell, the schema looks fine. I've spoken with @alexgav today, the one of tools work is still in progress. Once complete, i will revisit this and update.

**Comment by neilpeterson** [comment]
I have tested the tempalte provided by @StephenWeatherford with the 0.9.0 release. The one of issue have been resolved.
