### ISSUE TITLE
Display a loading schema error after running "Reload Cached Schemas" without network connection

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#425]
**OS:** All
**Build Version:** [20191215.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13140&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Disable network connection --> Open a deployment file.
2. Pop up a prompt asking if you want to use the latest schema like below.
![image](https://user-images.githubusercontent.com/34729092/70903498-fb538180-2039-11ea-887e-03030f428a75.png)
3. There displays many loading schema errors in "Azure Resource Manager Template" window like below.
![image](https://user-images.githubusercontent.com/34729092/70903600-2b9b2000-203a-11ea-8aa2-33e8fac6d2f6.png)
4. F1 --> Type and select "Azure Resource Manager Tools: Reload Cached Schemas".
5. Click "Use latest" on the prompt asking dialog.

**Expect:**
The schema should be replaced with the latest one.

**Actual:**
Display an error in "Azure Resource Managers Template" window.
![image](https://user-images.githubusercontent.com/34729092/70903767-8df42080-203a-11ea-80a9-7da192cad851.png)

**Comment by StephenWeatherford** [comment]
For me this happens on Mac, not Windows.

**Comment by v-dantch** [comment]
Yes, the schema can be replaced with the latest one on Windows. But there is still an error when opening a deployment file after running "Reload Cached Schemas"
![image](https://user-images.githubusercontent.com/34729092/70961230-25e61e80-20bc-11ea-9814-5170df6fd103.png)

**Comment by StephenWeatherford** [comment]
Could you try again with the most recent version?  Thanks!

**Comment by v-ruizh** [comment]
This issue does not reproduce on Mac with ARM extension [20200216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14857&view=results) installed.
![image](https://user-images.githubusercontent.com/45614674/74643726-29774e00-51b0-11ea-8d40-d4e6bd64d481.png)

**Comment by neilpeterson** [comment]
Thanks @v-ruizh I've also verified on my Mac. I'm going to close this issue now.
