### ISSUE TITLE
Not sure how to fix, tried installing .NET core runtime manually

### ISSUE THREAD

**Issue by farisjalal** [microsoft/vscode-azurearmtools#433]
Action: acquireDotnet
Error type: 1
Error Message: >>>> This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips.
Command failed: "c:\Users\P's PC\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\P''s PC\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
 

Version: 0.8.3
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:303:12
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

<details>
<summary>dotnetAcquireLog</summary>

```
Status bar: $(cloud-download) Downloading .NET Core tooling...
Status bar: $(alert) Error acquiring .NET Core tooling!

[dotnet 2.2.5]: Found an incompletely-installed version of dotnet 2.2.5... Uninstalling.
[dotnet 2.2.5]: Uninstalling dotnet version 2.2.5
[dotnet 2.2.5]: Removing folder c:\Users\P's PC\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5
[dotnet 2.2.5]: Finished removing folder c:\Users\P's PC\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5
[dotnet 2.2.5]: Finished uninstalling dotnet version 2.2.5
Using this command to install .NET Core version 2.2.5:
"c:\Users\P's PC\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\P''s PC\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
Downloading .NET Core tooling version(s) 2.2.5.....[dotnet 2.2.5]: STDERR: The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
 

 Error!
Failed to download .NET Core tooling 2.2.5:
Exit code: 1
Message: Command failed: "c:\Users\P's PC\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\P''s PC\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
 



```

</details>
window.

**Comment by StephenWeatherford** [comment]
Hey, so when you tried installing it manually, what happened?  Did it succeed?  Did you then tell the extension where to find dotnet.exe?  Thx.

**Comment by neilpeterson** [comment]
@farisjalal any update on the requested information? Are you still having an issue here?

Thanks

**Comment by StephenWeatherford** [comment]
@farisjalal We're still interested in any information that you may have.  Thanks!
