### ISSUE TITLE
error loading schemas

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/vscode-azurearmtools#438]
I'm trying to get the latest schemas and get this error after flushing cached schemas & restarting.

```
[Error - 2:41:14 PM] Unexpected: no 'allOf' member found in '{"type":"object","properties":{"type":{"enum":["Microsoft.Resources/deployments"]},"apiVersion":{"enum":["2014-04-01-preview"]},"name":{"type":"string","description":"Name of the deployment"},"dependsOn":{"type":"array","items":{"type":"string"},"description":"Collection of resources this deployment depends on"},"properties":{"allOf":[{"type":"object","properties":{"mode":{"enum":["Incremental"],"description":"Deployment mode"}},"required":["mode"]},{"anyOf":[{"type":"object","properties":{"templateLink":{"$ref":"#/definitions/templateLink"}}},{"type":"object","properties":{"template":{"type":"object"}}}]},{"anyOf":[{"type":"object","properties":{"parametersLink":{"$ref":"#/definitions/parametersLink"}}},{"type":"object","properties":{"parameters":{"type":"object","additionalProperties":{"$ref":"#/definitions/parameter"}}}}]}]}},"required":["type","apiVersion","name","properties"]}'
```

At this point, my instance of the ARM template manager indicates that multiple schema versions I'm using are not valid, which makes validation fail on templates that work in production.

Note, I'm using v0.8.3 of the plugin

**Comment by StephenWeatherford** [comment]
@alexgav What's the status of this bug?  https://dev.azure.com/devdiv/DevDiv/_boards/board/t/ARM%20Template%20Authoring/Stories

**Comment by StephenWeatherford** [comment]
@bmc-msft This has been fixed in the language server, should ship with our next version.  Thanks for reporting!

**Comment by StephenWeatherford** [comment]
FYI, the fix for this bug has just been released in v0.8.4

**Comment by bmc-msft** [comment]
I can confirm I'm no longer experiencing this issue.  Thanks!

**Comment by StephenWeatherford** [comment]
Good to hear, thanks for letting us know.
