### ISSUE TITLE
Microsoft.Resources/Deployment API Versions & child resources

### ISSUE THREAD

**Issue by drewkg** [microsoft/vscode-azurearmtools#439]
This might be a ARM schema issue, but in VS Code ARM Tools the validation for a ARM Deployment states

Value must be one of the following values: "2016-09-01", "2017-05-10", "2015-01-01", "2016-02-01"

Valid values here are now  "2019-10-01", "2019-08-01", "2019-07-01", "2019-05-10", "2019-05-01", "2019-03-01", "2018-05-01", "2018-02-01", "2017-05-10", "2016-09-01", "2016-07-01", "2016-02-01"

As per https://docs.microsoft.com/en-us/azure/templates/microsoft.resources/allversions

**Comment by JHStarner** [comment]
Seconding this issue.

It seems that child resources are forced to adopt the same API version as the Parent in the validation.

Are you guys able to update the validation so we can use child resources that may have a different or higher API version?

For example:
Microsoft.SQL/servers -> Highest API: 2015-05-01-Preview
Microsoft.SQL/servers/databases -> Highest API: 2019-06-01-Preview

If I nest the Database as a child resource of the server for deployment, I get a warning stating the following:

> OneOf (Require 1 match, following 8 not matched):
> Value must be one of the following values: \"failoverGroups\"
> Value must be one of the following values: \"2015-05-01-preview\"
> Value must be one of the following values: \"keys\"
> Value must be one of the following values: \"syncAgents\"
> Value must be one of the following values: \"virtualNetworkRules\"
> Value must be one of the following values: \"firewallRules\"
> Value must be one of the following values: \"current\"
> Value must be one of the following values: \"encryptionProtector\"

The warning will go away if I change the API level of the Database to the same as the Server level (2015-05-01-Preview), but some child resources do not exist at the same API level date.

None of this is breaking deployment, but it sure is a nuisance for trying to write a good clean template, when I have as many warnings as I have child resources.

Is this a part of the reduction in False Positives you guys are already working on?

**Comment by StephenWeatherford** [comment]
I can get to this quicker if you post a short sample deployment file or at least set of resources.  Thanks!

**Comment by JHStarner** [comment]
Fast example is here:
https://github.com/Azure/azure-quickstart-templates/blob/master/201-sql-auditing-server-policy-to-oms/azuredeploy.json

You'll notice when you put this Template into VSCode, you will get Warnings for the children Resources under the Microsoft.SQL/server. The warning will go away when you update their API to the same as the parent, but this opens new issues.

And this is not specific to Microsoft.SQL, it is with any children/nested resources.

(I copied the file locally, calling it "LogAnalyticsText.json". This is the output in the Problem Tab)
![image](https://user-images.githubusercontent.com/311828/72370820-09e09780-36d1-11ea-9efb-9de2447b5e10.png)

So it is two-fold. It looks like the apiVersion of the Parent is not seeing all capable child type resources. And Child resources are FORCED to be same apiVersion as Parent (even if said resource doesn't have an apiVersion with same date/time/number as parent.)

**Comment by StephenWeatherford** [comment]
Thanks!  We'll take a look.

**Comment by StephenWeatherford** [comment]
Tracked here: https://dev.azure.com/devdiv/DevDiv/_boards/board/t/ARM%20Template%20Authoring/Stories/?workitem=1051770

**Comment by JHStarner** [comment]
It looks like a board not viewable publicly.

**Comment by StephenWeatherford** [comment]
Yep, sorry, should have said.  We'll update here with progress.

**Comment by JHStarner** [comment]
Thanks! Looking forward to it.

**Comment by StephenWeatherford** [comment]
Fix should be in the next release.

**Comment by cconrado** [comment]
@StephenWeatherford when is that coming out?

**Comment by StephenWeatherford** [comment]
Probably late next week.

**Comment by StephenWeatherford** [comment]
@neilpeterson Could you verify the example from JHStarner above?  I still get errors... Thx.

**Comment by neilpeterson** [comment]
The child / parent api version mis-match issue has been fixed in the next release. With the fix, the extension will not limit child resource api versions to that of the parent. 

Example:

![image](https://user-images.githubusercontent.com/7844635/76646011-64eb0b00-6517-11ea-95bc-5118fa103a7b.png)

The oneOf / exactly one match warnings in the above example are a separate issue. We are hoping to have a fix for this in the next release but are still working on it. We can track oneOf / exactly one match in this issue which I will keep up to date with progress. 

https://github.com/microsoft/vscode-azurearmtools/issues/457

I will go ahead and close this (child / parent api match) issue.

**Comment by StephenWeatherford** [comment]
Just FYI, we've had some issues with the Azure schema CDN and some other things that have delayed this release.  Will have it out as soon as possible, hopefully next week.

**Comment by neilpeterson** [comment]
Fix went out today with this fix, thanks.
