### ISSUE TITLE
Login-AzureRMAccount - Bring to front

### ISSUE THREAD

**Issue by tsalinger** [Microsoft/vscode-azurearmtools#44]
>This issue has been moved from [Microsoft/vscode/](https://github.com/Microsoft/vscode/issues/43967)
Original author is <a href="/FlemmingRohde">
      <img class="avatar rounded-1" height="44" width="44" alt="@FlemmingRohde" src="https://avatars3.githubusercontent.com/u/35932745?s=88&amp;v=4">
    </a>@FlemmingRohde
---
### Issue Type
Bug

### Description

When trying command Login-AzureRMAccount the login prompt is hidden behind the Studio Code GUI. Please make the login prompt focus (bring to front)

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.93GB (8.76GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
azureautomation|Awe|0.6.2
xml|Dot|1.9.2
git-project-manager|fel|1.4.0
prettify-json|moh|0.0.3
azurecli|ms-|0.4.0
PowerShell|ms-|1.5.1
azurerm-vscode-tools|msa|0.4.0
vscode-manifest-yaml|Piv|0.1.3
vscode-icons|rob|7.20.0
arm-snippets|sam|1.1.0

</details>
Reproduces without extensions

---

**Comment by StephenWeatherford** [comment]
@FlemmingRohde I don't belong this belongs in this repo, either, or to https://github.com/Microsoft/vscode-azure-account.  What extension exposes the Login-AzureRMAccount command you're referring to?

**Comment by FlemmingRohde** [comment]
Hi,

It’s not an extension.

From terminal or psscript  in VSCode try to execute command Login-AzureRMAccount then below screen will be ‘hidden’ for you – it should have focus (brought to front).

[cid:image001.png@01D3C082.59270FD0]


Med venlig hilsen | Best regards

[cid:image001.png@01D2BAA5.E5C3A4A0]


Flemming Rohde
Mobile: +45 22421431
E-Mail: flr@automize.dk<mailto:flr@automize.dk>
LinkedIn: https://www.linkedin.com/in/flemming-rohde-b75bb877<https://www.linkedin.com/in/flemming-rohde-b75bb877/>

Automize | Bredgade 33, 1. sal | DK6000 Kolding | Tel  +45 71 71 53 53 | http://www.automize.dk<http://www.automize.dk/>

**Comment by StephenWeatherford** [comment]
@tsalinger This has nothing to do with this extension. See @FlemmingRohde's comment - this is referring to the PowerShell terminal in vscode. Could you please redirect to the right repo? Thx.
