### ISSUE TITLE
Make ARM viewer a dependency

### ISSUE THREAD

**Issue by SebastianSchuetze** [microsoft/vscode-azurearmtools#444]
Hi,

one of your colleagues created a pretty good VSCode extension, which allows generating a graphical preview of your template and saves it as PNG.

Maybe you could make this as a dependency on your project since this extension is very promising.

https://github.com/benc-uk/armview-vscode

And it also seems to test against all azure quickstart template, which means it must be pretty stable. What do you think?

**Comment by StephenWeatherford** [comment]
@alex-frankel @neilpeterson FYI.

@SebastianSchuetze It's a good idea, I believe it's actually been mentioned before.  Thanks.

**Comment by StephenWeatherford** [comment]
I wonder if it's possible to recommend an extension based on another extension being installed...

**Comment by SebastianSchuetze** [comment]
Yes I recommended this to @alex-frankel on twitter a few weeks ago. He thought it's a good idea, but I thought I push it here as well.

And yes it's possible: https://code.visualstudio.com/api/references/extension-manifest#extension-packs :-)

**Comment by SebastianSchuetze** [comment]
Just to add, I would love to have this tool possibly available through pipelines with a cli to auto-generate visualizer of ARM templates for documentation. That would be a perfect use case!

**Comment by neilpeterson** [comment]
Thanks all.

@SebastianSchuetze we do have a work item to consider this / figure out what makes best sense. I will update as we make progress.

**Comment by MarcusFelling** [comment]
@SebastianSchuetze Would adding ARM Viewer as a recommended extension be a good start? https://github.com/microsoft/vscode-azurearmtools/pull/1134

**Comment by SebastianSchuetze** [comment]
It is. Out if curiosity, what stops it from being a full dependency?

**Comment by MarcusFelling** [comment]
Short term updates:

- I've added ARM Viewer to the [Azure Extension Pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-azureextensionpack).
- I've added mention of the ARM Viewer to the ARM Tool's README: https://github.com/microsoft/vscode-azurearmtools/pull/1140
- If you would like to recommend the extension when working with certain repositories, you can use a [workspace recommendation](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions).

Longer term, I've started a discussion with the author of the extension to brainstorm. Will the extension support Bicep? Should a new extension be created for Bicep file visualizations? Should this be a native Bicep feature?

**Comment by MarcusFelling** [comment]
FYI @benc-uk
