### ISSUE TITLE
Updating ARM template to latest schema crashes VS Code text editor

### ISSUE THREAD

**Issue by JeeWeetje** [microsoft/vscode-azurearmtools#446]
Does this occur consistently? 
Repro steps:

1. Export a template from an existing resource on Azure
2. Open the downloaded template.json in VS Code
3. Click "Use Now" button when suggested by the extention to update the schema to the latest.

Action: queryUpdateSchema
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed

Version: 0.8.3
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.disposed workbench.desktop.main.js:53:147
e.$tryApplyEdits workbench.desktop.main.js:3435:757
g._doInvokeHandler workbench.desktop.main.js:3483:285
g._invokeHandler workbench.desktop.main.js:3482:999
g._receiveRequest workbench.desktop.main.js:3481:664
g._receiveOneMessage workbench.desktop.main.js:3480:477
file:/workbench.desktop.main.js:3478:754
c.fire workbench.desktop.main.js:114:893
v.fire workbench.desktop.main.js:379:97
t.PersistentProtocol._receiveMessage workbench.desktop.main.js:383:451
file:/workbench.desktop.main.js:380:635
c.fire workbench.desktop.main.js:114:893
g.acceptChunk workbench.desktop.main.js:376:532
file:/workbench.desktop.main.js:375:857
Socket.t workbench.desktop.main.js:386:698
Socket.emit events.js:200:13
addChunk _stream_readable.js:294:12
readableAddChunk _stream_readable.js:275:11
Socket.Readable.push _stream_readable.js:210:10
Pipe.onStreamRead stream_base_commons.js:166:17
```

</details>

**Comment by StephenWeatherford** [comment]
@JeeWeetje Thanks for entering.  I'm assuming this happens if you switch tabs or close the editor before answering yes?  (This should have already been fixed.)

**Comment by JeeWeetje** [comment]
I wasn't closing an editor or switching tabs as far I was remembering. But explicitly keeping focus on the editor does change the schema version.

I am not able to reproduce the problem at the moment. I will close the issue for now.

**Comment by StephenWeatherford** [comment]
Okay, thanks for reporting.  Let us know if you find a reproducible scenario.
