### ISSUE TITLE
Extension suggesting incorrect values for apiVersions

### ISSUE THREAD

**Issue by edburns** [microsoft/vscode-azurearmtools#447]
VS Code Version: 

```
Version: 142.0-insider (user setup) 
Commit: 5e758c10c969d668730f036abfc557d9cfb62b87 
Date: 
Electron: 7.17 
Chrome: 78.0.3904.130 
Nodejs: 128.1 
V8: 78.279.23-electron.O 
OS: Windows NT x64 100.19041 
```

Extension Id: msazurermtools.azurerm-vscode-tools
  
Extension Version: 0.8.2

Consider this ARM template extract.

```
{
	"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
...
"resources": [
    {
        "apiVersion": "2019-09-01",
        "name": "${tracking.pid}",
        "type": "Microsoft.Resources/deployments",
        "properties": {
            "mode": "Incremental",
            "template": {
                "$schema": "https://schema.management.azure.com/schemas/2019-09-01/deploymentTemplate.json#",
                "contentVersion": "1.0.0.0",
                "resources": []
            }
        }
    },
```

The extension paints apiVersion with the squiggly lines and says:

```
Value must be one of the following values: "2016-09-01", "2017-05-10", "2015-01-01", "2016-02-01"
```

That answer is wrong.  1. It's more than two years old.  2. When I ask
Azure itself, it gives me something entirely different.

```
az provider show --namespace Microsoft.Resources --query "resourceTypes[?resourceType=='deployments'].apiVersions | [0]" --out table
Result
------------------
2019-09-01
2019-05-01
2019-04-01
2019-03-01
2018-11-01
2018-09-01
2018-08-01
2018-07-01
2018-05-01
2018-02-01
2018-01-01
2017-08-01
2017-06-01
2017-05-10
2017-05-01
2017-03-01
2016-09-01
2016-07-01
2016-06-01
2016-02-01
2015-11-01
2015-01-01
2014-04-01-preview
```

**Comment by edburns** [comment]
I looked at the schema https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json .

It contains the following entries for `"type": "Microsoft.Resources/deployments",`

```
"$ref": "https://schema.management.azure.com/schemas/2016-09-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
"$ref": "https://schema.management.azure.com/schemas/2017-05-10/Microsoft.Resources.json#/resourceDefinitions/deployments"
"$ref": "https://schema.management.azure.com/schemas/2015-01-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
"$ref": "https://schema.management.azure.com/schemas/2016-02-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
"$ref": "https://schema.management.azure.com/schemas/2018-05-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
"$ref": "https://schema.management.azure.com/schemas/2019-05-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
```

However, this doesn't match with the above error message from the extension:

```
Value must be one of the following values: "2016-09-01", "2017-05-10", "2015-01-01", "2016-02-01"
```

The values in the message are a subset of what is in the schema.

Also, what is in the schema is a subset of what I get back from Azure.

**Comment by StephenWeatherford** [comment]
Can you try right-clicking in the editor -> Reload Cached Schemas and see if that if that helps?

**Comment by majguo** [comment]
I tried "right-clicking in the editor -> Reload Cached Schemas -> Restart VS code" , and get the following error messages in "OUTPUT" window:
```
[Info  - 3:55:05 PM] Finding descriptor for initialize
[Info  - 3:55:05 PM] Starting: Routing Request (0) initialize
[Info  - 3:55:05 PM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 3:55:05 PM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 3:55:05 PM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 3:55:05 PM] Finished: Routing Request (0) initialize in 75ms
[Info  - 3:55:05 PM] Finding descriptor for initialized
[Info  - 3:55:05 PM] Starting: Routing Notification initialized
[Info  - 3:55:05 PM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams
[Error - 3:55:06 PM] Unexpected: no 'allOf' member found in '{"type":"object","properties":{"type":{"enum":["Microsoft.Resources/deployments"]},"apiVersion":{"enum":["2014-04-01-preview"]},"name":{"type":"string","description":"Name of the deployment"},"dependsOn":{"type":"array","items":{"type":"string"},"description":"Collection of resources this deployment depends on"},"properties":{"allOf":[{"type":"object","properties":{"mode":{"enum":["Incremental"],"description":"Deployment mode"}},"required":["mode"]},{"anyOf":[{"type":"object","properties":{"templateLink":{"$ref":"#/definitions/templateLink"}}},{"type":"object","properties":{"template":{"type":"object"}}}]},{"anyOf":[{"type":"object","properties":{"parametersLink":{"$ref":"#/definitions/parametersLink"}}},{"type":"object","properties":{"parameters":{"type":"object","additionalProperties":{"$ref":"#/definitions/parameter"}}}}]}]}},"required":["type","apiVersion","name","properties"]}'
```

Besides, I still get the same problem listed in "PROBLEMS" window:
```
{
	"resource": "/c:/Users/jiangma/Downloads/testTemplate.json",
	"owner": "ARM Template Language Server diagnostics",
	"code": "",
	"severity": 4,
	"message": "Value must be one of the following values: \"2016-09-01\", \"2017-05-10\", \"2015-01-01\", \"2016-02-01\"",
	"source": "arm-template (schema)",
	"startLineNumber": 8,
	"startColumn": 13,
	"endLineNumber": 8,
	"endColumn": 25
}
```

**Comment by StephenWeatherford** [comment]
The oneOf error is a known issue, fixed in next version.

> I looked at the schema https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json .
> It contains the following entries for "type": "Microsoft.Resources/deployments",
> "$ref": "https://schema.management.azure.com/schemas/2016-09-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
> "$ref": "https://schema.management.azure.com/schemas/2017-05-10/Microsoft.Resources.json#/resourceDefinitions/deployments"
> "$ref": "https://schema.management.azure.com/schemas/2015-01-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
> "$ref": "https://schema.management.azure.com/schemas/2016-02-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
> "$ref": "https://schema.management.azure.com/schemas/2018-05-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
> "$ref": "https://schema.management.azure.com/schemas/2019-05-01/Microsoft.Resources.json#/resourceDefinitions/deployments"

I'm only seeing the following, along with the apiVersions they contain:
```
"$ref": "https://schema.management.azure.com/schemas/2016-09-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
                "apiVersion": {
                    "type": "string",
                    "enum": ["2016-09-01"]
                }
"$ref": "https://schema.management.azure.com/schemas/2017-05-10/Microsoft.Resources.json#/resourceDefinitions/deployments"
	            "apiVersion": {
                    "type": "string",
                    "enum": ["2017-05-10"]
                }
"$ref": "https://schema.management.azure.com/schemas/2015-01-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
                "apiVersion": {
                    "enum": ["2015-01-01"]
                }
"$ref": "https://schema.management.azure.com/schemas/2016-02-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
                "apiVersion": {
                    "type": "string",
                    "enum": ["2016-02-01"]
                }
```

Am I missing something?

**Comment by edburns** [comment]
I did the following and arrived at the same result you did.  I can't explain why I am not seeing

```
2018-05-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
2019-05-01/Microsoft.Resources.json#/resourceDefinitions/deployments"
```

as I did before.

1. Download https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json locally
2. Ran it through my jsonpretty alias `python -m json.tool`
3. Received output semantically equivalent to yours.


I do observe a questionable `last-modified` header via curl, however.

```
curl --verbose https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json
< HTTP/2 200 
< content-length: 195420
< content-type: application/json
< content-md5: oO3ZZXKphGVmg+gcHCpXkw==
< last-modified: Sat, 18 Jan 2020 02:05:14 GMT
< etag: 0x8D79BBADB77F795
< server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
< x-cache: TCP_HIT
< x-ms-request-id: 503ba1d5-c01e-00c3-2c95-cf86b3000000
< x-ms-version: 2009-09-19
< x-ms-lease-status: unlocked
< x-ms-blob-type: BlockBlob
< x-azure-ref-originshield: 04KolXgAAAADtICvqhqFdTb7LdRG2z76jU04xRURHRTA1MTMANGUxY2NkMWQtYjc3MC00YmQ4LWJhOWItNWQ3MjMzODY0YzUw
< x-azure-ref: 0fNYlXgAAAADTNchB8byhQYHYKwqRKh6zQVRBRURHRTEyMDkANGUxY2NkMWQtYjc3MC00YmQ4LWJhOWItNWQ3MjMzODY0YzUw
< date: Mon, 20 Jan 2020 16:34:03 GMT
< 
{"id":"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#","$schema":"http://json-sche
```

If this is `last-modified` header is to believed, my trust in the immutability of JSON schemas is misplaced.

**Comment by StephenWeatherford** [comment]
They're definitely not immutable - not only are new api versions and RPs being added, but improvements/fixes are being made in the current versions.  It sounds like they published some new api versions then had to back them out maybe?  I'm going to treat this as a pure schema issue.  Thanks!

**Comment by StephenWeatherford** [comment]
@neilpeterson Here's a new schema bug for you...  Thx.

**Comment by neilpeterson** [comment]
Thanks. I am looking into this. I believe I will end up opening up an issue in the [schemas repo](https://github.com/Azure/azure-resource-manager-schemas), but am also seeing discrepancies with [docs](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Resources/2019-10-01/deployments), so need to dig a bit.

**Comment by neilpeterson** [comment]
@edburns, confirmed that a resource schema has not been generated for  `2019-09-01` of the deployment resources. I've found some other wonkiness as well and have opened up an issue with that project.

https://github.com/Azure/azure-resource-manager-schemas/issues/844

I am looking into schema generation / alignment more broadly and hope that we can get this all sorted in the future.

I am going to close this issue and will track in the azure-resource-manager-schemas repository.

Thanks
