### ISSUE TITLE
Exactly 1 match required, but found more than 1 | arm-template (schema)

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azurearmtools#457]
I'm seeing this (https://github.com/microsoft/vscode-azurearmtools/issues/348) in the latest version (0.8.3)

![image](https://user-images.githubusercontent.com/2193314/73032998-938d1500-3df5-11ea-8b59-909734524384.png)

**Comment by neilpeterson** [comment]
@Tyriar  can you share the template?

**Comment by Tyriar** [comment]
@neilpeterson sent you a message on Teams

**Comment by Lusey77** [comment]
Was this issue resolved? I am experiencing the same issue with my template.

**Comment by Tyriar** [comment]
Not yet, I still see it

**Comment by neilpeterson** [comment]
This work is still in progress. I will update once completed.

Thanks

**Comment by yvesgermain** [comment]
I have the same problem.  I noticed that the last web site "type": "Microsoft.Web/sites/config" won't address the priority in the "ipSecurityRestrictions" section?
[template.json.txt](https://github.com/microsoft/vscode-azurearmtools/files/4312467/template.json.txt)

**Comment by jklaus** [comment]
Also seeing this.
Microsoft Visual Studio Enterprise 2019
Version 16.4.5

**Comment by neilpeterson** [comment]
The "Exactly 1 match" issue has been fixed in our latest release. @Tyriar looking at the related template that you shared privately, I was able to identify one remaining issue. I've opened up a new issue to track.

https://github.com/microsoft/vscode-azurearmtools/issues/624
