### ISSUE TITLE
Add space after colon with IntelliSense

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/vscode-azurearmtools#460]
When editing an ARM template, intellisense kicks in to suggest what to type after a colon. For example, if you add the apiVersion property, you will get a list of the available versions.
When selecting one of the suggestions, the value is added directly after the colon. I have a bit of OCD and I like my values to have a single space of room after the colon. I can't find a vscode setting for this anywhere. I don't know if this is only a ARM json thing. If so, please change this.

   Bad:  "apiVersion":"2019-11-04"
Good:  "apiVersion": "2019-11-04"

Thanks

**Comment by StephenWeatherford** [comment]
Valid point, although you might consider enable "Format on Save" in vscode's settings.  That way you don't have to worry about it at all.

**Comment by nielsvdc** [comment]
Format on Save will sometimes format more then I'd like, so I prefer to keep it off :-).

**Comment by StephenWeatherford** [comment]
Was there a reason you closed this?  I think we should fix it (format on save was only meant as a temporary work-around).

**Comment by nielsvdc** [comment]
If you are going to fix it, there was no reason to close it.

**Comment by StephenWeatherford** [comment]
https://dev.azure.com/devdiv/DevDiv/_boards/board/t/ARM%20Template%20Authoring/Stories

**Comment by StephenWeatherford** [comment]
This will be fixed in the next release, thanks for entering the issue.

**Comment by StephenWeatherford** [comment]
Just FYI, we've had some issues with the Azure schema CDN and some other things that have delayed this release.  Will have it out as soon as possible, hopefully next week.

**Comment by neilpeterson** [comment]
Release went out today with this fix - thanks.
