### ISSUE TITLE
"Format Document" and schema validation don't work against unsaved ARM templates

### ISSUE THREAD

**Issue by anthony-c-martin** [microsoft/vscode-azurearmtools#464]
When working with JSON files, the VSCode "Format Document" command is pretty handy for cleaning up and applying consistent formatting to a JSON document. When working with an ARM template, if I switch from language "JSON" to language "Azure Resource Manager Template", I lose this ability:

![image](https://user-images.githubusercontent.com/38542602/73291019-3f4ab200-41b4-11ea-9202-4ece5ce2f139.png)

The "Install Formatter..." link just takes me to the installation page for this extension. I currently have v0.8.3 installed.

**Comment by neilpeterson** [comment]
Thanks @anthony-c-martin I am not able to repo.

Before:

![image](https://user-images.githubusercontent.com/7844635/73292535-111aa180-41b7-11ea-8761-182729e10931.png)

After `shift - option - f` on a MacBook.

![image](https://user-images.githubusercontent.com/7844635/73292579-24c60800-41b7-11ea-8b53-d1d22991a79d.png)

In your example, the language show `[off]`. I've not seen this before, is there perhaps something going on with there?

**Comment by alex-frankel** [comment]
FWIW, I have seen this issue once before but was not able to repro consistently. I think I restarted VS Code and this issue went away

**Comment by anthony-c-martin** [comment]
Thanks @neilpeterson - I think I've figured it out. It only seems to happen if I open a new (blank) document, paste in a template, and then change the language to "Azure Resource Manager Template" without saving.

If I save the document and re-open it, the problem goes away.

**Comment by StephenWeatherford** [comment]
This is a symptom of https://github.com/microsoft/vscode-azurearmtools/issues/316.  Will dup that one against this, thanks!

**Comment by StephenWeatherford** [comment]
Lang server PR: https://dev.azure.com/devdiv/DevDiv/_git/ARM-LanguageServer/pullrequest/225545

**Comment by StephenWeatherford** [comment]
Needs lang server update

**Comment by StephenWeatherford** [comment]
FYI, the fix for this bug has just been released in v0.8.4
