### ISSUE TITLE
Unexpected warning when applying lock to resource group via nested template

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/vscode-azurearmtools#468]
In attached file you will see an example of a subscription deployment for a resource group with a nested template applying a lock to the resource group.
VSCode is giving the following warning on the properties and type field:
`"Value must be one of the following values: "Microsoft.Authorization/roleAssignments", "Microsoft.Authorization/roleDefinitions", "Microsoft.Authorization/policyAssignments", "Microsoft.Authorization/policyDefinitions", "Microsoft.Authorization/policySetDefinitions", "Microsoft.Peering/peerAsns", "Microsoft.Resources/resourceGroups", "Microsoft.Resources/deployments"`

If I a put the nested template code in a separate file, everything is fine.

[test.txt](https://github.com/microsoft/vscode-azurearmtools/files/4130310/test.txt)

![2020-01-29_202907](https://user-images.githubusercontent.com/10850600/73390314-1f131400-42d6-11ea-8fd7-aabd26b2db9a.png)

**Comment by neilpeterson** [comment]
Thanks @nielsvdc. We have a few running issues on nested templates, however this looks unique. I've been able to reproduce and we will prioritize looking into it.

**Comment by neilpeterson** [comment]
@nielsvdc we are prepping our next release which includes a fix for this. We hope to have this out next week. I will update if any significant delays.

**Comment by neilpeterson** [comment]
Release went out today, thanks.
