### ISSUE TITLE
Arm Template Outline doesn't show up when you first open a file, but does when you tab back to it

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#470]
Looks like a vscode bug. It would be nice to move into the default Outline window, though.

**Comment by nilshedstrom** [comment]
I fixed the bug in #483. 

To get into the normal outline view the extension needs to register a DocumentSymbolProvider. 
That would also give it the [bread crumb](https://code.visualstudio.com/updates/v1_26#_breadcrumbs) and [go to symbol](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol) features.

Do you want to implement the DocumentSymbolProvider in LanguageServer (C#) or should try to do it in typescript?

**Comment by StephenWeatherford** [comment]
Fixed by #483

As per DocumentSymbolProvider, if we go that route, it would probably make more sense to convert what we already have in TypeScript, right?  I've never used bread crumbs or go to symbol, though.  Wondering if it's worth the effort.

**Comment by nilshedstrom** [comment]
![image](https://user-images.githubusercontent.com/785949/74300162-4397d300-4d4f-11ea-9854-08eafed5c391.png)
I did a first implementation in https://github.com/nilshedstrom/vscode-azurearmtools/tree/outline

I did not find a way to have custom icons for the resources. 
I dont know if it makes sense to have an outline and an ARM template outline.

**Comment by StephenWeatherford** [comment]
I'll take a look next week.

**Comment by neilpeterson** [comment]
This release went out today. The extension should auto-update and at that time will include this functionality / fix.
