### ISSUE TITLE
This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension.

### ISSUE THREAD

**Issue by leparduk** [microsoft/vscode-azurearmtools#471]
Does this occur consistently? Yes
Repro steps:

1. Open code and the following occurs
2. I have runtime 2.2.5 installed and extension does not find it.
3. I copy the dotnet 2.2.5 files from the system installed folder into the extensions folder and it deletes them.

Action: acquireDotnet
Error type: 1
Error Message: >>>> This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips.
Command failed: "c:\Users\Developer\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\Developer\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
Could not find/download: ".NET Core Runtime" with version = 2.2.5
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
At C:\Users\Developer\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.ps1:633 char:5
+     throw "Could not find/download: `"$assetName`" with version = $Sp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find/download: ".NET Core Runtime" with version = 2.2.5
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
 

Version: 0.8.3
OS: win32
OS Release: 10.0.14393
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:303:12
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

<details>
<summary>dotnetAcquireLog</summary>

```
Status bar: $(cloud-download) Downloading .NET Core tooling...
Status bar: $(alert) Error acquiring .NET Core tooling!

[dotnet 2.2.5]: Found an incompletely-installed version of dotnet 2.2.5... Uninstalling.
[dotnet 2.2.5]: Uninstalling dotnet version 2.2.5
[dotnet 2.2.5]: Removing folder c:\Users\Developer\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5
[dotnet 2.2.5]: Finished removing folder c:\Users\Developer\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5
[dotnet 2.2.5]: Finished uninstalling dotnet version 2.2.5
Using this command to install .NET Core version 2.2.5:
"c:\Users\Developer\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\Developer\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
Downloading .NET Core tooling version(s) 2.2.5.......[dotnet 2.2.5]: dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/2.2.5/dotnet-runtime-2.2.5-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/2.2.5/dotnet-runtime-2.2.5-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Runtime/2.2.5/dotnet-win-x64.2.2.5.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/2.2.5/dotnet-win-x64.2.2.5.zip

[dotnet 2.2.5]: STDERR: Could not find/download: ".NET Core Runtime" with version = 2.2.5
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
At C:\Users\Developer\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.ps1:633 char:5
+     throw "Could not find/download: `"$assetName`" with version = $Sp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find/download: ".NET Core Runtime" with version = 2.2.5
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
 

 Error!
Failed to download .NET Core tooling 2.2.5:
Exit code: 1
Message: Command failed: "c:\Users\Developer\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.cmd" -InstallDir 'c:\Users\Developer\AppData\Roaming\Code\User\globalStorage\msazurermtools.azurerm-vscode-tools\.dotnet\2.2.5' -Runtime dotnet -Version 2.2.5
Could not find/download: ".NET Core Runtime" with version = 2.2.5
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
At C:\Users\Developer\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.8.3\assets\install scripts\dotnet-install.ps1:633 char:5
+     throw "Could not find/download: `"$assetName`" with version = $Sp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find/download: ".NET Core Runtime" with version = 2.2.5
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
 



```

</details>

**Comment by StephenWeatherford** [comment]
@leparduk Generally the error "Could not find/download" generally means that you were offline or it couldn't reach the dotnet website.  Could you try again when you know you're online?  Thanks!

See https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition#could-not-finddownload-net-core-runtime-with-version--225 for more info.

**Comment by leparduk** [comment]
I refuse to engage with someone who does not credit me with the intelligence to know whether I have a live internet connection or not. This is so patronising!

**Comment by StephenWeatherford** [comment]
I'm sorry, no patronization was intended.  We get a lot of issues filed with little or no thought given to them, so I can't assume much and start with the more obvious (note also I said "or it couldn't reach the dotnet website).  I have only seen the error message from the above logs when the websites were not available.  

I'll assume then that you can manually access https://dotnetcli.azureedge.net/dotnet/Runtime/2.2.5/dotnet-runtime-2.2.5-win-x64.zip and the extension still fails to install it?  If so, could you see if manually installing dotnet works?  See the work-around at https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition#work-around-installing-dotnet-core-manually.

Stephen

**Comment by StephenWeatherford** [comment]
*Ah*, I see I missed your comments at the beginning, sorry. My eyes went right to the technical info.
We don't currently try to find locally installed versions (might in the future), but you can set it to use one through the work-around I already mentioned (https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition#work-around-installing-dotnet-core-manually).
