### ISSUE TITLE
Add support for Azure Blueprint artifacts

### ISSUE THREAD

**Issue by david-jarman** [microsoft/vscode-azurearmtools#479]
Blueprint artifacts contain full ARM templates (just nested in a JSON property), but the language server does not seem to work with these files.

**Comment by neilpeterson** [comment]
Thanks @david-jarman - we will put this on the backlog and prioritize where it makes sense.

**Comment by HexagonSam** [comment]
Blueprint Artifacts support would be awesome. Definitely needed. We are moving most of our templates to using Blueprints-as-code, and this is a missing feature.

**Comment by neilpeterson** [comment]
@david-jarman / @HexagonSam we are going to close this in lieu of the upcoming template spec tech.

For information on tempalte specs, check out [this video](https://www.youtube.com/watch?v=YjqLnJnw_Y0&feature=youtu.be&t=720).
