### ISSUE TITLE
CopyIndex with 2 arguments is considered an error

### ISSUE THREAD

**Issue by hensilva** [Microsoft/vscode-azurearmtools#48]
I have a functioning template that incorrectly triggers an alert in VSCode (using Azure Resource Manager Tools 0.4.0)

![image](https://user-images.githubusercontent.com/23301459/37741367-e3ee98fc-2d3f-11e8-8d92-4e0e2fc4da07.png)

But copyIndex can accept 2 arguments and the script above is working as intended

![image](https://user-images.githubusercontent.com/23301459/37741387-fa190ae0-2d3f-11e8-901b-a756461ba67a.png)

**Comment by EricJizbaMSFT** [comment]
FYI @hensilva we just released an update that includes this fix
