### ISSUE TITLE
Space after colon (:) removes IntelliSense Selection List

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#482]
When authoring, adding a `:` will bring up an IntelliSense selection list, however if I then enter a space, the list is removed. It would be ideal, if after adding a space, we still have access to the IntelliSense options.

**Comment by StephenWeatherford** [comment]
Space after colon (:) removes IntelliSense Selection List

**Comment by StephenWeatherford** [comment]
Fixed in language server
