### ISSUE TITLE
Extension does not accept dashboard templates

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azurearmtools#487]
Repro:

- Create a dashboard on Azure
- Export the template (includes `"type": "Microsoft.Portal/dashboards"`)
- Paste into a file that the extension validates

<img width="924" alt="Screen Shot 2020-02-13 at 12 05 18 PM" src="https://user-images.githubusercontent.com/2193314/74473865-32d38400-4e59-11ea-850b-ae6870ec0399.png">

**Comment by neilpeterson** [comment]
@Tyriar thanks for the issue. What root level schema are you using?

I've verified that the Portal RP has been onboarded into the automated schema generation process, and that version `2015-08-01-preview` is included and the dashboard resource does validate when using the `2019-04-01` root schema.

![image](https://user-images.githubusercontent.com/7844635/74475361-269cf600-4e5c-11ea-87fd-0ada0f153433.png)


I can confirm also that it has not been added to the `2015-01-01` schema. If there is a need to have it here, I can look into having it patched in.

![image](https://user-images.githubusercontent.com/7844635/74475310-0836fa80-4e5c-11ea-8c36-b0b9f50e27e7.png)

**Comment by Tyriar** [comment]
Yes it's `"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",`

I would think that since this is what Azure exports, it should be working for that schema?

**Comment by neilpeterson** [comment]
That is a very good point.

@alex-frankel any thoughts on this?

**Comment by alex-frankel** [comment]
We generate off the 2019 root schema, but use the 2015 in the exported template since not all tools can handle the 2019 schema. It is admittedly an unfortunate edge case.

Once VS can handle the larger schema, we can switch export and github quickstarts to use the 2019 schema. @neilpeterson - Joe/AlexG should know more about the timeline there

**Comment by neilpeterson** [comment]
Thanks Alex, makes sense.

**Comment by Tyriar** [comment]
Also when I update the schema to latest I get 4 errors for the exported template ☹️ 

<img width="478" alt="Screen Shot 2020-02-14 at 9 24 49 AM" src="https://user-images.githubusercontent.com/2193314/74553317-f57bfe80-4f0b-11ea-992c-5d318cb0ddb0.png">

**Comment by neilpeterson** [comment]
Thanks @Tyriar we are working on the OneOf issues now.

**Comment by neilpeterson** [comment]
Update on this one. Code has been completed for the OneOf issues. We will test soon and have it in the next release.

**Comment by neilpeterson** [comment]
We are prepping for 0.9.0 release which includes a fix for these 'OneOf' issue. Hope to have it out within days.

I've just tested an exported template with dashboard resource against a recent build and it validates fine (after updating the root schema > 2019-04-01.
