### ISSUE TITLE
Present resource apiVersion in reverse chronological order

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#489]
Gathered from internal feedback.

On apiVersion intellisens, present the list in reverse chronological order so that the most recent is at the top of the list.

![image](https://user-images.githubusercontent.com/7844635/74482689-daf14900-4e69-11ea-8f65-3d4a086d45f9.png)

**Comment by StephenWeatherford** [comment]
https://dev.azure.com/devdiv/DevDiv/_boards/board/t/ARM%20Template%20Authoring/Stories/?workitem=1069201

**Comment by StephenWeatherford** [comment]
> We create completion items for apiVersions in GetApiVersionValuesCompletionItemsAsync of src\Languages\json\Editor\Arm\AsyncCompletion\ArmResourceTypeAndVersionCompletionProvider.cs
> 
> I think the easiest way to reverse-sort those would be to create non-empty sortText that would be reverse of what the "normal" completion item sort would be.

**Comment by StephenWeatherford** [comment]
fixed by #1276

**Comment by StephenWeatherford** [comment]
Not fixed?
