### ISSUE TITLE
The folder still exist in VS Code when deleting the folder from localhost

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-azurearmtools#49]
Repro Steps:
1.Open a folder from localhost in VS Code.
2.Delete the folder from localhost.
3.Check whether the folder still exist or not in VS Code.

Expect:
The folder is removed in VS Code.

Actual:
The folder still exists.

**Comment by StephenWeatherford** [comment]
I don't see what this has to do with the ARM Tools extension. If this is a vscode bug, please file it in their repo, but I think you'll need better repro steps, or maybe some images to help explain. Thanks.
