### ISSUE TITLE
Add auto-complete / IntelliSense for dependsOn

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#492]
When in a **dependsOn** block, `ctrl` > `space`  or opening `"` could suggest a list of all resources found in the current template.

We could just use the resource name, however if the tempalte contains multiple resources with the same name, `resourceId()` must be used. Also, the resourceId convention does give indication of resource type which can also be desirable.

Initial suggestion is to create the dependencies using the `resourceId()`function, open for discussion.

```
"dependsOn": [
    "[resourceId('Microsoft.Storage/storageAccounts', 'nepetersone')]",
    "[resourceId('Microsoft.Storage/storageAccounts', variables('name'))]"
]
```

Other notes that may be helpful:

- Dependencies only apply to resources defined within the same template.
- A dependency can be defined with resource name or resource id. When using name, it must be unique to the template.
- In addition to resources, dependencies can be created for copy blocks. For these use the copy block name.
- Dependencies between a child and parent is not implicit, they must be specified (nested and decoupled), [examples](https://github.com/neilpeterson/arm-template-collection/tree/master/3-other/resource-id-child-resources).
- Using the reference or list* functions do create an implicit dependency. Initial thought is that this should not factor into this work.

**Comment by alex-frankel** [comment]
Is there a way to show up after I type [ or the left " for each item in the array?

**Comment by neilpeterson** [comment]
Thanks Alex, I agree that this should be part of the experience. I've updated the initial issue to reflect. We  will look into it for sure.

**Comment by neilpeterson** [comment]
@bmoore-msft mentioned dependency on copy loops.

```
      "copy": {
        "name": "nicLoop",
        "count": "[parameters('numberOfInstances')]"
      },
```

Where the dependency would be the bane of the copy loop.

```
      "dependsOn": [
        "nicLoop"
      ],
```

**Comment by StephenWeatherford** [comment]
> Where the dependency would be the bane of the copy loop.

I agree...  But did you mean "name"? :-)

**Comment by bmoore-msft** [comment]
LOL - I think so ;)

**Comment by neilpeterson** [comment]
Yes, I've updated the text :).

**Comment by StephenWeatherford** [comment]
# Dev Spec/TODOs

- dependson from and into child resources (eg 101-sql-logical-server.json)
