### ISSUE TITLE
[Formatting] Auto complete commas where needed 

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#497]
In the following example, when hitting enter or on file save, can we insert a commas where needed? 

Cc: @satyavel 

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "type": "Microsoft.AAD/domainServices"  // missing comma here
            "apiVersion": "2017-01-01",
            "name": "test123",
            "properties": {
            }
        }
    ]
}
```

**Comment by StephenWeatherford** [comment]
Given that an extra comma is considered an error, I'm not sure this makes sense here, and I haven't seen this behavior in, say, TypeScript.  I do agree there are times when I wished commas were automatically added or removed, but I think we'd need a much clearer sense of the scenarios to consider something here.

**Comment by neilpeterson** [comment]
Apologies, I see now that the provided example did a bad job of demoing the scenario. I have updated it.

I've opened the issue as a placeholder while researching a. is this the right thing to do and b. potential implementation details. 

Are there other extensions or conventions around auto-completion of statement separators / terminators? I am looking at the TypeScript extension and it does not appear to handle terminating `;` nor does the built-in VS handling of JSON insert `,`.

Should flagging the issue, which we all-ready do, be sufficient?

**Comment by StephenWeatherford** [comment]
No problem with placeholders, as they foster discussion.  Adding statement terminators would probably be good. Unfortunately, these are statement separators, so depends on what comes after.  I guess I could see this being good during format/save (both adding and removing commas), much more hesitant about while typing.
