### ISSUE TITLE
Add intellisense for parameters()

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azurearmtools#499]
eg. press ctrl+space at the |:

```
"name": "[parameters(|)]"
```

**Comment by Tyriar** [comment]
This does work, nvm.

**Comment by StephenWeatherford** [comment]
Was there a scenario that was confusing and caused you to think this didn't work?  Thx.

**Comment by Tyriar** [comment]
I was using the new settings sync feature that I've been working on but forgot it doesn't sync extensions into remotes (was connected to wsl at the time).
