### ISSUE TITLE
The created files are by the order after creating files named with number

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-azurearmtools#50]
Repro Steps:
1.Open VS Code and create some files named with number.
2.Check whether the files are by the order or not.

Expect:
The files are by the order.

Actual:
The files are out of order. Please see the picture below.
![actual](https://user-images.githubusercontent.com/37653604/37762951-a97a7990-2db5-11e8-85e4-af165eaec79d.png)

**Comment by StephenWeatherford** [comment]
Opened editors go by tab order.
As for order of files in folders, it seems to be going by numerical order when beginning with a number, which is actually nice, I think.  
But none of this is related to the extension, and seems to be by design.
