### ISSUE TITLE
Suggestion: Auto-complete should not insert ()

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azurearmtools#501]
Experience in TS:

1. Find an item to auto-complete
   ![image](https://user-images.githubusercontent.com/2193314/75096446-824e3a00-5554-11ea-867a-8a2e6f73a5bf.png)
2. Press tab:
   ![image](https://user-images.githubusercontent.com/2193314/75096452-8b3f0b80-5554-11ea-9827-ee09f26eea44.png)
3. Press `(`:
   ![image](https://user-images.githubusercontent.com/2193314/75096455-97c36400-5554-11ea-85f8-1bda05521dd1.png)
4. Start typing var name:
   ![image](https://user-images.githubusercontent.com/2193314/75096463-add12480-5554-11ea-8893-e596f66bcdca.png)

---

Experience with ARM tools:

1. Find an item to auto-complete:
   ![image](https://user-images.githubusercontent.com/2193314/75096389-fc31f380-5553-11ea-9c38-921d26d040f5.png)
2. Press tab:
   ![image](https://user-images.githubusercontent.com/2193314/75096392-0b18a600-5554-11ea-9a40-3d70e0e182be.png)
3. Press `'`:
   ![image](https://user-images.githubusercontent.com/2193314/75096419-461ad980-5554-11ea-816c-402230c919a4.png)

Notice signature help doesn't show up, this is particularly bad since very few users actually know the ctrl+shift+space shortcut. Instead of inserting the brackets the extension should be relying on VS Code's core capability to auto-insert closing brackets, this also has the benefits of respecting settings like this (which I happen to use as well):

```
"editor.autoClosingBrackets": "never"
```

Ideally this would be the state when `'` is pressed:

![image](https://user-images.githubusercontent.com/2193314/75096403-297ea180-5554-11ea-8bd6-be2649daa1e8.png)

**Comment by Tyriar** [comment]
This issue really messes with my muscle memory and makes typing out `concat()` entries manually really frustrating.

**Comment by neilpeterson** [comment]
Thanks @Tyriar I see your point here and will prioritize this where it makes sense.

**Comment by StephenWeatherford** [comment]
ALSO:
1) Completing a user namespace should not add a "."

**Comment by StephenWeatherford** [comment]
Shipped yesterday
