### ISSUE TITLE
-Runtime dotnet -Version 2.2.5 Could not find/download: ".NET Core Runtime" with version = 2.2.5

### ISSUE THREAD

**Issue by MaolinPan** [microsoft/vscode-azurearmtools#504]
throw "Could not find/download: `"$assetName`" with version = $Sp ... +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException     + FullyQualifiedErrorId : Could not find/download: ".NET Core Runtime" with version = 2.2.5 Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Comment by StephenWeatherford** [comment]
Can you verify if this works when you are connected to the Internet?  See https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition#could-not-finddownload-net-core-runtime-with-version--225.  Thanks.

**Comment by MaolinPan** [comment]
Thanks

**Comment by StephenWeatherford** [comment]
Sounds like it's working.  Please re-open if not.

**Comment by MaolinPan** [comment]
thank you anyway
