### ISSUE TITLE
Remove properties that are set to default value

### ISSUE THREAD

**Issue by jochenvw** [microsoft/vscode-azurearmtools#506]
I would love to have the option to go through my ARM template and remove all properties set to default properties - in order to reduce the number of lines.

Consider the workflow here someone exports the ARM template from the portal to make modifications. The export of a webapp is very large - including properties like 'isXenon' ( https://docs.microsoft.com/en-us/azure/templates/Microsoft.Web/2019-08-01/sites ). Having an option to get rid of these lines would be awesome.

I checked - the schema has information about the default - so maybe we can also make lines kindof transparent where the property value is the default anyway. ( https://github.com/Azure/azure-resource-manager-schemas/blob/ff320d13e002510dc247f13440a3e70fa70ad479/schemas/2018-11-01/Microsoft.Web.json )

**Comment by neilpeterson** [comment]
Thanks @jochenvw, noted and summarized below:

Add command to remove all non-required resource properties. Particularly helpful when making changes to an exported tempalte.

**Comment by neilpeterson** [comment]
@jochenvw thanks again for entering this issue. This is a good suggestion however we are not going to be able to prioritize this one for the foreseeable future. 

I'm going to close for now but if we receive enough interest / feedback for similar features we will certainly revisit.
