### ISSUE TITLE
failed to download dotnet core 2.2.5

### ISSUE THREAD

**Issue by MaolinPan** [microsoft/vscode-azurearmtools#507]
if dotnet core 2.2.5 comes to its life end , what is the best substitution for "$schema":"https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json

**Comment by StephenWeatherford** [comment]
@MaolinPan Not sure I understand your question.  I will say that we've already updated to using dotnet core 3.0 with the next release.  Does that resolve your concern?  Thanks.

**Comment by StephenWeatherford** [comment]
Closing.  Feel free to reactivate.
