### ISSUE TITLE
Insert item

### ISSUE THREAD

**Issue by nilshedstrom** [microsoft/vscode-azurearmtools#508]
I think it would be nice if it was possible to create a new parameter, variable, function, resource and output with this extension.

The "Insert item" command could be available from the command palette, context menu for the text editor and the "ARM template outline".
That command would first ask what kind of item to create (parameter, variable, function, resource or output) with a quick pick and then ask about the name and type (if applicable). 
Then the text for the new item would be inserted at the correct location and the cursor would be located at the value-position so that he/she can start typing the value with intellisense.

If the user would right click in the "ARM template outline" on the parameters then the extension would have "Insert parameter" in the context menu (making it possible to select the type of item to insert by right clicking in the "ARM template outline").

When inserting a new resource the user would have to select what kind of resource (limited to the existing snippets) and then that snippet would be insert into the template and the user can start editing the different fields in the same was as he/she would have inserted the snippet manually.

Is this something that is usefull?

I can do this myself if I get some kind indication that it is regarded as a usefull feature.

**Comment by StephenWeatherford** [comment]
I'd definitely like us to do something along these lines, although I'm wondering if Intellisense is a better route for it.  After the current release, @neilpeterson and I can do something thinking and get back to you.  Thanks!

**Comment by neilpeterson** [comment]
Hey @nilshedstrom if we had better support for snippets / IntelliSense how would that change this proposal? For instance if while in a variable block, snippets were limited to only creating a new variable, would the meet the expectations of the experience? 

Much like Stephen, I would like to see this functionality, however we have been thinking about updating the capabilities around snippets, and I do wonder if snippets / IntelliSense is the correct place to provide the insert item experiance.

**Comment by nilshedstrom** [comment]
It would be great if the support for snippets / Intellisense were better but I do not see it as a replacement for the functionallity that I am suggesting, I think it would be nice to have both.

The snippet/intellisense support is great for power users who know the structure and syntax of ARM templates. They are used to editing the ARM template by hand and can get help while doing it. They know that they need to go to the variables-section to create a new variable and with the improved snippet/intellisense they get better support when they are creating the new variable.

I see two main use cases for the "Insert item" feature
* Beginner
The user are a beginner to ARM template and does not know the structure. This user does not know that you will get help creating a variable if you go inside the "variables" section. They are unfamiliar to the way snippets and intellisense work inside vscode. For this user the "Insert item" feature would mean that they get a way (that is easily discoverable) to create variables that they did not know how to do before. When it comes to creating resources they have the possibity to select the new resource from a nicely formatted list instead of the current list of snippets.
* Lazy power user
The user are a power user of ARM templates. They know the structure and the syntax and want to be as productive as possible. They know that in order to insert a variable they must go to the variables section but they want to find a faster way to do it. For this user the "Insert item" feature would mean that they get more productive when inserting new parameters, variables, functions and outputs. When it comes to creating a new resource they also enjoy the new dialog that is searchable and gives good name and description for all resources available.

The improved snippets/IntelliSense would be a great way to improve the current way the user edits ARM template using this extension. 
The "Insert item" feature would be a new way to edit ARM templates using this extension. I hope it would be appreciated by the "Beginner" because it is discoverability and the powerfull features and the "Lazy power user" because they get a faster way to do something they already knew how to do.

Here are some screenshots from Visual Studio 2019.

![image](https://user-images.githubusercontent.com/785949/76268199-9e005280-626d-11ea-835d-80325ecf3e7c.png)
![image](https://user-images.githubusercontent.com/785949/76268585-c9d00800-626e-11ea-9425-4918b162dfe6.png)

**Comment by neilpeterson** [comment]
Yep, this does make sense, thanks for the detail. Stephen also mentioned this same scenario this afternoon 👍 . 

There are a few things to think through here, would you mind if I reach out / set up some time to talk?

**Comment by nilshedstrom** [comment]
Sure. That is fine. 
I have time om Tuesday (today)

**Comment by StephenWeatherford** [comment]
@nilshedstrom I assume you've been working on variable extraction?  Saw something in the telemetry about a command named that...   :-)   That's a related feature that is also definitely on the roadmap.

**Comment by nilshedstrom** [comment]
> @nilshedstrom I assume you've been working on variable extraction? Saw something in the telemetry about a command named that... :-) That's a related feature that is also definitely on the roadmap.

I have been using [ARM Params Generator](https://github.com/wilfriedwoivre/vscode-arm-params-generator) that can extract a parameter or a variable. It is a great feature but not documented at all.

**Comment by nilshedstrom** [comment]
I implemented "Insert parameter" in: 
https://github.com/nilshedstrom/vscode-azurearmtools/tree/insertItem

**Comment by nilshedstrom** [comment]
@neilpeterson @StephenWeatherford 
I implemented the functionallity i planned in https://github.com/nilshedstrom/vscode-azurearmtools/tree/insertItem
It seems to work fine in CRLF mode and a small bug in Insert Resource for LF mode.
I am thinking about ways to write unit tests for the functionallity but I cannot find any good ones because there are so many questions to the user.

**Comment by StephenWeatherford** [comment]
For tests, there are two possibilities:
1) don't worry about mimicking the user interactions, just have an entry point that takes in all the assembled user args and does the actual work, and test that.
2) replace ext.ui with an instance of TestUserInput, which can be used to simulate the UI interactions (there are examples of this usage in https://github.com/microsoft/vscode-azurefunctions)

I think either is appropriate in this scenario.

**Comment by StephenWeatherford** [comment]
Fixed by #589

**Comment by StephenWeatherford** [comment]
Shipped yesterday
