### ISSUE TITLE
[Discussion] Reenable customer survey

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurearmtools#51]

**Comment by StephenWeatherford** [comment]
As part of this, re-enable AzureRMAssets.test.ts/AzureRMAssets/getSurveyMetadata - this failing test is why the survey is not currently working (surveyLink is undefined).

**Comment by bmoore-msft** [comment]
Instant.ly - which hosts the survey, has revamped their service - not sure if the survey has moved or has been removed.

**Comment by StephenWeatherford** [comment]
@fiveisprime Closing this since we now have a survey that applies to all our extensions.
