### ISSUE TITLE
Resource type - valid API version lookup - not latest

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [microsoft/vscode-azurearmtools#52]
Schema lookup not reflecting the latest API version for various resource types. Screenshot example: Microsoft.Compute/virtualMachines
![capture](https://user-images.githubusercontent.com/28310425/38342492-aa97d696-384c-11e8-81aa-e169608cb4d2.PNG)

Resource type API version found on https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines

**Comment by haugerbr** [comment]
@StephenWeatherford it appears that nobody updates those schemas. But I believe the [Azure REST API Specs](https://github.com/Azure/azure-rest-api-specs) are always up to date since the SDKs for various languages use those. Couldn't the schema's be generated off the info in that repo?

**Comment by Shell32-Natsu** [comment]
Why can't we have a `latest` pseudo version which always points to the latest one? This validation error is annoying.

**Comment by StephenWeatherford** [comment]
We are working on major changes with the extension which should improve this experience. 

BTW, I no longer get an error for 2017-12-01 for VMs.

**Comment by StephenWeatherford** [comment]
Closing for now since the original issue has been fixed and the work for the general scenario is ongoing.
