### ISSUE TITLE
[Unstable]Still display an error acquiring .NET Core tooling on Linux even though the vscode-dotnet-runtime installed

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#523]
Does this occur consistently? 
Repro steps:

1. Install the vscode-dotnet-runtime and ARM Tools extensions.
2. Open a deployment file.

Action: getDotNetPath
Error type: Error
Error Message: >>>> This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips.
Couldn't resolve the dotnet path!
![image](https://user-images.githubusercontent.com/34729092/76047528-ed106400-5f9d-11ea-966b-d09f20820fc2.png)

Version: 0.8.5
OS: linux
OS Release: 5.0.0-36-generic
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:218:769233
fulfilled extension.bundle.js:218:768536
```

</details>

**Comment by StephenWeatherford** [comment]
@v-dantch Does this still repro?
