### ISSUE TITLE
EnableGraph/EnableTable for Cosmos snippets?

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#524]
E.g. I know EnableGremlin is important for a graph.  See https://github.com/Azure/azure-quickstart-templates/blob/master/101-cosmosdb-gremlin/azuredeploy.json.
 
The Cosmos extension adds EnableGremlin for graphs and EnableTable for tables, and doesn't bother with SQL or Mongo.

**Comment by neilpeterson** [comment]
@StephenWeatherford I am looking into this now. From what you know, is this simply a configuration of the _capability_ property on the _Microsoft.DocumentDB/databaseAccounts_ resource?

We currently have both _EnableTable_ and _EnableGremlin_ in the snippet ([link](https://github.com/microsoft/vscode-azurearmtools/blob/master/assets/armsnippets.jsonc#L1061)).

I am adding _EnableCassandra_, and it looks like neither [SQL](https://docs.microsoft.com/en-us/azure/cosmos-db/manage-sql-with-resource-manager) or [Mongo](https://docs.microsoft.com/en-us/azure/cosmos-db/manage-mongodb-with-resource-manager) require a capability configuration.

I've linked the specific docs above (SQL and Mongo), this is also reflected in the ARM Tempalte reference for [Microsoft.DocumentDB/databaseAccounts@2019-12-12](https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/2019-12-12/databaseaccounts#capability-object).

**Comment by neilpeterson** [comment]
From what I can tell, this may be difficult to do with a single snippet for the `Microsoft.DocumentDB/databaseAccounts` resource. When deploying an account for the Casandra and SQL APIs the only difference is that Casandra has a capability specified where SQL does not.

Casandra: kind = _GlobalDocumentDB_ with capability of _EnableCassandra_

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "name": "Casandra",
            "type": "Microsoft.DocumentDB/databaseAccounts",
            "apiVersion": "2019-12-12",
            "location": "[resourceGroup().location]",
            "kind": "GlobalDocumentDB",
            "properties": {
                "consistencyPolicy": {
                    "defaultConsistencyLevel": "Eventual"
                },
                "locations": [
                    {
                        "locationName": "westus",
                        "failoverPriority": 0
                    }
                ],
                "databaseAccountOfferType": "Standard",
                "enableAutomaticFailover": true,
                "capabilities": [
                    {
                        "name": "EnableCassandra"
                    }
                ]
            }
        }
    ]
}
```

SQL kind = _GlobalDocumentDB_ with no capability specified

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "name": "sql",
            "type": "Microsoft.DocumentDB/databaseAccounts",
            "apiVersion": "2019-12-12",
            "location": "[resourceGroup().location]",
            "kind": "GlobalDocumentDB",
            "properties": {
                "consistencyPolicy": {
                    "defaultConsistencyLevel": "Eventual"
                },
                "locations": [
                    {
                        "locationName": "westus",
                        "failoverPriority": 0
                    }
                ],
                "databaseAccountOfferType": "Standard",
                "enableAutomaticFailover": true
            }
        }
    ]
}
```

I did try a null value for capability which results in:

```
Deployment failed. Correlation ID: 7636529c-5c82-4757-8284-da44aff7a75f. {
  "code": "BadRequest",
  "message": "Invalid supplied capabilities. Name: \r\nActivityId: 341f8513-a536-4140-aa0f-53c6202295e5, Microsoft.Azure.Documents.Common/2.11.0"
}
```

Perhaps a better approach would be to combine the _Microsoft.DocumentDB/databaseAccounts_ resource and the database / table resource into one snippet for each api type?
