### ISSUE TITLE
Error loading Schemas

### ISSUE THREAD

**Issue by StevonixDev** [microsoft/vscode-azurearmtools#536]
Hi,

When  initializing the extension following errors are written to the log.  I have tried to Reload Cached Schemas and have manually deleted .local/share/Microsoft/ARMLanguageServer but none worked.
This error prevents the plugin to function properly.

MacOS: 10.15.3 (19D76)
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

[Error - 9:21:25 PM] Unexpected: no 'oneOf' member found in 'https://schema.management.azure.com/schemas/2019-08-01/managementGroupDeploymentTemplate.json'
[Info  - 9:21:25 PM] Finding descriptor for initialize
[Info  - 9:21:26 PM] Starting: Routing Request (0) initialize
[Info  - 9:21:26 PM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 9:21:26 PM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 9:21:26 PM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 9:21:26 PM] Finished: Routing Request (0) initialize in 132ms
[Info  - 9:21:26 PM] Finding descriptor for initialized
[Info  - 9:21:26 PM] Finding descriptor for workspace/didChangeConfiguration
[Info  - 9:21:26 PM] Starting: Routing Notification initialized
[Info  - 9:21:26 PM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams
[Info  - 9:21:26 PM] logLevel set to Warning
[Error - 9:21:32 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-10-01/Microsoft.StorageSync.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2018-02-01/Microsoft.Resources.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2015-11-01/Microsoft.Resources.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2020-02-01/Microsoft.ContainerService.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2020-03-01/Microsoft.Batch.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-11-01-preview/Microsoft.AppConfiguration.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2018-03-01-preview/Microsoft.SignalRService.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-12-01-preview/Microsoft.ApiManagement.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-05-10/Microsoft.Resources.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2016-10-10/Microsoft.ApiManagement.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-03-01/Microsoft.Resources.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2016-07-01/Microsoft.Resources.json

[Error - 9:21:33 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-10-01-preview/Microsoft.Resources.json

[Error - 9:21:34 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-10-01/Microsoft.AppConfiguration.json

[Error - 9:21:34 PM] Error loading schema: https://schema.management.azure.com/schemas/2020-04-01-preview/Microsoft.EventGrid.json

[Error - 9:21:34 PM] Error loading schema: https://schema.management.azure.com/schemas/2020-03-01/Microsoft.DocumentDB.json

[Error - 9:21:34 PM] Error loading schema: https://schema.management.azure.com/schemas/2020-01-01-preview/Microsoft.EventGrid.json

[Error - 9:21:34 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-10-27-preview/Microsoft.ContainerService.json

**Comment by neilpeterson** [comment]
Thanks for opening this issue, we are investigating.

**Comment by neilpeterson** [comment]
@StevonixDev we are still working on this and have recently cleared the cache on the content delivery network (CDN) for the schemas. Can you try again to reload the schema cache and let us know the results?

Thanks

**Comment by StevonixDev** [comment]
Hi ,

thanks for working on my request. This plugin would really help me.
Sorry to say it is still not working. (If I call the schema file manually I can load it, so I guess it now my connection, proxy or so...)

This is what I tried:
-I reloaded the cached schemas  in with the VS Code
- restarted VS Code
- add file; test-arm.json
- used snipplet: arm!
  it created:
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {},
    "resources": [],
    "outputs": {},
    "functions": []
}

**Results in the Terminal VS Code Output:**

[Error - 2:56:17 PM] Unexpected: no 'oneOf' member found in 'https://schema.management.azure.com/schemas/2019-08-01/managementGroupDeploymentTemplate.json'
[Error - 2:56:17 PM] Unexpected: no 'oneOf' member found in 'https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json'
[Info  - 2:56:17 PM] Finding descriptor for initialize
[Info  - 2:56:18 PM] Starting: Routing Request (0) initialize
[Info  - 2:56:18 PM] Converting params for Request (0) initialize to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams
[Info  - 2:56:19 PM] Result was System.Threading.Tasks.Task`1[[OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult, OmniSharp.Extensions.LanguageProtocol, Version=0.12.0.0, Culture=neutral, PublicKeyToken=6d868dff454e6022]]
[Info  - 2:56:19 PM] Response value was OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult
[Info  - 2:56:19 PM] Finished: Routing Request (0) initialize in 260ms
[Info  - 2:56:19 PM] Finding descriptor for initialized
[Info  - 2:56:19 PM] Finding descriptor for workspace/didChangeConfiguration
[Info  - 2:56:19 PM] Starting: Routing Notification initialized
[Info  - 2:56:19 PM] Converting params for Notification initialized to OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializedParams
[Info  - 2:56:20 PM] logLevel set to Warning
[Error - 2:56:24 PM] Error loading schema: https://schema.management.azure.com/schemas/2019-05-10/Microsoft.Resources.json
.....
The $schema property gets marked as squiggly and mouse over shows:
There are problems with this document's schema impacting one or more items in the document

regards 
Stefan

**Comment by neilpeterson** [comment]
@StevonixDev we have identified the problem and have a fix in the works. I will update early next week with status.

**Comment by neilpeterson** [comment]
@StevonixDev fix is complete. We are preparing a hot fix release now which should be out within the coming days.

**Comment by StephenWeatherford** [comment]
Hotfix 0.8.5 is live.  Thanks for reporting!
