### ISSUE TITLE
There is no "Azure Resource Managers Template" output window after opening a deployment file

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#539]
**OS:** All
**Build Version:** [20200318.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16394&view=results)

**Repro Steps:**
1. Open a deployment file.
2. Check if there is a "Azure Resource Manager Template" output window.

**Expect:**
There is a "Azure Resource Manager Template" output window..

**Actual:**
There is no "Azure Resource Managers Template" output window.
![image](https://user-images.githubusercontent.com/45614674/76961612-9ff69f80-6958-11ea-9fda-717aa9d4a185.png)

**Comment by neilpeterson** [comment]
@v-ruizh I believe this PR consolidated the output into one channel, Azure Resource Manager Tools. 

https://github.com/microsoft/vscode-azurearmtools/pull/495

@StephenWeatherford to confirm.

**Comment by StephenWeatherford** [comment]
Correct, thanks!
