### ISSUE TITLE
Custom Script VM extension snippet error

### ISSUE THREAD

**Issue by backerman** [microsoft/vscode-azurearmtools#542]
The `arm-vm-script-windows` snippet has errors preventing language server validation:

- There is no `protectedSettings` block generated, which gets a warning squiggly (and should).
- The `commandToExecute` setting should be in `protectedSettings`. When it is moved to the correct location, the `settings` block gets a warning squiggly (but shouldn't).

The API version should probably also be updated to `2019-03-01` and the type handler version to `1.10` but the current values aren't causing any direct problems.

Resource generated by extension version 0.8.4:
```json
        {
            "name": "windowsVM1/customScript1",
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "apiVersion": "2018-06-01",
            "location": "[resourceGroup().location]",
            "tags": {
                "displayName": "customScript1 for Windows VM"
            },
            "dependsOn": [
                "[resourceId('Microsoft.Compute/virtualMachines', 'windowsVM1')]"
            ],
            "properties": {
                "publisher": "Microsoft.Compute",
                "type": "CustomScriptExtension",
                "typeHandlerVersion": "1.4",
                "autoUpgradeMinorVersion": true,
                "settings": {
                    "fileUris": [
                        "[concat('artifactsLocation', '/scripts/customScript.ps1', 'artifactsLocationSasToken')]"
                    ],
                    "commandToExecute": "powershell -ExecutionPolicy Bypass -file customScript.ps1"
                }
            }
        }
```

Resource that should be generated:

```json
        {
            "name": "windowsVM1/customScript1",
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "apiVersion": "2019-03-01",
            "location": "[resourceGroup().location]",
            "tags": {
                "displayName": "customScript1 for Windows VM"
            },
            "dependsOn": [
                "[resourceId('Microsoft.Compute/virtualMachines', 'windowsVM1')]"
            ],
            "properties": {
                "publisher": "Microsoft.Compute",
                "type": "CustomScriptExtension",
                "typeHandlerVersion": "1.10",
                "autoUpgradeMinorVersion": true,
                "settings": {
                    "fileUris": [
                        "[concat('artifactsLocation', '/scripts/customScript.ps1', 'artifactsLocationSasToken')]"
                    ]
                },
                "protectedSettings": {
                    "commandToExecute": "powershell -ExecutionPolicy Bypass -file customScript.ps1"
                }
            }
        }
```

External software versions: .NET Core 2.2.5, ARM language server 3.0.0-preview.20106.3; host Win10 x64 version 1909 build 18363.720.

**Comment by backerman** [comment]
Executing the "Reload Cached Schemas" command and restarting Visual Studio Code did not change this behavior.

**Comment by neilpeterson** [comment]
Thanks @backerman, I appreciate the issue. Most of this has been updated in this PR, which will ship in the next release.

https://github.com/microsoft/vscode-azurearmtools/pull/522

I will add the type handler update before the release as well.

**Comment by neilpeterson** [comment]
@backerman the remaining items have been added with this PR.

https://github.com/microsoft/vscode-azurearmtools/pull/543

Thanks again for opening the issue.

**Comment by neilpeterson** [comment]
Closing this issue due to fix being merged. I will come back and update once the updated extension has been released.

**Comment by neilpeterson** [comment]
This release went out today. The extension should auto-update and at that time will include this functionality / fix.
