### ISSUE TITLE
The first "{" does not support the Format Document function

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#544]
**OS: Windows**
**Build Version:**[ 20200320.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16514&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. Open a deployment file
2. Change the position of the first "{"
3. Right-click -> Format Document

**Expect:**
The first "{" returns to its original position

**Actual:**
The first "{" does not support the Format Document function
![image](https://user-images.githubusercontent.com/62053665/77156314-1b338f00-6ada-11ea-9a27-636399677741.png)

**More info:**
If there is only one pair of "{}" in the deployment file, the first "{" returns to its original position

**Comment by StephenWeatherford** [comment]
Thanks for entering. I agree that's weird, but the work-around is easy and won't happen very often, so I don't think this is worth fixing right now.
