### ISSUE TITLE
Schema doesn't recognize Microsoft.Management/managementGroups in tenant deployment

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#553]
{
    // from https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-tenant
    "$schema": "https://schema.management.azure.com/schemas/2019-08-01/tenantDeploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "mgName": {
            "type": "string",
            "defaultValue": "[concat('mg-', uniqueString(newGuid()))]"
        }
    },
    "resources": [
        {
            "type": "Microsoft.Management/managementGroups",
            "apiVersion": "2019-11-01",
            "name": "[parameters('mgName')]",
            "properties": {
            }
        }
    ]
}

Value must be one of the following values: "microsoft.aadiam/diagnosticSettings", "Microsoft.Authorization/roleAssignments", "Microsoft.Authorization/roleDefinitions", "Microsoft.Authorization/policyAssignments", "Microsoft.Authorization/policyDefinitions", "Microsoft.Authorization/policySetDefinitions", "Microsoft.Resources/deployments"

**Comment by StephenWeatherford** [comment]
Or Microsoft.Authorization/roleAssignments

{
    // from https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-tenant
    "$schema": "https://schema.management.azure.com/schemas/2019-08-01/tenantDeploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "mgName": {
            "type": "string",
            "defaultValue": "[concat('mg-', uniqueString(newGuid()))]"
        }
    },
    "resources": [
        {
            "type": "Microsoft.Management/managementGroups",
            "apiVersion": "2019-11-01",
            "name": "[parameters('mgName')]",
            "properties": {
            }
        }
    ]
}

**Comment by neilpeterson** [comment]
This PR in the schemas repo will provide schemas and root schema updates. We will then need to generate and ship a new ARM Tools schema package.

https://github.com/Azure/azure-resource-manager-schemas/pull/932

I will see what I can do to move it along.

**Comment by neilpeterson** [comment]
The schema PR has been merged.
