### ISSUE TITLE
FullyQualifiedErrorId : Could not find/download: ".NET Core Runtime" with version = 2.2.5

### ISSUE THREAD

**Issue by MaolinPan** [microsoft/vscode-azurearmtools#560]
The issue text was copied to the clipboard.  Please paste it into this window.

**Comment by StephenWeatherford** [comment]
@MaolinPan Can you verify that you are connected to the Internet?  If so, can you please copy the contents of the output window for Azure Resource Manager Tools and Azure Resource Manager Template?  Thanks!

<img width="565" alt="image" src="https://user-images.githubusercontent.com/6913354/77946151-bc5adc00-7276-11ea-82f7-b6c6a7d62abd.png">

**Comment by rushilShetty** [comment]
![image](https://user-images.githubusercontent.com/7541109/78654647-1e45c200-78c5-11ea-9f77-82b535175859.png)

I have the same problem as reported by MaolinPan. And yes I am connected to the internet (you can see that in the screenshot too). This is the output. 

Also my current dotnetcore installed version is 3.1.102.
![image](https://user-images.githubusercontent.com/7541109/78655210-f99e1a00-78c5-11ea-9613-3348f0c217db.png)

**Comment by ToroStanislaw** [comment]
Same exact issue here. Exactly the same output.

**Comment by rushilShetty** [comment]
So I was able to find a work around as mentioned [here ](https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition#could-not-finddownload-net-core-runtime-with-version--225) (even though it's not recommended) and it's working now.
![image](https://user-images.githubusercontent.com/7541109/78683406-87dac600-78ef-11ea-9097-90f36c647724.png)

**Comment by StephenWeatherford** [comment]
Sorry for the delay.  This should have been fixed with the 0.9.1 release, please let me know if it's still happening.

@rushilShetty you can try removing the work-around now, thanks!
