### ISSUE TITLE
Suggestion: Improve ARM templates deployment experience as Visual Studio 

### ISSUE THREAD

**Issue by giovannifl** [microsoft/vscode-azurearmtools#571]
Hello,
Any chance that Visual Studio Code ARM templates deployment experience could be improved to mimic Visual Studio where it's possible to:
- Select target subscription
- Select target resource group
- Select template JSON file
- Select parameter JSON file
- Edit parameter JSON file interactively (i.e. choosing between available values)

Thanks

**Comment by neilpeterson** [comment]
Thanks @giovannifl. This is something that we are keen on and have in the backlog. Here is the current work item.

https://github.com/microsoft/vscode-azurearmtools/issues/27

I am going to close this issue in favor of 27 but please feel free to track / add input to issue 27. 

Once we get the work scheduled you can track progress [here](https://github.com/microsoft/vscode-azurearmtools/projects/1).
