### ISSUE TITLE
Sparse filtering does not work for our expression Intellisense

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#572]

**Comment by neilpeterson** [comment]
@StephenWeatherford  I am trying to reproduce as you've described but am not seeing it. 

In this screen shot, I've typed `acco` for resource type and see the completion list filtered down based on those characters being present at any position in list of returned strings.

![image](https://user-images.githubusercontent.com/7844635/78819356-f7ea5a00-798a-11ea-8ab2-bb6897d7621d.png)

Are you describing something different?

**Comment by StephenWeatherford** [comment]
Pretty sure it's because we try to handle filtering ourselves...  Perhaps vscode didn't use to do that automatically?  It's old code.
