### ISSUE TITLE
VMSS Extension Resources - Value must be one of the following...

### ISSUE THREAD

**Issue by denious** [microsoft/vscode-azurearmtools#574]
Adding Azure Monitor to my Service Fabric VMSS deployment and getting the following error. It seems that neither of the required VM extensions is in the list of available options.

The entire deployment code is a copy-paste from official documentation/template:
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/vminsights-enable-at-scale-powershell#download-templates

I have recently opened a similar ticket that was subsequently tagged with "ported to language server." Let me know if there is a better place to report these!

![image](https://user-images.githubusercontent.com/7120854/78698835-ecd2f380-78d0-11ea-8932-0df2d0e1a425.png)

**Comment by StephenWeatherford** [comment]
@denious This is definition the correct place to enter these bugs, thanks!  
I'll let @neilpeterson verify if this is fixed in the current master branch.

**Comment by neilpeterson** [comment]
Hmm, this one seems like it might be legitimately schema related. @deniuos I'm curious, if you add `"settings": {}` inside of the properties section (second red box), does the issue resolve?

**Comment by denious** [comment]
Yes 👍

**Comment by neilpeterson** [comment]
Thanks @denious, there is still an issue here however looks schema related. I will open an issue over in that repo and will tag this one in it to track.
