### ISSUE TITLE
Microsoft.OperationInsights/workspaces - Value must be one of the following...

### ISSUE THREAD

**Issue by denious** [microsoft/vscode-azurearmtools#575]
Adding a Log Analytics Workspace which is required before enabling Azure Monitor for VMSS deployments and getting the following error.

![image](https://user-images.githubusercontent.com/7120854/78699769-69b29d00-78d2-11ea-9e14-c90827334c62.png)
![image](https://user-images.githubusercontent.com/7120854/78699823-8222b780-78d2-11ea-9f24-19d45ecf744a.png)

The entire deployment code is a copy-paste from official documentation/template:
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/vminsights-enable-at-scale-powershell#install-the-vminsights-solution

What I don't understand is that Microsoft.OperationInsights/**solutions** appears not supported not only by ARM validation but by the official schema as well?
https://docs.microsoft.com/en-us/azure/templates/microsoft.operationalinsights/allversions

![image](https://user-images.githubusercontent.com/7120854/78702475-a385a280-78d6-11ea-834f-fb7c99be46f4.png)

**Comment by neilpeterson** [comment]
Thanks @denious 

We are prepping a new release 0.9.0 which fixes these one of issues. We are hoping to have it out very soon.

I've just tested the docs sample against a 0.9.0 build and can confirm that they are fixed in the new release.

**Comment by StephenWeatherford** [comment]
Fixed, will let you know when it's released.

**Comment by neilpeterson** [comment]
This release went out today. The extension should auto-update and at that time will include this functionality / fix.
