### ISSUE TITLE
Add lightbulbs for parameter/variable rename

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#576]
for better discoverability

**Comment by nilshedstrom** [comment]
I do not understand the proposed functionallity. 

> A code action represents a change that can be performed in code, e.g. to fix a problem or to refactor code.

If we show a lightbulb next to all variables and parameters people might be annoyed if they connect the lightbulb with something that can be fixed/improved. Or do you suggest that we only show the lightbulb next to variables/parameters that have bad names?
As a reference: when I open C# or Typescript files in VS Code I do not see lightbulb next to all the variables, only where there is a fix (not rename) available.

**Comment by StephenWeatherford** [comment]
@neilpeterson You want to play with Nil's implementation of this and weigh in?  Nil is correct that C# doesn't show the lightbulb on all things that can be renamed, but it does show for various other refactorings that are optional, e.g.
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/6913354/79799790-e81a3080-830f-11ea-9c96-e7e887f3ff5b.png">
Did you get a sense from any of the interviews whether people knew you could rename in the template file?  My guess is that most don't think of trying, so I'm inclined to think this is a good idea.

**Comment by neilpeterson** [comment]
I've read through [this doc](https://code.visualstudio.com/docs/editor/refactoring) and see nothing to conclude that this would be an overt miss-use of code actions.

From telemetry, rename is not often engaged. The only customer feedback that I've received was from one whom was unaware of the capability, and very excited after learning about it. 

I like the implementation and agree that it may help discovery. I say we go for it and adjust if we get feedback on it.

Thanks again @nilshedstrom.

**Comment by StephenWeatherford** [comment]
Cool.

**Comment by StephenWeatherford** [comment]
@nilshedstrom @neilpeterson Another option, if you think this is too much, is to just show the lightbulb when they're on a *definition*, and not when inside an expression.  This would still help with discoverability but wouldn't be as much in the way.

**Comment by StephenWeatherford** [comment]
Fixed by https://github.com/microsoft/vscode-azurearmtools/pull/621

**Comment by StephenWeatherford** [comment]
@nilshedstrom Shipped yesterday.  Your attribution will ship with 0.10.1, sorry again :-(
