### ISSUE TITLE
ARM Template Outline Browser does not appear

### ISSUE THREAD

**Issue by edburns** [microsoft/vscode-azurearmtools#577]
I observe non-deterministic behavior regarding whether or not the ARM Template Outline Browser appears in the "Explorer" pane in VS Code.  I find I have to go through the following gymnastics to make it reliably appear.

Consider a folder "workarea" with the following layout.

```
.
├── arm-oraclelinux-wls-dynamic-cluster
│   ├── pom.xml
│   ├── src
│   │   └── main
│   │       ├── arm
│   │       │   ├── createUiDefinition.json
│   │       │   ├── mainTemplate.json
│   │       │   └── nestedtemplates
│   │       │       └── clusterTemplate.json
```

I find I must open both mainTemplate.json and clusterTemplate.json, then move the focus between the two tabs to cause the ARM Template Outline to appear.

**Comment by neilpeterson** [comment]
Thanks for raising the issue Ed. This behavior is fixed in the next release (days away from release).

https://github.com/microsoft/vscode-azurearmtools/issues/470

**Comment by neilpeterson** [comment]
This release went out today. The extension should auto-update and at that time will include this functionality / fix.
