### ISSUE TITLE
There is no "Azure Resource Manager Tools: Reload Cached Schemas" command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#583]
**OS:** Mac (Not verify on Windows and Linux)
**Build Version:** [20200410.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17576&view=results)

**Repro Steps:**
F1 to check if there is a command "Azure Resource Manager Tools: Reload Cached Schemas".

**Expect:**
There is a command "Azure Resource Manager Tools: Reload Cached Schemas".

**Actual:**
There is no "Azure Resource Manager Tools: Reload Cached Schemas" command.
![image](https://user-images.githubusercontent.com/45614674/78984241-5ca6df80-7b58-11ea-9682-bb35fc7bd469.png)

**Comment by StephenWeatherford** [comment]
Thanks for bringing this up.  This was actually an intentional change as of 0.8.5.  We no longer try to download schemas, we also use the zip file that is shipped with the extension, due to various problems with the published schemas.
