### ISSUE TITLE
The associating parameter file name is truncated in status bar if the name is long

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#584]
**OS:** Mac (Not verify on Windows and Linux)
**Build Version:** [20200410.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17576&view=results)

**Repro Steps:**
1. Open a template file which has a long name and create a parameter file for it.
2. Check the associating parameter file name from status bar.

**Expect:**
The full name can be checked.

**Actual:**
The associating parameter file name is truncated.
![image](https://user-images.githubusercontent.com/45614674/78985337-1737e180-7b5b-11ea-8378-bc37ff6032ef.png)

**Comment by StephenWeatherford** [comment]
This shouldn't be a common case (if you've opened a folder and are using templates in that folder or subfolders, you'll see relative paths), don't think we need to worry about it, but thanks anyway.
