### ISSUE TITLE
Unrecognized function name 'listCallbackUrl'.

### ISSUE THREAD

**Issue by DonKarlssonSan** [Microsoft/vscode-azurearmtools#59]
I'm using `listCallbackUrl` in one of our ARM templates. It is working fine but I get the warning "Unrecognized function name 'listCallbackUrl'." in VS Code.

I figured out that `listCallbackUrl` [works a bit different](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#listkeys-listsecrets-and-list) compared to the `listKeys` and `listSecrets` methods. The latter two are "built in" and available, whereas the first one depends on the resource. To figure out which ones are available you can "View the REST API operations... or Use the Get-AzureRmProviderOperation PowerShell cmdlet ... or Use the following Azure CLI command"

Is it possible to add `listCallbackUrl` as a valid function?

Should I create a PR where this function is added to ExpressionMetadata.json?

**Comment by StephenWeatherford** [comment]
If you'd like to add it yourself, please go ahead, thanks!  Otherwise let us know and we'll take a look.

**Comment by DonKarlssonSan** [comment]
I'll give it a try

**Comment by bmoore-msft** [comment]
Add the list functions as they appear so we can get proper intellisense/autocomplete... the shape of these functions is more likely to diverge than converge.

**Comment by StephenWeatherford** [comment]
The arguments are the same for all of them.

**Comment by bmoore-msft** [comment]
but the members/properties returned are not - so using list* would make it much harder for us to include those.

**Comment by StephenWeatherford** [comment]
Okay, makes sense.

**Comment by EricJizbaMSFT** [comment]
FYI @DonKarlssonSan we just released an update that includes this fix
