### ISSUE TITLE
This extension is trying to install a legacy dot net core version

### ISSUE THREAD

**Issue by j03INTHECLOUD** [microsoft/vscode-azurearmtools#598]
Error:
Downloading .NET Core tooling version(s) 3.0.2........[dotnet 3.0.2]: dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.2/dotnet-runtime-3.0.2-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.2/dotnet-runtime-3.0.2-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.2/dotnet-win-x64.3.0.2.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.2/dotnet-win-x64.3.0.2.zip

**Comment by cox-antohi** [comment]
My solution was to to add 
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
inside
**C:\Users\USERNAME\\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.9.0\assets\install scripts\dotnet-install.ps1**
after the line with
`$HttpClient.Timeout = New-TimeSpan -Minutes 20`

It seems to me that the next line having the `$HttpClient.GetAsync` command is getting **Could not create SSL/TLS secure channel.**.

**Comment by robmatear** [comment]
> My solution was to to add
> `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
> inside
> **C:\Users\USERNAME\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.9.0\assets\install scripts\dotnet-install.ps1**
> after the line with
> `$HttpClient.Timeout = New-TimeSpan -Minutes 20`
> 
> It seems to me that the next line having the `$HttpClient.GetAsync` command is getting **Could not create SSL/TLS secure channel.**.

This solution worked for me (it installed 3.0.2) but there is still the problem of the script targeting an old version of the runtime when a newer one is available.

**Comment by StephenWeatherford** [comment]
@j03INTHECLOUD @cox-antohi @robmatear Thanks for reporting!

We're about to ship a hot fix that changes the way we retrieve .net core, and should avoid this problem in the future.

**Comment by StephenWeatherford** [comment]
@sfoslund Is the Tls12 issue above already fixed in the newer install scripts?  Or is it related to trying to download 3.0.2 (didn't use to repro).  Thx.

**Comment by sfoslund** [comment]
@StephenWeatherford this looks like a known install script issue that came up last week. It was fixed in the SDK by [this PR](https://github.com/dotnet/installer/pull/7068/files). 

@wli3 does it make sense to set `[Net.ServicePointManager]::SecurityProtocol = 'Tls12, Tls13'` in the command evoking the install scripts in the vscode extension as well?

**Comment by wli3** [comment]
I think that make sense

**Comment by StephenWeatherford** [comment]
See https://github.com/microsoft/vscode-azurearmtools/pull/620

**Comment by StephenWeatherford** [comment]
Thanks for reporting, we just released 0.9.1, which we believe will fix this issue.  Please let us know if this works for you.
