### ISSUE TITLE
Revision comparison states unexpected problems

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/vscode-azurearmtools#601]
I have a ARM file that contains comments. When I save changes for this file, go to the Source Control pane and click the file, I get a comparison between the saved changes and the current revision in source control.
When I look at the editor window for the current revision, I see unexpected problems that should not be there.

- Comments are not permitted in JSON
- String does not match the pattern of "^[-\w\._\(\)]+$"

See attached test file and a screenshot of the errors and windows.

[test.txt](https://github.com/microsoft/vscode-azurearmtools/files/4481292/test.txt)

![vscode_errors](https://user-images.githubusercontent.com/10850600/79340279-5afb6400-7f2a-11ea-9740-c26e4c8c1437.png)

**Comment by StephenWeatherford** [comment]
Turns out git uses a separate scheme "git" that we're not registering for.

**Comment by StephenWeatherford** [comment]
I can no longer see this on vscode insiders Version: 1.47.0-insider.  I think they stopped showing errors in the left-hand pane, which is good (the errors you were getting were from the JSON language service, which should not be enabled for ARM templates).

**Comment by nielsvdc** [comment]
@StephenWeatherford I just tried with vscode 1.47.0 and with 1.48.0-insider and I still get the same problem notifications.

**Comment by StephenWeatherford** [comment]
Okay, I am seeing them.
