### ISSUE TITLE
Parameter validation issue when using more then one parameter file

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#602]
Create a parameter file from the following template and give the `containerName` parameter a value of `one`. 

At this point, things are good.

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "containerName": {
            "type": "string",
            "allowedValues": [
                "one",
                "two"
            ]
        }
    },
    "resources": [],
    "outputs": {
        "demo-issue": {
           "type": "string",
           "value": "[parameters('containerName')]"
        }
    }
}
```

Now create a second parameter file from the same tempalte, and also give the `containerName` parameter a value of `one`, save the parameter file and return to the template. 

At this point the template is mapped to the second parameter file however an error is thrown that the value is not one of the allowed.

![image](https://user-images.githubusercontent.com/7844635/79368741-c03c5e80-7f04-11ea-8099-f6f0e1369504.png)

Reload VS Code and the error is resolved.

**Comment by StephenWeatherford** [comment]
The lang server file watcher is not picking up the change in file to watch?

**Comment by neilpeterson** [comment]
This does still repro, however feels edge-case-ish. Closing as wont fix.
