### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yaser27** [microsoft/vscode-azurearmtools#603]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.9.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\PayThoN\msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by neilpeterson** [comment]
Thanks @yaser27 would it be possible to share the ARM tempalte that caused this performance issue?

**Comment by StephenWeatherford** [comment]
@yaser27 It would also be useful to have the cpuprofile.txt file as mentioned, thanks.
