### ISSUE TITLE
msazurermtools extension failed to import dotnet core

### ISSUE THREAD

**Issue by rajagopalanrg** [microsoft/vscode-azurearmtools#611]
Error: >>>> This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension.s copied to the clipboard.  Please paste it into this window.

**Comment by StephenWeatherford** [comment]
https://github.com/microsoft/vscode-azurearmtools/pull/620

**Comment by StephenWeatherford** [comment]
Thanks for reporting, we just released 0.9.1, which we believe will fix this issue.
