### ISSUE TITLE
[Suggestion] Change the oldest vscode version that the ARM extension supported

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#614]
**OS:** Windows
**Build Version:**[20200416.27](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17915&view=results)
**VS Code Version:** 1.31.1

**Repro Steps:**

1. Figure out the oldest vscode version that the ARM extension supported-->1.31.0
  ![image](https://user-images.githubusercontent.com/62053665/79551852-d268f900-80cc-11ea-8286-c385604a2d21.png)
2. Install an older VS Code 1.31.1.
3. Install ARM extension to VS Code 1.31.1.

**Actual:**
Unable to install ARM Extension. I guess this is expected.
![image](https://user-images.githubusercontent.com/62053665/79552722-fc6eeb00-80cd-11ea-90ca-372090cb931d.png)

**Suggestion:**
Change the oldest vscode version that the ARM extension supported in ARM extension.

**Comment by StephenWeatherford** [comment]
Fixed by #618 (0.9.2)
