### ISSUE TITLE
Schema validation is not identifying correct location in nested templates

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#625]
In a nested tempalte, schema validation is identifying an incorrect location for validation issues.

![image](https://user-images.githubusercontent.com/7844635/79645388-dac04300-8163-11ea-85b9-516b5742188a.png)

Here is the template shown in the above image.

https://github.com/neilpeterson/arm-template-collection/blob/master/2-tools-issues/nested-validation-precision.json

**Comment by cconrado** [comment]
yup same issue

**Comment by StephenWeatherford** [comment]
Fixed by https://github.com/microsoft/vscode-azurearmtools/pull/794.

@neilpeterson Can you please verify?

**Comment by StephenWeatherford** [comment]
Verified, adding test.

**Comment by StephenWeatherford** [comment]
Shipped with 0.11.0
