### ISSUE TITLE
ApiVersion not getting latest versions

### ISSUE THREAD

**Issue by cconrado** [microsoft/vscode-azurearmtools#627]
extension not getting the latest version from site
![image](https://user-images.githubusercontent.com/9168464/79670548-7c0dc000-8189-11ea-85b3-30cc5acff6d9.png)

![image](https://user-images.githubusercontent.com/9168464/79670659-51703700-818a-11ea-99e7-e0eb9a371a46.png)

**Comment by neilpeterson** [comment]
Thanks @cconrado. A schema has not yes been fully generated for `Microsoft/Web/*` for version `2019-08-01` ([it would be here](https://github.com/Azure/azure-resource-manager-schemas/tree/master/schemas/2019-08-01)). 

We currently have an initiate underway to create schemas for all resources + all api versions. Web is currently in progress. Status can be tracked [here](https://github.com/Azure/azure-resource-manager-schemas/projects/1) and the individual pull request is [here](https://github.com/Azure/azure-resource-manager-schemas/pull/968). Once generated we will pull that into the VS Code extension.

I'm going to close this, status can be tracked at the link above.

Thanks again.
