### ISSUE TITLE
Template with apiProfile not honored among resources

### ISSUE THREAD

**Issue by msft-jasonparker** [microsoft/vscode-azurearmtools#635]
1.  apiProfile does not allow for the most current api version
2.  Using an apiProfile with an intellisensed api version, downlevel resources show problems for missing required apiVersion.

Using an apiProfile should negate the need to provide an apiVersion under a resource, but you can specify and apiVersion to override the apiProfile version.

![image](https://user-images.githubusercontent.com/62903215/79921143-79f46d00-83e6-11ea-8882-3357b73df5eb.png)

![image](https://user-images.githubusercontent.com/62903215/79921176-8b3d7980-83e6-11ea-97c3-0ec8d874ffc2.png)

**Comment by neilpeterson** [comment]
Thanks @msft-jasonparker. I do see that the latest versions are missing from the root schema and am looking into having this updated.

https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-04-01/deploymentTemplate.json#L12

**Comment by neilpeterson** [comment]
@msft-jasonparker we have added `2019-03-01-hybrid` which should ship with the next releases schema package. This should take care of the example given above.

https://github.com/Azure/azure-resource-manager-schemas/pull/992

There is still some work to do to support the remaining apiProfiles and these will be added once ready. I will update this issue once released.

**Comment by StephenWeatherford** [comment]
Unfortunately this didn't make it into our next release on Monday.  We'll probably do a hot fix soon to pick up new schemas, but I can't guarantee when because we've got a lot of releases planned this month.

**Comment by StephenWeatherford** [comment]
Fix released with 0.11.0
