### ISSUE TITLE
dateTimeAdd function not recognized

### ISSUE THREAD

**Issue by bergmeister** [microsoft/vscode-azurearmtools#636]
`dateTimeAdd` is a supported function in ARM, see here: https://docs.microsoft.com/azure/azure-resource-manager/templates/template-functions-date#datetimeadd
However, the extension does not recognize it. Using version `0.9.1` of the extension.

![image](https://user-images.githubusercontent.com/9250262/79968093-95fc1b00-8487-11ea-99c6-84183dc74dd9.png)

**Comment by alex-frankel** [comment]
FYI @neilpeterson, this is a brand new function. Here is the doc page: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-date#datetimeadd

**Comment by neilpeterson** [comment]
Thanks @bergmeister and @alex-frankel I've added the function and pending no issues we will ship this with our next release.

https://github.com/microsoft/vscode-azurearmtools/pull/638

**Comment by bergmeister** [comment]
Awesome, thanks

**Comment by StephenWeatherford** [comment]
Shipped yesterday
