### ISSUE TITLE
databaseAccounts 2020-03-01 apiVersion isn't supported

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azurearmtools#637]
This is what came out of export template:

![image](https://user-images.githubusercontent.com/2193314/79999026-46f6bb80-8470-11ea-9a2e-b895c4729ecd.png)

**Comment by Tyriar** [comment]
Ok extension wasn't enabled before (needs to be installed in remote), I guess that's regular json schema validation? Problem still occurs with extension enabled:

![image](https://user-images.githubusercontent.com/2193314/80000388-f2544000-8471-11ea-978c-700354381f41.png)

**Comment by neilpeterson** [comment]
Thanks @Tyriar can you verify the extension version? I've just checked on my end and do see the `2020-03-01` apiVersion as an option. This is on version 0.9.1 of the extension.

![image](https://user-images.githubusercontent.com/7844635/80011782-2f73fe80-8481-11ea-82c6-4b125caec26c.png)

**Comment by Tyriar** [comment]
Extension is 0.9.1, installed on Debian WSL remote.

![image](https://user-images.githubusercontent.com/2193314/80016366-e4111e80-8487-11ea-86f1-37d306753bde.png)

VS Code version: Code - Insiders 1.45.0-insider (9328b32008089c515f39a13db9c71e57c7d36823, 2020-04-22T08:44:55.510Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by StephenWeatherford** [comment]
@Tyriar Are you using the new schema ("https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#")?

**Comment by Tyriar** [comment]
No it wasn't. I think I was in this situation a couple of months ago as well, it seems like the problem is that Azure is outputting invalid templates 😕

**Comment by neilpeterson** [comment]
Thanks @Tyriar. I will sync up with the ARM team on export and see what we can do there. Alex had left a note in a previous issue, I will follow up.

https://github.com/microsoft/vscode-azurearmtools/issues/487
