### ISSUE TITLE
multiple property copy loops are flagged as invalid

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#646]
... when they are siblings, see:

https://github.com/Azure/azure-quickstart-templates/blob/master/modules/Microsoft.KeyVault/vaults/1.0/azuredeploy.json#L179-L196

duplicate property names are invalid JSON, but you know ARM...

**Comment by StephenWeatherford** [comment]
Ugh!

**Comment by bmoore-msft** [comment]
IKR?

**Comment by StephenWeatherford** [comment]
@alexgav @neilpeterson The error is coming from the language server:

    A member with the name "copy" already exists.

Do you think it's possible to disable this when the property name is "[Cc][Oo][Pp][Yy]"?  If not, I could intercept the error from the extension if it had more info than just the English message.

**Comment by bmoore-msft** [comment]
I think it has to be fixed in the lang server because it looks like further eval of the template stops...

**Comment by neilpeterson** [comment]
@bmoore-msft is this a common configuration? I've been spelunking the quick start gallery / GitHub but cannot find any other instances. That said, it's a difficult configuration for precision matching.

Thanks, just trying to set priority / decide on what to fix / etc.

**Comment by dennis-benzinger-hybris** [comment]
The first example in the documentation about copying variables:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/copy-variables#example-templates

has two `copy`s on the same level:

https://github.com/Azure/azure-docs-json-samples/blob/master/azure-resource-manager/multipleinstance/copyvariables.json#L7-L29

**Comment by staal-it** [comment]
I found that having a second copy element does not work. The first one will be removed on deployment without an error. I for example tried to deploy a KeyVault doing: 

```json
{
      "type": "Microsoft.KeyVault/vaults",
      "apiVersion": "2019-09-01",
      "name": "[variables('keyVaultName')]",
      "properties": {
        "networkAcls": {
          "bypass": "AzureServices",
          "defaultAction": "Allow",
          "copy": [
            {
              "name": "ipRules",
              "count": "[length(variables('ipRulesArray'))]",
              "input": {
                "value": "[variables('ipRulesArray')[copyIndex('ipRules')]]"
              }
            }
          ],
          "copy": [
            {
              "name": "virtualNetworkRules",
              "count": "[length(variables('vnetsToBeAllowed'))]",
              "input": {
                "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', variables('virtualNetworkName'), variables('vnetsToBeAllowed')[copyIndex('virtualNetworkRules')])]"
              }
            }
          ]
        }
      }
    }`

A workaround is to move one of those copies into the variables definition. Again, it only accepts one copy element there so it only works with max 2 and functions like resouceId don't work in variables.

**Comment by dennis-benzinger-hybris** [comment]
The value of `copy` is an array. You should be able to combine both `copy`s into one.

**Comment by staal-it** [comment]
@bmoore-msft I'm not seeing an error. The result is that only the second copy gets processed. When I look at the template in the Azure Portal after a deploy, the first one is gone. Looks like some processor removes / overwrites that with the second one?

**Comment by staal-it** [comment]
@dennis-benzinger-hybris I'm not sure if I understand your comment? The result should be two separate arrays in the properties section like so:
```json
"networkAcls": {
      "bypass": "string",
      "defaultAction": "string",
      "ipRules": [
        {
          "value": "string"
        }
      ],
      "virtualNetworkRules": [
        {
          "id": "string"
        }
      ]
    }
```

as described [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2019-09-01/vaults)

**Comment by StephenWeatherford** [comment]
@staal-it How are you deploying?  It could be that az or PowerShell or whatever is accidentally removing it (since it's not valid JSON).

**Comment by staal-it** [comment]
@StephenWeatherford using the standard task in Azure DevOps

**Comment by dennis-benzinger-hybris** [comment]
@staal-it, try this:
```
          "copy": [
            {
              "name": "ipRules",
              "count": "[length(variables('ipRulesArray'))]",
              "input": {
                "value": "[variables('ipRulesArray')[copyIndex('ipRules')]]"
              }
            },
            {
              "name": "virtualNetworkRules",
              "count": "[length(variables('vnetsToBeAllowed'))]",
              "input": {
                "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', variables('virtualNetworkName'), variables('vnetsToBeAllowed')[copyIndex('virtualNetworkRules')])]"
              }
            }
          ]
```
To find the relevant documentation search for "the copy element is an array so you can specify more than one property for the resource" on https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/copy-properties#property-iteration.

**Comment by staal-it** [comment]
@dennis-benzinger-hybris Ah now I get it, that makes total sense. Thanks!

**Comment by bmoore-msft** [comment]
yeah, turns out this is a "bug" in ARM... ARM silently removes duplicate keys (happens with copy, vars, params, etc).  So what VS Code is doing here is helpful..

I submitted a PR to fix the example in the OP, closing this since it's not an extension bug
