### ISSUE TITLE
Provide 'go to definition' support for resource types

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#648]
Go to definition could take in resource type and api version and open the resource schema (file on disk).

From internal work item:  1006933

**Comment by nilshedstrom** [comment]
@neilpeterson This seems interesting. Where can I find the files that contain the schema?

**Comment by neilpeterson** [comment]
Thanks @nilshedstrom! Here are the patch from both Windows and Mac.

```
/Users/neilpeterson/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.9.1/languageServer/Schemas/JSON/azure-resource-manager-schemas.zip
C:\Users\nepeters\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.9.1\languageServer\Schemas\JSON\azure-resource-manager-schemas.zip
```

**Comment by nilshedstrom** [comment]
Any idea on how I can read files from inside a zip-file?

**Comment by neilpeterson** [comment]
I do not have insights on reading from the zip file however have confirmed that this is what the language server is doing.

We recently made the change from downloading individual schemas to shipping a compressed package with the extension. This was due some some inconsistent behavior in downloads and I do think that this is something we may revisit.

Perhaps we should wait on this on until we have had a chance to revisit schema downloads and storage.

**Comment by nilshedstrom** [comment]
After thinking about this functionallity I asked myself which users that will benefit from this functionality.
If it will be implemented the user will be able to go from a Storage Account (2019-06-01) to the definition that probably would look similar to [this](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2019-06-01/Microsoft.Storage.json). For me that file is hard to read and I imagine that it will be hard to implement navigation inside that file.
But if we could open the [documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-06-01/storageaccounts#Microsoft.Storage/storageAccounts) as suggested in #590 it would be more usefull for me (easy to read and easy to navigate).

**Comment by neilpeterson** [comment]
I would also prefer docs when authoring templates. I am aware of some whom use schemas for docs and think there may be some cases where providing a quick way to access schemas would come in helpful, but perhaps the best bang for our buck here is to focus on docs.

I've added a few notes to https://github.com/microsoft/vscode-azurearmtools/issues/590

**Comment by MarcusFelling** [comment]
Tracking in #590
