### ISSUE TITLE
Add possibility to add missing parameters to (possibly multiple) parameter files from within the template file

### ISSUE THREAD

**Issue by DOliana** [microsoft/vscode-azurearmtools#652]
Imagine:

1. you have an existing template with multiple parameter files
1. you want to add a resource to the template and introduce multiple new parameters
1. wouldn't it be nice to 
   - open the parameter file and be able to do things like
     - add all parameters missing from deployment file
     - add single parameters from deployment file which are not yet defined (new or old)
   - stay in the deployment file and
     - click on the error stating that the parameter is not set in the parameter file and has no default value and just let VSCode add the parameter to the current parameter file

**Comment by neilpeterson** [comment]
Thanks @DOliana! In the upcoming release we will have some functionality that addresses the first bullet points.

From the parameter file, we will have functionality to add all or all missing parameters.

![image](https://user-images.githubusercontent.com/7844635/80504470-04c5f200-8928-11ea-9a38-86a089ad0b51.png)

and an authoring experience that allows for auto-completion of parameters 1 by 1.

![image](https://user-images.githubusercontent.com/7844635/80504760-54a4b900-8928-11ea-802e-92327bafba9d.png)

Does this address your asks for the parameter file? How does the above experiences look to you?

For the second point (stay in the deployment file..). @StephenWeatherford do you have anything in the works to address this?

**Comment by StephenWeatherford** [comment]
I've considered whether we should do that or not, it's certainly doable and not a lot of work.  But then the user will still need to go to the parameter file to fill in the value, so I've questioned its value.  What do you think?

I've also considered adding code lens above each parameter to indicate the current value in the param file.

**Comment by DOliana** [comment]
@neilpeterson  Looks good! How is the contextmenu triggered? 
@StephenWeatherford I think it would be worth doing. (additionally it would be nice to be able to link multiple parameter files to a single deployment file)
In our scenario we usually have one deployment file and three parameter files - one for each environment: dev/int/pro. So when adding a new parameter in the deployment file, it's copy&paste to each parameter file.

**Comment by StephenWeatherford** [comment]
@DOliana The first bullet point is already covered in https://github.com/microsoft/vscode-azurearmtools/issues/566, which will be released soon, the week after next.  I've changed the title of this bug to represent the ability to do this from the template file, which is not currently implemented.  Thanks again for the suggestions, we appreciate them!

**Comment by StephenWeatherford** [comment]
@DOliana Actually, just noticed something else in your original comment, mentioning that the template has multiple parameter files.  This is something else that we've considered by have not implemented - right now you will need to select the parameter file that you want to edit.  How important is it to be able to have multiple parameter files selected for a template file?  You'd probably have to choose a specific param file for validation, but theoretically we could enable things like auto-completion of parameters, renames, etc. across multiple param files.

**Comment by DOliana** [comment]
I cannot give an importance ranking, but for me having multiple parameter files for a single deployment is one of the main points to deploy infrastructure. I think that it is kind of default to have multiple environments - at least development and production (with different scaling) and eventually even test, integration and so on.
To give you an understanding: In my situation only in the beginning (when only the dev environment exists) I have a single parameter file. As soon the solution evolve I have multiple files and when I add a resource to dev, I have to copy & paste it to all other parameter files. If you see an issue in my process feel free to comment :-)

**Comment by StephenWeatherford** [comment]
Whoops

**Comment by StephenWeatherford** [comment]
To come back quickly to this, these were the asks:

1. support selecting multiple parameters files at once (presumably things such as find reference could work here)
2. open the parameter file and be able to do things like
  - add all parameters missing from deployment file
  - add single parameters from deployment file which are not yet defined (new or old)
3. stay in the deployment file and
  - click on the error stating that the parameter is not set in the parameter file and has no default value and just let VSCode 
  - add the parameter to the current parameter file

Request 2 is completely implemented.
Request 3 already has similar functionality - there's a code lens next to a param definition showing the current value, which you can click on to take you to the param file and easily add the new value

The functionality that is not currently supported is being able to add to multiple param files at once.

**Comment by DOliana** [comment]
Thanks for coming back and indeed what your write sounds very good. Just to avoid misunderstanding - by implemented you do not mean released, right? (Reason being, that I only see options to add all or missing parameters - not single parameters)

**Comment by StephenWeatherford** [comment]
Actually, I do mean released.  Place the cursor inside the "parameters" section and type a double quote, see what happens.  Thanks!

**Comment by DOliana** [comment]
Thanks - looks good!
