### ISSUE TITLE
Contextualize snippets

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#654]
Resource snippets should not shown when in the parameters section of a template

- [x] empty doc
- [ ] CUT empty new plaintext doc
- [x] parameters
- [x] variables
- [x] resources
  - [x] remove surrounding braces (what about snippets with multiple resources?)
  - [x] child resources
  - [x] CUT subnets special case
- [x] outputs
- [x] functions
  - [x] members
  - [x] func parameters https://github.com/microsoft/vscode-azurearmtools/pull/867
- [x] tags https://github.com/microsoft/vscode-azurearmtools/pull/868
- [x] nested template parameter definitions
- [x] nested template parameter values
  - [x] getting doubles
- [x] CUT parameter file snippets read from file?
- [x] CUT comma before/after?
- [x] Use simpler naming (e.g. "new-parameter" instead of ("arm-parameter")
- [ ] Format after insertion -> https://github.com/microsoft/vscode-azurearmtools/issues/895
- [x] Should enter not complete resource snippets?

**Comment by StephenWeatherford** [comment]
@neilpeterson I'd like to do this in 0.11.0
