### ISSUE TITLE
The list for resourceId completions contains extra entries

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#659]
**OS:** Win10
**Build:** [20200429.10](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18516&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Open the 101-acsengine-swarmmode.json file.
2. Find the "id" --> Add a new { } with an "id" property in it and starting typing an expression with "resourceId()".
3. Select 'Microsoft.NetworkloadBalancers' and press a comma (",").
4. Check the result.

**Expected:**
The list should contain exactly two entries.
![image](https://user-images.githubusercontent.com/57662131/80682401-009aff80-8af5-11ea-8ad3-d350ebd70fd2.png)

**Actual:**
The list also contains extra entries.
![image](https://user-images.githubusercontent.com/57662131/80682292-c7fb2600-8af4-11ea-9c25-3327612cf5d7.png)

**Comment by StephenWeatherford** [comment]
Thanks for entering!  The testcase was wrong, and I have corrected it.
