### ISSUE TITLE
[Suggestion] Remove the single quote when executing the rename symbol

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#660]
**OS:** Win10
**Build:** [20200429.10](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18516&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Open any template file, e.g. new-vm.json.
2. Right click a parameter or variable ->  Rename Symbol.
3. Observe the result.

**Expected:**
Only show the name.

**Actual:**
Show the name and extra single quote.
![image](https://user-images.githubusercontent.com/57662131/80680031-a4ce7780-8af0-11ea-95db-5a4ec86e6649.png)

**More Info:**
1. This issue doesn't reproduce in the parameter file.
2. This issue doesn't reproduce for parameter definition.

**Comment by StephenWeatherford** [comment]
Weird...  I then get an error saying that it can't be renamed.

**Comment by StephenWeatherford** [comment]
Not a regression
