### ISSUE TITLE
Error shows when selecting parameter file for an unsaved template file

### ISSUE THREAD

**Issue by behzad23Rana** [microsoft/vscode-azurearmtools#666]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'C:\Users\behzad.javiad\AppData\Local\Programs\Microsoft VS Code\Untitled-1'

Version: 0.9.2
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

**Comment by StephenWeatherford** [comment]
I can repro this when the template file has not yet been saved

**Comment by williamgr** [comment]
I had this error with our without saving the file. I solved the issue by uninstalling, restarting vscode, then resinstalling the extension

**Comment by StephenWeatherford** [comment]
More visible now with the new parameters code lens
