### ISSUE TITLE
Azure ARM Workbook freezes VSCode

### ISSUE THREAD

**Issue by sundbing** [microsoft/vscode-azurearmtools#672]
### Issue we are facing
When opening an ARM template of type "microsft.insights/workbooks", this extension is freezing VS Code.
In the bottom info bar, it is showing "Starting ARM Template Language Server" and VS Code is not responding to any command anymore.
After a while, a popup is comming up that states, that the windows does not react anymore (propaply a OS popup from MS Windows).

### Expected situation
VS Code is not freezing on opening Azure ARM template of any kind.

### Workaround
Disabling the extension is solving the problem of freezing VS Code.

### Reproduce the error
I have attached the file causing the error here:
[VM-cpuUsage.json.txt](https://github.com/microsoft/vscode-azurearmtools/files/4580763/VM-cpuUsage.json.txt)

**Comment by neilpeterson** [comment]
Thanks @sundbing, sorry that you are running into this issue. 

I can reproduce with the file that you have provided however not with a very simple template (in code block below) nor [this random sample](https://github.com/acearun/managedsolutions/blob/e4a81fe5164e52b69673ce6c1e3325750db44168/Workbooks/Test1/mainTemplate.json) found on GitHub.

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {
        "location": "[resourceGroup().location]"
    },
    "resources": [
        {
            "name": "string",
            "type": "microsoft.insights/workbooks",
            "apiVersion": "2018-06-17-preview",
            "kind": "user",
            "location": "[variables('location')]",
            "properties": {
                "displayName": "test123",
                "serializedData": "string",
                "category": "string",
                "userId": "string"
            }
        }
    ]
}
```

We will look into this ASAP and get back with you.

**Comment by neilpeterson** [comment]
Few additional notes.

- I've updated the root schema version to `2019-04-01` which does not improve the situation.
- It seems like the extension is trying to process the `serializedData` which is causing the issues.
- I am not familiar with with app insights workbooks, but the template deploys fine and the workbook is created, which seems to indicate that the serialized data is properly formed.

**Comment by sundbing** [comment]
Hi @neilpeterson , thanks for looking into it.

The template was extracted from Azure Portal, where workbooks can be exported as ARM templates or JSON files for gallery view.
The ARM template itself is containing the galleryview version in serialized version.

**Comment by StephenWeatherford** [comment]
@neilpeterson I can repro with 0.9.2 but not master.  Have you tried master yet?

**Comment by StephenWeatherford** [comment]
Actually, it's a difference in vscode.  I can repro in vscode stable 1.44.2 but not insider 1.45.0-insider.

**Comment by StephenWeatherford** [comment]
Likely related to https://github.com/microsoft/vscode-azurearmtools/issues/330

**Comment by neilpeterson** [comment]
@StephenWeatherford I am seeing the same. The issue repros is stable 1.44.2 but not insiders 1.45.0.

**Comment by StephenWeatherford** [comment]
I can't repro in vscode 1.45.1.

**Comment by StephenWeatherford** [comment]
Added regression test.
