### ISSUE TITLE
Completion list for "location" shows incorrect icons

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#676]
![image](https://user-images.githubusercontent.com/7844635/81134987-5fa0b000-8f0b-11ea-8ea8-ddf3ed09c394.png)

Expected (from JSON and 0.6.0 release):

![image](https://user-images.githubusercontent.com/7844635/81135003-67605480-8f0b-11ea-9c11-724989067ee6.png)

From internal 987484

**Comment by StephenWeatherford** [comment]
AFTER:
![image](https://user-images.githubusercontent.com/6913354/84956198-87a83500-b0ad-11ea-8c2d-425c00c34211.png)
![image](https://user-images.githubusercontent.com/6913354/84956305-c1793b80-b0ad-11ea-8c3f-3323eb9fcb12.png)
![image](https://user-images.githubusercontent.com/6913354/84956328-cb02a380-b0ad-11ea-9466-88d8e9309bf2.png)
Note that the first two cases are different in vscode JSON.  But the VS code which we're using doesn't differentiate these two cases, thus I wasn't able to give them separate icons.
