### ISSUE TITLE
Top-level "metadata" property gives schema error (arm-template-language-samples/subscription-level.json)

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#677]
metadata property name is not allowed by schema.

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "metadata": {
    "comments": "This template was developed for demonstration purposes.",
    "author": "Example Name"
  }
}
```

From internal 1012865

**Comment by StephenWeatherford** [comment]
- [ ] Enable the "subscription-level.json" suite

**Comment by MarcusFelling** [comment]
@anthony-c-martin do you have any thoughts on this?

**Comment by anthony-c-martin** [comment]
Related to https://github.com/Azure/azure-resource-manager-schemas/issues/1079.

I think it would be worthwhile modeling "metadata" in our template schemas to fix this.

**Comment by StephenWeatherford** [comment]
Yay!
