### ISSUE TITLE
Gray out unused params/vars/etc

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#679]
From internal 1040737

**Comment by StephenWeatherford** [comment]
export namespace DiagnosticTag {
    /**
     * Unused or unnecessary code.
     *
     * Clients are allowed to render diagnostics with this tag faded out instead of having
     * an error squiggle.
     */
    export const Unnecessary: 1 = 1;
    /**
     * Deprecated or obsolete code.
     *
     * Clients are allowed to rendered diagnostics with this tag strike through.
     */
    export const Deprecated: 2 = 2;
}

export interface Diagnostic {
tags?: DiagnosticTag[];
