### ISSUE TITLE
[modify suites] "Missing required property apiVersion" error with apiProfile set to 2017-03-09-profile

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#688]
- [x] apiprofile.json suite
- [x] apiprofile2.json suite
- [x] apiprofile3.json suite - this one works

This template deploys without error.  Some give errors, others not.

{
	"resource": "apiprofile2.json",
	"owner": "ARM Template Language Server diagnostics",
	"severity": 4,
	"message": "Missing required property \"apiVersion\"",
	"source": "arm-template (schema)",
	"startLineNumber": 10,
	"startColumn": 9,
	"endLineNumber": 10,
	"endColumn": 10
}
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "apiProfile": "2017-03-09-profile",
    "parameters": {
    },
    "variables": {
    },
    "resources": [
        {
            "name": "as",
            "type": "Microsoft.Compute/availabilitySets",
            "location": "[resourceGroup().location]",
            "properties": {
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts",
            "name": "[uniquestring(resourcegroup().id)]",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "Standard_LRS"
            },
            "kind": "Storage",
            "properties": {
            }
        }
    ]
}
```

**Comment by StephenWeatherford** [comment]
[apiprofiles.zip](https://github.com/microsoft/vscode-azurearmtools/files/4596438/apiprofiles.zip)

**Comment by neilpeterson** [comment]
[This PR](https://github.com/Azure/azure-resource-manager-schemas/pull/992) added a new API profile `2019-03-01-hybrid` to the `2019-04-01/deploymentTemplate` schema. I wonder of this new API profile would resolve some of these?

**Comment by StephenWeatherford** [comment]
So it might be fixed by https://dev.azure.com/devdiv/DevDiv/_git/ARM-LanguageServer/pullrequest/247434?_a=files?

**Comment by StephenWeatherford** [comment]
@neilpeterson 

1) The above still repros
2) The above still repros with the 2019 schema
3) The above still repros with the 2019 schema and the 2019-03-01-hybrid profile

**Comment by neilpeterson** [comment]
Thanks. I will look into it.

**Comment by neilpeterson** [comment]
**Observation:**

I have some assumptions on what is going on here. 

Here is the list of apiProfiles from Microsoft.Compute/availabilitySets. Notice that profileVersion `2017-03-09-profile` maps to apiVersion `2016-03-30`

```
$ az provider list --query "[?contains(namespace, 'Microsoft.Compute')].resourceTypes[] | [?resourceType=='availabilitySets'] | [].apiProfiles"

[
  [
    {
      "apiVersion": "2016-03-30",
      "profileVersion": "2017-03-09-profile"
    },
    {
      "apiVersion": "2017-03-30",
      "profileVersion": "2018-03-01-hybrid"
    },
    {
      "apiVersion": "2017-12-01",
      "profileVersion": "2018-06-01-profile"
    }
  ]
]
```
However, we have not yet generated a schema for `Microsoft.Compute/availabilitySets@2016-03-30` so we cannot validate that version. 

We do have a PR that includes this schema but it will take some time to get reviewed.

https://github.com/Azure/azure-resource-manager-schemas/pull/876

**Fix:**

We do have a schema for `Microsoft.Compute/availabilitySets@2017-12-01`. Updating the apiProfile in the attached templates to `2018-06-01-profile` does fix the issue.

I'm assuming once the Compute schemas PR is merged, all apiProfiles will work for the Availability Set resource.

**Comment by StephenWeatherford** [comment]
We should go ahead and change the suites to 2018-06-01-profile.
