### ISSUE TITLE
Comma can't bring up Intellisense inside expressions

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#692]
**OS:** All
**Build:** [20200507.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18842&view=results)

**Repro Steps:**
1. Create a template file with the following contents:
```
{
	"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
	"artifactsLocation": {
	"type": "string"
	},
	"location": {
	"type": "string",
	"defaultValue": "westus"
	}
	},
	"resources": [
	{
	"name": "nestedDeployment1",
	"type": "Microsoft.Resources/deployments",
	"apiVersion": "2019-10-01",
	"properties": {
	"mode": "Incremental",
	"templateLink": {
	"uri": "[concat('artifactsLocation', '/nestedTemplates/nestedTemplate.json', 'artifactsLocationSasToken')]",
	"contentVersion": "1.0.0.0"
	},
	"parameters": {
	}
	}
	},
	{
	"name": "automationCertificate1",
	"type": "Microsoft.Automation/automationAccounts/certificates",
	"apiVersion": "2015-10-31",
	"dependsOn": [
	],
	"properties": {
	"base64Value": "base64Value",
	"description": "description",
	"thumbprint": "thumbprint",
	"isExportable": true
	}
	},
	{
	"name": "automationCertificate2",
	"type": "Microsoft.Automation/automationAccounts/certificates",
	"apiVersion": "2015-10-31",
	"dependsOn": [
	],
	"properties": {
	"base64Value": "base64Value",
	"description": "description",
	"thumbprint": "thumbprint",
	"isExportable": true
	}
	}
	],
	"outputs": {
	"output1": {
	"type": "string",
	"value": ""
	}
	}
	}

```
2. Create a new parameter file for it (choose "Only required parameters").
3. Type a comma after "}" that marks the end of "artifactionsLocation" --> CTRL+SPACE
4. Check the result.

**Expected:** 
Display the list contains "new parameter" and "location".

**Actual:**
Display the "No suggestions".
![image](https://user-images.githubusercontent.com/57662131/81393978-ca442c80-9153-11ea-8a98-3b529b054ec9.png)

**More Info:**
Display the list if type a space after comma.

**Comment by StephenWeatherford** [comment]
An expression is a string that begins and ends with "[" and "]", e.g. "[concat('a', 'b')]".  The comma here is not inside a string, therefore also not inside a comma.  The testcase indicates that intelligence should *not* come up in this scenario (after typing a comma outside of a string):
<img width="448" alt="image" src="https://user-images.githubusercontent.com/6913354/81436797-eaa5c400-911e-11ea-9a6a-461a3b7bb39e.png">
If you type a double quote or a CTRL+SPACE, it *should* come up at that point.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/6913354/81436889-0f01a080-911f-11ea-8f71-93994e096103.png">


Thanks

**Comment by v-xinda** [comment]
Got it. Thanks for your sharing.
