### ISSUE TITLE
[Suggestion] Remove the deleted parameter file from the "parameter file list"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#693]
**OS:** All
**Build Version:** [20200507.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18842&view=results)

**Repro Steps:**
1. Open a template file which has associating parameter file.
2. Remove the parameter file.
3. Close the template file and reopen it.
4. Check the parameter file display from task bar.
![image](https://user-images.githubusercontent.com/45614674/81397773-915b8600-915a-11ea-94d9-d123c8c55597.png)
5. In the task bar, click on the parameter file display and check the "parameter file list".

**Actual:**
The deleted parameter file is selected.
![image](https://user-images.githubusercontent.com/45614674/81397784-96203a00-915a-11ea-88b9-e1be581bd101.png)

**Suggestion:** 
Remove the deleted parameter file from the list.

**Comment by StephenWeatherford** [comment]
Rather than removing it, it should indicate that the file is not found.
