### ISSUE TITLE
Consider using arm-template langid for param files (getting "Unknown Schema" for deploymentParameters.json schema)

### ISSUE THREAD

**Issue by JHStarner** [microsoft/vscode-azurearmtools#705]
Looks like the extension is validating parameter files based on name, maybe?

Because under "Problems" I get the following when trying to use the "deploymentParameters.json#" schema:

`https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#`

This shows problems for parameter files, trying to validate them as full deployment templates.

**Comment by JHStarner** [comment]
What's strange, is when I make a new file using the `armp!` snippet, validation passes.

**Comment by StephenWeatherford** [comment]
In the bottom-right of VS Code, can you make sure that "Select Language Mode" is set to JSON for the parameter file, and not "Azure Resource Manager Template"?

![image](https://user-images.githubusercontent.com/6913354/81735168-7e420200-9449-11ea-8d0d-43911775cdc9.png)

**Comment by JHStarner** [comment]
This does correct it.

Will schema deploymentParameters.json schema be included in the ARM Template language mode in an upcoming release?

**Comment by StephenWeatherford** [comment]
See https://github.com/microsoft/vscode-azurearmtools/issues/546, felt there was no real need for it.  But if people are going to switch it manually thinking it necessary (is that what happened?), maybe it makes sense.

If we don't, I could add code to switch it back if detected.

@alexgav How hard would it be to support the params file schema via the language server?  Wouldn't actually need the ARM schema handling but I doubt it would hurt, either.  We could skip send it through the validation code.

**Comment by JHStarner** [comment]
It was because I had "deploymentTemplate.json" as the schema, which has worked just fine in the past. But I was trying to be more correct in my setup. So when I swapped to "deploymentParameters.json" for the schema, the language server didn't auto-switch back to JSON.

Looking at #546 do you think there is a lot of extra JSON stuff people would do in a Parameters template? I mean the files denote what schema, so shouldn't the schema denote the Language?

I am probably super oversimplifying. But just discussing. :)

**Comment by StephenWeatherford** [comment]
Ah, thanks for the info.  Azure ignores the schema when deploying, so it's more about letting the editing tools know how to behave, at least right now.

> Looking at #546 do you think there is a lot of extra JSON stuff people would do in a Parameters template? I mean the files denote what schema, so shouldn't the schema denote the Language?
More of an implementation issue.  If we change the lang id, then the default JSON functionality (Intellisense, errors, etc) from vscode stop working and we get to/have to provide it ourselves. This was important for template files because the default JSON functionality caused false positives for ARM, but not for param files.  Just need to make sure the language server can take these over if we switch langids.  Switching is not required for the additional features we add on top (completions, missing param errors etc).

**Comment by StephenWeatherford** [comment]
@JHStarner 
Added #754 (Switch back to JSON(C) automatically if arm-template langid used on a parameter file) to solve the problem in case others encounter it and don't know what to do.

**Comment by JHStarner** [comment]
Thanks!
