### ISSUE TITLE
non-actionable error when adding parameters to ill-formed template

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#710]
Does this occur consistently? Yes

**Repro steps:**

Note: Requires a build containing functionality specified in [issue 649](https://github.com/microsoft/vscode-azurearmtools/issues/649)

1. Create a parameter file / tempalte mapping.

2. Update the parameter file so that is matches this and save the file (note missing closing bracket):

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {}
```

3. Use light build to add parameters.

![image](https://user-images.githubusercontent.com/7844635/81868175-c5ea8b80-9526-11ea-917c-6666dcf3d10f.png)

**Issue:**

![image](https://user-images.githubusercontent.com/7844635/81868280-f16d7600-9526-11ea-92ed-8e20b1395424.png)

Action: azurerm-vscode-tools.codeAction.addMissingRequiredParameters
Error type: ERR_ASSERTION
Error Message: Cannot get a character index for a line index greater than the number of parsed lines (lineIndex: 4, lines parsed: 4).

Version: 0.10.0-alpha
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.fixed_ok [as assert] extension.bundle.js:1:69342
ParseResult.getCharacterIndex extension.bundle.js:1:86610
DeploymentParameters.getDocumentCharacterIndex extension.bundle.js:127:90347
DeploymentParameters.<anonymous> extension.bundle.js:1:567729
fulfilled extension.bundle.js:1:563926
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by jodavis** [comment]
Should be fixed in 0.12.0
