### ISSUE TITLE
expressionEvaluationOptions is not in completion list for nested template properties

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#714]
1) Use this template:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
    },
    "resources": [
        {
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2019-10-01",
            "name": "nestedTemplate1",
            "properties": {

            }
        }
    ]
}
```
2) Put cursor inside properties and hit CTRL+SPACE
!) completion list should include `expressionEvaluationOptions` but doesn't
![image](https://user-images.githubusercontent.com/6913354/81997664-526b7b80-9605-11ea-8e8e-5fbde857ee95.png)

**Comment by StephenWeatherford** [comment]
I assume an issue with the schema.

**Comment by neilpeterson** [comment]
Looks like the auto-gen process removed it from the schema. I will track down.

https://github.com/Azure/azure-resource-manager-schemas/commit/3eb617e26b6abed4923cbf346831731d7467a561#diff-2268fae0f09d027108277946cefd0f06

**Comment by neilpeterson** [comment]
Issue was raised against the Swagger repo, I will check in.

https://github.com/Azure/azure-rest-api-specs/issues/9486

**Comment by neilpeterson** [comment]
Internal work item for tracking - https://msazure.visualstudio.com/One/_workitems/edit/7403132

**Comment by MarcusFelling** [comment]
It looks like this was fixed in API version 2020-06-01:
![image](https://user-images.githubusercontent.com/6855361/103546724-12455b80-4e69-11eb-9556-5ac3c86e36a8.png)

**Comment by alex-frankel** [comment]
Yes I think @filizt took care of this

**Comment by filizt** [comment]
Right, the Resource Manager API version 2020-06-01 supports expressionEvaluationOptions property. Looks like the changes are reflected in the VS Code extension now. PR link for reference: https://github.com/Azure/azure-rest-api-specs/pull/11174/files

**Comment by StephenWeatherford** [comment]
@MarcusFelling Are you using a version of the extension with updated schema somehow?  I don't see this on my machine with main.

**Comment by StephenWeatherford** [comment]
@filizt

**Comment by StephenWeatherford** [comment]
@filizt That fixes it for 2020-06-01, but what about all the older versions that support it?  E.g. https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/scope-functions?tabs=azure-powershell shows it being used on a 2017 version.  How hard would it be to backport this fix?

We are going to change our snippets to use the new version, which will fix it for new templates, so if it's not easy, might not be worth doing.

**Comment by filizt** [comment]
> @filizt That fixes it for 2020-06-01, but what about all the older versions that support it? E.g. https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/scope-functions?tabs=azure-powershell shows it being used on a 2017 version. How hard would it be to backport this fix?
> 
> We are going to change our snippets to use the new version, which will fix it for new templates, so if it's not easy, might not be worth doing.

@StephenWeatherford unfortunately updating old versions require going through approval processes and it's not easy.  I'd recommend updating the templates to 2020-06-01 version.

**Comment by MarcusFelling** [comment]
That makes sense, the api's should be backwards compatible. Good to close @StephenWeatherford?
