### ISSUE TITLE
VS Code formatting should not format scriptContent object of Microsoft.Resources/deploymentScripts

### ISSUE THREAD

**Issue by yobyot** [microsoft/vscode-azurearmtools#717]
Hello,

I don't know if this is possible in the ARM extension for VS Code, but it would certainly be welcome if it were possible to _not_ format the script in the `scriptContent` object of `Microsoft.Resources/deploymentScripts` when the user selects the VS Code `FormatDocument` action (Option(Alt)-Shift-F).

As you can see from the attached .gif, doing so makes the PowerShell script highly unreadable since the line breaks inserted are arbitrary.

Thanks.

![DontFormatDeploymentScriptCode](https://user-images.githubusercontent.com/14332263/82161290-73340b00-9869-11ea-9199-4a9d4161ac3b.gif)

**Comment by neilpeterson** [comment]
Thanks @yobyot, understand the issue and we will look into it / prioritize where we can.

Looks like this issue is related - https://github.com/microsoft/vscode-azurearmtools/issues/435

**Comment by yobyot** [comment]
Thank you, @neilpeterson.

**Comment by neilpeterson** [comment]
@yobot thanks again for taking the time to open this issue. I am going to go ahead and close this and track the issue (multi-line string formatting) in https://github.com/microsoft/vscode-azurearmtools/issues/435.
