### ISSUE TITLE
listSecrets and generic list* functions not recognized

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurearmtools#72]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#list

**Comment by StephenWeatherford** [comment]
Adding listSecrets.  Others we'll add as people try to use them.

**Comment by PrashanthCorp** [comment]
Is there telemetry to record the usage of the other commands?

**Comment by StephenWeatherford** [comment]
#84
