### ISSUE TITLE
apiVersion stored in variable is not recognized

### ISSUE THREAD

**Issue by Michael-Kuritzky** [microsoft/vscode-azurearmtools#723]
We have a huge template file that creates an Azure Data Factory with many resources inside.
Since we need to specify `apiVersion` for each resource, and we didn't want to duplicate the value everywhere, we opted to store it in a `variable`:
```json
"variables": {
    "apiVersion": "2018-06-01"
}
```
Then we reference that variable in each resource, e.g.:
```json
"apiVersion": "[variables('apiVersion')]"
```

Unfortunately, this breaks the ARM extension's capabilities:
![image](https://user-images.githubusercontent.com/47433292/82557094-b6e18a00-9b73-11ea-8d14-40941add08a2.png)

(now it doesn't load typing suggestions, etc.)

**Comment by neilpeterson** [comment]
@Michael-Kuritzky thanks a bunch for taking the time to enter this issue and apologies that this is affecting you.

This is a known / duplicate issue that we intend on fixing. I am going to go ahead and close this issue and we can track here - https://github.com/microsoft/vscode-azurearmtools/issues/485 .

Thanks again.

**Comment by StephenWeatherford** [comment]
@Michael-Kuritzky BTW, note that we do currently support most apiProfiles, might be worth considering.
