### ISSUE TITLE
Please add code snippets for Azure Data Factory

### ISSUE THREAD

**Issue by Michael-Kuritzky** [microsoft/vscode-azurearmtools#728]
Please add code snippets for creating Azure Data Factories and their components (pipelines, triggers, datasets, etc.).
Thanks! :)

**Comment by neilpeterson** [comment]
Thanks for raising the issue @Michael-Kuritzky. We will take a look at this one resourcing / priroity allows.

**Comment by StephenWeatherford** [comment]
@Michael-Kuritzky Feel free to add the snippet as a contribution, or even just provide suggested content that would result from adding such a snippet, might help it happen quicker...  See https://github.com/microsoft/vscode-azurearmtools/blob/master/assets/armsnippets.jsonc.

**Comment by MarcusFelling** [comment]
@Michael-Kuritzky - Can you help me understand how you're using the extension with ADF? Are you authoring ARM templates for components that get added through the Azure Data Factory UI? If so, have you tried the [Git integration for ADF](https://docs.microsoft.com/en-us/azure/data-factory/source-control)? It will auto-generate the ARM templates for the factory.

**Comment by Michael-Kuritzky** [comment]
@MarcusFelling - we're authoring full, complex ADFs through ARM templates.
