### ISSUE TITLE
"9999-12-31T23:59:00Z" not parsing as valid ISO 8601 DateTime

### ISSUE THREAD

**Issue by vllama** [microsoft/vscode-azurearmtools#729]
I have a template with a setting ( which was exported from Azure Resource Manager btw.)
I  don't believe this warning is valid as that is a valid iso datetime as far as I can tell.  I'm not sure about the string type error.
```
{
	"resource": "/c:/Projects//powershell/ServicePlan-Template.json",
	"owner": "ARM Template Language Server diagnostics",
	"severity": 4,
	"message": "Value must conform to exactly one of the associated schemas\r\n|   Value must be a valid ISO 8601 datetime at #/resources/1/properties/siteConfig/requestTracingExpirationTime\r\n|   or\r\n|   Value must be one of the following types: string",
	"source": "arm-template (schema)",
	"startLineNumber": 138,
	"startColumn": 11,
	"endLineNumber": 138,
	"endColumn": 23
}
```

*Section from Template*

> 
>                 ...
>                 "numberOfWorkers": 1,
>                 "defaultDocuments": [],
>                 "netFrameworkVersion": "v4.0",
>                 "requestTracingEnabled": true,
>                 "requestTracingExpirationTime": "9999-12-31T23:59:00Z",
>                 "remoteDebuggingEnabled": false,
>                 "httpLoggingEnabled": true,
>                 "logsDirectorySizeLimit": 35,
>                 ...
> 
>

**Comment by neilpeterson** [comment]
Thanks for reporting this issue @vllama. Can you share the template and if not the resource type / apiVersion on which this is happening.

Thanks

**Comment by vllama** [comment]
Here is the template

**Comment by neilpeterson** [comment]
@vllama thanks for providing the template.

I am not seeing an issue on `requestTracingExpirationTime` however I do see a potential false positive on both resources with ` "type": "config"`. From what I understand `config` should be a valid type (when nested under Microsoft.Web/sites), however it seems that the schema validation is expecting a type of `Microsoft.Web/sites/config`.

Investigating.

**Comment by vllama** [comment]
This is what I see:
![image](https://user-images.githubusercontent.com/43180217/83338805-10f6f380-a2c8-11ea-9455-22f3bd2017f0.png)

**Comment by neilpeterson** [comment]
Thanks @vllama 

For reference, here is what I am seeing on both my Windows and Mac system.

Unmodified template:

![image](https://user-images.githubusercontent.com/7844635/83429616-20ba2900-a3e9-11ea-933a-a8849ac6ae21.png)

If I purposely invalidate the `requestTracingExpirationTime` value, I do see the issue. In the following example I have removed the trailing `z`.

![image](https://user-images.githubusercontent.com/7844635/83429735-552de500-a3e9-11ea-8bac-effbb72acdce.png)

@alexgav any thoughts why this would validate in my environments fine but not for @vllama ?

Thanks a bunch.

**Comment by StephenWeatherford** [comment]
@neilpeterson Are you using 0.10.0 or 0.10.1?  .1 has a new schema zip.

**Comment by neilpeterson** [comment]
0.10.0 in both environments.

**Comment by alexgav** [comment]
Hi @vllama, would you please share your date and time format settings in Windows, e.g. as described in https://www.windowscentral.com/how-change-date-and-time-formats-windows-10.
