### ISSUE TITLE
Consider adding quickstart templates to the snippet experience.

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#732]
Opening this issue to discuss the potential for adding templates from the quick start gallery to the ARM Tools snippet system. This is a customer request.

**Comment by StephenWeatherford** [comment]
For the first experience, I'd suggest instead providing an easy way for users to browse the quick starts and filter by keyword, then either take them to that location on github or open the file directly.

**Comment by nilshedstrom** [comment]
I like the suggestion from @StephenWeatherford that you can browse/search the Quickstart Templates. After the user selected template it would be nice if it would open in VS code (with the correct parameter file). 
An option to consider would be to merge the selected quickstart template with the current arm template and its parameters.
