### ISSUE TITLE
The highlight doesn't contain the final "}“ after inserting an item 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#736]
**OS:** Mac
**Build:** 20200528.2

**Repro Steps:**

1. Open a template file in VS Code.
2. Right click in editor --> Insert an item.
3. Check the result.

**Expect:**
The highlight contains the final "}“.

**Actual:**
The highlight doesn't contain the final "}“.
![image](https://user-images.githubusercontent.com/62053665/83240241-b1b3b900-a1cb-11ea-8f3f-e10989aa7dd6.png)

**Comment by StephenWeatherford** [comment]
We're not actually trying to highlight anything, we're placing the cursor (and therefore the selection) inside the value's expression so the user can start typing.  Ideally this would be a snippet, maybe we'll make that change sometime in the future.
