### ISSUE TITLE
[Suggestion] Add "." on the end of notification after sorting template

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#737]
**OS:** Mac/Win 10
**Build:** 20200528.2

**Repro Steps:**

1. Open a template file in VS Code. 
2. Sort from "ARM TEMPLATE OUTLINE" --> Click the sort icon.
3. Check the notification.

**Actual:**
There is no "." on the end of notification.
![image](https://user-images.githubusercontent.com/62053665/83242583-3a802400-a1cf-11ea-80d2-18dc158d590d.png)

**Suggestion:**
Add "." on the end of notification.

**Comment by StephenWeatherford** [comment]
Thanks for the suggestion.  I'm not sure there's a definite requirement for this, though, in practice I've seen it both ways.
