### ISSUE TITLE
[Unstable] There is no highlight on the left side of insert item

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#738]
**OS:** Mac/Win 10
**Build:** 20200528.2

**Repro Steps:**

1. Open a template file in VS Code.
2. Right click in editor --> Insert an item.
3. Check the result.

**Expect:**
There is a highlight on the left side of insert item.

**Actual:**
There is no highlight on the left side of insert item.
![image](https://user-images.githubusercontent.com/62053665/83243064-f5a8bd00-a1cf-11ea-8aa0-df8f95460330.png)

**Comment by StephenWeatherford** [comment]
Not sure what highlight you're expecting to see, but we don't control that, VS Code does.  The selection is in the correct place to start typing, so it seems like it's good.
