### ISSUE TITLE
[Unstable] There is no "sort icon" and "insert item icon"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#739]
**OS:** Mac/Win 10
**Build:** 20200528.2

**Repro Steps:**

1. Open a template file in VS Code.
2. Check the "ARM TEMPLATE OUTLINE".

**Expect:**
There is a "sort icon" and a "insert item icon", such as:
![image](https://user-images.githubusercontent.com/62053665/83247421-170ca780-a1d6-11ea-8234-a71627a743f6.png)

**Actual:**
There is no "sort icon" and "insert item icon". 
![image](https://user-images.githubusercontent.com/62053665/83247331-f6dce880-a1d5-11ea-99a4-1934e4653979.png)

**Comment by StephenWeatherford** [comment]
Do you see them when you hover over that item?  That's VS Code's intended behavior (I see the icons when hovering).

**Comment by v-mengwe** [comment]
Yes, I check them when I hover over that item, this issue is unstable.

**Comment by StephenWeatherford** [comment]
I'm sorry, I don't understand what you're seeing.  Here's a video of what I'm seeing.  This is the expected behavior. Are you seeing something different?
![icons](https://user-images.githubusercontent.com/6913354/83422746-d7fd7280-a3de-11ea-9daa-f00571347516.gif)

**Comment by v-mengwe** [comment]
Verified on the latest build 20200602.11, this issue is not reproduce, so close it.
