### ISSUE TITLE
Type 'microsoft.insights/workbooks' not recognized

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#749]
From the file posted in #672: [VM-cpuUsage.json.zip](https://github.com/microsoft/vscode-azurearmtools/files/4724787/VM-cpuUsage.json.zip)

```
    "resources": [
      {
        "name": "[parameters('workbookId')]",
        "type": "microsoft.insights/workbooks",
        "location": "[resourceGroup().location]",
```
Value must be one of the following values: "Microsoft.HealthcareApis/services", "Microsoft.AppConfiguration/configurationStores", "Microsoft.Genomics/accounts", "Microsoft.Network/FrontDoorWebApplicationFirewallPolicies", "Microsoft.Network/frontDoors", "Microsoft.Network/NetworkExperimentProfiles", "Microsoft.Network/NetworkExperimentProfiles/Experiments", "Microsoft.Network/frontDoors/rulesEngines", "Microsoft.Cache/Redis", "Microsoft.Cache/Redis/firewallRules", "Microsoft.Cache/Redis/linkedServers", "Microsoft.Cache/Redis/patchSchedules", "Microsoft.Search/searchServices", "Microsoft.AnalysisServices/servers", "Microsoft.RecoveryServices/vaults", "Microsoft.RecoveryServices/vaults/certificates", "Microsoft.RecoveryServices/vaults/extendedInformation", "Microsoft.DocumentDB/databaseAccounts", "Microsoft.DocumentDB/databaseAccounts/apis/databases", "Microsoft.DocumentDB/databaseAccounts/apis/databases/collections", "Microsoft.DocumentDB/databaseAccounts/apis/databases/containers", "Microsoft.DocumentDB/databaseAccounts/apis/databases/graphs", "Microsoft.DocumentDB/databaseAccounts/apis/keyspaces", "Microsoft.DocumentDB/databaseAccounts/apis/keyspaces/tables", "Microsoft.DocumentDB/databaseAccounts/apis/tables", "Microsoft.KeyVault/vaults/secrets", "Microsoft.KeyVault/vaults/accessPolicies", "Microsoft.DevTestLab/labs", "Microsoft.DevTestLab/labs/artifactsources", "Microsoft.DevTestLab/labs/customimages", "Microsoft.DevTestLab/labs/formulas", "Microsoft.DevTestLab/labs/policysets/policies", "Microsoft.DevTestLab/labs/schedules", "Microsoft.DevTestLab/labs/virtualmachines", "Microsoft.DevTestLab/labs/virtualnetworks", "Microsoft.RecoveryServices/vaults/replicationAlertSettings", "Microsoft.RecoveryServices/vaults/replicationFabrics", "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationNetworks/replicationNetworkMappings", "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers", "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationMigrationItems", "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectedItems", "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectionContainerMappings", "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationRecoveryServicesProviders", "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationStorageClassifications/replicationStorageClassificationMappings", "Microsoft.RecoveryServices/vaults/replicationFabrics/replicationvCenters", "Microsoft.RecoveryServices/vaults/replicationPolicies", "Microsoft.RecoveryServices/vaults/replicationRecoveryPlans", "Microsoft.DigitalTwins/digitalTwinsInstances", "Microsoft.DigitalTwins/digitalTwinsInstances/endpoints", "Microsoft.Web/certificates", "Microsoft.Web/serverfarms", "Microsoft.DomainRegistration/domains", "Microsoft.DomainRegistration/domains/domainOwnershipIdentifiers", "Microsoft.CertificateRegistration/certificateOrders", "Microsoft.CertificateRegistration/certificateOrders/certificates", "Microsoft.Web/csrs", "Microsoft.Web/sites", "Microsoft.Web/sites/config", "Microsoft.Web/sites/deployments", "Microsoft.Web/sites/domainOwnershipIdentifiers", "Microsoft.Web/sites/hostNameBindings", "Microsoft.Web/sites/hybridconnection", "Microsoft.Web/sites/hybridConnectionNamespaces/relays", "Microsoft.Web/sites/instances/deployments", "Microsoft.Web/sites/premieraddons", "Microsoft.Web/sites/publiccertificates", "Microsoft.Web/sites/slots", "Microsoft.Web/sites/slots/config", "Microsoft.Web/sites/slots/deployments", "Microsoft.Web/sites/slots/domainOwnershipIdentifiers", "Microsoft.Web/sites/slots/hostNameBindings", "Microsoft.Web/sites/slots/hybridconnection", "Microsoft.Web/sites/slots/hybridConnectionNamespaces/relays", "Microsoft.Web/sites/slots/instances/deployments", "Microsoft.Web/sites/slots/premieraddons", "Microsoft.Web/sites/slots/publiccertificates", "Microsoft.Web/sites/slots/virtualNetworkConnections", "Microsoft.Web/sites/slots/virtualNetworkConnections/gateways", "Microsoft.Web/sites/sourcecontrols", "Microsoft.Web/sites/slots/sourcecontrols", "Microsoft.Web/sites/virtualNetworkConnections", "Microsoft.Web/sites/virtualNetworkConnections/gateways", "Microsoft.Web/hostingEnvironments", "Microsoft.Web/hostingEnvironments/workerPools", "Microsoft.Web/hostingEnvironments/multiRolePools", "Microsoft.Web/serverfarms/virtualNetworkConnections/gateways", "Microsoft.Web/serverfarms/virtualNetworkConnections/routes", "Microsoft.Kusto/clusters", "Microsoft.Kusto/clusters/databases", "Microsoft.Kusto/clusters/databases/dataconnections", "Microsoft.Kusto/clusters/AttachedDatabaseConfigurations", "Microsoft.Kusto/clusters/dataConnections", "Microsoft.Kusto/clusters/principalAssignments", "Microsoft.Kusto/clusters/databases/principalAssignments", "Microsoft.Insights/alertrules", "Microsoft.Insights/components", "Microsoft.Insights/autoscalesettings", "Microsoft.Insights/webtests", "microsoft.visualstudio/account", "Microsoft.NotificationHubs/namespaces/notificationHubs", "Microsoft.NotificationHubs/namespaces/NotificationHubs/authorizationRules", "Microsoft.Network/trafficManagerProfiles", "Microsoft.Storage/storageAccounts", "Microsoft.Storage/storageAccounts/blobServices/containers", "Microsoft.Storage/storageAccounts/blobServices/containers/immutabilityPolicies", "Microsoft.Storage/storageAccounts/managementPolicies", "Microsoft.Storage/storageAccounts/blobServices", "Microsoft.Storage/storageAccounts/fileServices", "Microsoft.Storage/storageAccounts/fileServices/shares", "Microsoft.Storage/storageAccounts/privateEndpointConnections", "Microsoft.VMwareCloudSimple/dedicatedCloudNodes", "Microsoft.VMwareCloudSimple/dedicatedCloudServices", "Microsoft.VMwareCloudSimple/virtualMachines", "Microsoft.Compute/availabilitySets", "Microsoft.Compute/virtualMachines/extensions", "Microsoft.Compute/virtualMachineScaleSets", "Microsoft.KeyVault/vaults", "Microsoft.Scheduler/jobCollections", "Microsoft.NotificationHubs/namespaces", "Microsoft.NotificationHubs/namespaces/AuthorizationRules", "Microsoft.Compute/virtualMachines", "Microsoft.DataLakeStore/accounts", "Microsoft.DataLakeStore/accounts/firewallRules", "Microsoft.DataLakeStore/accounts/trustedIdProviders", "Microsoft.DataLakeAnalytics/accounts", "Microsoft.DataLakeAnalytics/accounts/dataLakeStoreAccounts", "Microsoft.DataLakeAnalytics/accounts/storageAccounts", "Microsoft.DataLakeAnalytics/accounts/firewallRules", "Microsoft.DataLakeAnalytics/accounts/computePolicies", "Microsoft.CognitiveServices/accounts", "Microsoft.PowerBI/workspaceCollections", "Microsoft.PowerBIDedicated/capacities", "Microsoft.DataCatalog/catalogs", "Microsoft.ContainerService/containerServices", "Microsoft.Network/dnszones", "Microsoft.Network/dnszones/A", "Microsoft.Network/dnszones/AAAA", "Microsoft.Network/dnszones/CNAME", "Microsoft.Network/dnszones/MX", "Microsoft.Network/dnszones/NS", "Microsoft.Network/dnszones/PTR", "Microsoft.Network/dnszones/SOA", "Microsoft.Network/dnszones/SRV", "Microsoft.Network/dnszones/TXT", "Microsoft.Cdn/profiles", "Microsoft.Cdn/profiles/endpoints", "Microsoft.Cdn/profiles/endpoints/customDomains", "Microsoft.Cdn/profiles/endpoints/origins", "Microsoft.Batch/batchAccounts", "Microsoft.Batch/batchAccounts/applications", "Microsoft.Batch/batchAccounts/applications/versions", "Microsoft.Batch/batchAccounts/certificates", "Microsoft.Batch/batchAccounts/pools", "Microsoft.Logic/workflows", "Microsoft.Logic/integrationAccounts", "Microsoft.Logic/integrationAccounts/agreements", "Microsoft.Logic/integrationAccounts/certificates", "Microsoft.Logic/integrationAccounts/maps", "Microsoft.Logic/integrationAccounts/partners", "Microsoft.Logic/integrationAccounts/schemas", "Microsoft.Logic/integrationAccounts/assemblies", "Microsoft.Logic/integrationAccounts/batchConfigurations", "Microsoft.Web/connections", "Microsoft.Web/connectionGateways", "Microsoft.Web/customApis", "Microsoft.Scheduler/jobCollections/jobs", "Microsoft.MachineLearning/webServices", "Microsoft.MachineLearning/commitmentPlans", "Microsoft.MachineLearning/workspaces", "Microsoft.MachineLearningServices/workspaces", "Microsoft.MachineLearningServices/workspaces/computes", "Microsoft.MachineLearningExperimentation/accounts", "Microsoft.MachineLearningExperimentation/accounts/workspaces", "Microsoft.MachineLearningExperimentation/accounts/workspaces/projects", "Microsoft.Automation/automationAccounts", "Microsoft.Automation/automationAccounts/runbooks", "Microsoft.Automation/automationAccounts/modules", "Microsoft.Automation/automationAccounts/certificates", "Microsoft.Automation/automationAccounts/connections", "Microsoft.Automation/automationAccounts/variables", "Microsoft.Automation/automationAccounts/schedules", "Microsoft.Automation/automationAccounts/jobs", "Microsoft.Automation/automationAccounts/connectionTypes", "Microsoft.Automation/automationAccounts/compilationjobs", "Microsoft.Automation/automationAccounts/configurations", "Microsoft.Automation/automationAccounts/jobSchedules", "Microsoft.Automation/automationAccounts/nodeConfigurations", "Microsoft.Automation/automationAccounts/webhooks", "Microsoft.Automation/automationAccounts/credentials", "Microsoft.Automation/automationAccounts/watchers", "Microsoft.Automation/automationAccounts/softwareUpdateConfigurations", "Microsoft.Automation/automationAccounts/sourceControls", "Microsoft.Automation/automationAccounts/sourceControls/sourceControlSyncJobs", "Microsoft.Automation/automationAccounts/python2Packages", "Microsoft.Media/mediaServices", "Microsoft.Media/mediaServices/accountFilters", "Microsoft.Media/mediaServices/assets", "Microsoft.Media/mediaServices/assets/assetFilters", "Microsoft.Media/mediaServices/contentKeyPolicies", "Microsoft.Media/mediaServices/liveEvents", "Microsoft.Media/mediaServices/liveEvents/liveOutputs", "Microsoft.Media/mediaServices/streamingEndpoints", "Microsoft.Media/mediaServices/streamingLocators", "Microsoft.Media/mediaServices/streamingPolicies", "Microsoft.Media/mediaServices/transforms", "Microsoft.Media/mediaServices/transforms/jobs", "Microsoft.Devices/IotHubs", "Microsoft.Devices/IotHubs/eventHubEndpoints/ConsumerGroups", "Microsoft.Devices/provisioningServices", "Microsoft.ServiceFabric/clusters", "Microsoft.ServiceFabric/clusters/applications", "Microsoft.ServiceFabric/clusters/applications/services", "Microsoft.ServiceFabric/clusters/applicationTypes", "Microsoft.ServiceFabric/clusters/applicationTypes/versions", "Microsoft.StorSimple/managers", "Microsoft.StorSimple/managers/accessControlRecords", "Microsoft.StorSimple/managers/bandwidthSettings", "Microsoft.StorSimple/managers/devices/alertSettings", "Microsoft.StorSimple/managers/devices/backupPolicies", "Microsoft.StorSimple/managers/devices/backupPolicies/schedules", "Microsoft.StorSimple/managers/devices/timeSettings", "Microsoft.StorSimple/managers/devices/volumeContainers", "Microsoft.StorSimple/managers/devices/volumeContainers/volumes", "Microsoft.StorSimple/managers/extendedInformation", "Microsoft.StorSimple/managers/storageAccountCredentials", "Microsoft.Authorization/locks", "Microsoft.Resources/deployments", "Microsoft.Solutions/applianceDefinitions", "Microsoft.Solutions/appliances", "Microsoft.ApiManagement/service", "Microsoft.ApiManagement/service/apis", "Microsoft.ApiManagement/service/apis/operations", "Microsoft.ApiManagement/service/apis/operations/policies", "Microsoft.ApiManagement/service/apis/operations/tags", "Microsoft.ApiManagement/service/apis/policies", "Microsoft.ApiManagement/service/apis/releases", "Microsoft.ApiManagement/service/apis/schemas", "Microsoft.ApiManagement/service/apis/tagDescriptions", "Microsoft.ApiManagement/service/apis/tags", "Microsoft.ApiManagement/service/authorizationServers", "Microsoft.ApiManagement/service/backends", "Microsoft.ApiManagement/service/certificates", "Microsoft.ApiManagement/service/diagnostics", "Microsoft.ApiManagement/service/diagnostics/loggers", "Microsoft.ApiManagement/service/groups", "Microsoft.ApiManagement/service/groups/users", "Microsoft.ApiManagement/service/identityProviders", "Microsoft.ApiManagement/service/loggers", "Microsoft.ApiManagement/service/notifications", "Microsoft.ApiManagement/service/notifications/recipientEmails", "Microsoft.ApiManagement/service/notifications/recipientUsers", "Microsoft.ApiManagement/service/openidConnectProviders", "Microsoft.ApiManagement/service/policies", "Microsoft.ApiManagement/service/products", "Microsoft.ApiManagement/service/products/apis", "Microsoft.ApiManagement/service/products/groups", "Microsoft.ApiManagement/service/products/policies", "Microsoft.ApiManagement/service/products/tags", "Microsoft.ApiManagement/service/properties", "Microsoft.ApiManagement/service/subscriptions", "Microsoft.ApiManagement/service/tags", "Microsoft.ApiManagement/service/templates", "Microsoft.ApiManagement/service/users", "Microsoft.ApiManagement/service/apis/diagnostics", "Microsoft.ApiManagement/service/api-version-sets", "Microsoft.ApiManagement/service/apiVersionSets", "Microsoft.ApiManagement/service/caches", "Microsoft.Compute/disks", "Microsoft.Compute/snapshots", "Microsoft.Compute/images", "Microsoft.ContainerRegistry/registries", "Microsoft.ContainerRegistry/registries/replications", "Microsoft.ContainerRegistry/registries/webhooks", "Microsoft.ContainerRegistry/registries/buildTasks", "Microsoft.ContainerRegistry/registries/buildTasks/steps", "Microsoft.ContainerRegistry/registries/tasks", "Microsoft.Insights/actionGroups", "Microsoft.Insights/activityLogAlerts", "Microsoft.Network/publicIPAddresses", "Microsoft.Network/virtualNetworks", "Microsoft.Network/loadBalancers", "Microsoft.Network/networkSecurityGroups", "Microsoft.Network/networkInterfaces", "Microsoft.Network/routeTables", "Microsoft.Network/applicationGateways", "Microsoft.Network/connections", "Microsoft.Network/localNetworkGateways", "Microsoft.Network/virtualNetworkGateways", "Microsoft.Network/virtualNetworks/subnets", "Microsoft.Network/virtualNetworks/virtualNetworkPeerings", "Microsoft.Sql/servers", "Microsoft.Sql/servers/advisors", "Microsoft.Sql/servers/administrators", "Microsoft.Sql/servers/auditingPolicies", "Microsoft.Sql/servers/backupLongTermRetentionVaults", "Microsoft.Sql/servers/communicationLinks", "Microsoft.Sql/servers/connectionPolicies", "Microsoft.Sql/servers/databases", "Microsoft.Sql/servers/databases/advisors", "Microsoft.Sql/servers/databases/auditingPolicies", "Microsoft.Sql/servers/databases/backupLongTermRetentionPolicies", "Microsoft.Sql/servers/databases/connectionPolicies", "Microsoft.Sql/servers/databases/dataMaskingPolicies", "Microsoft.Sql/servers/databases/dataMaskingPolicies/rules", "Microsoft.Sql/servers/databases/extensions", "Microsoft.Sql/servers/databases/geoBackupPolicies", "Microsoft.Sql/servers/databases/securityAlertPolicies", "Microsoft.Sql/servers/databases/transparentDataEncryption", "Microsoft.Sql/servers/disasterRecoveryConfiguration", "Microsoft.Sql/servers/elasticPools", "Microsoft.Sql/servers/firewallRules", "microsoft.insights/privateLinkScopes", "Microsoft.Insights/privateLinkScopes/privateEndpointConnections", "Microsoft.Insights/privateLinkScopes/scopedResources", "Microsoft.Sql/managedInstances", "Microsoft.Sql/servers/databases/auditingSettings", "Microsoft.Sql/servers/databases/syncGroups", "Microsoft.Sql/servers/databases/syncGroups/syncMembers", "Microsoft.Sql/servers/encryptionProtector", "Microsoft.Sql/servers/failoverGroups", "Microsoft.Sql/servers/keys", "Microsoft.Sql/servers/syncAgents", "Microsoft.Sql/servers/virtualNetworkRules", "Microsoft.Sql/managedInstances/databases", "Microsoft.Sql/servers/auditingSettings", "Microsoft.Sql/servers/databases/extendedAuditingSettings", "Microsoft.Sql/servers/securityAlertPolicies", "Microsoft.Sql/managedInstances/databases/securityAlertPolicies", "Microsoft.Sql/managedInstances/securityAlertPolicies", "Microsoft.Sql/servers/databases/vulnerabilityAssessments/rules/baselines", "Microsoft.Sql/servers/databases/vulnerabilityAssessments", "Microsoft.Sql/managedInstances/databases/vulnerabilityAssessments/rules/baselines", "Microsoft.Sql/managedInstances/databases/vulnerabilityAssessments", "Microsoft.Sql/servers/vulnerabilityAssessments", "Microsoft.Sql/managedInstances/vulnerabilityAssessments", "Microsoft.Sql/servers/dnsAliases", "Microsoft.Sql/servers/extendedAuditingSettings", "Microsoft.Sql/servers/jobAgents", "Microsoft.Sql/servers/jobAgents/credentials", "Microsoft.Sql/servers/jobAgents/jobs", "Microsoft.Sql/servers/jobAgents/jobs/executions", "Microsoft.Sql/servers/jobAgents/jobs/steps", "Microsoft.Sql/servers/jobAgents/targetGroups", "Microsoft.StreamAnalytics/streamingjobs", "Microsoft.StreamAnalytics/streamingjobs/functions", "Microsoft.StreamAnalytics/streamingjobs/inputs", "Microsoft.StreamAnalytics/streamingjobs/outputs", "Microsoft.StreamAnalytics/streamingjobs/transformations", "Microsoft.TimeSeriesInsights/environments", "Microsoft.TimeSeriesInsights/environments/eventSources", "Microsoft.TimeSeriesInsights/environments/referenceDataSets", "Microsoft.TimeSeriesInsights/environments/accessPolicies", "Microsoft.MachineLearningServices/workspaces/privateEndpointConnections", "Microsoft.ImportExport/jobs", "Microsoft.Network/dnsZones/CAA", "Microsoft.AzureStack/registrations", "Microsoft.AzureStack/registrations/customerSubscriptions", "Microsoft.Compute/virtualMachineScaleSets/extensions", "Microsoft.DBforMariaDB/servers", "Microsoft.DBforMariaDB/servers/configurations", "Microsoft.DBforMariaDB/servers/databases", "Microsoft.DBforMariaDB/servers/firewallRules", "Microsoft.DBforMariaDB/servers/virtualNetworkRules", "Microsoft.DBforMariaDB/servers/securityAlertPolicies", "Microsoft.DBforMySQL/servers", "Microsoft.DBforMySQL/servers/configurations", "Microsoft.DBforMySQL/servers/databases", "Microsoft.DBforMySQL/servers/firewallRules", "Microsoft.DBforMySQL/servers/virtualNetworkRules", "Microsoft.DBforMySQL/servers/securityAlertPolicies", "Microsoft.DBforPostgreSQL/servers", "Microsoft.DBforPostgreSQL/servers/configurations", "Microsoft.DBforPostgreSQL/servers/databases", "Microsoft.DBforPostgreSQL/servers/firewallRules", "Microsoft.DBforPostgreSQL/servers/virtualNetworkRules", "Microsoft.DBforPostgreSQL/servers/securityAlertPolicies", "Microsoft.Network/expressRouteCircuits/authorizations", "Microsoft.Network/expressRouteCircuits/peerings", "Microsoft.Network/networkSecurityGroups/securityRules", "Microsoft.Network/routeTables/routes", "Microsoft.Network/expressRouteCircuits", "Microsoft.Network/applicationSecurityGroups", "Microsoft.Network/ddosProtectionPlans", "Microsoft.Network/expressRouteCrossConnections", "Microsoft.Network/azureFirewalls", "Microsoft.Network/expressRouteCircuits/peerings/connections", "Microsoft.Network/expressRouteCrossConnections/peerings", "Microsoft.Network/loadBalancers/inboundNatRules", "Microsoft.Network/networkWatchers", "Microsoft.Network/networkWatchers/connectionMonitors", "Microsoft.Network/networkWatchers/packetCaptures", "Microsoft.Network/routeFilters", "Microsoft.Network/routeFilters/routeFilterRules", "Microsoft.Network/virtualHubs", "Microsoft.Network/virtualWans", "Microsoft.Network/vpnGateways", "Microsoft.Network/vpnGateways/vpnConnections", "Microsoft.Network/vpnSites", "Microsoft.Network/publicIPPrefixes", "Microsoft.Network/serviceEndpointPolicies", "Microsoft.Network/serviceEndpointPolicies/serviceEndpointPolicyDefinitions", "Microsoft.Network/ExpressRoutePorts", "Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies", "Microsoft.Network/bastionHosts", "Microsoft.Network/ddosCustomPolicies", "Microsoft.Network/expressRouteGateways", "Microsoft.Network/expressRouteGateways/expressRouteConnections", "Microsoft.Network/natGateways", "Microsoft.Network/networkInterfaces/tapConfigurations", "Microsoft.Network/networkProfiles", "Microsoft.Network/p2svpnGateways", "Microsoft.Network/privateEndpoints", "Microsoft.Network/privateLinkServices", "Microsoft.Network/privateLinkServices/privateEndpointConnections", "Microsoft.Network/virtualNetworkTaps", "Microsoft.Network/virtualWans/p2sVpnServerConfigurations", "Microsoft.Network/firewallPolicies", "Microsoft.Network/firewallPolicies/ruleGroups", "Microsoft.Network/virtualRouters", "Microsoft.Network/virtualRouters/peerings", "Microsoft.Network/vpnServerConfigurations", "Microsoft.Network/ipGroups", "Microsoft.Network/virtualHubs/routeTables", "Microsoft.Network/privateDnsZones", "Microsoft.Network/privateDnsZones/virtualNetworkLinks", "Microsoft.Network/privateDnsZones/A", "Microsoft.Network/privateDnsZones/AAAA", "Microsoft.Network/privateDnsZones/CNAME", "Microsoft.Network/privateDnsZones/MX", "Microsoft.Network/privateDnsZones/PTR", "Microsoft.Network/privateDnsZones/SOA", "Microsoft.Network/privateDnsZones/SRV", "Microsoft.Network/privateDnsZones/TXT", "Microsoft.Network/networkWatchers/flowLogs", "Microsoft.Network/connections/sharedkey", "Microsoft.Network/networkVirtualAppliances", "Microsoft.Network/IpAllocations", "Microsoft.Network/privateEndpoints/privateDnsZoneGroups", "Microsoft.Network/securityPartnerProviders", "Microsoft.DataMigration/services", "Microsoft.DataMigration/services/projects", "Microsoft.Insights/components/pricingPlans", "Microsoft.Consumption/budgets", "Microsoft.Insights/metricAlerts", "Microsoft.BatchAI/clusters", "Microsoft.BatchAI/fileServers", "Microsoft.BatchAI/jobs", "Microsoft.Insights/scheduledQueryRules", "Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers", "Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers/protectedItems", "Microsoft.RecoveryServices/vaults/backupPolicies", "Microsoft.RecoveryServices/vaults/backupstorageconfig", "Microsoft.RecoveryServices/vaults/backupFabrics/backupProtectionIntent", "Microsoft.ContainerInstance/containerGroups", "Microsoft.Compute/galleries", "Microsoft.Compute/galleries/images", "Microsoft.Compute/galleries/images/versions", "Microsoft.Compute/hostGroups", "Microsoft.Compute/hostGroups/hosts", "Microsoft.Compute/proximityPlacementGroups", "Microsoft.Compute/virtualMachineScaleSets/virtualmachines", "Microsoft.IoTCentral/IoTApps", "Microsoft.Maps/accounts", "Microsoft.BatchAI/workspaces", "Microsoft.BatchAI/workspaces/clusters", "Microsoft.BatchAI/workspaces/experiments", "Microsoft.BatchAI/workspaces/experiments/jobs", "Microsoft.BatchAI/workspaces/fileServers", "Microsoft.Insights/ProactiveDetectionConfigs", "Microsoft.ContainerService/managedClusters", "Microsoft.OperationalInsights/workspaces/savedSearches", "Microsoft.OperationalInsights/workspaces/storageInsightConfigs", "Microsoft.OperationalInsights/workspaces", "Microsoft.OperationalInsights/workspaces/dataSources", "Microsoft.OperationalInsights/workspaces/linkedServices", "Microsoft.OperationalInsights/clusters", "Microsoft.OperationsManagement/ManagementConfigurations", "Microsoft.OperationsManagement/solutions", "Microsoft.Peering/peerings", "Microsoft.Peering/peeringServices", "Microsoft.Peering/peeringServices/prefixes", "Microsoft.Peering/peerings/registeredAsns", "Microsoft.Peering/peerings/registeredPrefixes", "Microsoft.AAD/domainServices", "Microsoft.SignalRService/signalR", "Microsoft.NetApp/netAppAccounts", "Microsoft.NetApp/netAppAccounts/capacityPools", "Microsoft.NetApp/netAppAccounts/capacityPools/volumes", "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots", "Microsoft.StorSimple/managers/certificates", "Microsoft.StorSimple/managers/devices/backupScheduleGroups", "Microsoft.StorSimple/managers/devices/chapSettings", "Microsoft.StorSimple/managers/devices/fileservers", "Microsoft.StorSimple/managers/devices/fileservers/shares", "Microsoft.StorSimple/managers/devices/iscsiservers", "Microsoft.StorSimple/managers/devices/iscsiservers/disks", "Microsoft.Maps/accounts/privateAtlases", "Microsoft.ManagedIdentity/userAssignedIdentities", "Microsoft.HDInsight/clusters", "Microsoft.HDInsight/clusters/applications", "Microsoft.HDInsight/clusters/extensions", "Microsoft.Security/locations/jitNetworkAccessPolicies", "Microsoft.Security/pricings", "Microsoft.Security/securityContacts", "Microsoft.Security/workspaceSettings", "Microsoft.Security/autoProvisioningSettings", "Microsoft.Security/advancedThreatProtectionSettings", "Microsoft.Security/informationProtectionPolicies", "Microsoft.Migrate/assessmentProjects", "Microsoft.Migrate/assessmentProjects/groups", "Microsoft.Migrate/assessmentProjects/groups/assessments", "Microsoft.Migrate/assessmentProjects/hypervcollectors", "Microsoft.Migrate/assessmentProjects/vmwarecollectors", "Microsoft.ManagedServices/registrationAssignments", "Microsoft.ManagedServices/registrationDefinitions", "Microsoft.BareMetal/crayServers", "Microsoft.ContainerService/managedClusters/agentPools", "Microsoft.Authorization/policyAssignments", "Microsoft.Migrate/migrateProjects", "Microsoft.Migrate/migrateProjects/solutions", "Microsoft.ServiceBus/namespaces", "Microsoft.ServiceBus/namespaces/AuthorizationRules", "Microsoft.ServiceBus/namespaces/queues", "Microsoft.ServiceBus/namespaces/queues/authorizationRules", "Microsoft.ServiceBus/namespaces/topics", "Microsoft.ServiceBus/namespaces/topics/authorizationRules", "Microsoft.ServiceBus/namespaces/topics/subscriptions", "Microsoft.ServiceBus/namespaces/disasterRecoveryConfigs", "Microsoft.ServiceBus/namespaces/migrationConfigurations", "Microsoft.ServiceBus/namespaces/networkRuleSets", "Microsoft.ServiceBus/namespaces/topics/subscriptions/rules", "Microsoft.ServiceBus/namespaces/ipfilterrules", "Microsoft.ServiceBus/namespaces/virtualnetworkrules", "microsoft.visualstudio/account/extension", "microsoft.visualstudio/account/project", "Microsoft.EventHub/namespaces", "Microsoft.EventHub/namespaces/AuthorizationRules", "Microsoft.EventHub/namespaces/eventhubs", "Microsoft.EventHub/namespaces/eventhubs/authorizationRules", "Microsoft.EventHub/namespaces/eventhubs/consumergroups", "Microsoft.EventHub/namespaces/disasterRecoveryConfigs", "Microsoft.EventHub/namespaces/networkRuleSets", "Microsoft.EventHub/clusters", "Microsoft.EventHub/namespaces/ipfilterrules", "Microsoft.EventHub/namespaces/virtualnetworkrules", "Microsoft.Relay/namespaces", "Microsoft.Relay/namespaces/AuthorizationRules", "Microsoft.Relay/namespaces/HybridConnections", "Microsoft.Relay/namespaces/HybridConnections/authorizationRules", "Microsoft.Relay/namespaces/WcfRelays", "Microsoft.Relay/namespaces/WcfRelays/authorizationRules", "Microsoft.Web/sites/extensions", "Microsoft.Web/sites/functions", "Microsoft.Web/sites/functions/keys", "Microsoft.Web/sites/instances/extensions", "Microsoft.Web/sites/migrate", "Microsoft.Web/sites/networkConfig", "Microsoft.Web/sites/privateAccess", "Microsoft.Web/sites/siteextensions", "Microsoft.Web/sites/slots/extensions", "Microsoft.Web/sites/slots/functions", "Microsoft.Web/sites/slots/functions/keys", "Microsoft.Web/sites/slots/instances/extensions", "Microsoft.Web/sites/slots/networkConfig", "Microsoft.Web/sites/slots/privateAccess", "Microsoft.Web/sites/slots/siteextensions", "Microsoft.DataFactory/factories", "Microsoft.DataFactory/factories/datasets", "Microsoft.DataFactory/factories/integrationRuntimes", "Microsoft.DataFactory/factories/linkedservices", "Microsoft.DataFactory/factories/pipelines", "Microsoft.DataFactory/factories/triggers", "Microsoft.DataFactory/factories/dataflows", "Microsoft.EventGrid/topics", "Microsoft.EventGrid/eventSubscriptions", "Microsoft.EventGrid/domains", "Microsoft.EventGrid/domains/topics", "Microsoft.AppPlatform/Spring", "Microsoft.AppPlatform/Spring/apps", "Microsoft.AppPlatform/Spring/apps/bindings", "Microsoft.AppPlatform/Spring/apps/deployments", "Microsoft.Compute/diskEncryptionSets", "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/extensions", "Microsoft.VMwareVirtustream/privateClouds", "Microsoft.VMwareVirtustream/privateClouds/clusters", "Microsoft.WindowsESU/multipleActivationKeys", "Microsoft.Search/searchServices/privateEndpointConnections", "Microsoft.Synapse/workspaces", "Microsoft.Synapse/workspaces/administrators", "Microsoft.Synapse/workspaces/bigDataPools", "Microsoft.Synapse/workspaces/firewallRules", "Microsoft.Synapse/workspaces/managedIdentitySqlControlSettings", "Microsoft.Synapse/workspaces/sqlPools", "Microsoft.Synapse/workspaces/sqlPools/auditingSettings", "Microsoft.Synapse/workspaces/sqlPools/metadataSync", "Microsoft.Synapse/workspaces/sqlPools/schemas/tables/columns/sensitivityLabels", "Microsoft.Synapse/workspaces/sqlPools/securityAlertPolicies", "Microsoft.Synapse/workspaces/sqlPools/transparentDataEncryption", "Microsoft.Synapse/workspaces/sqlPools/vulnerabilityAssessments", "Microsoft.Synapse/workspaces/sqlPools/vulnerabilityAssessments/rules/baselines", "Microsoft.ResourceGraph/queries", "Sendgrid.Email/accounts", "Microsoft.Resources/links", "Microsoft.Authorization/roleAssignments", "Microsoft.Authorization/roleDefinitions"

**Comment by MarcusFelling** [comment]
Schema PR complete
