### ISSUE TITLE
There is no "sort icon" and "insert item icon" in "Functions/Parameters/Variables/Resources" items

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#759]
**OS:** Mac/Win 10
**Build:** 20200602.11

**Repro Steps:**

1. Open "udf1.json" template file in VS Code.
2. Check the "ARM TEMPLATE OUTLINE".

**Expect:**
There is a "sort icon" and a "insert item icon" in all items when hover over that item, such as:
![83422746-d7fd7280-a3de-11ea-9daa-f00571347516](https://user-images.githubusercontent.com/62053665/83730426-a35a1700-a67b-11ea-8a3b-0fac02a3b92d.gif)

**Actual:**
There is no "sort icon" and "insert item icon" in "Functions/Parameters/Variables/Resources" items.
![image](https://user-images.githubusercontent.com/62053665/83731348-eec0f500-a67c-11ea-8540-8cc748cc7635.png)

**More info:**
There is a "sort icon" and a "insert item icon" only in "outputs" item.
![image](https://user-images.githubusercontent.com/62053665/83731428-14e69500-a67d-11ea-83b9-d6d2873d62e2.png)

**Comment by StephenWeatherford** [comment]
@neilpeterson Do you see this?  i don't.

**Comment by neilpeterson** [comment]
Interesting, I cannot repo either. I've tested both 0.10.0 and a new build from source and see the sort item in the correct places.

![image](https://user-images.githubusercontent.com/7844635/83913740-c096f000-a724-11ea-9a35-a7c9636c12b6.png)

@v-mengwe, thanks a bunch for looking through the extension.

**Comment by StephenWeatherford** [comment]
Could you attach a video?  I use LiceCAP for that purpose.  Is it ipossible it depends on the versoin of vscode?

**Comment by neilpeterson** [comment]
I have tested again with 0.11.0 in both code and insiders and cannot repro. I suggest closing this issue with the _needs repro_ label and re-addressing once we have a repro. I will do so now, feel free to re-open if you disagree :).
