### ISSUE TITLE
Colourization not working beyond version 0.6

### ISSUE THREAD

**Issue by charec** [microsoft/vscode-azurearmtools#762]
If I update beyond version 0.6 I no longer get any colourization within my ARM template.

This is not true of others in my organization but we cannot what the difference is between our settings, they look the same.

Any help identifying what I need to change would be appreciated.

**Comment by neilpeterson** [comment]
Thanks for opening this issue.

What color theme are you using in VS Code. I have noticed that if using Dark (Visual Studio) or Light (Visual Studio) that colorization is not fully complete.

Can you also confirm that you have version 0.10.0 of the extension installed?

**Comment by charec** [comment]
Hello,

Thanks for getting back to me. I am using Dark+ (default dark).

When using version 0.10.0 I get no colourisation, I am currently using 0.6 which gives me colourisation on ARM template JSON files but not Blueprint JSON files. If I upgrade passed 0.6 It removes all colourisation.

Chris

**Comment by StephenWeatherford** [comment]
@charec That's weird, not a problem we've seen.  Can you first verify the language id being used?  It must be "Azure Resource Manager Template", in the bottom right-hand corner of vscode:
![image](https://user-images.githubusercontent.com/6913354/84089557-1fb66800-a9a4-11ea-9706-4219c7c99708.png)
You can click to change it.

If that's not it, two more things to try:
1) Uninstall the extension, then manually delete its folder (for Windows, C:\USERS\<username>\.vscode\extensions\msazurermtools.*
Restart vscode and reinstall the extension

2) F1 -> Developer: Inspect Editor Tokens and Scopes
Place the cursor inside an expression that you are expecting to be colorized and take a screenshot, e.g.:
![image](https://user-images.githubusercontent.com/6913354/84089793-c26ee680-a9a4-11ea-9c4e-ea61f7be167c.png)
That will tell me more about what's going on.

Stephen
