### ISSUE TITLE
There is no cursor in inserted portion

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#763]
**OS:** Mac/Win 10
**Build:** 20200604.33

**Repro Steps:**

1. Open a template file on VS Code.
2. Right click in editor --> Insert a parameter Item.
3. Check the result.

**Expect:**
The cursor will reveal in inserted portion.

**Actual:**
There is no cursor in inserted portion.
![image](https://user-images.githubusercontent.com/62053665/83848817-fea20d00-a740-11ea-908f-961c1df6b074.png)

**Comment by StephenWeatherford** [comment]
Good observation, but in this case there's nothing else for the user to enter, so it's good.
