### ISSUE TITLE
Support COPY blocks correctly for nested templates

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#776]
See https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/linked-templates#using-variables-to-link-templates

**Comment by StephenWeatherford** [comment]
@neilpeterson Can you see if there's anything for us to do here?  Thx.

**Comment by neilpeterson** [comment]
@StephenWeatherford 

To me it looks like things currently work. This template, with associated parameter file validates fine. I've used schema completions to add the copy block which also works good. 

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "resources": [
        {
            "name": "nestedDeployment1",
            "copy": {
                "name": "test",
                "count": 2
            },
            "type": "Microsoft.Resources/deployments",
            "apiVersion": "2019-10-01",
            "properties": {
                "expressionEvaluationOptions": {
                    "scope": "outer"
                },
                "mode": "Incremental",
                "template": {
                    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
                    "contentVersion": "1.0.0.0",
                    "parameters": {},
                    "variables": {},
                    "resources": [],
                    "outputs": {}
                }
            }
        }
    ]
}
```

We could add a snippet with tab stops for the copy block, however if doing so would want to think through how to nudge the consumer to add `copyIndex()` in the appropriate places.

Is this what you were looking for? Happy to keep digging if I am on the right path.

**Comment by StephenWeatherford** [comment]
Thanks!  Added the following to consider in refactorings story:

Blue Sky thinking
 "COPY-ize" a resource(s), etc. - convert single instance resource(s) into multiple instances
