### ISSUE TITLE
STORY: Template refactorings

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#787]
# Parameters/variables P1
- [ ] Extract to variable #515 P1
- [ ] Extract to parameter #515 P1
- [ ] Parameter -> variable P2
- [ ] Variable -> parameter P2

# Resources
Related: STORY: Show dependencies between resources #833
- [ ] Rename a resource (and fix up all dependsOn/resourceId references) P1
- [ ] Drag resources up/down in the tree, or move up/down in the template editor P2
- [ ] Sort by dependencies P2?
- [ ] Extract child resource from nested under parent to top level and vice versa P2
- [ ] Update api versions for all resources of a particular type, or maybe find/replace all resources with the same type and apiversion.  e.g. Change all storage accounts to this api version. P2??  (rethinking guidance of vars/params for api versions)

# Nested/linked templates
- [ ] Extract resources to nested/linked template (requires picking up referenced vars/params) P1
- [ ] Nested template <-> linked template
- [ ] Inner-scoped template <-> outer-scoped template P2?
- [ ] Inline nested/linked template into the template

# dependsOn
- [ ] convert from string (just name, full name in string, or full name with concat) -> resourceId reference P3
- [ ] convert the other direction?? P3

# User functions (P3)
- [ ] Extract to user function P3

# apiVersions P2
- [ ] Auto-fix: (change to newer api version that we support, or newest, or first newer version that we support)
- [ ] Auto-fix for all apiversions?

# Blue Sky thinking
- [ ] "COPY-ize" a resource(s), etc. - convert single instance resource(s) into multiple instances P1? (what's the algorithm?)
- [X] Can we do anything to help with resource dependencies?

**Comment by nilshedstrom** [comment]
Extract to variable and parameter is mentioned in #515 and initial implementation is done in https://github.com/nilshedstrom/vscode-azurearmtools/tree/extractVariableOrParameter

**Comment by StephenWeatherford** [comment]
Cool, may take me a couple days to get to looking at it, focused on shipping 0.11.0.
