### ISSUE TITLE
Json Outline pane doesn't use displayName tag

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vscode-azurearmtools#80]
If a resource has tags ➝ displayName, Visual Studio's JSON outline view would display this value in the outline view rather than the 'name' variable. It seems this extension just uses the 'name' variable here. This is particularly useful to make the outline more readable when all the names come from variables/parameters.

Could this be supported for more friendly display names in the JSON outline pane?

**Comment by StephenWeatherford** [comment]
Sounds like a good idea, thanks.  There was a similar request in #29 about having a setting.  Is there anything other than the displayName tag that you would want us to consider using?

**Comment by damienpontifex** [comment]
@StephenWeatherford maybe icons of the resource type? 

May not have to be exhaustive, but e.g. `"type": "Microsoft.Web/sites"` having a matching web app icon and a few things like this rather than the 'resource box' type icon.

**Comment by EricJizbaMSFT** [comment]
FYI @damienpontifex we just released an update that includes this fix (specifically the displayName stuff - the icon stuff is tracked by https://github.com/Microsoft/vscode-azurearmtools/issues/92)
