### ISSUE TITLE
There is no "Select/Create Parameter File…" in status bar after resetting global state

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#802]
**OS:** Windows 10
**Build Version:** 20200619.4

**Repro Steps:**
1. Open a template file and create a parameter file for it.
2. Remove the association with the parameter file (Select Parameter File... -> None -> Reset global extension state)
3. It will reload the VS Code -> Check the status bar

**Expect:**
There is a "Select/Create Parameter File..." in status bar.

**Actual:**
There is no "Select/Create Parameter File..." in status bar.
![image](https://user-images.githubusercontent.com/45614674/85117989-40a77480-b252-11ea-97d7-61d2bdc24ce6.png)

**Comment by StephenWeatherford** [comment]
I can't seem to repro.
![image](https://user-images.githubusercontent.com/6913354/85163964-7c254d00-b218-11ea-8a71-118005d55653.png)

For me, it took a few seconds before the status bar message came up, but it did come up every time.  If it's still reproing for you, does it get fixed if you change tabs, close/reopen the file, etc?
