### ISSUE TITLE
There is no error when inputting an invalid URI for "templateLink" 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#807]
**OS:** All
**Build Version:** 20200621.8

**Repro Steps:**
1. Create a linked template with following content.
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2019-10-01",
      "name": "linkedTemplate",
      "properties": {
        "mode": "Incremental",
        "templateLink": {
          "uri":"",
          "contentVersion":"1.0.0.0"
        }
      }
    }
  ],
  "outputs": {
  }
}
2. There is an error for it.
![Screen Shot 2020-06-22 at 5 29 49 PM](https://user-images.githubusercontent.com/45614674/85277711-6a60d580-b4b6-11ea-8725-554b36c28a16.png)
3. Input an invalid URI "test" and check the result.

**Expect:**
There is an error "Incorrect URI".

**Actual:**
There is no error.
![Screen Shot 2020-06-22 at 5 30 13 PM](https://user-images.githubusercontent.com/45614674/85278134-199dac80-b4b7-11ea-8058-4364a62b402b.png)

**Comment by StephenWeatherford** [comment]
Thanks for entering.  We're doing work for linked template validation for the next release, and that should show errors for any URI that is not able to be downloaded, including this.
