### ISSUE TITLE
The completion list icon is inconsistent between "Ctrl+Space" and press "tab" to move the tab stops

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#808]
**OS:** Win10
**Build Version:** 20200621.8

**Repro Steps:**

1. Open a template file in VS Code.
2. F1 --> Type and select "Insert Item..." --> Select "Resource" --> Select "Application Gateway".
3. Press "tab" to move between the tab stops.

	
**Expect:**
The completion list icon is consistent between "Ctrl+Space" and press "tab" to move the tab stops.

**Actual:**
The completion list icon is inconsistent between "Ctrl+Space" and press "tab" to move the tab stops.
![image](https://user-images.githubusercontent.com/62053665/85277012-3e912000-b4b5-11ea-894c-388f11c0e87d.png)

**Comment by StephenWeatherford** [comment]
Good catch.  Unfortunately there's nothing I can do about this without (probably non-trivial) changes in the webtools code.
