### ISSUE TITLE
Save dialog for arm-template files should suggest saving with JSON extension like json files do

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#809]
**OS:** Win10
**Build Version:** 20200621.8

**Repro Steps:**

1. File --> Select "New File" --> Select Language Mode "JSON“.
2. Copy/paste the following into the editor:
 { "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#", 
	    "variables": { "appInsName": "appIniCheck", "responseAlertName": "[concat('ResponseTime-', toLower(variables('appInsName')))]" },
 	    "resources": [ { "apiVersion": "2014-04-02", "name": "[variables('appInsName')]", "type": "Microsoft.Insights/components", "location": "[parameters('location')]", "properties": {
 	                "ApplicationId": "[variables('appInsName')]"
             } } ] }
8. Save this json file by "Ctrl+s".

**Actual:**
File type is recognized as txt format.
![image](https://user-images.githubusercontent.com/62053665/85278664-d1cb5500-b4b7-11ea-8a72-574ce112fc46.png)

**Suggestion:**
File type is recognized as json format will be better.

**More info:**
File type is recognized as json format if it is an empty file.

**Comment by StephenWeatherford** [comment]
Weird.

**Comment by StephenWeatherford** [comment]
Doesn't appear to be a way I can do this.  Created vscode bug: https://github.com/microsoft/vscode/issues/102438
