### ISSUE TITLE
Invalid location given for error when resource name evaluates to empty string

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#816]
[Archive.zip](https://github.com/microsoft/vscode-azurearmtools/files/4822330/Archive.zip)
1) Open attached JSON, attach to attached params file
!) 
EXPECTED: Error with line/col info
ACTUAL: 
{
	"resource": "/Users/stephwe/Downloads/bug.json",
	"owner": "ARM Template Language Server diagnostics",
	"severity": 8,
	"message": "Template validation failed: The template resource '' at line '<null>' and column '<null>' is not valid. The name property cannot be null or empty. Please see https://aka.ms/arm-template/#resources for usage details.",
	"source": "arm-template (validation)",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

**Comment by johnwildes** [comment]
This is what I get ... 
![image](https://user-images.githubusercontent.com/1375512/85875973-aa67d700-b79a-11ea-8d19-f6d68c5ef987.png)

Hard to use something that consistently fails like this.

**Comment by StephenWeatherford** [comment]
@johnwildes What other types of failures are you seeing?  Thanks.

**Comment by johnwildes** [comment]
@StephenWeatherford This is is the only one that happens with every template.

**Comment by jorgecotillo** [comment]
I was able to identify the issue and working on fixing it, will submit a PR on the engine repo soon.

**Comment by StephenWeatherford** [comment]
testWithLanguageServer(`Invalid location given for error when resource name evaluates to empty string #816`, async () =>
