### ISSUE TITLE
Error:  Action: startArmLanguageServer

### ISSUE THREAD

**Issue by akopitsa** [microsoft/vscode-azurearmtools#822]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.11.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:393:92108
Object.<anonymous> extension.bundle.js:484:768397
fulfilled extension.bundle.js:484:767293
```

</details>

**Comment by StephenWeatherford** [comment]
@akopitsa Thanks for reporting.  Did the instructions at https://aka.ms/vscode-armtools-dotnet help?
