### ISSUE TITLE
Problem with auto populate

### ISSUE THREAD

**Issue by Cairn23** [microsoft/vscode-azurearmtools#823]
I am new to the tool and installed the latest version. 
In the video it shows in the properties section Quotes are inserted and the list of properties are then display to select.
I cannot get this to operate with latest studio code and ARM tools v 0.11.0

**Comment by StephenWeatherford** [comment]
@Cairn23 Right now this is supported only from a parameter file.  You first need to associated it with the template file:
1) open the template file
2) You should see a "code lens" above the "properties" section in the template file:
![image](https://user-images.githubusercontent.com/6913354/86415600-6b46f380-bc7c-11ea-9a07-5e95422fca8a.png)
3) Click it and select your parameter file
4) Go to the parameter file and type double quote inside the "parameters section"
5) You should now see "new-parameter-value" plus an entry for every 
![image](https://user-images.githubusercontent.com/6913354/86415746-cb3d9a00-bc7c-11ea-9986-dce5c918de1b.png)

**Comment by StephenWeatherford** [comment]
Whoops, didn't mean to close.

**Comment by Cairn23** [comment]
Sorry but this is not the problem. if you watch the video stream you will see that when the person goes to the properties section of the newly created resource they add "", at which point a selection of the proprieties that can be used with the Web Site is displayed and the user selected https

**Comment by StephenWeatherford** [comment]
@Cairn23 Sorry, my bad.  I don't see a video showing an https selection in our README, if that's what you meant.  Could you provide a portion of the template file with instructions on what you're trying to do so that we can try to help you?  Thanks!

**Comment by Cairn23** [comment]
The video image is running on the visual code installation instruction and on the project code github page https://github.com/microsoft/vscode-azurearmtools . I was just following the same pattern as the video in that you create a new json file, then create a Web app, setup variables, and then under the web app properties set a httpsonly property as true. No in the video once the quotes are added a list of possible propeties to set are displayed in a drop down, but when I attempt this no dropdown is offered

**Comment by StephenWeatherford** [comment]
Some questions:
1. Can you verify the status bar indicates "Azure Resource Manager Template"?
<img width="362" alt="image" src="https://user-images.githubusercontent.com/6913354/86844405-dcabeb00-c05c-11ea-9e28-2700cb4791e2.png">
2. If you type CTRL+SPACE, does the completion dropdown come up?
3. If still no, can you go to the output panel, and choose .NET Core Tooling and also Azure Resource Manager Tools, and copy the text from those two?  
Thx.

**Comment by Cairn23** [comment]
The status bar is the same as you have. 
I tried CTRL+SPACE, but it does not have the possible option of properties, instead the list of options are the more resource type based, so do not understand where it's getting it's list of properties options from.

**Comment by StephenWeatherford** [comment]
Could you please also do number 3?  I'm looking for possible errors, especially from the language server, which handles the dropdowns for schema-related Intellisense.  If you'd like, we could try a team meeting so I can see exactly what's happening.

**Comment by Cairn23** [comment]
This is the output that I get

Using dotnet core executable at c:\Users\graha\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\3.1.5\dotnet.exe
Starting ARM Template Language Server at c:\Users\graha\.vscode\extensions\msazurermtools.azurerm-vscode-tools-0.11.0\languageServer\Microsoft.ArmLanguageServer.dll
Language server nuget version: 3.0.0-preview.20319.5
Client options:
{
  "documentSelector": [
    {
      "language": "arm-template",
      "scheme": "file"
    },
    {
      "language": "arm-template",
      "scheme": "untitled"
    }
  ],
  "diagnosticCollectionName": "ARM Template Language Server diagnostics",
  "outputChannel": {
    "outputChannel": {
      "name": "Azure Resource Manager Tools",
      "extensionPrefix": "azureResourceManagerTools",
      "_outputChannel": {
        "name": "Azure Resource Manager Tools",
        "_channel": {}
      }
    }
  },
  "revealOutputChannelOn": 3,
  "synchronize": {
    "configurationSection": "azureResourceManagerTools"
  }
}
Server options:
{
  "run": {
    "command": "c:\\Users\\graha\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-dotnettools.vscode-dotnet-runtime\\.dotnet\\3.1.5\\dotnet.exe",
    "args": [
      "c:\\Users\\graha\\.vscode\\extensions\\msazurermtools.azurerm-vscode-tools-0.11.0\\languageServer\\Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  },
  "debug": {
    "command": "c:\\Users\\graha\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-dotnettools.vscode-dotnet-runtime\\.dotnet\\3.1.5\\dotnet.exe",
    "args": [
      "c:\\Users\\graha\\.vscode\\extensions\\msazurermtools.azurerm-vscode-tools-0.11.0\\languageServer\\Microsoft.ArmLanguageServer.dll",
      "--logLevel",
      "Warning"
    ],
    "options": {
      "shell": false
    }
  }
}

**Comment by StephenWeatherford** [comment]
I'm stumped.  The only two suggestions I have are:
1) try uninstalling/reinstalling the extension
2) can we do a Teams, Skype or other share-screen consultation?

**Comment by StephenWeatherford** [comment]
One other possibility I just stumbled on.  What $schema value are you using?  Best is the new one:
```
"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#"
```

Turns out if you're using http instead of https, schema Intellisense doesn't work (like you're seeing) - #834

**Comment by Cairn23** [comment]
I have done a re-install which had no effect. 
I then started another project, but noticed the schema version is not the latest version, and things now work as expected. 
Not quite sure why it now picks up the latest schema as I only first installed this a couple of weeks ago, and auto schema update has always been tuned on

**Comment by StephenWeatherford** [comment]
Perhaps you had answered "No" at some point to the dialog?  That gets saved.  

At any rate, from your comments it appears this is now working, so I'll close. We'll fix the http vs https issue so hopefully no one else hits it.  Thanks!
