### ISSUE TITLE
VS Code flags partial expressions as incorrect...

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/vscode-azurearmtools#828]
If I have an expression without a closing bracket, we flag it as an invalid expression... but in ARM it's a valid string property.  For example

"defaultValue": "[newGuid()"

Is a valid property value that will evaluate literally in ARM - but we throw a squiggly.

Most of the time this is likely correct (i.e. it's a mistake) so I don't know that we should simply remove it... but could evaluate the string for valid expressions before throwing that error.  The flip side is then we would not be able to evaluate valid expressions because we're not in expression mode...

So not 100% certain we need a change here (or what it would be) but something to think about.

**Comment by StephenWeatherford** [comment]
Tracked by #900
