### ISSUE TITLE
Validation error with resourceGroup() tags when using parameter file

### ISSUE THREAD

**Issue by anlau** [microsoft/vscode-azurearmtools#831]
Following minimal ARM template produces an error when using a parameter file:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {
        "someTag": "[resourceGroup().tags['SomeTag']]"
    },
    "resources": [],
    "outputs": {}
}
```

![image](https://user-images.githubusercontent.com/4398546/87039366-0e3bc800-c1bd-11ea-911e-3a8098a65985.png)

> Template validation failed: The template variable 'someTag' is not valid: The language expression property 'tags' doesn't exist, available properties are 'id, name, type, location, properties'.. Please see https://aka.ms/arm-template-expressions for usage details.arm-template (validation)

Reproducible with an empty parameter file:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
    }
}
```

Everything is fine when no parameter file is specified.

Extension v0.11.0
VS Code 1.46.1
W10

**Comment by StephenWeatherford** [comment]
This is fixed when within a nested template.

**Comment by jorgecotillo** [comment]
Fix has been pushed, waiting to be merged
