### ISSUE TITLE
filename.json does not appear to be an Azure Resource Manager deployment template file

### ISSUE THREAD

**Issue by turagittech** [microsoft/vscode-azurearmtools#838]
Does this occur consistently? Yes
Repro steps:

1. Right click in Parameter section of ARM Template file and select Create Parameter File
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: "c:\Users\userrname\source\repos\DataPlatform\dataFactoryDeploy.json" does not appear to be an Azure Resource Manager deployment template file.

Version: 0.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:3:349982
fulfilled extension.bundle.js:3:347122
```

</details>

**Comment by StephenWeatherford** [comment]
@turagittech  What's the encoding on the file?  We had seen this on files with a UTF-8 encoding, but that should be fixed in 0.11.0.

**Comment by xtrc** [comment]
I'm also experiencing the same issue. File is using UTF-8 encoding and I'm using extension version 0.11.0.

**Comment by StephenWeatherford** [comment]
@xtrc/@turaggittech Can you tell me what steps you are taking when the errors occurs?  I haven't been able to repro this.  Thanks!

**Comment by hollowpnt92** [comment]
I was receiving this error as well on OSX Catalina with visual studio code. 

My issue was that Visual Studio Code was in my downloads folder and not in applications. I realize that intial poster was on windows but I had the same error if anyone finds this post on OSX.

**Comment by StephenWeatherford** [comment]
@hollowpnt92 Just tried it on Catalina with VSCode in my downloads folder and couldn't repro.  Are you saying the error went away when you move it to Applications?  Thanks!

**Comment by hollowpnt92** [comment]
Yes the error went away once I moved it from my downloads folder to my application folder. This could have also stemmed from the permissions on my downloads folder

**Comment by StephenWeatherford** [comment]
I think maybe I finally figured out the scenario...
1) create new file
2) save as .json file (while the file is still empty)
3) Use "arm!" snippet or copy a template from elsewhere
4) Before saving the file, attempt to select/create a parameter file

In this scenario, I see the bug.  Is that what you guys did?  Thanks!

**Comment by hollowpnt92** [comment]
Yes! That is exactly what I did

**Comment by StephenWeatherford** [comment]
@hollowpnt92 Great, then it should be fixed in the next release. Thanks much!
