### ISSUE TITLE
this is why nobody submits reports

### ISSUE THREAD

**Issue by jmstrupp-psjh** [microsoft/vscode-azurearmtools#842]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'Untitled-6'

Version: 0.11.0
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

**Comment by StephenWeatherford** [comment]
@jmstrupp-psjh Thanks for taking the time to report this.  I just put in a fix for this about half an hour ago (https://github.com/microsoft/vscode-azurearmtools/issues/666), should be in the next release.

Could you please elaborate on why it is that nobody submits reports?  Thanks!  

cc @neilpeterson

**Comment by StephenWeatherford** [comment]
@neilpeterson You think he's referring to the need to join github first?

**Comment by neilpeterson** [comment]
I'm not sure. @jmstrupp-psjh can you elaborate? We want to understand but do not have enough context. 

As the fix to the issue has been completed, we will go ahead and close this out, but please get back with us in regards to your sentiment on opening issue for this project.

Thanks
