### ISSUE TITLE
Refactor and remove use of ArmSnippits.jsonc

### ISSUE THREAD

**Issue by Cairn23** [microsoft/vscode-azurearmtools#844]
The current working rely on the armsnippits.jsonc in order to formulate the basic template for the user to populate. The problem I see with this is that it's possible to then get out of sync with the scheme's. Would it not be better to only utilise the schema and the resource definitions. from my reading to date the convention to date is that if the definition name does not include and underscore its a piece of Azure compute that can be deployed. Those with the underscore are sub components .
eg in the Microsoft.web.json you have a Sites definition, than all the sub components are names sites_***.
Therefore from this you should be able to build as required, and also remove the dependency on the code snippets

**Comment by neilpeterson** [comment]
Thanks for opening this issue @cairn23. Are you suggesting that instead of using the static *armsnippets.jsonc* for providing snippet services we use something that dynamically creates snippets fro arm schemas?

We are considering what to do next with snippets, which may include a refactoring of the snippet source. Details / dicssion can be found in this issue: https://github.com/microsoft/vscode-azurearmtools/issues/748

**Comment by Cairn23** [comment]
That's correct. It should be possible to create the required code from the schema's. 
My thinking is that upon starting the tool, the schemas are loaded forming some form of map, and the key is the template type. when a user then creates a completely blank template, and adds a resource, the map is then used to form the dropdown of options. Once a compute type is selected it will then form the rest of the template resource contents. We have seen that its possible to do bits of this already as when you  attempt to add a property  the schemas are used for this, so this in effect making the whole think dynamic and will also require less support as it is possible the schema could change which will not match the snippets

**Comment by StephenWeatherford** [comment]
We've discussed automatically generating snippets from schema, but it's not as simple as it sounds.  It would work in many cases but will probably yield poor results in many others. It would still be nice to have the option available for ones we don't have more specific snippets for.

@alexgav How much work do you think that would be?  And how successful do you think it would be?

**Comment by Cairn23** [comment]
The schema should be the definition of whats is possible, so would be good to understand why you think it will yield poor results, unless you are indicating there are problems with the schemas

**Comment by neilpeterson** [comment]
Adding some notes / thoughts for discussion.

Template reference documentation is created using autorest and the [azureresourceschema](https://github.com/Azure/autorest.azureresourceschema) plugin. Perhaps we can investigate this method for auto-generating snippets.

That said, some considerations:

### Terseness

Consider is the verbosity / terseness of auto-generated snippets. For example, take a look at the auto-generated snippet in [this doc](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters) vs. the current snippet. 

```
        {
            "name": "aksCluster1",
            "type": "Microsoft.ContainerService/managedClusters",
            "apiVersion": "2020-02-01",
            "location": "[resourceGroup().location]",
            "properties": {
                "kubernetesVersion": "1.15.7",
                "dnsPrefix": "dnsprefix",
                "agentPoolProfiles": [
                    {
                        "name": "agentpool",
                        "count": 2,
                        "vmSize": "Standard_A1",
                        "osType": "Linux",
                        "storageProfile": "ManagedDisks"
                    }
                ],
                "linuxProfile": {
                    "adminUsername": "adminUserName",
                    "ssh": {
                        "publicKeys": [
                            {
                                "keyData": "keyData"
                            }
                        ]
                    }
                },
                "servicePrincipalProfile": {
                    "clientId": "servicePrincipalAppId",
                    "secret": "servicePrincipalAppPassword"
                }
            }
        }
``` 

I have spoken with many customers about this and preference is to start terse and layer on optional properties as desired. However on the flip side, we have received significant feedback on snippet coverage, autogenerated / verbose snippets may be a compromise.

### Tab stops

Would we be able to intelligently add tab stops ideally with potential values? I do not use them much myself but they do add a nice polish.

### Resource generalization

One of the things I'm keen on doing is adding some resource generalization. For example, if I add a storage account .via a snippet would I also add and reference a parameter for the name. This may be the same discussion as tab stops, but want to point out the specific feature.

**Comment by StephenWeatherford** [comment]
Other considerations:
# Best practices
Just filling in the available properties may not yield a resource with best practices
# Multiple-resource snippets
Quite a few of our snippets create multiple resources


That said, I've never liked being in the business of owning snippets for other teams.

**Comment by jodavis** [comment]
We're tracking this as part of a larger Snippets effort, #748
