### ISSUE TITLE
Insert Item and Insert Resource should consider scoped deployments and schema 

### ISSUE THREAD

**Issue by rchaganti** [microsoft/vscode-azurearmtools#845]
When using a subscription level deployment, only [a few resource types are supported](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-subscription). However, selecting insert item and choosing resource or choosing Insert Resource within the template outline, all resource types are listed. Filtering this list to what is supported based on the schema would be relevant and useful.

**Comment by neilpeterson** [comment]
Thanks for opening this issue @rchaganti, totally agree. We are discussing / planning updates for snippets which includes contextualization for scoped deployments (work item below). This work will ideally also apply when using the inset item feature.

https://github.com/microsoft/vscode-azurearmtools/issues/748

**Comment by StephenWeatherford** [comment]
I'm working on contextualization based on position right now.  I guess I need to do the work soon to get the list of types so we don't have to filter based on deployment scope manually.

**Comment by MarcusFelling** [comment]
@bhsubra FYI - we will want this in Bicep for snippets
