### ISSUE TITLE
Error "Does not appear to be an Azure Resource Manager deployment template file"

### ISSUE THREAD

**Issue by aaukhan** [microsoft/vscode-azurearmtools#848]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: "c:\Users\Aman\Documents\aaudeploy.json" does not appear to be an Azure Resource Manager deployment template file.

Version: 0.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:3:349982
fulfilled extension.bundle.js:3:347122
```

</details>

**Comment by StephenWeatherford** [comment]
@aaukhan What's the encoding of your file? You can tell from the status bar:
![image](https://user-images.githubusercontent.com/6913354/87459193-edf67980-c5bf-11ea-81c5-cb7acf7d6e16.png)

**Comment by aaukhan** [comment]
Thanks for your reply.
Issue resolved

**Comment by StephenWeatherford** [comment]
@aaukhan  Thanks!  Could you tell me how you resolved it?  I want to make sure the issue doesn't occur again for others.

**Comment by aaukhan** [comment]
UTF-8 wasn't selected

**Comment by StephenWeatherford** [comment]
Tracked by #838, fixed in next release.  BTW, you can work around it by saving the template file before creating a parameter file.
