### ISSUE TITLE
Unusual issue on one of the macs

### ISSUE THREAD

**Issue by debanjanbasu** [microsoft/vscode-azurearmtools#849]
Does this occur consistently? 
Repro steps:

1.
2.

Action: Language Server Error
Error type: Error
Error Message: The connection to the ARM Template Language Server got closed.

Version: 0.11.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code - Insiders
Product Version: 1.48.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:484:769370
Object.callWithTelemetryAndErrorHandlingSync extension.bundle.js:3:192205
WrappedErrorHandler.closed extension.bundle.js:484:769238
LanguageClient.handleConnectionClosed vscode-languageclient/client.js:2044:55
LanguageClient.handleConnectionClosed vscode-languageclient/main.js:127:15
closeHandler vscode-languageclient/client.js:2023:18
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
closeHandler vscode-jsonrpc/main.js:226:26
CallbackList.invoke vscode-jsonrpc/events.js:62:39
Emitter.fire vscode-jsonrpc/events.js:120:36
StreamMessageReader.fireClose vscode-jsonrpc/messageReader.js:111:27
Socket.<anonymous> vscode-jsonrpc/messageReader.js:151:46
Socket.emit events.js:215:7
Pipe.<anonymous> net.js:658:12
```

</details>

**Comment by StephenWeatherford** [comment]
@debanjanbasu Could you please copy in the text from the Output window for Azure Resource Manager Template when the error occurs?
<img width="784" alt="image" src="https://user-images.githubusercontent.com/6913354/87610114-43fb1800-c6b9-11ea-9d8b-8a009f89eb01.png">
Thanks!
