### ISSUE TITLE
Error while creating parameter file

### ISSUE THREAD

**Issue by sanjayntms** [microsoft/vscode-azurearmtools#852]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: "f:\vsc\azuredeploy.json" does not appear to be an Azure Resource Manager deployment template file.

Version: 0.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:3:349982
fulfilled extension.bundle.js:3:347122
```

</details>

**Comment by StephenWeatherford** [comment]
Been trying to find out how to reproduce this bug (see #838).  Are these the steps you took?

1) create new file
2) save as .json file (while the file is still empty)
3) Use "arm!" snippet or copy a template from elsewhere
4) Before saving the file, attempt to select/create a parameter file

Thanks!

**Comment by StephenWeatherford** [comment]
This should be fixed in the next release.
