### ISSUE TITLE
Does not appear to be an Azure Resource Manager deployment template file.

### ISSUE THREAD

**Issue by robnotto** [microsoft/vscode-azurearmtools#857]
Does this occur consistently? 
Repro steps:

1. Create file new file named azuredeploy.json
2. copy quick start data from github
3. 'select or create a parameter file to enable full validation'

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: "c:\Users\robnotto\git\AppGWv2\azuredeploy.json" does not appear to be an Azure Resource Manager deployment template file.

Version: 0.11.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:3:349982
fulfilled extension.bundle.js:3:347122
```

</details>

**Comment by StephenWeatherford** [comment]
Thanks for taking the time to enter this.  This is being tracked by #848 and has been fixed for the next release.  To work around it, please make sure you save the template file being creating a parameter file.  Thanks!
