### ISSUE TITLE
problem in ARM template creation

### ISSUE THREAD

**Issue by meghagarg2020** [microsoft/vscode-azurearmtools#864]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azurerm-vscode-tools.selectParameterFile
Error type: Error
Error Message: "c:\Users\megha.i.garg\Desktop\azuredeploy.json" does not appear to be an Azure Resource Manager deployment template file.

Version: 0.11.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:3:349982
fulfilled extension.bundle.js:3:347122
```

</details>

**Comment by StephenWeatherford** [comment]
Thanks for taking the time to enter.  This has been fixed (#852) and the fix will appear in the next release.
