### ISSUE TITLE
It only replaces the parameter name before the cursor

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#869]
**OS:** Mac
**Build Version:** 20200722.1

**Repro Steps:**

1. Open a new-vm.json file in VS Code.
2. Put the cursor anywhere insider a parameter name in the "parameters" portion of the file.
4. Press CTRL+SPACE.
5. Select one.

**Expect:**
It replaces the entire parameter name.

**Actual:**
It only replaces the parameter name before the cursor.
![Capture](https://user-images.githubusercontent.com/62053665/88275448-feb99480-cd0f-11ea-9c9a-308abb47e395.JPG)

**More Info:**
This issue also reproduces if put the cursor anywhere insider a variable/resource name in the "variables"/"resources" portion.

**Comment by StephenWeatherford** [comment]
This is a true bug, it doesn't happen in a regular JSON file.  However, it's not a scenario that users would actually need to do, so I'm going to won't fix it. Thanks!
