### ISSUE TITLE
Suggestion: Update validation text (amazing feature that looks like an issue)

### ISSUE THREAD

**Issue by SeanKilleen** [microsoft/vscode-azurearmtools#882]
## What I originally thought was an issue ...

When creating an ARM template and adding a parameter, in this case [following a docs tutorial](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/quickstart-create-templates-use-visual-studio-code?tabs=CLI), I see a perplexing validation issue:

> ![image](https://user-images.githubusercontent.com/2148318/88662435-f367bf80-d0a7-11ea-9d90-6e0af12c2a14.png)

It appears that the minLength field on a parameter is triggering the "must be greater or equal to 3" validation when it is set to exactly `3`. 

It looks like either the validation rule itself needs to be updated, or the text of the validation should be updated to reflect that it must be greater than 3.

## ...turned out to be an awesome feature...

It turns out, this was the tooling being really helpful. I had generated a parameters file, but had not yet filled it out. As such, the template itself showed an error. Which is an amazing holistic way to think about templates and really helpful.

## ...only I couldn't tell it was a feature.

I am reasonably new to the ARM template tooling in VS code so maybe this is just a newcomer's issue. The error message reads:

> Template validation failed: The provided value for the template parameter 'storageAccountName' at line '10' and column '26' is not valid. Length of the value should be greater than or equal to '4'. Please see https://aka.ms/arm-template/#parameters for usage details.arm-template (validation)

Upon close inspection, this could make sense. It's the value for the parameter, not the minLength itself. However, line 10 and column 26 reference where that value is, and since I'm in the context of the ARM template file, I assume the validation issue that's discovered must be within that context, not another context in a separate file.

## Potential suggestions to help

A few things I think could help alleviate this -- if there's any low-hanging fruit there, might make sense to take it up.

* If it would be possible, reference the parameter json filename -- that would have been a really helpful clue in this instance,
* Move (or at least add) this validation to the parameter json file, which will make it very clear when I flip over to that file that it's the issue.
* In the validation, provide the supplied value, e.g. `Parameter value retrieved: ""`. This would clearly indicate to the user what the validation is seeing, which could have also allowed me to quickly understand the discrepancy. 
* Update the error message language: perhaps instead of ` The provided value for the template parameter 'storageAccountName'`, the phrasing could be `The retrieved value for the template parameter 'storageAccountName'`. By using `retrieved`, that quickly tells me that the parameter is coming from somewhere else. `Provided` makes me look at the value that exists on that line.
* Instead of `Template validation failed`, perhaps these validations could read "Parameter retrieval failed" or "Parameter application failed" or "Parameter value validation failed".

**Comment by SeanKilleen** [comment]
I'm willing to submit a PR for some of these language changes etc. if someone wants to point me in the right direction. I wasn't easily able to find them.

**Comment by StephenWeatherford** [comment]
Thanks for entering!  Unfortunately it's not quite that simple, most of these come from outside of the TypeScript portion of the extension, from a separate assembly.  But we'll review and see what we can do.

**Comment by SeanKilleen** [comment]
> Unfortunately it's not quite that simple

The story of our profession. 😆 Thanks for looking into it!

**Comment by StephenWeatherford** [comment]
@neilpeterson to start a conversion with ARM team.

**Comment by StephenWeatherford** [comment]
https://msazure.visualstudio.com/One/_workitems/edit/7984007

**Comment by apclouds** [comment]
Hi @SeanKilleen when walking through the tutorial, where you able to see the **Value:"ab"** on top of the "storageAcountName" parameter?
![image](https://user-images.githubusercontent.com/8324022/92532704-d83bb400-f1fe-11ea-84ac-29e28d217e28.png)

Thanks for the suggestion on adding the retrieved value to the error message. Will check with the team on that one and get back to you asap!

**Comment by StephenWeatherford** [comment]
@SeanKilleen The Azure guys are going to take a look at hopefully providing more information in the actual errors coming from Azure.  In the meantime, as @apclouds pointed out above, the extension does provide the value in the editor in some scenarios (we're hoping to extend that to linked templates soon as well).  Given that, I'm going to close this issue for now.  thanks!
