### ISSUE TITLE
There is an extra "type" in the resource snippets list 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#883]
**OS:** Win10
**Build Version:** 20200729.4

**Repro Steps:**

1. In VS Code, create a new "JSON" file.
2. Type "arm" and CTRL+SPACE.
3. Select "arm".
4. Type a left curly brace ("{") inside the "resources" section.
5. Check the list of resource snippets.

**Expect:**
There is the same list of resource snippets.
![image](https://user-images.githubusercontent.com/62053665/88775892-dc17f780-d1b7-11ea-9948-e6864b24823e.png)

**Actual:**
There is an extra "type" in the list.
![image](https://user-images.githubusercontent.com/62053665/88775954-efc35e00-d1b7-11ea-8512-c7c44deee9f7.png)

**Comment by StephenWeatherford** [comment]
Thanks for catching.  This is expected, I have corrected the test case.
