### ISSUE TITLE
There is an extra "{ }" When CTRL+SPACE inside the "resources" section

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#884]
**OS:** Win10
**Build Version:** 20200729.4

**Repro Steps:**

1. In VS Code, create a new "JSON" file.
2. Type "arm" and CTRL+SPACE.
3. Select "arm".
4. Inside the "resources" section and CTRL+SPACE.
5. Check the list of resource snippets.

**Expect:**
There is only resource snippets.
![image](https://user-images.githubusercontent.com/62053665/88774173-affb7700-d1b5-11ea-80f8-ad2443e7d6f9.png)

**Actual:**
There is an extra "{ }".
![image](https://user-images.githubusercontent.com/62053665/88774356-e46f3300-d1b5-11ea-9949-c82090d4f62d.png)

**Comment by StephenWeatherford** [comment]
Thanks. This is expected, I have corrected the test case.
