### ISSUE TITLE
Missing one warning in the error list after changing the property from "inner" to "outer"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#891]
**OS:** Win10/Mac
**Build Version:** 20200731.2

**Repro Steps:**

1. Open the nested-sql-server.json file in VS Code.
2. Change the following property from "inner" to "outer":
`"expressionEvaluationOptions": {
		"scope": "inner"
	},`
3. Check the errors.

**Expect:**
Display the following errors:
![image](https://user-images.githubusercontent.com/57662131/89028487-09eb7080-d35f-11ea-81be-afb89f1e1022.png)

**Actual:**
Missing one warning in the error list.
![image](https://user-images.githubusercontent.com/57662131/89028565-3606f180-d35f-11ea-925d-05194a529544.png)

**Comment by StephenWeatherford** [comment]
Fixed by #894
