### ISSUE TITLE
[Suggestion] The format of curly braces are consistent between the "resources" section and the "variables" section

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#892]
**OS:** All
**Build Version:** 20200731.2

**Repro Steps:**

1. In VS Code, create a new "Azure Resource Manager Template" file.
2. Type and select "arm!".
3. Type a left curly brace ("{") inside the "resources" section.
4. Check the display of curly braces.
5. Type a left curly brace ("{") inside the "variables" section.
6. Check the display of curly braces.

**Actual:**
The format of curly braces are inconsistent between the "resources" section and the "variables" section.
![image](https://user-images.githubusercontent.com/62053665/89020178-136ddc00-d351-11ea-8c9d-b592269c9ab1.png)

**Suggestion:**
The format of curly braces are consistent between the "resources" section and the "variables" section.

**Comment by StephenWeatherford** [comment]
Variables is an object and therefore requires members to be properties of the form 
  "key": "value"
Having "{}" inside it isn't valid.

Resources is an array of objects, so "{}" inside the "[]" brackets is valid and expected.

Therefore this is by design, thanks.
