### ISSUE TITLE
The name isn't completely highlighted after renaming it with a longer name

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#893]
**OS:** All
**Build Version:** 20200731.2

**Repro Steps:**
1. Open one deployment template in VS Code.
2. Select one variable name and rename it with a longer name.
3. Check the result.

**Expect:**
The name is completely highlighted.

**Actual:**
The name isn't completely highlighted.
![image](https://user-images.githubusercontent.com/45614674/89031017-3655bb80-d364-11ea-97f5-8be4a228332d.png)

**More Info:**
This issue also reproduces when renaming a parameter.

**Comment by v-mengwe** [comment]
Verified on the latest build 20201215.1, this issue also reproduces for now, we will continue to track this issue.
![arm2](https://user-images.githubusercontent.com/62053665/102585008-892ce580-4142-11eb-8220-2ac5d180d32b.gif)
