### ISSUE TITLE
error on vs code

### ISSUE THREAD

**Issue by AdamRussak** [microsoft/vscode-azurearmtools#898]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: linux
OS Release: 3.10.0-1127.10.1.el7.x86_64
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:395:93998
Object.<anonymous> extension.bundle.js:486:771149
fulfilled extension.bundle.js:486:770045
```

</details>

**Comment by StephenWeatherford** [comment]
Did the troubleshooting tips at https://aka.ms/vscode-armtools-dotnet help?

**Comment by StephenWeatherford** [comment]
@AdamRussak I've been looking for more info about this issue, would love any additional info you can provide.  Did the troubleshooting tips help?  If so, which one?  Thanks!

**Comment by AdamRussak** [comment]
I closed the ticket :)
Sorry.

**Comment by StephenWeatherford** [comment]
Does that mean you never tried again?  Thx.

**Comment by AdamRussak** [comment]
> Does that mean you never tried again? Thx.

used the extension again, hers the error:
```
Downloading .NET Core tooling version(s) 3.1.6 .... Error!
Failed to download .NET Core tooling 3.1.6:
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:25 char:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
Missing '(' after 'if' in if statement.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:25 char:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Missing type name after '['.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:25 char:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:28 char:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
Missing '(' after 'if' in if statement.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:28 char:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Missing type name after '['.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:28 char:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:28 char:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Missing type name after '['.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:42 char:13
+ say_warning() {
+             ~
An expression was expected after '('.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:46 char:9
+ say_err() {
+         ~
An expression was expected after '('.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:47 char:67
+     printf "%b\n" "${red:-}dotnet_install: Error: $1${normal:-}" >&2
+                                                                   ~
Missing file specification after redirection operator.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 


 Error!
Dotnet Core Acquisition Failed: undefined
```

**Comment by StephenWeatherford** [comment]
@sfoslund Sarah, why does it look like the .ps1 file is a Linux shell script?

**Comment by AdamRussak** [comment]
> @sfoslund Sarah, why does it look like the .ps1 file is a Linux shell script?

if you whant i can take a look at the PS script

**Comment by sfoslund** [comment]
Interesting, it looks like the .sh script is getting downloaded but placed in a .ps1 file extension. @AdamRussak you're using linux, right? So the correct script is being downloaded but it has the wrong file extension.

**Comment by StephenWeatherford** [comment]
From the paths above, he's using Windows.

**Comment by sfoslund** [comment]
Hmm, then why does the original issue metadata say linux?

**Comment by AdamRussak** [comment]
> Interesting, it looks like the .sh script is getting downloaded but placed in a .ps1 file extension. @AdamRussak you're using linux, right? So the correct script is being downloaded but it has the wrong file extension. 

I'm using a windows OS and using vs code ssh and the error happened on both of them (on windows I manually downloaded the sdk and it fixed it)

**Comment by sfoslund** [comment]
>The message is from win

You mean the original issue message, where it says the OS is linux, or the error message in [this comment](https://github.com/microsoft/vscode-azurearmtools/issues/898#issuecomment-672808151)?

**Comment by AdamRussak** [comment]
> >The message is from win
> 
> You mean the original issue message, where it says the OS is linux, or the error message in [this comment](https://github.com/microsoft/vscode-azurearmtools/issues/898#issuecomment-672808151)?

The original was on Linux (the issue is still active there)
The later errors I posted was on windows

**Comment by sfoslund** [comment]
Okay, it seems that the .sh file is getting downloaded and saved to a .ps1 file. I'm not sure how this is happening so it will require some investigation, mind if I move this over to our repo?

**Comment by sfoslund** [comment]
This issue was moved to dotnet/vscode-dotnet-runtime#114
