### ISSUE TITLE
Expressionifying strings: Need better experience editing existing string to make it an expression

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#902]
From #643 @Tyriar @neilpeterson @bmoore-msft @jodavis 

Proposed strategy: 
- When the user inserts a "[" at the beginning of an existing JSON string, we provide a snippet completion that suggests turning the entire string into an expression (by placing the ending "]").
- Add other entrypoints (e.g. light bulb, context menus)
![tostring](https://user-images.githubusercontent.com/6913354/88746653-e24b9c80-d101-11ea-8f31-c7d56fa57880.gif)

Alternative strategy: 
- When the user inserts a "[" at the beginning of an existing JSON string, we automatically fill in the ending "]" without asking.
_I'm not sure this can be done reliably due to timing issues.  Also not sure it's the appropriate thing to do._

**Comment by StephenWeatherford** [comment]
From @bmoore-msft (https://github.com/microsoft/vscode-azurearmtools/issues/643#issuecomment-668173802):
> I think the "end" described in the additional issue is still the same (IMO) - if take the example of I have literal value of:
> 
> "someResourceName"
> 
> And I want to turn that into a resourceId... but leave the literal part. I would insert the opening bracket and start typing "resourceId(" but would get not autocomplete for it since it's not yet considered an expression... If we turned it into an expression straight-away I get all the goodness of autocomplete for resourceId (and in this case dependsOn).
> 
> I tried to figure out the short-cut for selecting a property value text and didn't figure it out :b - I think the refactoring will help, but only in the scenario where I'm converting to param/var which won't catch quite a few scenarios...

**Comment by bmoore-msft** [comment]
Ah, ok now following the split of the issues.  Because this is so common, I vote for the alternate strategy.

**Comment by StephenWeatherford** [comment]
I can give it a try.

**Comment by StephenWeatherford** [comment]
won't fix
