### ISSUE TITLE
Quickstart needs updating

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#907]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/quickstart-create-templates-use-visual-studio-code?tabs=CLI

**Comment by neilpeterson** [comment]
Thanks for catching this @StephenWeatherford, I will get this updated. At quick glance, it looks like the only inaccuracy is when adding the parameter. If there is anything else that you want addressed, let me know.

**Comment by StephenWeatherford** [comment]
Didn't run through it all, that may be the only issue (and it's minor).

**Comment by neilpeterson** [comment]
I have updated the docs to align with the 0.12.0 release. These updates were published today.
