### ISSUE TITLE
Don't ask to associate a matching parameter file, just do it automatically

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#911]

**Comment by MCKLMT** [comment]
+ 1 so annoying to see this window each time I open a template.

![image](https://user-images.githubusercontent.com/5141735/89980189-ae2fba00-dc71-11ea-82e0-918911fe096c.png)

**Comment by timetatime06** [comment]
?

**Comment by StephenWeatherford** [comment]
Thanks for the feedback, added to 0.13.0.
