### ISSUE TITLE
The type of parameter is inconsistent between the help message and the template file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#912]
**OS:** Win10/Mac
**Build Version:** 20200806.9

**Repro Steps:**

1. Open any template file in VS Code.
2. Hover the mouse over parameter name.
3. Check the help massage.

**Expect:**
The type of parameter is consistent between the help message and the template file.

**Actual:**
The type of parameter is inconsistent between the help message and the template file, it keeps showing "Type: object".
![image](https://user-images.githubusercontent.com/62053665/89621158-72889f00-d8c3-11ea-842c-f9d4f4a8002b.png)

**More Info:**
This issue also reproduces for the parameters which created from "Insert Item..." command.

**Comment by StephenWeatherford** [comment]
This hover info is coming from the language server, hence is talking about JSON.  And indeed the parameter definition is a JSON object.

I could add hover info to this to provide info that this is a parameter of type string, and additional info if we wanted to.  With a little work, I could probably get rid of the "Type: object" part coming from the language server.

@neilpeterson, @jodavis Is any of this worth doing?  Personally I'd put it at a pri 3.

**Comment by neilpeterson** [comment]
I had never noticed this before. Looking at it now, it doesn't seem like a huge issue. If there is some related work, perhaps bundle it in. If not, my vote would be to hold off until customer +1.

**Comment by StephenWeatherford** [comment]
Waiting for customer feedback before taking the time to fix.
