### ISSUE TITLE
Show icons of common resources types

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurearmtools#92]
From @damienpontifex via #80 

VS does this:
![image](https://user-images.githubusercontent.com/6913354/39331673-046db294-495a-11e8-9e8f-9db7913f1e35.png)

**Comment by StephenWeatherford** [comment]
Actually, we already do this, but perhaps need more icons?

**Comment by PrashanthCorp** [comment]
Closing this. Not high enough priority.
