### ISSUE TITLE
error in vs code to load .net

### ISSUE THREAD

**Issue by ivanpedro** [microsoft/vscode-azurearmtools#920]
Does this occur consistently? 
Repro steps:

1.click at the bottom of the vs code  error acquiring .net core tooling
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:395:93998
Object.<anonymous> extension.bundle.js:486:771149
fulfilled extension.bundle.js:486:770045
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by StephenWeatherford** [comment]
@ivanpedro Did the troubleshooting steps help?  Thanks.
