### ISSUE TITLE
[Suggestion] It's better to quit all completion lists after entering "Esc" one time

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#923]
**OS:** Windows 10 and Mac
**Build Version:** 20200818.1

**Repro Steps:**
1. Open one template file, such as new-vm.json.
2. Find any string expression and remove the contents of the string.
3. Type this into the string "[concat(".
4. Verify that the completion lists displayed.
![image](https://user-images.githubusercontent.com/45614674/90608398-262f4e80-e235-11ea-89e7-8aba0304e2d9.png)
5. Enter "Esc".

**Actual:**
Not all completion lists are disappeared. ("Esc" should be entered twice to quit all completion lists)
![image](https://user-images.githubusercontent.com/45614674/90608944-e87ef580-e235-11ea-9554-56e2b517fc09.png)

**Suggestion:**
It's better to quit all completion lists after entering "Esc" one time.

**More Info:**
All completion lists will be disappeared after clicking other positions of this template file.

**Comment by StephenWeatherford** [comment]
@v-ruizh Thanks for entering, but we have no control over this - this is vscode behavior.
