### ISSUE TITLE
The IntelliSense is not disappeared after inputting space/commas/period in a blank template file

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurearmtools#924]
**OS:** Windows 10 and Mac
**Build Version:** 20200818.1

**Repro Steps:**
1. In VS Code, create a new file but don't save it.
2. Set language ID to "Azure Resource Manager Template".
3. Entering "Ctrl+Space" to show the IntelliSense.
4. Input space/commas/period and check the result.

**Expect:**
The IntelliSense is disappeared after inputting space/commas/period.

**Actual:**
The IntelliSense is not disappeared after inputting space/commas/period.
![image](https://user-images.githubusercontent.com/45614674/90616679-4dd7e400-e240-11ea-88b3-6f58ada481b0.png)

**Comment by StephenWeatherford** [comment]
@v-ruizh Thanks for entering.  This might be a little weird, but doesn't hinder the user experience, and I'm not certain it's actually bad behavior.
