### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yosefbennywidyo** [microsoft/vscode-azurearmtools#925]
- Issue Type: `Performance`
- Extension Name: `azurerm-vscode-tools`
- Extension Version: `0.12.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.48.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/yosef_bw/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt`
[msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-azurearmtools/files/5100162/msazurermtools.azurerm-vscode-tools-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by StephenWeatherford** [comment]
@yosefbennywidyo Just got back from vacation.  The profile seems to indicate all the high CPU was during loading of the extension, about 6.5 seconds.  This is certainly longer than usual (on my current machine I see .5s) but it can be influenced by a number of things, including virus detectors and so forth.  Was this just a single occurrence, or is it a regular problem?  Is it noticeable problem for your usage?  Thanks!

**Comment by yosefbennywidyo** [comment]
@StephenWeatherford I do have McAfee and after I opened this issue, I never had the problem again. I'll let you know when it's happen again.

**Comment by StephenWeatherford** [comment]
Okay, thanks!
