### ISSUE TITLE
"Insert Snippet" from command panel does not work when language mode is Azure Resource Manager Template

### ISSUE THREAD

**Issue by tobz1000** [microsoft/vscode-azurearmtools#934]
1. Open an `azuredeploy.json` with a valid template, so that the language is set to Azure Resource Manager Template (or manually set the language mode)
2. `CTRL-SHIFT-P` -> "Insert Snippet"

The list of available snippets is blank:
![image](https://user-images.githubusercontent.com/1471978/91589544-c7af5200-e951-11ea-9995-18c27387e8dc.png)

Reproduce on 0.11 and 0.12. 0.10 seems to be working correctly (shown below):
![image](https://user-images.githubusercontent.com/1471978/91589607-eada0180-e951-11ea-8048-5da371f9eeac.png)

**Comment by StephenWeatherford** [comment]
@tobz1000 Thanks for entering. Starting with 0.12.0, we converted our snippets to Intellisense completions.  This has multiple advantages, the main one being that we can now suggest completions only where they make sense (e.g., under "resources").  But that does mean vscode isn't aware of the snippets anymore.

Inside the "resources" array, try typing a "{", pressing CTRL+SPACE, or just start typing (it will find words in the snippet name or the snippet description).  Please try out the new experience for a while, and let us know if you have suggestions to improve it (or even if you hate it).  Thanks!

**Comment by tobz1000** [comment]
Thank you for the info - I will have a chance to use it today and will try and provide feedback!

**Comment by tobz1000** [comment]
I have a few thoughts on the new design, which I would assume are the result of limitations of VS Code's intellisense filtering vs. the "Insert Snippet" dialog:

- Browsing snippets takes a little longer when you don't already know what you're looking for, as you can only see the description of one snippet at a time.
- Search-filtering is not as effective:
  - Filter queries cannot contain a space, which may have an impact on the results;
  - The search filter results just seem to be poorer for the intellisense list. E.g. searching for "extension" in the snippets, in 0.10, brings up `arm-vm-script-linux`, `arm-vm-script-windows`, `arm-vm-windows-diagnostics`, which all include the word "extension" in their description. Searching for "extension" in 0.12 only brings up `arm-vm-windows-diagnostics`.

**Comment by StephenWeatherford** [comment]
Thanks!  Not sure if there's anything we can do about those, but will take a look.  BTW, have you seen the "Insert Item..." context menu?

**Comment by StephenWeatherford** [comment]
> * Browsing snippets takes a little longer when you don't already know what you're looking for, as you can only see the description of one snippet at a time.

Two ways to possibly alleviate this:
1a) Add a "browse..." to the completions list which would bring up a dialog similar to that from VS Code
![image](https://user-images.githubusercontent.com/6913354/92177420-5100d180-edf5-11ea-8fe1-d8f655df6022.png)
1b) Show the snippet description instead of the prefix
![image](https://user-images.githubusercontent.com/6913354/92177918-485ccb00-edf6-11ea-957c-51c9f7d429a5.png)
I hesitated to do that since some users might be used to the previous prefixes, but I'm inclined to change it (I could still add the prefixes to the filter search)
1c) Push on vscode to show the detail for all items, not just the current one (like they do for actual snippets)

> * Search-filtering is not as effective:
>   
>   * Filter queries cannot contain a space, which may have an impact on the results;

Personally not convinced this one makes a difference.  You can type "virtualne" or even "vn" and intellisense finds "virtual network".  

>   * The search filter results just seem to be poorer for the intellisense list. E.g. searching for "extension" in the snippets, in 0.10, brings up `arm-vm-script-linux`, `arm-vm-script-windows`, `arm-vm-windows-diagnostics`, which all include the word "extension" in their description. Searching for "extension" in 0.12 only brings up `arm-vm-windows-diagnostics`.

I've added the description to the filter text so this should work in the next version.


Thoughts on 1) options above?  Would any of these help?

**Comment by tobz1000** [comment]
> BTW, have you seen the "Insert Item..." context menu?

I hadn't! Good to know about it as another option.

> 1a) Add a "browse..." to the completions list which would bring up a dialog similar to that from VS Code

If this opened a larger snippet-like panel, I would welcome it - but I suppose others might feel it's superfluous.

> 1b) Show the snippet description instead of the prefix
> I hesitated to do that since some users might be used to the previous prefixes, but I'm inclined to change it (I could still add the prefixes to the filter search)

I agree that it would be best to keep the short names visible for the same reason - and additionally, it allows people to learn shortcuts for resources etc. that they frequently use.

> Personally not convinced this one makes a difference. You can type "virtualne" or even "vn" and intellisense finds "virtual network".

You're probably right, I just have to get used to not typing spaces for fuzzy search.

> I've added the description to the filter text so this should work in the next version.

If the description wasn't being filtered by at all, I'm confused as to how `arm-vm-windows-diagnostics` was prompted by "extension" in 0.12 🤔.

Regardless, that sounds great; thanks for helping me out, I trust whatever you decide is best.

**Comment by StephenWeatherford** [comment]
> If the description wasn't being filtered by at all, I'm confused as to how `arm-vm-windows-diagnostics` was prompted by "extension" in 0.12 🤔.

I already had the name in the filter text, just not the description.  Name is "Windows VM Diagnostics Extension"

I tried adding the name to the label directly, but it's too busy.  We'll close for now, given the fix for description, and see if anyone else comments on it.  Thanks again!
