### ISSUE TITLE
The 'Microsoft.Network/virtualNetworks' is deleted after selecting "sku"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#945]
**OS:** Win10
**Build:** 20200904.1

**Repro Steps:**
1. Create a new .json file with the following.
```
	{
	"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
	"subnet1Name": {
	"type": "object",
	"defaultValue": {
	"property1": "hi",
	"property2": {
	"property2a": "2a"
	}
	}
	},
	"sku": {
	"type": "string"
	}
	},
	"functions": [],
	"variables": {
	"subnet1Name": {
	"property1": "hi",
	"property2": {
	"property2a": "2a"
	}
	},
	"subnet2Name": "subnet2",
	"v2": "[resourceId('Microsoft.Network/virtualNetworks', parameters('subnet2Name'))]",
	"v3": "name-from-template(staging)"
	},
	"resources": [],
	"outputs": {}
	}
```
2. Add the content as the below at the end of the "subnet2Name" variable's line.
`"v2": "[resourceId('Microsoft.Network/virtualNetworks', parameters('subnet2Name'))]"`
3. Put the cursor right after "resourceId(", type "parameters('".
4.  Select 'sku'.
5. Check the result.

**Expect:**
The 'Microsoft.Network/virtualNetworks' is not deleted.

**Actual:**
The 'Microsoft.Network/virtualNetworks' is deleted.
![image](https://user-images.githubusercontent.com/57662131/92229377-f68e7080-eedb-11ea-96a0-ecfea472357e.png)

**Comment by v-xinda** [comment]
@StephenWeatherford Hi, 
More details please see the record: [https://web.microsoftstream.com/video/d72ca4ff-0400-96f3-b2ea-f1eaf0cce6cf](https://web.microsoftstream.com/video/d72ca4ff-0400-96f3-b2ea-f1eaf0cce6cf)

**Comment by StephenWeatherford** [comment]
It says I don't have access.

**Comment by v-xinda** [comment]
I am so sorry  that give you a url which you can't access.
You can access this new url: [https://msit.microsoftstream.com/video/275fa1ff-0400-96f3-c8e0-f1eaf23f0045](https://web.microsoftstream.com/video/275fa1ff-0400-96f3-c8e0-f1eaf23f0045)
