### ISSUE TITLE
Issue coming is VS code

### ISSUE THREAD

**Issue by santoshdata** [microsoft/vscode-azurearmtools#946]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:395:93998
Object.<anonymous> extension.bundle.js:486:771149
fulfilled extension.bundle.js:486:770045
```

</details>

**Comment by StephenWeatherford** [comment]
@santoshdata Did the troubleshooting steps at https://aka.ms/vscode-armtools-dotnet help?  thanks
