### ISSUE TITLE
Unable to remove file reference from parameter file to template file if template file is deleted

### ISSUE THREAD

**Issue by ReneRebsdorf** [microsoft/vscode-azurearmtools#952]
Does this occur consistently? yes
Repro steps:

1. Create a template file
2. Create a template parameters file
3. Link the two using the extension
4. Delete the linked template file (preserving the parameter file)

It would be a great if when reporting this error an option was provided to remove the link.
Pressing the "Template File" to normally provide a template file just reproduces this error.

Action: azurerm-vscode-tools.openTemplateFile
Error type: Error
Error Message: cannot open file:///<path>/azureDeploy.json. Detail: Unable to read file 'path\azureDeploy.json' (Error: Unable to resolve non-existing file 'path\azureDeploy.json')

Version: 0.12.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:6239:388
```

</details>

**Comment by StephenWeatherford** [comment]
I agree this should be fixed.  As a work-around, you can delete this association in your vscode user settings.

**Comment by ReneRebsdorf** [comment]
Yep, that's what I ended up doing. The purpose of this issue was to bring attention to a bug that I can across

Mvh. / Best Regards
René Rebsdorf

________________________________
