### ISSUE TITLE
Whenever I open Visual Studio, error comes up - Error acquiring .Net Core Tooling

### ISSUE THREAD

**Issue by sakarchatta** [microsoft/vscode-azurearmtools#953]
Does this occur consistently?  Yes
Repro steps:

1. I open Visual Studio Code
2.I go to Terminal and I get below error:
This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined
See '.NET Core Tooling' in the output window for more information.
Error: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

3. I tried installing the latest version even then I am getting this error.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:395:93998
Object.<anonymous> extension.bundle.js:486:771149
fulfilled extension.bundle.js:486:770045
```

</details>

**Comment by StephenWeatherford** [comment]
@sakarchatta Did the troubleshooting tips in the error message help?

**Comment by StephenWeatherford** [comment]
FYI I've improved the troubleshooting instructions at https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition.
