### ISSUE TITLE
Make solutions to .net acquisition more visible and maybe automatic for the user

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#956]
I continue getting lots of bugs on .net acquisition: https://github.com/microsoft/vscode-azurearmtools/issues?q=label%3A%22story%3A+acquire+dotnet%22+

Some possible options:
1) Add help button to the error dialog (ours or dotnet?)
2) Take them to download link and allow them to point to dotnet via dialog (us or dotnet?)
3) Better way to get feedback for the problem?  Pretty much everybody ignores the troubleshooting tips and ignores any requests for additional information

**Comment by StephenWeatherford** [comment]
See https://github.com/dotnet/vscode-dotnet-runtime/pull/125

**Comment by StephenWeatherford** [comment]
Still needed?

**Comment by sfoslund** [comment]
> Still needed?

The first two items have been merged and will be included in the next release. Let me know if you have more concrete suggestions for the third item, thanks!

**Comment by StephenWeatherford** [comment]
Fixed by #1093
