### ISSUE TITLE
The new added parameter name is still "parameter1" when a parameter named "parameter1" exists

### ISSUE THREAD

**Issue by v-menliu** [microsoft/vscode-azurearmtools#958]
**OS:** Windows 10
**Build Version:** 20200909.16
**Regression:** Not a regression

**Repro Steps:**

  1. In VS Code insider, open a template file, such as "new-vm.json".
  2. Type CTRL+SPACE and click "new-parameter" to add a parameter with default name "parameter1" inside the "parameters" section.
  3. Repeat step 2 to add a new parameter again, then check its default name.

**Expect:**
The new parameter name is "parameter2".

**Actual:**
The new parameter name is "parameter1", and an error tip displays in output.
![image](https://user-images.githubusercontent.com/70553044/93066118-298aee00-f6ac-11ea-9991-623fad38f910.png)

**More info:**
This issue also reproduces when adding a new variable/resource/function/output.

**Comment by StephenWeatherford** [comment]
We expect people to rename these anyway, so not worth changing, thanks.
