### ISSUE TITLE
Validation error with resourceGroup().tags.Anything

### ISSUE THREAD

**Issue by kirkone** [microsoft/vscode-azurearmtools#961]
Hi,

the validation in VS Code fails when using the following code:

```
"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "product": {
      "type": "string",
      "defaultValue": "[resourceGroup().tags.Product]",
      "metadata": {
        "description": "The product name for all ressources deployed with this template. Default: 'resourceGroup().tags.Product'"
      }
    },
```

the Error Message is:

```
Template validation failed: The template resource 'product' at line '5' and column '16' is not valid: The language expression property 'Product' doesn't exist, available properties are ''.
```

Am I doing something wrong here? Should it be possible to use the Tags that way?
The ARM Template works as expected when deploying it so I suspect the validation is not correct here.

**Comment by StephenWeatherford** [comment]
You are correct that this is a bug, thanks for taking the time to let us know..  It's currently tracked by #831.  @jorgecotillo Any thoughts on how hard this is to fix?  Thanks.

**Comment by StephenWeatherford** [comment]
Tracked by #831
