### ISSUE TITLE
I have been facing this issue when try to make JSON template in Visual Studio Code. I have ARM extension installed. Any help will be highly appreciated. Thanks

### ISSUE THREAD

**Issue by CloudsAnatomy** [microsoft/vscode-azurearmtools#962]
Does this occur consistently? 
Repro steps:

1. Open Visual Studio Code, click on select language mode and then choose JSON as language.  
2. After choosing the JSON to make an ARM template for deploying Azure resources I have been facing this issue.

The screenshot is for reference.

![image](https://user-images.githubusercontent.com/60945320/93208369-e6954d00-f775-11ea-94ef-26efc2654648.png)

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:395:93998
Object.<anonymous> extension.bundle.js:486:771149
fulfilled extension.bundle.js:486:770045
```

</details>

**Comment by StephenWeatherford** [comment]
@CloudsAnatomy Did you try the troubleshooting steps from the link in the help message?  Thanks.

**Comment by CloudsAnatomy** [comment]
@StephenWeatherford not yet, but thank you for suggesting. I'm going to use the provided links to further look into this issue. In case of failure, I'll post here on this same thread. Thanks.

Regards
CloudsAnatomy
cloudsanatomy@gmail.com

**Comment by StephenWeatherford** [comment]
@CloudsAnatomy Any luck?  Thanks.

**Comment by StephenWeatherford** [comment]
FYI I've improved the troubleshooting instructions at https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition.
