### ISSUE TITLE
Cannot install Azure ARM Tools for VSCODe

### ISSUE THREAD

**Issue by stefanstranger** [microsoft/vscode-azurearmtools#963]
Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

**Comment by stefanstranger** [comment]
Solved by commenting out my PowerShell profile required modules part.

**Comment by StephenWeatherford** [comment]
@stefanstranger Thanks for letting us know!  Could you be more specific as to what you did so we can add this to our troubleshooting page?  Thanks!

cc @sfoslund

**Comment by stefanstranger** [comment]
Hi Stephen,

The Azure ARM Tool extension is dependent on .NET Core and it has some code (I don't know where) to download and install .NET core using PowerShell. 

While this PowerShell (script?) is called my PowerShell profile will be loaded. I have some #require statements in my Profile which somehow where not available on my system. 

I would suggest that the PowerShell script being called to install .NET core is called with the -noprofile switch.

HTH
Stefan

**Comment by StephenWeatherford** [comment]
@stefanstranger Thanks!

**Comment by StephenWeatherford** [comment]
Moved to https://github.com/dotnet/vscode-dotnet-runtime/issues/121.

**Comment by StephenWeatherford** [comment]
https://github.com/dotnet/vscode-dotnet-runtime/issues/121 marked as fixed
