### ISSUE TITLE
Validation needs to recognize new top-level "scope" property

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#967]
See https://github.com/Azure/azure-resource-manager-schemas/pull/1191.

**Comment by jorgecotillo** [comment]
@StephenWeatherford I looked into the code and would like some confirmation from you, does this update needs to be a schema update? Is the validation code complaining about an invalid property by any chance?

**Comment by StephenWeatherford** [comment]
@jorgecotilloThis is what I see:

> Template validation failed: The template resource '[parameters('workbookId')]' at line '35' and column '28' is invalid. 'Scope' property is not supported. Please see https://aka.ms/arm-template/#resources for usage details.

... which would indicate the validation assembly.  I don't see any errors coming from the schema validation.  Am I missing something?
