### ISSUE TITLE
The `list` function is unrecognised but is a valid function

### ISSUE THREAD

**Issue by MattJeanes** [microsoft/vscode-azurearmtools#970]
As seen on [the documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#list), the `list()` function is a valid function but throws an `Unrecognised function name 'list'.` error in VSCode.

I have run this ARM template successfully so it's definitely valid

**Comment by MattJeanes** [comment]
I've just seen this fixed in recent commits, nice one guys!

Closing as dupe of #949

**Comment by StephenWeatherford** [comment]
Thanks for taking the time to enter.  Please let us know if there are others!  This fix should be out within the next 2 weeks.
