### ISSUE TITLE
error

### ISSUE THREAD

**Issue by itsabhinav2010** [microsoft/vscode-azurearmtools#973]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:395:93998
Object.<anonymous> extension.bundle.js:486:771149
fulfilled extension.bundle.js:486:770045
propagateAslWrapper async-listener/index.js:504:23
glue.js:188:31async-listener/glue.js:188:31
index.js:541:70async-listener/index.js:541:70
glue.js:188:31async-listener/glue.js:188:31
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by StephenWeatherford** [comment]
@itsabhinav2010 Did the troubleshooting steps help?  Thanks!

**Comment by StephenWeatherford** [comment]
I've updated the troubleshooting instructions at https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition.  Please let me know if that does not clarify things.  Also, are you seeing any other error messages or dialogs?  Thanks!
