### ISSUE TITLE
JSON outline doesn't show up when file type changed from Plain Text to JSON or JSONC

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-azurearmtools#98]
Related to #24

This is problematic because currently just opening a JSONC file doesn't seem to put it into JSONC language mode.

**Comment by StephenWeatherford** [comment]
https://github.com/Microsoft/vscode/issues/48969

**Comment by EricJizbaMSFT** [comment]
Closing this as I've verified it was fixed on VS Code insiders

**Comment by EricJizbaMSFT** [comment]
Sorry - the VS Code bug mentioned has been fixed, but the bug described in the ARM extension still repros. Re-opening and moving to next milestone

**Comment by PrashanthCorp** [comment]
Closing it pending customer feedback.
