### ISSUE TITLE
There is no help message for namespace name without references after pressing "Shift+F12" action

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#990]
**OS:** All
**Build Version:** 20200928.5

**Repro Steps:**

1. Click on a namespace name(that no references) anywhere in the template file.
2. Press Shift+F12.
3. Check the result.

**Expect:**
Display the help message "No references found for the 'namespace name'", such as:
![image](https://user-images.githubusercontent.com/62053665/94530061-1f045300-026d-11eb-9c68-bc2c0978952f.png)

**Actual:**
There is no help message.

**Comment by StephenWeatherford** [comment]
Won't fix.
