### ISSUE TITLE
The file which shows the parents or children is not closed after double clicking a parent or child

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurearmtools#992]
**OS:** All
**Build Version:** 20200928.5

**Repro Steps:**

1. Open the "dependson-database-migration-service" template file in VS Code.
2. Clicking on the code lens should show the parents or children in the file.
3. Double click a parent or child.
![image](https://user-images.githubusercontent.com/57662131/94543388-955c8180-027c-11eb-8de9-67a38c2e08b8.png)
4. Check the result.

**Expect:**
The file which shows the parents or children should be closed and the cursor points to where the child or parent is in the template file.

**Actual:**
The file which shows the parents or children is not closed after double clicking a parent or child.

**Comment by StephenWeatherford** [comment]
This behavior is controlled by vscode, we can't do anything to change it.
