### ISSUE TITLE
Issue popped up after opening the template

### ISSUE THREAD

**Issue by pawel-rozek** [microsoft/vscode-azurearmtools#993]
Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: linux
OS Release: 4.4.0-18362-Microsoft
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:395:93998
Object.<anonymous> extension.bundle.js:486:771149
fulfilled extension.bundle.js:486:770045
```

</details>

**Comment by StephenWeatherford** [comment]
@pawel-rozek FYI I've improved the troubleshooting instructions at https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition.
